Kong/kubernetes-ingress-controller

internal/apis/admin/v1/types.go
internal/apis/configuration/v1/types.go
internal/ingress/controller/kong.go

Add hash_on_header to upstream objects

---

docs/examples/externalnamejwt.md

More examples on how to use ingress with plugins for auth.

added jwt plugin example

---

docs/custom-types.md
docs/examples/externalname.md

Fix the readme link error

---

internal/apis/admin/service.go
internal/ingress/controller/kong.go

Current version is only support create service. Fix it.

Support patch service

---

internal/ingress/controller/kong.go

**Which issue this PR fixes**: fixes #51

Fix health check errors

---

deploy/README.md
deploy/openshift.md

This PR fix mardown's issues in README and OPENSHIFT files of deploy section. 
**Which issue this PR fixes**: 
- It fix preview of the readme file.
- It fix preview and add titles to `openshift.md` file

Fixing style of deploy readme

---

internal/apis/configuration/v1/types.go
internal/ingress/controller/kong.go

feat: add protocols property to Routes in Ingress

---

.github/ISSUE_TEMPLATE.md

We will be redirect users to Kong Nation for questions and feature requests to
keep track of bugs only in Github issues.

chore(github) update Github Issue template

---

docs/custom-types.md

There was a typo in the documentation that led to some of the discussion in #70.
**Which issue this PR fixes**: 
fixes #70

Fixing documentation example for KongConsumer custom_id field

---

deploy/README.md
deploy/gke.md
deploy/provider/cloud/gke-kong-proxy-loadbalancer-service.yaml

This PR improve deployment documentation on GKE
Related to #59 

improving docs on GKE

---

README.md
docs/design.md
docs/faq.md
docs/ingress-class.md

This is part of a patchset aimed to improve
and add documentation.

docs(*) revamp and reorganize documentation

---

cli/ingress-controller/flags.go
cli/ingress-controller/header_roundtripper.go
cli/ingress-controller/main.go
internal/apis/admin/certificate.go
internal/apis/admin/plugin.go
internal/apis/admin/v1/types.go
internal/apis/configuration/v1/types.go
internal/apis/plugin/v1/types.go
internal/ingress/annotations/annotations.go
internal/ingress/annotations/annotations_test.go
internal/ingress/controller/controller.go
internal/ingress/controller/endpoints.go
internal/ingress/controller/kong.go
internal/ingress/controller/kong_test.go
internal/ingress/controller/store/store.go
internal/ingress/errors/errors.go

Cherry picked commits from master for 0.1.2.
This PR will be merged using a merge commit.
All feat/fix commits have no breaking changes.

Chore/cherry pick for 0.1.2

---

docs/annotations.md
docs/custom-resources.md
docs/deployment/gke.md
docs/deployment/minikube.md
docs/deployment/openshift.md
docs/design.md
docs/troubleshooting.md

Corrected some grammatical mistakes in the docs. Thanks

Fixed some grammatical mistakes in docs

---

docs/deployment/README.md
docs/deployment/aks.md

Add docs on how to deploy the Ingress Controller on Azure k8s Service.

docs(deploy) add docs for deploying on AKS

---

deploy/manifests/dummy-application-openshift.yaml
deploy/manifests/dummy-application.yaml
deploy/manifests/ingress-controller.yaml
deploy/manifests/kong.yaml
deploy/manifests/migration.yaml
deploy/manifests/postgres.yaml
deploy/manifests/rbac.yaml
deploy/single/all-in-one-postgres.yaml

**What this PR does / why we need it**: Fix YAML indentation consistensy

Fix YAML indentation consistency

---

CONTRIBUTING.md

Updated link to deployment guide, which improves the reading experience.

fix(docs) Updated link to deployment guide

---

test/e2e/e2e.go

- This fixes using `dep ensure`

fix(test) removed references to unused tests

---

docs/external-service/externalname.md
docs/external-service/externalnamejwt.md

Updates documentation so it is up to date with current implementation
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

Updated external-service documentation with new plugin specification

---

README.md
deploy/README.md

**What this PR does / why we need it**: Fixes links to documentation

chore(docs) updated links to deployment docs

---

internal/ingress/controller/kong.go

Rebased on next and squashed.
See #248
(@hbagdi)

Set default value of PreserveHost for new routes to true.

---

internal/ingress/controller/kong.go
internal/ingress/controller/parser/parser.go

Consumers are now synced via decK, which provides:
- Consumers are tagged when tagging support is available in Kong.
Meaning, consumers created via API calls to Kong will not be deleted
by the Ingress Controller. This is one of the most heavily requested
feature from the community.
- The logic is much more robust and now gives us a simple path forward
to support consumer-level plugins.
- Credentials are still synced manually via the code in this repository
because they can't be diffed, but those are the only entities left
now.
Credentials are now gathered in parser, removing the duplication between
dbless and db modes.
See #246, #243

feat: simplify consumer sync using deck

---

internal/ingress/controller/parser/parser.go

If an Ingress resource references a plugin which is not present in k8s's
store, ingress controller bails out and stops syncing any other
configuration updates as well.
This commit changes that and allows user to proceed in case where
Ingress is applied but the service is not present in the system.
The test cases for these are in works with a fake store implementation.
It is not ideal that all errors are logged and we never error out. An
error from, let's say, looking up an item from cache, should result in a
failure to sync, while an error of an item not existing can merely be
logged.
This is again in the works, where errors will be classified and metrics
around the errors exposed for alerting in Prometheus.

fix: do not error out due to a missing service or plugin

---

internal/ingress/controller/kong.go

If tagging feature is in use, skip loading all the consumers and load
only tagged consumers. This significantly reduces the amount of
consumers that will be loaded for cases when consumers are dynamically
created via direct API calls to Kong's Admin API.

perf: skip loading all consumers when tagged

---

docs/deployment/README.md

spelling fix only - Google not Goolge.
fix spelling

nit: Spelling fix

---

docs/guides/README.md

fixes link to KongConsumer and KongCredential resources document

fixes link to KongConsumer and KongCredential resources document

---

.ci/build-master.sh
.travis.yml

These builds are pushed to following Docker repository:
https://bintray.com/beta/#/kong/kubernetes-ingress-controller/master

chore(ci) build Docker image for each commit to master branch

---

docs/guides/getting-started.md

fix(doc) bad service name

---

internal/ingress/controller/controller.go
internal/ingress/controller/plugin_schema_helper.go

Use the new `NewRequest` method in the client to build request.

refactor: simplify PluginSchemaStore

---

README.md

It took several hours until we find [this issue](https://discuss.konghq.com/t/expose-admin-api-in-kong-k8-ingress/2196/8) confirming the admin API is supported and the doc is outdated.

Remove warning about entities deletion

---

docs/references/custom-resources.md

To use the correct singular rather than an incorrect plural.
**What this PR does / why we need it**: Fixes a small error in the documentation of how to add a Consumer to an ACL group which would result in the consumer not being able to be added to the group.

docs(custom-resources): update acl KongCredential

---

docs/deployment/k4k8s-enterprise.md

In order to publish the bintray secret and the license to the kong namespace it needs to exist in advance

Added kong namespace creation

---

internal/ingress/controller/kong.go
internal/ingress/controller/kong/dbless/kong_inmemory.go
internal/ingress/controller/kong/dbless/kong_inmemory_test.go
internal/ingress/controller/parser/parser.go
internal/ingress/controller/parser/parser_test.go

feat: plugins associated with multiple entities

---

docs/deployment/k4k8s-enterprise.md

Fix wring link to bintray

---

CONTRIBUTING.md

To update CONTRIBUTING.md as this repo no longer uses `dep` as dependency management.

docs(contribute) remove  related section

---

internal/ingress/controller/event_handler.go

fix:delete event twice

---

internal/ingress/controller/parser/parser.go
internal/ingress/controller/parser/parser_test.go

service.Protocol needs to be set otherwise the code panics.
Fix #511

fix(parser) process default backend correctly

---

internal/ingress/controller/parser/parser.go
internal/ingress/controller/parser/parser_test.go

When the same SNI is associated with different Kubernetes Secrets.
When using Kong with a database, this results in the same SNI being
associated with a different certificate and the controller fails to
update the SNI in Kong.
This fix reduces the likelihood of this happening for some cases but
will not fix the problem for all cases.
See
https://github.com/hbagdi/deck/commit/890404c3012a620bf46b220705a54e338e5387b1
for the root cause of this issue.
Fix #510

fix(parser) handle same SNI across different Ingress rules

---

docs/deployment/minikube.md

Signed-off-by: Gabriel R Sezefredo <g@briel.dev>
fixes typos in documentation

docs: fix typos in minikube deployment guide

---

docs/concepts/deployment.md

added comment about default kong ingress class behavior

note about default kong ingress class

---

docs/deployment/minikube.md

docs(deployment/minikube): fix service name and describe namespace

---

docs/deployment/k4k8s-enterprise.md

This completes the work started in
https://github.com/Kong/kubernetes-ingress-controller/pull/556.

docs: update link to helm values to incorporate new secret name

---

internal/ingress/controller/parser/parser.go

fix: Incorrect error return

---

docs/guides/configuring-https-redirect.md

https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/configuring-https-redirect.md
The readme title doesn't match the context.
This is not a serious problem, just change the title.

Update the title https redirect

---

docs/concepts/ha-and-scaling.md

Just fixing a typo on the file

Typo fixing

---

docs/concepts/k4k8s-with-kong-enterprise.md
docs/deployment/kong-enterprise.md
docs/guides/configure-acl-plugin.md
docs/guides/redis-rate-limiting.md
docs/guides/upstream-mtls.md
internal/ingress/controller/controller.go
internal/ingress/controller/parser/parser.go

I'm currently expelling the code base and read a lot of the documentation.
While doing this, I found some trivial grammar mixups and mild formatting issues that I'd like to help correct:
* "its" vs "it's"
* 80-character alignment of documentation
* Missing newlines at the end of files
This PR is documentation only and should not have any effects on the code itself.
That's why I don't think it should be mentioned in the release and doesn't update the release-notes.md document.

[pet peeve] Fix some grammar and formatting issues

---

docs/guides/README.md
docs/guides/using-mtls-auth-plugin.md

Add a guide on how to use mtls-auth (enterprise) plugin 
**Which issue this PR fixes** 
None
None

docs: add guide on using mtls-auth plugin and CA certificates

---

docs/references/annotations.md

I forgot to remove some parts of the copy pasta when adding this section. Oops.

Fix incorrect regex-priority header in docs

---

deploy/manifests/postgres/kong-ingress-postgres.yaml
deploy/single/all-in-one-postgres.yaml

deploy: fix the version of kong in init-container

---

docs/guides/using-rewrites.md

Add a guide to path and host rewrites.

Add guide to path and host rewrites

---

README.md

docs(readme): adding guides and tutorials in main README.md

---

docs/concepts/design.md

This PR fixes a typo in *Kong Ingress Controller Design* Page.
**Which issue this PR fixes** 
This PR fixes a typo in *Kong Ingress Controller Design* Page.
NA

Fixed typo

---

cli/ingress-controller/main.go

Added retry when getting data returned by Kong Admin API.
fixes #761 
fixes #766

fix: solve the restart caused by kong not starting

---

cli/ingress-controller/main.go

Sorry, due to my negligence, there is a logical judgment wrong, please merge it together.
Original PR #771 
@hbagdi

fix the error in PR#771

---

docs/references/plugin-compatibility.md

The annotations in the table doesn't match the order if the footnotes. Correcting after talking with @rainest.

Fix annotation order

---

cli/ingress-controller/main.go

- Introduces a timeout (fixed at 3 seconds per @hbagdi's request) for the initial Kong API call
fixes #766

feat: kong connection timeout (#688)

---

docs/guides/README.md
docs/guides/getting-started-istio.md

Defines a Getting Started guide using KIC and Istio 1.6.7, deploying a sample application, and seeing the data collected by Istio.
closes #703 #777
Please consider whether linking it immediately under _Getting started_ is appropriate

docs(istio): istio guide - k8s 1.18, istio 1.6.7

---

docs/references/annotations.md

docs: fix incorrect key for konghq.com/methods

---

CODEOWNERS
MAINTAINERS.md

Add myself to KIC maintainers.
Also, fix a missing `)` on Harry's entry.

Add mflendrich to KIC maintainers

---

CHANGELOG.md
Makefile
deploy/manifests/base/kong-ingress-dbless.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

Release 1.0.0 to next
:musical_note: [SYNTHPOP](https://www.youtube.com/watch?v=wO0A0XcWy88) :musical_note:

Release 1.0.0 to next

---

docs/concepts/deployment.md

**What this PR does / why we need it**: fix bad link to rbac.yaml file

fix link to rbac.yaml

---

.github/workflows/test.yaml
deploy/manifests/enterprise-k8s/kong-enterprise-k8s.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml
docs/deployment/k4k8s-enterprise.md

Update bitly link

---

docs/guides/using-kongclusterplugin-resource.md

The header did not match the content of the file, so I fixed it. 

docs(guides): Fixed header

---

docs/guides/cert-manager.md

- Updated the guide in order to be compatible with kubernetes-ingress-controller version 0.10.0 and later.
- Updated the guide to be compatible with latest cert-manager, and kubernetes versions.
**What this PR does / why we need it**: Currently the cert-manager guide does not work "out-of-the-box" if one installs the latest Kong kubernetes-ingress-controller with the latest cert-manager. The ACME Ingress gets stuck in a "Creating Ingress"-mode since the lack of the ingress class configuration.

Cert-manager guide fix for new controller versions

---

docs/guides/using-tcpingress.md

[kong] fix: small doc typo

---

docs/guides/setting-up-custom-plugins.md

This PR adds clarifying documentation to `Setting up custom plugins`, defining details that are necessary for successful installation. 

Updates custom plugin documentation for clarity

---

CHANGELOG.md

:facepalm: realized after the fact that the header didn't look the way it should.

Correct broken link in changelog

---

CHANGELOG.md
CONTRIBUTING.md
Makefile
README.md
deploy/manifests/base/custom-types.yaml
hack/dev/common/custom-types.yaml
internal/ingress/controller/parser/parser.go
internal/ingress/controller/parser/parser_test.go
test/integration/cases/08-externalname/ingress.yaml
test/integration/cases/08-externalname/verify.sh

include commits from main + changelog + makefile version bump

Release v1.1.1 to next

---

.github/workflows/test.yaml
.gitignore
Makefile
README.md
cli/ingress-controller/main.go
internal/ingress/store/store.go
internal/ingress/utils/ingressapi.go
internal/ingress/utils/ingressapi_test.go

This enables code coverage for `next`, among others.

Merge main to next

---

CODEOWNERS
Dockerfile
cli/ingress-controller/main.go
internal/admission/validator.go
test/integration/util/install-sut.sh

Merge main into next, mostly to get the CI fix in https://github.com/Kong/kubernetes-ingress-controller/pull/1054 and CODEOWNERS update.

chore(*) merge main into next

---

railgun/CONTRIBUTING.md
railgun/keps/0001-single-kic-multi-gateway.md
railgun/keps/0002-kong-gateway-api.md
railgun/keps/0003-kic-kubebuilder-re-architecture.md
railgun/keps/0004-kong-kubernetes-testing.md

The purpose of this PR is to add the KEPs we had previously in a private repo which are relevant to the KIC so that going forward the community can engage in the KEP process with the maintainers to discuss and propose enhancements to the KIC.

Publish KIC KEPs, add KEPs to CONTRIBUTING.md

---

railgun/keps/0003-kic-kubebuilder-re-architecture.md
railgun/keps/0005-definition-of-done.md

Small context adds to KEP3 and a spelling correction for KEP5.

docs: small updates for KEPs

---

.github/workflows/license.yaml

Merge main into next, again! Pull in the CI fix from https://github.com/Kong/kubernetes-ingress-controller/pull/1198

Merge main into next

---

railgun/test/integration/udpingress_test.go

This PR adds cleanup tests to the `v1alpha1.UDPIngress` tests.
Contributes to resolving https://github.com/Kong/kubernetes-ingress-controller/issues/1189

fix: expand udp integration tests

---

railgun/manager/manager.go
railgun/test/integration/suite_test.go

Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1225

fix: enable leader election ID override

---

railgun/examples/httpbin.yaml
railgun/test/integration/ingress_test.go
railgun/test/integration/kongingress_test.go
railgun/test/integration/suite_test.go
railgun/test/integration/tcpingress_test.go

Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1258

feat: use httpbin as stardard http test tooling

---

railgun/cmd/rootcmd/rootcmd.go
railgun/controllers/configuration/zz_generated_controllers.go
railgun/controllers/corev1/endpoints_controller.go
railgun/controllers/corev1/service_controller.go
railgun/hack/generators/controllers/networking/main.go
railgun/internal/ctrlutils/kong.go
railgun/internal/ctrlutils/utils.go
railgun/manager/manager.go
railgun/pkg/constants/constants.go
railgun/test/integration/ingress_test.go
railgun/test/integration/kongingress_test.go
railgun/test/integration/suite_test.go
railgun/test/integration/tcpingress_test.go
railgun/test/integration/udpingress_test.go

Partially resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1220
Sets up https://github.com/Kong/kubernetes-ingress-controller/issues/1266

feat: add ingress.class override for mgr

---

.github/dependabot.yml

Add github-actions versions checking with dependabot

Add github-actions versions checking with dependabot

---

railgun/internal/proxy/suite_test.go
railgun/pkg/config/config.go

Part of https://github.com/Kong/kubernetes-ingress-controller/issues/1097
Review of env var loads was at https://github.com/Kong/kubernetes-ingress-controller/issues/1182#issuecomment-847310784

chore(*) remove outdated comment

---

.github/workflows/test.yaml
deploy/manifests/base/kong-ingress-dbless.yaml
deploy/manifests/enterprise-k8s/kustomization.yaml
deploy/manifests/enterprise/kustomization.yaml
deploy/manifests/postgres/kong-ingress-postgres.yaml
deploy/manifests/postgres/migration.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

Bumps KIC to 1.3, Kong to 2.4, and Kong Enterprise to 2.4.1.0.

Bump KIC and Kong versions in manifest

---

CHANGELOG.md

Bad link from when I wrote this originally; points to the wrong PR.

Fix incorrect link in changelog

---

.github/workflows/2x-integration-test.yaml
.github/workflows/common-test.yaml
.gitignore
Makefile
railgun/Makefile

**What this PR does / why we need it**: This PR plugs codecov coverage check for `integration-tests`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1310

chore(ci) add coverage for integration tests

---

pkg/util/debug_logging.go
pkg/util/debug_logging_test.go
railgun/Makefile
railgun/internal/proxy/clientgo_cached_proxy_resolver.go
railgun/internal/proxy/proxy.go
railgun/main.go
railgun/manager/run.go
railgun/test/integration/plugin_test.go
railgun/test/integration/suite_test.go
railgun/test/integration/tcpingress_test.go
railgun/test/integration/webhook_test.go

This fixes several flakes and provides some general cleanup for our integration tests.
fixes #1432
fixes #1444

Integration test fixes

---

CONTRIBUTING.md

This PR adds some documentation for the KEP process and for Kubebuilder SDK to our CONTRIBUTING.md and resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1093

[docs] Update CONTRIBUTING.md for recent KIC 2.0 tooling

---

pkg/annotations/annotations_test.go
pkg/kongstate/upstream_test.go
pkg/util/ingressapi_test.go
pkg/util/secretgetter_test.go

**What this PR does / why we need it**: This PR increases the code coverage.

chore(*) improve code coverage

---

go.mod
go.sum
pkg/adminapi/client.go

chore: update go-kong to v0.20.0

---

railgun/internal/ctrlutils/ingress-status.go
railgun/test/integration/ingress_https_test.go

Service might have multiple routes, this fix configure ingress with multiple routes which is aligned with proxy configuration;
Only get expected content when accessing service through routes test case work as expected. Fix ingress_https_tests check point
only throw error if err is not nil
Fix service multiple routes function; 
Add status check within ingress_https_test
Fix logic error

[chore][quality] fix -  ingress_https_test check points;  multiple routes update; only throw error if err is not nil

---

.github/workflows/test.yaml
Makefile
hack/generators/controllers/networking/main.go
hack/verify-generators.sh
hack/verify-manifests.sh
pkg/clientset/clientset.go
pkg/clientset/fake/clientset_generated.go
pkg/clientset/fake/register.go
pkg/clientset/scheme/register.go
pkg/clientset/typed/configuration/v1/configuration_client.go
pkg/clientset/typed/configuration/v1/fake/fake_configuration_client.go
pkg/clientset/typed/configuration/v1/fake/fake_kongclusterplugin.go
pkg/clientset/typed/configuration/v1/fake/fake_kongconsumer.go
pkg/clientset/typed/configuration/v1/fake/fake_kongingress.go
pkg/clientset/typed/configuration/v1/fake/fake_kongplugin.go
pkg/clientset/typed/configuration/v1/kongclusterplugin.go
pkg/clientset/typed/configuration/v1/kongconsumer.go
pkg/clientset/typed/configuration/v1/kongingress.go
pkg/clientset/typed/configuration/v1/kongplugin.go
pkg/clientset/typed/configuration/v1beta1/configuration_client.go
pkg/clientset/typed/configuration/v1beta1/fake/fake_configuration_client.go
pkg/clientset/typed/configuration/v1beta1/fake/fake_tcpingress.go
pkg/clientset/typed/configuration/v1beta1/fake/fake_udpingress.go
pkg/clientset/typed/configuration/v1beta1/tcpingress.go
pkg/clientset/typed/configuration/v1beta1/udpingress.go

I noticed we didn't have any tests that proved PRs didn't break our generator code, so this patch includes some small fixes and tweaks to our generator code and makefile targets, and then adds a script to test them and verify their output in CI, which is now added as a step in our test workflows for Github Actions on every PR.

[feat] ci to check generators

---

README.md
RELEASE.md

Moving to main branch from now on, clean associated docs and github workflows

updating docs associated to release and github workflow process

---

.github/dependabot.yml

Remove target-branch to use main instead of next
Define configuration to update Dockerfile, so there won't be any manual PR like #1691

Update dependabot after removal of next branch and add docker

---

CHANGELOG.md
internal/kongstate/kongstate.go

https://github.com/Kong/kubernetes-ingress-controller/issues/729#issuecomment-901336616
Resolves one of the tasks for https://github.com/Kong/kubernetes-ingress-controller/issues/729
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1722

fix: remove credentials constraint violation dropping

---

.golangci.yaml
internal/ctrlutils/ingress-status.go
internal/diagnostics/server.go
internal/kongstate/credentials.go
internal/kongstate/util.go
internal/parser/parser.go
internal/store/store.go

Setup go-errorlint to treat error wrapping
**Which issue this PR fixes** : fixes #1573

chore(lint): setup go-errorlint

---

test/e2e/istio_test.go

Didn't notice it in the original PR but it seems there's a timing flake issue with the Istio E2E tests that can happen occasionally:
https://github.com/Kong/kubernetes-ingress-controller/runs/3747084509?check_suite_focus=true
Basically we just need to allow some time for the Kiali API to actually be up, responding and ready rather than assuming it will be immediately ready when the deployment is up.

fix: timing flake in istio e2e tests

---

test/e2e/istio_test.go

Recently I've observed that Github Actions environment can
be completely happy with a given test for some days but then
for a few hours in the next day that same test will fail. There
appears to be what I can only describe as "general unpredictability"
of that environment.
This patch simply removes several optimistic HTTP requests
that were being made in the Istio tests as I saw several
inconsistent failures of them in CI (but could not reproduce
locally), in favor of more defensive retry logic.

chore: extra defensive http checks in istio e2e tests

---

CONTRIBUTING.md
README.md

What this PR does / why we need it:
I got some errors following docs to startup Kong Ingress in dev mode, here are some changes in docs I did to accomplish and better understanding.

docs: improve contrib docs

---

CHANGELOG.md
go.mod
go.sum
internal/admission/errors.go
test/integration/webhook_test.go

Reintegrates the `2.0.x` branch into `main`.

Merge v2.0.6 into main

---

go.mod
go.sum
test/integration/webhook_test.go

#2025 merged accidentally without CI passing.
- Runs `go mod tidy`
- Fixes the validation integration test that was manually merged incorrectly

chore(deps): go mod tidy and fix test errors following #2025

---

test/integration/webhook_test.go

Adds a delay to a test after creating a ton of resources, before creating another ton of resources that depend on the first set.
I observed apparent random failures of a new test during an unrelated PR, e.g. https://github.com/Kong/kubernetes-ingress-controller/actions/runs/1491413745/attempts/2
```
2021-11-22T17:55:44.2590784Z time="2021-11-22T17:55:44Z" level=error msg="failed to run validation: Secret \"background-noise-consumer-176-credential-4\" not found" component=admission-server
2021-11-22T17:55:44.2899130Z === CONT  TestValidationWebhook
2021-11-22T17:55:44.2900565Z     webhook_test.go:216: 
2021-11-22T17:55:44.2901353Z         	Error Trace:	webhook_test.go:216
2021-11-22T17:55:44.2904041Z         	Error:      	Received unexpected error: …
```

fix(test) add delay in webhook test

---

test/integration/gateway_test.go

An occasional flake was found in CI with Gateway APIs when waiting for `Listeners` on `Gateway` objects to settle. This patch makes those wait times more deliberate to allow more time for completion.
Fixes #2065 
I ran this test several times over in my local environment and could not get it to fail once. In fact, It was very quick in succeeding. So as to not spend too much time digging for something I can't reproduce, I reasoned that we've seen Github Actions environments be _very slow_ in the past and decided that the casual timeouts provided previously needed to be made more deliberate and longer to accomodate for slow envs. Hopefully this helps the situation as I can't reproduce …

fix: gateway integration test wait times

---

LICENSE

Update copyright year to 2022.
ref:
- https://github.com/Kong/kong/pull/8240

chore(*) update copyright year

---

config/base/kong-ingress-dbless.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

Bump controller image to 2.1.1

chore(deploy) rebuild manifests

---

Makefile

More 1.3.4 release; forgot to do the version bumps after backports.

chore(*) update controller version

---

CHANGELOG.md

1.3.4 changelog into main. Tentatively set for actual release tomorrow to allow time for review of this and #2182

doc(changelog) add 1.3.4

---

CHANGELOG.md

Adds 2.0.7 and fixes some minor issues.
#2005 was erroneously reported as in 2.0.6. Dunno what happened but the commit is indeed not in 2.0.6.

doc(changelog) add 2.0.7

---

keps/0002-kong-gateway-api.md

For the alpha `Gateway` support the relevant KEP had lagged behind the implementation some and this patch improves the language regarding "unmanaged gateway mode" to be more clear and in line with the current direction and intent of the code.

KEP - reword unmanaged gateways mode

---

.github/workflows/license.yaml

Reverts Kong/kubernetes-ingress-controller#2150

Revert "chore(deps): bump actions/github-script from 4.1 to 5.1.0"

---

internal/dataplane/parser/translate.go
internal/dataplane/parser/translate_httproute.go

Now that #834 is declined, remove the related TODO comments.

chore: remove todos from translate code

---

README.md

Updates the README.md with some modernizations and does some cleanup for language, grammar and dead links.

docs: README.md cleanup

---

Makefile

The `make run` target has been useless for a long time because nothing can work without any flags. This patch adds some defaults for those flags (which align with [KTF](https://github.com/kong/kubernetes-testing-framework) environment defaults) which can be overridden. I basically just had these functions in my `.bashrc` for a while and realized I might as well put them in the `Makefile` so that it actually works. Also added `make debug` which uses the same flags but for `dlv`.

tests: add run and debug to Makefile

---

internal/util/reports_test.go

I did something silly :facepalm: 
Resolves #2395

tests: fix reporter ordering in test

---

internal/admission/server.go
internal/admission/validator.go
internal/dataplane/kongstate/kongstate.go
internal/dataplane/parser/parser.go
internal/dataplane/parser/translate_httproute.go
internal/dataplane/parser/translate_ingress.go
internal/dataplane/parser/translate_knative.go
internal/dataplane/parser/translate_kong_l4.go
internal/dataplane/parser/translate_tcproute.go
internal/dataplane/parser/translate_udproute.go
internal/dataplane/sendconfig/sendconfig.go

Use `log.WithError(err).Error("...")` instead of `log.Errorf("...,%v",err)` for structured logging, recording error to a separate field. 
Searched for all `log.Errorf()` and `*.logger.Errorf()` in the whole repo, and replaced most of them. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1013

feat change log.Errorf to log.WithError

---

CHANGELOG.md
config/crd/bases/configuration.konghq.com_kongingresses.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml
pkg/apis/configuration/v1/kongingress_types.go

Add descriptions for each field of `kongingress` CRD, so that `kubectl explain kongingress` can show the introductions of each field in `kongingress` CRD
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1766

doc(crd) add descripiton for each field of kongingress CRD

---

internal/manager/config.go

I found the flag description to be a bit confusing so I'm fixing it.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: None

refactor: improve description for --proxy-timeout-seconds flag

---

.github/ISSUE_TEMPLATE/release.yaml

move release checklist in `RELEASE.md` to issue template so that we can create release issues
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1647 

doc(repo) move release checklist to issue template

---

CHANGELOG.md
internal/manager/run.go
internal/manager/utils/reports.go
internal/meshdetect/detector.go
internal/meshdetect/detector_test.go
internal/meshdetect/mesh_kind.go
internal/meshdetect/types.go
internal/util/reports.go
internal/util/reports_mesh.go
internal/util/reports_mesh_test.go

Detect the following things about service mesh and report them:
- whether a service mesh is deployed to the cluster
- whether KIC is injected with service mesh
- count of services injected within mesh networks

feat(telemetry) implement mesh detection and reporting

---

.github/ISSUE_TEMPLATE/release.yaml

fix the `unique id` problem in release issue template
See: https://github.com/randmonkey/kubernetes-ingress-controller/blob/fix_release_issue_template/.github/ISSUE_TEMPLATE/release.yaml

fix(issue template) fix duplicate id in release issue template

---

internal/meshdetect/detector.go

optimize the performance of service mesh detection. After the update, we could finish the detection in < 30s in a cluster with 100k headless services.

fix(mesh_detect) optimize performance of mesh detection

---

.github/workflows/e2e.yaml
.github/workflows/release.yaml
internal/meshdetect/detector.go

update kubernetes versions in e2e and release workflows for releasing 2.5.0:
- update patch versions in e2e
- update to minor version to 1.{20,21,22,23,24} in release workflow 

chore(workflow) update kubernetes versions for e2e and release workflow

---

.github/ISSUE_TEMPLATE/bug_report.yaml

This PR will update some of the grammar problems that can make filling out this template harder to read. As per my opinion, I have updated it and made this PR for the changes I've made.
N/A
N/A (minor changes)

chore(Issue Templates) Fix bug_report.yaml grammar problems

---

CHANGELOG.md
LICENSES
config/image/oss/kustomization.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

release KIC v2.5.0 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2651 

chore(*) release 2.5.0

---

test/integration/kongingress_test.go

To help in debugging `TestKongIngressEssentials` failures this PR adds some more logging.
Related: #2632

tests: add logs to TestKongIngressEssentials

---

test/e2e/kuma_test.go

add logs for flaky e2e test case `TestDeployAllInOnePostgresKuma`, log the service before updating and the latest status if updating fails.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: related to #2699 

test(e2e) log service before/after updating

---

.github/workflows/nightly.yaml

run tests for release in each nightly build.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2593 

test(nightly) run integration tests for on nightly builds as in release action

---

test/integration/tcpingress_test.go

add logs and check for pod readiness for testcase `TestTCPIngressTLSPassthrough`
related: #2735 

test:add logs and wait for pod in flaky case

---

test/e2e/kuma_test.go

Use `retry.RetryOnConflict` to avoid conflicts on updating services in kuma e2e tests.
related: #2733 

fix(e2e) use RetryOnConflict for updating services for kuma tests

---

test/integration/ingress_test.go

Retries some potentially unsafe updates. This maybe doesn't affect controller tests, I misread what https://github.com/Kong/gateway-operator/issues/115 was for because it's a very similar test. Wrote the fix though, so may as well.

chore(tests) retry TestIngressEssentials conflicts

---

CHANGELOG.md
pkg/clientset/fake/register.go
pkg/clientset/scheme/register.go

A simple fix of typos in CHANGELOG.md.

typos fix in CHANGELOG

---

CHANGELOG.md
internal/controllers/gateway/gateway_controller.go
internal/controllers/gateway/gateway_controller_test.go
internal/controllers/gateway/gateway_utils.go
internal/controllers/gateway/gatewayclass_controller.go
internal/controllers/gateway/gatewayclass_controller_test.go
test/integration/gateway_test.go

treat status conditions of `gateway` and `gatewayclass` as snapshots, replace the condition with same type when update conditions.
fixes #2694 

fix: treat status conditions of gateway and gatewayclass as snapshots

---

internal/manager/controllerdef.go
internal/manager/run.go

Disables gateway features when one of the beta resources in Gateway APIs: `Gateway`, `GatewayClass` or `HTTPRoute` is not installed in the cluster, and output a log with `INFO` level.
fixes #2814 

fix(gateway_api) disable gateway features when necessary CRDs are not installed

---

test/integration/tcproute_test.go

When removing a TCPRoute, treat RSTs as a valid indication that the route is no longer available.
Related to https://github.com/Kong/kubernetes-ingress-controller/issues/2668#issuecomment-1218519307. That linked comment covers the why of this solution in more detail.
Not closing immediately after this to confirm that we don't see some other failure instead.

fix(tests) handle TCPRoute RSTs

---

test/e2e/all_in_one_test.go
test/e2e/features_test.go

add logs and dump diagnostics for e2e test case`TestWebhookUpdate` to resolve its flakiness.
related: #2798 

test: add diagnostics and logs for e2e TestWebhookUpdate

---

Makefile

This PR aims to address #2856 by using `client-gen`'s `--trim-path-prefix` flag.
Fixes #2856

fix(build): don't use temp dir for clien-gen

---

.github/workflows/kong3.0_compatibility.yaml

Add integration tests against kong 3.0 release candidate images to test compatibility with kong 3.0.  e2e tests will be added after #2884.
partially solves #2870.

test: add integration tests against kong 3.0 images

---

.github/workflows/kong3.0_compatibility.yaml

fix `if` syntax in kong 3.0 compatibility tests actions, and put license step to the last step before running integration tests because env will be printed in `echo` steps. (although the actual confidentials are displayed as `***` so secrets are not actually leaked  )

test: fix if syntax in actions

---

test/e2e/all_in_one_test.go
test/e2e/helpers_test.go
test/e2e/kuma_test.go
test/e2e/utils_test.go

support loading custom images for kong in e2e tests.
fixes #2884 

test: load kong image for e2e tests

---

.github/workflows/kong3.0_compatibility.yaml

Add e2e tests into kong 3.0 compatibility tests.
fixes #2870 

test: add e2e tests in kong 3.0 compatibility test action

---

CHANGELOG.md
config/image/oss/kustomization.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

Commits 2.7 changes to main.
Part of #2973

chore(*) release 2.7.0

---

internal/controllers/gateway/gateway_controller_test.go
internal/controllers/gateway/gatewayclass_controller_test.go
internal/controllers/gateway/route_utils_test.go
internal/dataplane/kongstate/kongstate_test.go
internal/dataplane/kongstate/route_test.go
internal/dataplane/kongstate/service_test.go
internal/dataplane/kongstate/util_test.go
internal/dataplane/parser/ingressclassparemeters_test.go
internal/dataplane/parser/ingressrules_test.go
internal/dataplane/parser/parser_test.go
internal/dataplane/parser/translate_httproute_test.go
internal/dataplane/parser/translate_utils_test.go
internal/dataplane/parser/translators/ingress_test.go
internal/dataplane/sendconfig/sendconfig_test.go
internal/store/fake_store_test.go
internal/store/store_test.go
internal/util/relations_test.go

The Go [testing documentation](https://pkg.go.dev/testing) states that the tests must use the following naming convention:
```go
func TestXxx(*testing.T)
```
We comply with this convention for the most part of the tests, but not for all of them. Many tests are named as follows:
```go
func Test_xxx(*testing.T)
```
This PR aims at changing all the non-compliant test names from `Test_xxx` to `TestXxx`.

fix test names

---

.github/workflows/e2e.yaml
.github/workflows/nightly.yaml
.github/workflows/test.yaml

BuildPulse action requires repository to be checked out locally, sample failing run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3189865136/jobs/5204525722
Part of #2985
- ~~[ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~~

chore(tests): buildpulse-report step requires repo checkout

---

test/conformance/gateway_conformance_test.go
test/conformance/suite_test.go

This cleans up the setup for conformance tests and fixes a data race which was a result of making changes to scheme after starting the controller.
This also removes an unnecessary `testutils.DeployCRDsForCluster()` invocation which is already called inside `DeployControllerManagerForCluster()`.
Fixes #3012

fix(tests): move schema changes to before running controller to fix a data race in conformance tests

---

.github/workflows/e2e.yaml

The collected reports' names don't match the generated ones. 
Sample run which failed to send reports: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3191719007/jobs/5208365903
- ~~[ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~~

chore(tests): collect proper junit reports from e2e tests

---

internal/admission/server.go
internal/controllers/gateway/gateway_controller.go
internal/controllers/gateway/gatewayclass_controller.go
internal/util/reports.go
test/integration/suite_test.go

This PR removes some of the `nolint` directives.

chore(lint): remove some of the nolint directives

---

test/e2e/kuma_test.go

In order to mitigate failures like these - https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3262526069/jobs/5359765210#logs - let's add diagnostics dump to e2e kuma test.

chore(tests): dump diagnostics for e2e kuma test

---

.gitattributes
internal/controllers/configuration/zz_generated_controllers.go

It will make the pull-request-size bot ignore files that were generated when calculating the PR T-shirt size. https://github.com/noqcks/pull-request-size/blob/master/README.md#excluding-files

chore: use .gitattributes to annotate generated files for pull-request-size bot

---

.github/actions/redhat-opdev-preflight-action/entrypoint.sh

fix(ci): fix use of wrong docker registry in preflight scan

---

internal/dataplane/parser/translate_httproute_test.go
internal/util/builder/httpbackendref.go
internal/util/builder/kongstateservicebackend.go

Moves backends refs creation outside of parser test, to reduce size of the test input and expected output, as it was really hard to grasp what's happening in particular test.
More utils to reduce tests size should be introduced soon.

chore(tests): add backend builder utility to reduce parser tests lengths

---

internal/dataplane/parser/translate_httproute_test.go
internal/util/builder/httproutematch.go

chore(tests): add httproutematch builder utility to reduce parser tests

---

internal/dataplane/parser/translate_httproute_test.go

Apparently some objects have escaped the refactoring PR https://github.com/Kong/kubernetes-ingress-controller/pull/3091
This PR fixes that, by applying changes from https://github.com/Kong/kubernetes-ingress-controller/pull/3091 to remaining objects.

chore(tests) replace duplicate objects def with existing obeject ref in parser tests

---

internal/controllers/gateway/route_utils_test.go
internal/util/builder/address.go
internal/util/builder/listener.go

This PR add Gateway API Listener builder to minimize boilerplate in tests.

Add Gateway API listener builder

---

.golangci.yaml
go.mod
internal/dataplane/kongstate/util.go
test/e2e/utils_test.go

Use `sigs.k8s.io/yaml` as the only YAML library.
See also: https://github.com/Kong/deck/pull/800 and https://github.com/Kong/go-kong/pull/239

chore(deps) use consistent YAML lib

---

.github/workflows/release.yaml

Set `max-parallel`([max-parallel](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel)) to 16 of e2e tests running on GKE to 16 to prevent from failure of exceeding subnet number limit (30).
possibly fixes #3326 
We should ensure that the occupation of subnet is released in the env cleanup. This happens in [KTF](https://github.com/Kong/kubernetes-testing-framework). 

fix: set max-parallel to 16 on e2e tests on GKE

---

hack/e2e/cluster/cleanup/main.go

When GKE clusters end up in a "broken" state (no nodes)
`cluster.Endpoint` will be empty when creating a client in ktf https://github.com/Kong/kubernetes-testing-framework/blob/e1d6feb1e4019bc09b0ec6a0bdca9029ec20498d/pkg/clusters/types/gke/utils.go#L66 causing errors like: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3844910128/jobs/6548453298#step:5:41
```
failed to cleanup all clusters: [could not retrieve cluster kic-0558e0ef-61c6-4bf4-9f4a-4786408dcbf9: host must be a URL or a host:port pair: "https://" could not retrieve cluster kic-57637bd0-2d71-42b1-8c80-95e998367168: host must be a URL or a host:port pair: "https://" could not retrieve cluster kic-5ba898e9-2cbd-4514-82e7-b0f7fdc3c6d1: host must be a URL or a host:port …
```

chore(ci): fix GKE cleanup for broken clusters

---

CHANGELOG.md

> This is all the way at the bottom. It's the thing we always forget.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3322.

chore: add v2.8.1 diff link to changelog

---

internal/util/test/webhooks.go
test/e2e/features_test.go
test/e2e/helpers_test.go
test/e2e/utils_test.go

Makes it possible to debug why particular commands fail in tests.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3358.

chore: improve logging in tests running commands

---

test/integration/httproute_test.go

In order to prevent errors like these: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3913763697/jobs/6690043172#step:6:4770
Operation cannot be fulfilled on httproutes.gateway.networking.k8s.io "4e4a0536-db7f-49b4-a43c-2d1f6fdb39c2": the object has been modified; please apply your changes to the latest version and try again
let's perform a `.Get()` repeatedly before `.Update()`.
This PR also assigns the return value of calls to API server to use the values returned by the server.

test: fix TestHTTPRouteFilterHosts test by repeatedly querying for an HTTPRoute before Update

---

internal/dataplane/parser/parser.go

Upstream service annotation has been checked twice. This PR removes the second check and does some minor refactor in `getEndpoints`.

refactor: don't check service upstream twice for service

---

internal/dataplane/kong_client.go

Extract `prepareSendDiagnosticFn` to avoid unrelated noise in the `sendToClient` method.
Part of #3430.

refactor: extract prepareSendDiagnosticFn

---

CHANGELOG.md

chore: Confomance flakiness changelog update

---

internal/manager/config_validation.go
internal/manager/config_validation_test.go

validation of checking whether TLS cert provided and whether TLS key provided are mistaken, should be swapped.

fix: correct validation of tls cert and key

---

internal/dataplane/parser/parser.go

Fix incorrect log entry logging about a missing listener status information while it is in place.
Closes #3133

fix: fix incorrect debug log about listener missing status information

---

internal/dataplane/kong_client.go
internal/dataplane/parser/ingressclassparemeters_test.go
internal/store/fake_store.go
internal/store/store.go

The parameters are always set to false.

chore: remove unused Store params

---

examples/gateway-httproute.yaml
examples/gateway-tcproute.yaml
examples/gateway-tlsroute.yaml
examples/gateway-udproute.yaml

The Gateway-API-related warning messages have been removed from the Gateway API examples.

chore: warning messages removed

---

internal/util/debug_logging_test.go

It seems that the reduced redundancy logger hook is indeed indeterministic.
Here's a random failure on CI: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4135405311/jobs/7147810842#step:5:2041
```
=== RUN   TestDebugLoggerThreadSafety
debug_logging_test.go:145: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/util/debug_logging_test.go:145
Error:      	"" does not contain "unique"
Test:       	TestDebugLoggerThreadSafety
--- FAIL: TestDebugLoggerThreadSafety (0.00s)
```
I've looked into it, and couldn't really figure out why this is failing sporadically.
Can be reliably reproduced if the count of total writes to the logger (and hence concurrent loggers) is decreased to a small …

tests: fix TestDebugLoggerThreadSafety test

---

.github/workflows/cleanup.yaml
.github/workflows/e2e.yaml
.github/workflows/e2e_targeted.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
.github/workflows/test_nightly.yaml
CHANGELOG.md

chore(ci): bump go to 1.20

---

test/e2e/all_in_one_test.go

TestDeployAllInOneDBLESSMultiGW is flaky. This extends the timeout when waiting for gateway pods to be configured.
Example failing run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4172074809

test(e2e): extend gw configuration timeout in multi-gw test

---

CHANGELOG.md

chore: CHANGELOG.md updated with gwapi 0.6.1

---

internal/controllers/gateway/route_utils.go
test/conformance/gateway_conformance_test.go

test(conformance): routes generation bumped

---

internal/manager/run.go

include pod namespace in Konnect node hostname for KIC nodes, using `namespace/name` pattern. If namespace or name is not found, fall back to use `os.Hostname`, which will be the pod name.

fix: add pod namespace in node hostname

---

internal/konnect/client.go
internal/konnect/node_agent.go

list all nodes in konnect runtime group by iterating through `Pages.NextPage` until all nodes are listed.

fix: list all nodes in konnect by pages

---

internal/dataplane/clients_manager.go
internal/dataplane/clients_manager_test.go

Provides a way to subscribe to GatewayClients changes via `AdminAPIClientsManager.SubscribeToGatewayClientsChanges` method.
Enables addressing https://github.com/Kong/kubernetes-ingress-controller/pull/3587#discussion_r1114287994.

feat(dataplane): allow subscribing to gateway clients changes

---

internal/controllers/gateway/route_utils.go
internal/controllers/gateway/route_utils_test.go

Ensures and tests that KIC does not load GWAPI Routes whose parentRef indicates something other than a Gateway.
Fix #3075 

feat(gwapi) reject non-Gateway parentRefs

---

internal/konnect/client.go
test/e2e/helpers_test.go
test/e2e/konnect_test.go

add tests for konnect node registration in e2e tests

test(e2e): add e2e tests for konnect node registration

---

internal/controllers/gateway/gateway_utils_test.go

test(unit): listener conditions appear only once

---

internal/dataplane/parser/translate_httproute.go
test/conformance/gateway_conformance_test.go

fix for `httpRouteMatchin` standard conformance test

test(conformance): fix httpRouteMatching test

---

test/e2e/features_test.go

We updated the logs when disabling the controller of a certain kind of resource, the checking logs part in e2e tests should also be updated.

test(e2e_logs): fix checking logs for disabling controllers in e2e tests

---

test/conformance/suite_test.go

Gateway API tests create (and delete during cleanup) namespaces which are used when the tests are run.
This can be sometime a problem with one wants to run the conformance tests in a loop, e.g. like so:
```
while GOTESTFLAGS="-count 1" KONG_TEST_CLUSTER="kind:<MY_CLUSTER_ID>" make test.conformance; do ; done
```
In that case the namespaces might not be deleted when the new run is started and that causes issues in conformance tests harness and ultimately makes tests fail.
This PR aims to fix that by 
- deleting those namespaces when they are present in the cluster
- waiting for them to be deleted

tests: allow running Gateway API conformance tests in a loop

---

config/image/oss/kustomization.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless-konnect.yaml
deploy/single/all-in-one-dbless-legacy.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

Bump KIC version in manifests to 2.9.0 to fix manifests check of release workflow
unblocks #3672 

chore(release): update kic image tag to 2.9.0 in config

---

internal/dataplane/parser/atc/field.go
internal/dataplane/parser/atc/matcher.go
internal/dataplane/parser/atc/predicate.go
internal/dataplane/parser/atc/route.go

Round two of suggestions for #3780. Adds comments to most public functions, makes a consistency name change, and replaces some concats with Sprintf.

Suggestions for #3780

---

CHANGELOG.md

Manual backport of https://github.com/Kong/kubernetes-ingress-controller/pull/3828

2.8.2 changelog 2

---

internal/dataplane/clients_manager.go
internal/dataplane/clients_manager_test.go

Fixes a deadlock that could occur when multiple calls to AdminAPIClientsManager.Notify happened in parallel. The calls are made by the KongAdminAPIServiceReconciler, so if the endpoint slices of the Kong Admin API Service change frequently (i.e. when scaling up), it makes the chances of the deadlock happening higher.
Co-authored-by: Tao Yi  <tao.yi@konghq.com>
(cherry picked from commit 456f93114ffdf2134087b3e134920da855a1d041)

[backport] fix: make AdminAPIClientsManager.Notify safe for concurrent use (#3816)

---

CHANGELOG.md

Updates changelog for 2.9.2 release.
Part of #3835.

chore: update changelog for 2.9.2

---

go.mod

chore: go version updated to 1.20 in go.mod

---

test/integration/tcproute_test.go

Uses the cleaner utility throughout TestTCPRouteReferenceGrant. Previously it was using a mix of that and old style deferred deletes, which led to some resources being deleted before collecting diagnostics.

chore(tests) use cleaner in TestTCPRouteReferenceGrant

---

CHANGELOG.md
config/image/oss/kustomization.yaml
config/variants/enterprise/kustomization.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless-konnect.yaml
deploy/single/all-in-one-dbless-legacy.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

Prepare 2.9.3 release
Related: #3898

chore: prepare release 2.9.3

---

CHANGELOG.md
config/image/oss/kustomization.yaml
deploy/single/all-in-one-dbless-enterprise.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless-konnect-enterprise.yaml
deploy/single/all-in-one-dbless-konnect.yaml
deploy/single/all-in-one-dbless-legacy.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

Update changelog and manifests for 2.9.3.

chore: update changelog and manifests for 2.9.3

---

test/integration/knative_test.go

This is a follow up to #3968. It seems that Knative is removing all sample images?
https://console.cloud.google.com/gcr/images/knative-samples/GLOBAL is empty 🤔 
This PR changes the used image to `kong/httpbin`.

tests(knative): fix knative integration test

---

internal/konnect/node_agent_test.go

This aims to fix flaky konnect node update unit test.
Fixes #3955

chore(tests): fix flaky konnect node agent unit test

---

.github/ISSUE_TEMPLATE/gw_testing_request.yaml

Creates a new issue template for cross-project testing requests.

chore(github): new issue template gw_testing_request.yaml

---

README.md
TESTING.md

This PR adds a testing guidelines document which is meant to be an overview of our current testing strategy.
Related: #4107
We can try this as initial scaffolding for testing documentation. This is not meant to be complete at this stage.
Every one is encourage to add to this doc and raise concerns about our current setup.

docs: add TESTING.md

---

.golangci.yaml

Similar to https://github.com/Kong/go-kong/pull/337

chore(linter) update depguard configuration

---

test/conformance/gateway_conformance_test.go

The conformance test `GatewaySecretReferenceGrantSpecific` has been enabled.

test(conformance): enable `GatewaySecretReferenceGrantSpecific` conformance test

---

.github/workflows/pr_checks.yaml

(cherry picked from commit 9ec5633ad7c4eed1d32e1a294962e1347a0538f8)

[backport] ci: run PR checks on PRs against all branches (#4223)

---

.github/workflows/cleanup.yaml

fix "hack/cleanup not in GOROOT" problem in running cleanup workflow.

fix(actions) fix path in cleanup workflow

---

internal/dataplane/parser/translate_grpcroute.go

backport #4238 to fix translator of `GRPCRoute` to be compatible with Kong 2.x.
We refactored `GRPCRoute` translator in 2.10 so that we cannot directly backport the PR to `release/2.9.x`.

backport #4238: fix: do not prepend ~ before regex paths for Kong < 3.0

---

test/envtest/telemetry_test.go
test/helpers/certificate/certificate.go
test/integration/ingress_https_test.go
test/integration/tcpingress_test.go
test/integration/tlsroute_test.go
test/internal/helpers/certificate.go

Generate certificate/key pair in each run of integration test cases using TLS certificates. 
part of #4118 , also fixes #4257
~~- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~~ No need to update CHANGELOG because it only updates test code

test: generate certs in each run in integration tests using TLS

---

CHANGELOG.md
internal/dataplane/parser/translators/atc_utils.go
internal/dataplane/parser/translators/ingress_atc.go
internal/dataplane/parser/translators/ingress_atc_test.go

assign priorities to Kong routes generated from ingresses.
fixes #4248

feat(expression router) assign route priority ingress

---

CHANGELOG.md

prepare release 2.10.2
fixes #4263 

prepare release 2.10.2

---

config/image/oss/kustomization.yaml
deploy/single/all-in-one-dbless-enterprise.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless-konnect-enterprise.yaml
deploy/single/all-in-one-dbless-konnect.yaml
deploy/single/all-in-one-dbless-legacy.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

update image version of KIC to the (upcoming) patch release `2.10.2`.
~~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR!~~

chore(manifests): update KIC image version to 2.10.2 in manifests

---

CHANGELOG.md
config/rbac/leader_election_role.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless-konnect.yaml
deploy/single/all-in-one-dbless-legacy.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

This PR when backported and released in 2.9.x will fix https://github.com/Kong/gateway-operator/issues/744 when those changes are incorporated in KGO as per https://github.com/Kong/gateway-operator/issues/744 description and comments.
Why we need this? To fix the issue for 2.9, since it's already fixed for 2.10 and we generate roles in KGO we don't want to have it broken for 2.9 and fixed for 2.10 which currently we support both.

[Backport release/2.9.x] fix(rbac): fix leader election policy rules

---

CHANGELOG.md

Adds missing changelog entry for v2.10.2.

chore: add v2.10.2 changelog entry

---

config/rbac/gateway/role.yaml
deploy/single/all-in-one-dbless-enterprise.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless-konnect-enterprise.yaml
deploy/single/all-in-one-dbless-konnect.yaml
deploy/single/all-in-one-dbless-legacy.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml
internal/controllers/gateway/httproute_controller.go

The RBACs have been updated with grants to watch, list, and get namespaces.
The `*Route` controllers need to get namespaces [here](https://github.com/Kong/kubernetes-ingress-controller/blob/8003ef9cc3c1d2f53e00cca24d2f0949a505041e/internal/controllers/gateway/route_utils.go#L444).

chore: namespace RBACs added

---

test/envtest/gatewayclass_envtest_test.go

To prevent failures like [this](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5523919976/jobs/10075502866#step:4:543):
```
gatewayclass_envtest_test.go:326: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/gatewayclass_envtest_test.go:260
/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/gatewayclass_envtest_test.go:326
Error:      	Condition never satisfied
Test:       	TestGatewayWithGatewayClassReconciliation/unmanaged_gateway_class
gatewayclass_envtest_test.go:326: expected to find an Accepted and Programmed conditions with Status True, got []v1.Condition{v1.Condition{Type:"Accepted", Status:"Unknown", ObservedGeneration:0, …
```

tests: watch instead of busy loop in gatewayclass envtest

---

CHANGELOG.md
internal/clients/manager.go
internal/clients/manager_test.go
internal/dataplane/kong_client.go
internal/dataplane/kong_client_test.go
internal/konnect/mock_node_api_test.go
internal/konnect/node_agent.go
internal/konnect/node_agent_test.go
internal/util/clock/clock.go
internal/util/clock/ticker.go
test/mocks/ticker.go
test/mocks/ticker_test.go

[Backport 2.10.x] fix(konnect): update nodes status only when it actually changes

---

.github/workflows/release.yaml
CHANGELOG.md
config/image/oss/kustomization.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless-konnect.yaml
deploy/single/all-in-one-dbless-legacy.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml

Prepares release 2.9.4.
Part of #4262.

chore: prepare release 2.9.4

---

MAINTAINERS.md

`MAINTAINERS.md` file updated. 

chore: maintainers.md update

---

test/internal/helpers/kong.go

It's possible to have a message logged like this
```log
#1: failed parsing kong (URL: http://172.18.0.100:8001) semver from body: : unknown Kong version : ''
#2: failed parsing kong (URL: http://172.18.0.100:8001) semver from body: : unknown Kong version : ''
...
```
after changes introduced in this PR more meaningful message is logged
```log
#1: failed getting kong version from http://172.18.0.101:8001: 401 Unauthorized: {"message":"Invalid RBAC credentials"}
#2: failed getting kong version from http://172.18.0.101:8001: 401 Unauthorized: {"message":"Invalid RBAC credentials"}
...
```

chore(tests): add proper error for unexpected status code in GetKongVersion

---

test/integration/suite_test.go

Before
```log
INFO: waiting for cluster db16525c-2640-4861-866f-4d5c659b253f and all addons to become ready
INFO: collecting urls from the kong proxy deployment
WARNING: failure occurred, performing test cleanup
INFO: cluster db16525c-2640-4861-866f-4d5c659b253f is being deleted
Error: tests failed: All attempts fail:
#1: failed getting kong version from http://172.18.0.101:8001: 401 Unauthorized: {"message":"Invalid RBAC credentials"}
#2: failed getting kong version from http://172.18.0.101:8001: 401 Unauthorized: {"message":"Invalid RBAC credentials"}
#3: failed getting kong version from http://172.18.0.101:8001: 401 Unauthorized: {"message":"Invalid RBAC credentials"}
#4: failed getting kong version from http://172.18.0.101:8001: 401 …
```

chore(tests): better logging for retries of GetKongVersion

---

hack/generators/controllers/networking/main.go
internal/controllers/configuration/kongadminapi_controller.go
internal/controllers/configuration/secret_controller.go
internal/controllers/configuration/zz_generated_controllers.go

We defined a `Reconciler` interface in `internal/controllers` to use it in envtests. While the reconcilers in `internal/controllers/configurations` does not satisfy the interface, because they do not have the `SetLogger` method. 
This PR adds the method to ALL reconcilers in `configurations` package (including the generated reconcilers), and also an assignment statement to verify the satisfaction of the interface. 
**Which issue this PR fixes**:  

chore: add SetLogger to all reconcilers to use them in envtest

---

CHANGELOG.md
internal/dataplane/parser/translate_grpcroute.go
internal/dataplane/parser/translate_grpcroute_test.go
internal/dataplane/parser/translators/grpcroute_atc.go
internal/dataplane/parser/translators/grpcroute_atc_test.go
internal/dataplane/parser/translators/grpcroute_test.go
internal/dataplane/parser/translators/httproute_atc.go
internal/dataplane/parser/translators/httproute_atc_test.go

Implement assigning priorities to Kong routes translated from `GRPCRoute`.
fixes #4250 

feat: implement assignment of priorities to Kong routes from GRPCRoutes

---

internal/manager/config.go
internal/util/test/controller_manager.go
internal/util/test/crds.go
internal/util/test/rbacs.go

- Use RBACs permissions in integration test for faster feedback related permission problems.
- We've run the integration tests with cluster-admin permissions.
fixes #2617 

tests: add impersonation to integration test

---

.github/workflows/pr_checks.yaml

Fixes the up-to-date job condition in CI.

ci: fix up-to-date job

---

hack/cleanup/gke_clusters.go

This PR adds skipped cluster name logging in the cleanup job to get more visibility into what clusters are running in the `k8s-team-playground` project.

chore(ci): log skipped gke clusters

---

.github/dependabot.yml

Instead of having one PR per dependencies, groups are updated together in one.

ci(deps): group updates of several dependencies

---

internal/konnect/node_agent_test.go

This PR fixes `TestNodeAgent_TickerResetsOnEveryNodesUpdate` flakiness which is most likely caused by time duration rounding errors since we're moving the ticker each time by half the tick period.
Verified by running:
```
go test -race -c ./internal/konnect && echo done && ./konnect.test -test.run TestNodeAgent_TickerResetsOnEveryNodesUpdate -test.count 10000
```
and then 
```
while ./konnect.test -test.run TestNodeAgent_TickerResetsOnEveryNodesUpdate -test.count 1000; do ; done
```
continuously and no failures were detected locally.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/4495

tests: fix flaky TestNodeAgent_TickerResetsOnEveryNodesUpdate

---

.github/ISSUE_TEMPLATE/release.yaml
.github/workflows/_integration_tests.yaml
.github/workflows/e2e_nightly.yaml
.github/workflows/test_nightly.yaml
test/consts/helm.go
test/internal/helpers/ktf.go
test/internal/testenv/testenv.go

Since in charts 2.26.1 we fixed the parsing of semvers, we update the charts to the latest 2.26.3. 

test: update helm chart version to the latest

---

.github/workflows/_integration_tests.yaml
FEATURE_GATES.md

Add `RewriteURIs` to `FEATURE_GATES.md`.
part of #4397
REVIEW: do we add a brief introduction of feature of rewrite URIs in `FEATURE_GATES.md`?

docs: add RewriteURI to `FEATURE_GATES.md`

---

.github/workflows/_integration_tests.yaml

fix e2e nightly: add definition of `kong-oss-effective-version` and `kong-enterprise-effective-version`.
fixes failures of e2e nightly failures.

fix: define vars for effective semver in manifest of integration tests

---

CHANGELOG.md

chore(docs) add 2.10.5 changelog

---

internal/dataplane/kongstate/kongstate.go
internal/dataplane/kongstate/kongstate_test.go
internal/dataplane/parser/testdata/golden/kongplugin-instance-name/default_golden.yaml
internal/dataplane/parser/testdata/golden/kongplugin-instance-name/in.yaml
test/integration/plugin_test.go

2.11 backport of https://github.com/Kong/kubernetes-ingress-controller/pull/4588; I forgot the label.

fix(plugins) add suffix to instance_name

---

Dockerfile

This PR effectively starts using the go mod cache (by default `$GOPATH/pkg/mod`) which we already cache using the built in mechanism of `actions/setup-go@v4`.

feat(build): add docker cache mounts for go mod cache

---

.github/workflows/_e2e_tests.yaml

fix wrong yaml layers for `go-version-file` in workflow manifests
fixes the failing e2e nightly https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6092752294

chore: fix workflow manifests for go-version-file

---

test/conformance/gateway_conformance_test.go
test/conformance/gateway_expermimental_conformance_test.go

test: enable `GatewayWithAttachedRoutes` test

---

internal/controllers/gateway/gateway_utils.go
test/conformance/gateway_conformance_test.go

test(conformance): `gatewayclassGenerationBump` test enabled

---

.github/workflows/validate_kong_image.yaml

Add comment when kong image validation workflow fails

ci: add comment when kong image validation workflow fails

---

CHANGELOG.md
internal/annotations/annotations_test.go
internal/dataplane/parser/translate_ingress_test.go
internal/dataplane/parser/translators/ingress.go
internal/dataplane/parser/translators/ingress_test.go
test/integration/ingress_test.go

Replaces the `${1}` rewrite format with `$1` to be more intuitive to other pattern matching libraries.
N/A

feat(rewrite): Remove braces from the rewrite annotation format

---

test/envtest/run.go

It seems that controller-runtime can still log after the manager `.Run()` has exited:
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6259344239/job/16995194592?pr=4703
```
==================
WARNING: DATA RACE
Read at 0x00c0001efd10 by goroutine 3282:
bytes.(*Buffer).String()
/opt/hostedtoolcache/go/1.21.1/x64/src/bytes/buffer.go:71 +0x91
github.com/kong/kubernetes-ingress-controller/v2/test/envtest.RunManager.func2()
/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/run.go:118 +0x71
testing.(*common).Cleanup.func1()
/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1169 +0x182
testing.(*common).runCleanup()
/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1347 +0x1c2 …
```

tests: fix data race when accessing manager buffer in envtest based tests

---

CHANGELOG.md

In follow-up to #4699, explicitly state the deprecations in preparation for KIC v3.0.
Part of #4699
n/a

changelog: add 2.12 deprecations

---

.github/workflows/checks.yaml
README.md

chore: fix build badge

---

config/crd/bases/configuration.konghq.com_kongingresses.yaml
deploy/single/all-in-one-dbless-enterprise.yaml
deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
deploy/single/all-in-one-dbless-konnect-enterprise.yaml
deploy/single/all-in-one-dbless-konnect.yaml
deploy/single/all-in-one-dbless-legacy.yaml
deploy/single/all-in-one-dbless.yaml
deploy/single/all-in-one-postgres-enterprise.yaml
deploy/single/all-in-one-postgres.yaml
docs/api-reference.md
pkg/apis/configuration/v1/kongingress_types.go

Update `KongIngress` CRD doc by mentioning the allowed values.

chore: update KongIngress algorithm CRD doc

---

internal/dataplane/parser/parser_test.go

Another approach on #4777. Instead of changing the code to produce the service route this changes the asserts in `TestParserSNI` to not care about their order

chore(tests): fix flaky asserts in TestParserSNI

---

.github/workflows/check_fixed_issues_references.yaml
.github/workflows/e2e_nightly.yaml
hack/check_fixed_issues_references.sh
hack/generators/controllers/networking/main.go
internal/admission/validation/gateway/httproute.go
internal/controllers/gateway/gateway_controller.go
internal/controllers/gateway/route_utils.go
internal/dataplane/kongstate/upstream.go
internal/dataplane/synchronizer.go
pkg/apis/configuration/v1/kongingress_types.go
test/integration/gateway_test.go

Fixes #4676 
CI failure Example: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6432953458/job/17468963648?pr=4778
Slack notification example: https://kongstrong.slack.com/archives/C0576JF24DB/p1696600883506559

check issues state

---

internal/manager/telemetry/reports.go
internal/manager/utils/kongconfig/root.go
internal/manager/utils/kongconfig/root_test.go
test/internal/helpers/kong.go

The proposition in comment https://github.com/Kong/kubernetes-ingress-controller/pull/4810#discussion_r1354343208 to increase test coverage inspired refactoring helpers used in tests to make code DRY and better covered with tests (because it uses helpers already covered with tests now).

chore(refactor): reuse tested code in test helpers

---

hack/deploy-admission-controller.sh

Fixes `deploy-admission-controller.sh` on darwin.
Fixes: #4787

fix: fix deploy-admission-controller.sh broken on darwin

---

test/integration/translation_failures_test.go

fix the flake in integration tests on translation failure events. 
If multiple events related to the same object received, but the first one does not contain the expected reason while others may contain, the test failes. 
Example failing runs:https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6541857852/job/17763999399?pr=4780   
fixes #4861
~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ No CHANGELOG update needed

test: fix flake on finding translation failure events if multiple events received

---

README.md

Brush up documentation for release 3.0.0. Showcase Gateway API.  As mentioned in the issue document that it is still in beta and will be GA soon. 
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4714
After the release of https://docs.konghq.com/kubernetes-ingress-controller/latest/ for KIC 3.0.0 double-check every link in that README.

chore(docs): update README for KIC 3.0.0

---

CHANGELOG.md

Adds a changelog entry for #5030.

chore: add #5030 changelog entry for release 2.12.1

---

hack/generators/controllers/networking/main.go
internal/clients/manager.go
internal/cmd/rootcmd/servers.go
internal/controllers/configuration/secret_controller.go
internal/controllers/configuration/zz_generated_controllers.go
internal/controllers/gateway/gateway_utils.go
internal/controllers/gateway/gatewayclass_controller.go
internal/controllers/gateway/grpcroute_controller.go
internal/controllers/gateway/httproute_controller.go
internal/controllers/gateway/tcproute_controller.go
internal/controllers/gateway/tlsroute_controller.go
internal/controllers/gateway/udproute_controller.go
internal/dataplane/configfetcher/config_fetcher.go
internal/dataplane/deckgen/generate.go

chore(logs): modifying the capitalization consistency of the logs - Part4

---

internal/diagnostics/server.go
internal/konnect/node_agent.go
internal/license/agent.go
internal/manager/featuregates/feature_gates.go
internal/manager/featuregates/feature_gates_test.go
internal/manager/setup.go
internal/store/store.go

chore(logs): modifying the capitalization consistency of the logs - Part5

---

CHANGELOG.md
hack/cleanup/gke_clusters.go
hack/cleanup/konnect_runtime_groups.go
hack/generators/controllers/networking/main.go
internal/cmd/rootcmd/servers.go
internal/controllers/configuration/zz_generated_controllers.go
internal/controllers/gateway/gateway_controller.go
internal/controllers/gateway/gatewayclass_controller.go
internal/controllers/gateway/grpcroute_controller.go
internal/controllers/gateway/httproute_controller.go
internal/controllers/gateway/referencegrant_controller.go
internal/controllers/gateway/tcproute_controller.go
internal/controllers/gateway/tlsroute_controller.go
internal/controllers/gateway/udproute_controller.go

more about `internal/controllers/gateway`

chore(logs): modifying the capitalization consistency of the logs about internal/controllers/gateway

---

CHANGELOG.md
LICENSES
config/image/oss/kustomization.yaml
test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect.yaml
test/e2e/manifests/all-in-one-dbless.yaml
test/e2e/manifests/all-in-one-postgres-enterprise.yaml
test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
test/e2e/manifests/all-in-one-postgres.yaml

Release 3.0.0-rc1
Part of #5017

chore: release 3.0.0-rc1

---

test/envtest/gatewayclass_envtest_test.go

This PR:
- changes the usage of a non-sleep busy loop which made the rate limiter to kick in in tests
- prevents using a cancelled context in an assertion which would then fail ( due to the context being cancelled, not due to the assertion invariant being violated)
```
case <-ctx.Done():
gateway, err := gwClient.Get(ctx, gw.Name, metav1.GetOptions{})
```
Exemplar failure on CI: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6743686236/job/18332099697#step:4:821

tests: fix flaky TestGatewayWithGatewayClassReconciliation envtest based test

---

CHANGELOG.md
internal/dataplane/kong_client.go
internal/dataplane/kongstate/kongstate.go
internal/dataplane/kongstate/route.go
internal/dataplane/parser/backendref.go
internal/dataplane/parser/ingressrules.go
internal/dataplane/parser/parser.go
internal/dataplane/parser/parser_test.go
internal/dataplane/parser/translate_grpcroute.go
internal/dataplane/parser/translate_httproute.go
internal/dataplane/parser/translate_tlsroute.go
internal/dataplane/parser/translate_udproute.go
internal/dataplane/sendconfig/inmemory_error_handling.go
internal/dataplane/sendconfig/kong.go
internal/dataplane/sendconfig/sendconfig.go
internal/dataplane/synchronizer.go
internal/diagnostics/server.go
internal/license/agent.go
internal/manager/health_check.go

(cherry picked from commit 6e1bbc917971035ca4f40b0d100c5ddd61f4c7b4)

[backport] chore(logs): The log format starts with a capital letter in internal/dataplane (#5065)

---

CHANGELOG.md

Make the last 3 releases' titles link to their diffs similarly to the rest.

chore: make the last 3 releases' titles link to their diffs

---

internal/dataplane/configfetcher/config_fetcher.go
internal/dataplane/configfetcher/kongrawstate.go
internal/dataplane/configfetcher/kongrawstate_test.go

(cherry picked from commit 477e93229d3d29ac0ef918333468b3e1ed0b5b81)

[backport] fix: fix a panic when receiving a broken config from Gateway (#5003)

---

CHANGELOG.md
config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
config/crd/bases/configuration.konghq.com_kongplugins.yaml
internal/admission/errors.go
internal/admission/validator.go
internal/admission/validator_test.go
pkg/apis/configuration/v1/kongclusterplugin_types.go
pkg/apis/configuration/v1/kongplugin_types.go
test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect.yaml
test/e2e/manifests/all-in-one-dbless.yaml
test/e2e/manifests/all-in-one-postgres-enterprise.yaml
test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
test/e2e/manifests/all-in-one-postgres.yaml
test/envtest/crds_envtest_test.go

feat(crd): enforce KongPlugin and KongClusterPlugin's `plugin` field be immutable via CRD validation rules

---

test/integration/ingress_test.go

This PR fixes (and refactors) `TestIngressRewriteURI` (introduced by an outside contributor, not run in CI for his PR)
- commit aecf725028290cf477284cf3a2edee4366eabb03 checks properly feature flag, fixing it allows us to run this test end-to-end for the first time and reveal that it's broken
- commit 0dddac5595aee88d40d4a0999de3611e85f24fcb contains actual refactor and fixes to make it check what it's supposed to check when introduced
This is a part of https://github.com/Kong/kubernetes-ingress-controller/issues/5021 (it doesn't contain a fix for the issue described, but ensures that what was provided works). The actual test for it and the fix will be provided in subsequent PR.

fix(test): TestIngressRewriteURI

---

internal/dataplane/translator/translate_ingress_test.go

tests: add unit test for ingress with default backend targeting the same Service

---

.github/workflows/_conformance_tests.yaml
.github/workflows/_integration_tests.yaml
.github/workflows/checks.yaml

Dump KIC's logs to a separate file and upload it to reduce the logs in GH actions.
fixes #5191
REVIEW: upload logs only integration/conformance tests fails?
~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ No need to update changelog

test: output logs to separate file and upload the file

---

.github/workflows/benchmarks.yaml
.github/workflows/checks.yaml

If we make changes to `docs`, `keps`, or `*.md` files, there is no need to run all tests. This will save us time.
fixes: https://github.com/Kong/kubernetes-ingress-controller/issues/5206

chore(test): skip test when only docs be changed

---

README.md

Because the standard channel only includes a subset of resources, users who follow this document will not be able to access all the functions that KIC has already provided.

chore(docs): install GWAPI from experimental channel

---

README.md

Before this PR - the README quick start only has the Helm option.
After this PR - the README has not only Helm but also KGO as an option.

docs(readme): add KGO instructions alongside Helm

---

CHANGELOG.md
internal/dataplane/translator/subtranslator/grpcroute.go
internal/dataplane/translator/subtranslator/grpcroute_test.go
internal/dataplane/translator/testdata/golden/grpcroute-example/default_golden.yaml

fix: set tags on GRPCRoute routes (follow-up)

---

test/integration/ingress_test.go
test/internal/helpers/setup.go

- Skip ingress test case `TestIngressRewriteURI` if feature gate `RewriteURI` is not enabled
- add logs when `Cleanup` of test starts
part of #5272 

test: skip TestIngressRewriteURI if rewrite uri is disabled

---

.github/workflows/_e2e_tests.yaml
.github/workflows/_integration_tests.yaml
.github/workflows/test_nightly.yaml

This will resolve the block of #5346 's CI

Backport 1p creds to release/2.12.x

---

CHANGELOG.md

part of https://github.com/Kong/kubernetes-ingress-controller/issues/5257

docs: update v2.12.3 release date

---

CHANGELOG.md

docs: add the CHANGELOG for v2.12.3

---

CHANGELOG.md

docs: Add CHANGELOG for v3.0.2

---

.github/workflows/_performance_tests.yaml
test/e2e/performance_basic_test.go

* added plugin and consumer resources
* update comments

refactor performance test

---

CHANGELOG.md
LICENSES
config/image/oss/kustomization.yaml
test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect.yaml
test/e2e/manifests/all-in-one-dbless.yaml
test/e2e/manifests/all-in-one-postgres-enterprise.yaml
test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
test/e2e/manifests/all-in-one-postgres.yaml

- Adds release highlights (following the release blog post) to the changelog, reorders entries to match the highlights
- Bumps KIC version in manifests 
- Updates licensing report
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/5443.

chore: prepare release 3.1.0

---

.github/workflows/_performance_tests.yaml
.github/workflows/performance_nightly.yaml
.github/workflows/performance_targeted.yaml
test/e2e/performance_basic_test.go

test(perf): Reduce time consumption by using batch writing.

---

.github/workflows/performance_nightly.yaml

fix: typo in performance nightly workflow

---

.github/test_dependencies.yaml
CHANGELOG.md
Makefile
config/webhook/manifests.yaml
internal/admission/handler.go
internal/controllers/gateway/gateway_controller.go
internal/controllers/gateway/gateway_controller_test.go
internal/controllers/gateway/gateway_utils.go
internal/controllers/gateway/gatewayclass_controller.go
internal/controllers/gateway/route_utils.go
internal/controllers/gateway/route_utils_test.go
test/envtest/admission_webhook.go
test/envtest/admission_webhook_envtest_test.go
test/envtest/kong.go
test/envtest/log.go
test/envtest/run.go
test/integration/webhook_test.go
test/kongintegration/containers/kong.go

backport PRs to release/3.1.x

---

CHANGELOG.md

chore: prepare release 3.1.1

---

CHANGELOG.md

Update CHANGELOG for KIC 3.1.2 release.
part of #5693.

prepare release 3.1.2: update CHANGELOG for kic 3.1.2

---

test/integration/isolated/tcproute_test.go
test/integration/isolated/udpingress_test.go
test/integration/isolated/udproute_test.go

To have nicer logs in case of a failure, pass `t *testing.T` to helpers. 
Spotted during CR for https://github.com/Kong/kubernetes-ingress-controller/pull/5743

chore(tests): improve helpers - pass `t *testing.T`

---

.github/workflows/_docker_build.yaml
Dockerfile
Dockerfile.debug
Makefile
skaffold.yaml

Similar to https://github.com/Kong/gateway-operator-archive/pull/1554 add GOCACHE to Dockerfile and skaffold configs.

build: add GOCACHE to Dockerfile and skaffold

---

.tools_versions.yaml
Makefile
third_party/go.mod
third_party/go.sum
third_party/staticcheck.go

Take 2 of #5767 that accidentally got pushed to `main` and then reverted to get a proper review

ci: manage staticcheck with mise

---

.github/workflows/nightly.yaml

ci: remove GHA environment for nightly build

---

test/integration/tlsroute_test.go
test/internal/helpers/http.go

There is a flake for [TestTLSRoutePassthroughReferenceGrant](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8473218350/job/23217091804#step:6:2036) that will benefit from better logging and also too verbose logs for checking HTTP request, [see](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8466614681/job/23195800536#step:7:153).

chore(tests): improve logging in tests

---

internal/dataplane/synchronizer_test.go

Fixes the flaky test by adjusting the wait time essentially.
This PR also makes the fake client's `Update()` cancellable. 
Observed in this CI run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8523330437/job/23345436484?pr=5789#step:4:1266
```
=== RUN   TestSynchronizer_IsReadyDoesntBlockWhenDataPlaneIsBlocked
=== RUN   TestSynchronizer_IsReadyDoesntBlockWhenDataPlaneIsBlocked/dbmode=off
--- PASS: TestDeleteReferencesByReferrer/should_delete_references_with_referrer_correctly (0.16s)
=== RUN   TestDeleteReferencesByReferrer/should_not_delete_unrelated_references
synchronizer_test.go:115: verifying the first update happened and the synchronizer is ready
ok  	github.com/kong/kubernetes-ingress-controller/v3/internal/controllers/ga …
```

tests: fix flaky `TestSynchronizer_IsReadyDoesntBlockWhenDataPlaneIsBlocked`

---

test/integration/ingress_test.go

Fix flaky `TestIngressMatchByHost` test where ingress update can fail due to out of date resource.
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8543799014/job/23408483398?pr=5797#step:7:647
```
ingress_test.go:1031: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/ingress_test.go:1031
Operation cannot be fulfilled on ingresses.networking.k8s.io "httpbin": the object has been modified; please apply your changes to the latest version and try again
Test:       	TestIngressMatchByHost
```
Complete these before marking the PR as `ready to …

tests: fix flaky TestIngressMatchByHost

---

CHANGELOG.md

What it says on the tin. Forgot the fix entry for this earlier.

chore(docs) add missing changelog for #5817

---

test/integration/httproute_test.go

There is an occasional flake related to HTTPRoute integration tests, see [example run](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8621585001/job/23630872881#step:7:550), improve logs/assertions for better understanding what happened when it occurs again.
Ideally one day all our tests will use those `EventuallyWithT` assertions, but I think we are good for now doing it opportunistically.

chore(tests): better logs for HTTPRoute integration tests

---

.github/workflows/validate_kong_image_trigger_via_label.yaml

Trigger a "validate Kong image" workflow from `ci/run-validate-kong-image` label.
fixes #5838 

add workflow to trigger "validate kong image" from issue label

---

.github/workflows/validate_kong_image_trigger_via_label.yaml

Fix the workflow to trigger validate Kong image tests.

fix: add runs-on to `check-and-remove-issue-label`

---

Dockerfile
Dockerfile.debug
go.mod
third_party/go.mod

Bump golang version to 1.21.9 in release 3.0.x.
Part of #5900

backprt: bump golang to 1.21.9 in 3.0.x

---

CHANGELOG.md

Add changelog entries of 2.12.x
changelog part of #5949 

add 2.12.4 changelog entries

---

.github/workflows/validate_kong_image_trigger_via_label.yaml

Add `checkout repository` step in each job of trigger Kong image validate workflow.

chore: add checkout step to each job in trigger kong image test workflow

---

internal/dataplane/kongstate/kongstate.go

refactor: refactor getPluginRelations

---

CHANGELOG.md

Add changelog entries for releasing KIC 3.0.3.

prepare changelog for 3.0.3

---

internal/store/cache_stores_snapshot.go

Fixes failing CI for https://github.com/Kong/kubernetes-ingress-controller/commit/6e16f279b1f9590115d60221809da4443e3ba8c5

fix: replace c.listAllStores() with c.ListAllStores()

---

internal/dataplane/kong_client_test.go

Review suggestion to https://github.com/Kong/kubernetes-ingress-controller/pull/6073.

review suggestion: add unit test

---

test/conformance/gateway_conformance_test.go

Enable `HTTPRoutePathRewrite` test
Closes #3686

conformance: enable HTTPRoutePathRewrite test

---

test/integration/vault_test.go

Fix flaky ingress update in `TestCustomVault`
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/9368732308/job/25791617751?pr=6127#step:7:1052
```
vault_test.go:121: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/vault_test.go:121
Operation cannot be fulfilled on ingresses.networking.k8s.io "httpbin": the object has been modified; please apply your changes to the latest version and try again
Test:       	TestCustomVault
```

tests: fix flaky `TestCustomVault` test

---

.github/ISSUE_TEMPLATE/release.yaml

Update release issue template with steps to update CRDs and RBAC policy rules upon release.

chore: add notes in release procedure about updating CRDs in charts

---

.github/workflows/conformance_tests_report.yaml

Install mise as it's a prereq for the Makefile targets.

chore(ci): add mise install step to conformance tests report

---

CHANGELOG.md

chore: fix 3.2.0 changelog

---

.github/ISSUE_TEMPLATE/release.yaml

Update the release procedure to include an additional step for appointing a dedicated person to perform testing of newly released features by following documentation. Fix also some typos.

chore: update release procedure

---

test/conformance/gateway_conformance_test.go

According to the found in #6144, the comment has been updated.

chore: update comment about gRPCRoute conformance test

---

.github/workflows/performance_nightly.yaml

Before the performance test nightly, there was no drawing result, which I overlooked. Now I have completed it.
The following is the job that I have triggered and started running.
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/9648219872

ci(perf): draw report for performance test

---

CHANGELOG.md

Prepare changelog for KIC 2.12.5
Part of #6233 

prepare changelog for release 2.12.5

---

CHANGELOG.md

"Forward port" changelogs of 2.12.4 and 2.12.5 into main.

docs(changelog): add changelog for 2.12.4 and 2.12.5 into main

---

CHANGELOG.md
internal/dataplane/kongstate/kongstate.go
internal/dataplane/kongstate/kongstate_test.go
internal/util/objectmeta.go
internal/util/objectmeta_test.go

Correct the settings of the reference checker when we check the permission of referencing to a plugin.
The reference checker checks for if the "target" (former arg, on the "from" part of `ReferenceGrant.Spec`) is allowed to refer to "request" (latter arg, on the "to" part), so we should put the referrer on the first arg and namespace/name of plugin on the second arg for creating a reference checker.
fixes #6290 

fix(plugin): fix filling type meta and namespace in plugin reference check

---

CHANGELOG.md
docs/cli-arguments.md
internal/adminapi/client.go
internal/adminapi/konnect.go
internal/dataplane/kong_client.go
internal/dataplane/kong_client_test.go
internal/manager/config.go

feat: --konnect-disable-consumer-sync flag

---

.github/ISSUE_TEMPLATE/release.yaml

We agreed on doing retro only after a release. So let's have the person releasing schedule the meeting.

docs: add retro to release checklist

---

internal/clients/readiness.go

https://github.com/Kong/kubernetes-ingress-controller/issues/5068#issuecomment-2232675192
When there are a large number of DPs, by modifying the status check of the gateway client to be concurrent, it can shorten the time it stays in pending state and synchronize the configuration to DP faster.
related https://github.com/Kong/kubernetes-ingress-controller/issues/5068

chore: make the status check of the gateway client to be executed concurrently

---

CHANGELOG.md

Prepare changelog for 2.12.6.
part of #6401 

update changelog for 2.12.6

---

CHANGELOG.md

Add change log entries for 3.2.4 and 2.12.6.

chore(changelog): Add changelog entries for 3.2.4 and 2.12.6

---

CHANGELOG.md
config/image/oss/kustomization.yaml
test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect.yaml
test/e2e/manifests/all-in-one-dbless.yaml
test/e2e/manifests/all-in-one-postgres-enterprise.yaml
test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
test/e2e/manifests/all-in-one-postgres.yaml

part of https://github.com/Kong/kubernetes-ingress-controller/issues/6439 

chore(release): prepare 3.3.0 release

---

CHANGELOG.md

chore(docs): Add the compare link in Changelog

---

CHANGELOG.md

Add highlight items in KIC 3.3 release
Part of #6439 

Chore(changelog): add highlight items for KIC 3.3

---

CHANGELOG.md

Prepares release 3.3.1.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/6458.

chore: prepare 3.3.1 release

---

.github/dependabot.yml
.github/workflows/_linters.yaml
config/crd/bases/configuration.konghq.com_ingressclassparameterses.yaml
config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml
config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml
config/crd/bases/configuration.konghq.com_kongconsumers.yaml
config/crd/bases/configuration.konghq.com_kongcustomentities.yaml
config/crd/bases/configuration.konghq.com_kongingresses.yaml
config/crd/bases/configuration.konghq.com_konglicenses.yaml
config/crd/bases/configuration.konghq.com_kongplugins.yaml
config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml
config/crd/bases/configuration.konghq.com_kongvaults.yaml
config/crd/bases/configuration.konghq.com_tcpingresses.yaml
config/crd/bases/configuration.konghq.com_udpingresses.yaml
config/crd/incubator/incubator.ingress-controller.konghq.com_kongservicefacades.yaml
test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect.yaml
test/e2e/manifests/all-in-one-dbless.yaml
test/e2e/manifests/all-in-one-postgres-enterprise.yaml
test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
test/e2e/manifests/all-in-one-postgres.yaml

Same thing as in https://github.com/Kong/gateway-operator/pull/588

chore: group dependabot k8s libs bumps

---

Makefile

After https://github.com/jwillker/asdf-go-junit-report/pull/4 got merged we can now get back to using upstream's version.

chore: get back to using junit's upstream version of mise plugin

---

.github/ISSUE_TEMPLATE/release.yaml

It wasn't clear what the content of the invite should be.

docs(release): improve task about retro in release issue template

---

test/envtest/kongupstreampolicy_test.go

Similar to #6624 but for `KongUpstreamPolicy` tests:
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/11705687389/job/32601184853?pr=6624#step:6:1080
```
==================
WARNING: DATA RACE
Write at 0x00c00338a130 by goroutine 21541:
reflect.typedmemmove()
/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/mbarrier.go:225 +0x0
reflect.Value.Set()
/opt/hostedtoolcache/go/1.23.2/x64/src/reflect/value.go:2318 +0x184
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).array()
/home/runner/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20221116044647-bc3834ca7abd/internal/golang/encoding/json/decode.go:586 +0xb2b
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).value() …
```

tests: fix data race in KongUpstreamPolicy envtest tests

---

internal/admission/validation/consumers/credentials/validation.go
internal/admission/validation/consumers/credentials/validation_test.go

chore: remove unused code

---

config/variants/multi-gw/debug/kustomization.yaml

Reintroduce #6652 which was lost by accident in #6619

chore(Makefile): fix target debug.skaffold

---

CHANGELOG.md

update changelog to release v2.12.7
part of https://github.com/Kong/kubernetes-ingress-controller/issues/6710

chore: update changelog for 2.12.7

---

CHANGELOG.md

When submitting the Changelog for version 2.12.7 to the main branch, I received suggestions from @pmalek and made modifications accordingly. I believe we should synchronize this modification to the corresponding release branch.

chore: sync 2.12.7 changelog

---

.github/workflows/_conformance_tests.yaml
.github/workflows/_docker_build.yaml
.github/workflows/_e2e_tests.yaml
.github/workflows/_envtest_tests.yaml
.github/workflows/_integration_tests.yaml
.github/workflows/_kongintegration_tests.yaml
.github/workflows/_linters.yaml
.github/workflows/_test_reports.yaml
.github/workflows/_unit_tests.yaml
.github/workflows/backport.yaml
.github/workflows/check_pr_labels.yaml
.github/workflows/checks.yaml
.github/workflows/e2e_trigger_via_label.yaml

Use `pull_request` instead of `pull_request_target` in CI.
For more information see: https://kongstrong.slack.com/archives/C011RQPHDC7/p1732790590733219

chore(ci): use pull_request instead of pull_request_target

---

.github/ISSUE_TEMPLATE/release.yaml

Add mention in release template about konnect-ui-apps

chore: add mention in release template about konnect-ui-apps

---

test/integration/isolated/suite_test.go
test/internal/helpers/setup.go
test/internal/helpers/teardown.go

chore(tests): dump diagnostics in isolated integration tests

---

.github/ISSUE_TEMPLATE/epic.yaml

We've been in the past few releases working out of umbrella issues for complex tasks (.i.e: epic).
We've also in retros mentionned the need to do some things systematically (docs, user acceptance testing...).
This issue template is an attempt at codifying this
N/A

docs(ISSUE_TEMPLATE): add epic template

---

CHANGELOG.md
internal/dataplane/kongstate/customentity.go
internal/dataplane/kongstate/customentity_test.go
internal/dataplane/testdata/golden/kong-custom-entity-ee/default_golden.yaml
internal/dataplane/testdata/golden/kong-custom-entity-ee/in.yaml

Verify if the referenced `KongPlugin` and `KongClusterPlugin` exists and set `KongCustomEntity`'s status condition accordingly

fix: verify if the referenced KongPlugin/KongClusterPlugin exists and set Programmed condition accordingly

---

internal/dataplane/kong_client.go

When objects fail to apply and KIC receives `sendconfig.UpdateError` from `sendconfig.PerformUpdate()` we should send the raw response error to the diagnostics channel so that it's available through `/debug/config/raw-error`.
This PR fixes this.

fix(debug): fix /raw-error endpoint not serving raw response body

---

test/kongintegration/containers/kong.go

This PR solves an issue with envtest suite where tests sometimes fail to start kong container due to already occupied port.
This shouldn't happen because we use https://github.com/Kong/kubernetes-ingress-controller/blob/cf7445545707789c5052f089e5a93b419b06d970/test/helpers/ports.go but it still does happen sometimes.
Exemplar tests fail locally:
```
admission_webhook_envtest_test.go:185: starting envtest environment for test TestAdmissionWebhook_KongPlugins...
admission_webhook_envtest_test.go:185: envtest environment (v1.31.0) started at https://127.0.0.1:53223/
kong.go:88:
Error Trace:    /Users/patryk.malek@konghq.com/code_/kubernetes-ingress-controller/test/kongintegration/containers/kong.go:88 …
```

tests(kongintegration): retry when creating kong's container

---

CHANGELOG.md
FEATURE_GATES.md

Update FEATURE_GATES.md with `KongCustomEntity` being promoted to GA in 3.4.0

chore: update FEATURE_GATES.md

---

renovate.json

Re: https://github.com/Kong/kubernetes-configuration/pull/196

chore(ci): fix extractVersion for kustomize

---

CHANGELOG.md

chore: prepare 3.4.1

---

.github/workflows/backport.yaml
.github/workflows/check_pr_labels.yaml
.github/workflows/e2e_trigger_via_label.yaml

[Backport release/3.3.x] chore(ci): use pull_request instead of pull_request_target

---

CHANGELOG.md

chore: update changelog for 3.4.1

---

.github/workflows/backport.yaml
.github/workflows/check_pr_labels.yaml
.github/workflows/e2e_trigger_via_label.yaml

chore(ci): use pull_request instead of pull_request_target (#6743)

---

.github/workflows/_conformance_tests.yaml
.github/workflows/_docker_build.yaml
.github/workflows/_e2e_tests.yaml
.github/workflows/_envtest_tests.yaml
.github/workflows/_integration_tests.yaml
.github/workflows/_kongintegration_tests.yaml
.github/workflows/_linters.yaml
.github/workflows/_performance_tests.yaml
.github/workflows/_test_reports.yaml
.github/workflows/_unit_tests.yaml
.github/workflows/benchmarks.yaml
.github/workflows/check_fixed_issues_references.yaml
.github/workflows/checks.yaml
.github/workflows/cleanup.yaml
.github/workflows/codeql.yaml
.github/workflows/conformance_tests_report.yaml
.github/workflows/e2e_targeted.yaml
.github/workflows/e2e_trigger_via_label.yaml
.github/workflows/license.yaml
.github/workflows/nightly.yaml
.github/workflows/performance_nightly.yaml
.github/workflows/performance_targeted.yaml
.github/workflows/performance_trigger_via_label.yaml
.github/workflows/regenerate_on_deps_bump.yaml
.github/workflows/release.yaml
.github/workflows/release_docs.yaml
.github/workflows/test_nightly.yaml
.github/workflows/validate_kong_image.yaml
.github/workflows/validate_kong_image_trigger_via_label.yaml

chore(ci): ensure used GitHub action versions are pinned by SHA

---

.github/workflows/_conformance_tests.yaml
.github/workflows/_docker_build.yaml
.github/workflows/_e2e_tests.yaml
.github/workflows/_envtest_tests.yaml
.github/workflows/_integration_tests.yaml
.github/workflows/_kongintegration_tests.yaml
.github/workflows/_linters.yaml
.github/workflows/_performance_tests.yaml
.github/workflows/_permission_check.yaml
.github/workflows/_test_reports.yaml
.github/workflows/_unit_tests.yaml
.github/workflows/backport.yaml
.github/workflows/benchmarks.yaml
.github/workflows/check_fixed_issues_references.yaml
.github/workflows/check_pr_labels.yaml
.github/workflows/checks.yaml
.github/workflows/conformance_tests_report.yaml
.github/workflows/e2e_nightly.yaml
.github/workflows/license.yaml
.github/workflows/nightly.yaml
.github/workflows/performance_nightly.yaml
.github/workflows/performance_targeted.yaml
.github/workflows/regenerate_on_deps_bump.yaml
.github/workflows/release.yaml
.github/workflows/release_docs.yaml
.github/workflows/test_nightly.yaml
.github/workflows/validate_kong_image_trigger_via_label.yaml

Co-authored-by: Patryk Małek <patryk.malek@konghq.com>
(cherry picked from commit 013ebfbd2bd445c44e146b660a6b665ca42a8699)
Backport #6924 to `release/3.4.x`.

pin third party workflows by hashes (#6924)

---

.github/workflows/scorecard.yml

Adding `scorecard` code scanning workflow.
Related: https://github.com/Kong/gateway-operator/pull/1004

ci: add scorecard

---

.github/workflows/_docker_build.yaml
.github/workflows/_e2e_tests.yaml
.github/workflows/_integration_tests.yaml
.github/workflows/_test_reports.yaml
.github/workflows/backport.yaml
.github/workflows/benchmarks.yaml
.github/workflows/check_pr_labels.yaml
.github/workflows/e2e_nightly.yaml
.github/workflows/license.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/release_docs.yaml
.github/workflows/test_nightly.yaml

Pin imported 3rd party actions in `release/2.12.x`. Since there are many actions using different versions with `main`, the PR made another run of checking actions.

pin 3rd party actions by hashes

---

.github/dependabot.yml

chore(dependabot): group testcontainers updates

---

.github/dependabot.yml

chore(dependabot): group actions/* updates

---

.github/actions/redhat-opdev-preflight-action/Dockerfile
Dockerfile
Dockerfile.debug
renovate.json

chore: add Dockerfile pins

---

.github/workflows/_conformance_tests.yaml
.github/workflows/_docker_build.yaml
.github/workflows/_e2e_tests.yaml
.github/workflows/_envtest_tests.yaml
.github/workflows/_integration_tests.yaml
.github/workflows/_kongintegration_tests.yaml
.github/workflows/_linters.yaml
.github/workflows/_performance_tests.yaml
.github/workflows/_test_reports.yaml
.github/workflows/_unit_tests.yaml
.github/workflows/benchmarks.yaml
.github/workflows/check_fixed_issues_references.yaml
.github/workflows/checks.yaml
.github/workflows/cleanup.yaml
.github/workflows/codeql.yaml
.github/workflows/conformance_tests_report.yaml
.github/workflows/e2e_targeted.yaml
.github/workflows/e2e_trigger_via_label.yaml
.github/workflows/license.yaml
.github/workflows/nightly.yaml
.github/workflows/performance_nightly.yaml
.github/workflows/performance_targeted.yaml
.github/workflows/performance_trigger_via_label.yaml
.github/workflows/regenerate_on_deps_bump.yaml
.github/workflows/release.yaml
.github/workflows/release_docs.yaml
.github/workflows/test_nightly.yaml
.github/workflows/validate_kong_image.yaml
.github/workflows/validate_kong_image_trigger_via_label.yaml

chore: pin actions to digests

---

test/integration/tlsroute_test.go

change all the error checks to accept `connection reset by peer` for scenarios expecting no response in `TestTLSPassThrough` to fix the nightly failures.

test(integration): change all error checks in TestTLSPassThrough

---

.github/workflows/e2e_nightly.yaml

gateway team has moved Kong OSS nightly images to `kong/kong-dev` from `kong/kong`. We need to update the config of workflows too.

chore(ci):  update kong OSS nightly repo

---

go.mod
go.sum

bump golang.org/x/net to 0.33.0 in release/3.4.x

---

CHANGELOG.md

Update `CHANGELOG.md` in `main` to include the latest release of 3.4.2.

chore(doc): update changelog for 3.4.2

---

CHANGELOG.md

Preparation for release
- https://github.com/Kong/kubernetes-ingress-controller/issues/7176
it will be released from top of `main` branch

chore(release): prepare 3.4.3 release

---

internal/manager/setup.go

Start respecting retry delay and attempt settings from configuration when initializing Kong Admin API clients. This is needed in KGO to set attempt settings to exactly 1 to avoid unnecessary polling.

fix: respect Admin API init retry options

---

internal/controllers/reference/reference.go

Third-party contribution, many thanks to @cangqiaoyuzhuo 
- https://github.com/Kong/kubernetes-ingress-controller/pull/7183
cherry-picked to KIC repo to run CI and merge it successfully (by-pass limitation of current KIC CI setup)

fix: fix the wrong error return value

---

CHANGELOG.md
internal/controllers/gateway/gateway_controller.go
internal/controllers/gateway/gateway_utils.go
internal/controllers/gateway/gateway_utils_test.go

Third-party contribution, many thanks to @potterhe 
- https://github.com/Kong/kubernetes-ingress-controller/pull/7111
cherry-picked to KIC repo to run CI and merge it successfully (by-pass limitation of current KIC CI setup)
fixes https://github.com/Kong/kubernetes-ingress-controller/issues/7031

fix: GatewayReconciler will fall into a loop and cannot converge to stable state

---

internal/adminapi/kong.go
internal/adminapi/kong_test.go
test/mocks/admin_api_handler.go

(cherry picked from commit 3c892d72748882eee85a353f5365dc259266bf8b)
Backport of #7233: Do not check `/status` endpoint when workspace is given.

Do not check Kong gateway status by /status endpoint if workspace is given (#7233)

---

.github/workflows/license.yaml

chore(ci): fix FOSSA

---

CHANGELOG.md

Update changelog for release 3.4.4.
Part of #7309.

prepare release 3.4.4

---

.github/workflows/release.yaml

Retrofit #7326 to `release/2.12.x`.

chore(ci): fix release workflow DockerHub login

---

test/e2e/konnect_test.go

Do not remove control plane roles (called "runtime group roles" then) in cleanups of tests on Konnect.
Equivalent of backporting #7227. 

test(e2e): Do not remove CP roles in cleanups of konnect tests in release/2.12.x

---

.github/workflows/checks.yaml

Run `checks` on `merge_group` event on `main` branch for enabling merge queue on `main`.

chore(ci): run checks on merge_group event

---

CHANGELOG.md
go.mod
go.sum
internal/dataplane/kongstate/kongstate.go
internal/dataplane/testdata/golden/fallback-config-kong-custom-entities-ee/default_golden.yaml
internal/dataplane/testdata/golden/kong-custom-entity-ee/default_golden.yaml
internal/dataplane/testdata/golden/kong-service-facade/expression-routes-on_golden.yaml
internal/dataplane/testdata/golden/kong-service-facade/feature-flag-on_golden.yaml
internal/dataplane/testdata/golden/kongplugin-instance-name/default_golden.yaml
internal/dataplane/translator/translator_test.go

Fill IDs for plugins based on plugin's name and combination of attached service, route, consumer and consumer group.
fixes #7394

fix(kongstate): Fill ID for plugins

---

CHANGELOG.md

Update changelog for KIC 3.4.5.
Part of #7379

chore(release): update changelog for release 3.4.5

---

test/envtest/manager_envtest_test.go

Ignore goroutine leaks happening in the `controller-runtime` framework before https://github.com/kubernetes-sigs/controller-runtime/issues/3218 fixed.
fixes #7423 

test(envtest): Ignore goroutine leaks in controller-runtime

---

.github/test_dependencies.yaml

Update k8s minor versions in kind e2e tests: add 1.32.x back.

chore(ci): update kind k8s minor versions

---

CHANGELOG.md
Makefile
config/crd/incubator/kustomization.yaml
config/crd/kustomization.yaml
docs/api-reference.md
go.mod
go.sum
internal/dataplane/kongstate/kongupstreampolicy.go
internal/dataplane/kongstate/upstream.go
test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect.yaml
test/e2e/manifests/all-in-one-dbless.yaml
test/e2e/manifests/all-in-one-postgres-enterprise.yaml
test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
test/e2e/manifests/all-in-one-postgres.yaml
test/envtest/crds_envtest_test.go

* update the kcfg dependency
* add translate logic for sticky-sessions
[x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR

update kcfg dependency and add translate logic

---

.github/workflows/release_docs.yaml

Updates docs on release in the new documentation repo developer.docshq.com
fixes: #7542

ci(docs): release docs to developer.konghq.com

---

config/crd/incubator/kustomization.yaml
config/crd/kustomization.yaml
docs/api-reference.md
go.mod
go.sum
test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect.yaml
test/e2e/manifests/all-in-one-dbless.yaml
test/e2e/manifests/all-in-one-postgres-enterprise.yaml
test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
test/e2e/manifests/all-in-one-postgres.yaml

chore(dep): update kubernetes-configuration to v1.5.1

---

CHANGELOG.md

part of https://github.com/Kong/kubernetes-ingress-controller/issues/7501

prepare changelog for 3.5.0

---

config/image/oss/kustomization.yaml
test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml
test/e2e/manifests/all-in-one-dbless-konnect.yaml
test/e2e/manifests/all-in-one-dbless.yaml
test/e2e/manifests/all-in-one-postgres-enterprise.yaml
test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
test/e2e/manifests/all-in-one-postgres.yaml

part of https://github.com/Kong/kubernetes-ingress-controller/issues/7501
~- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~

chore: update kic image to 3.5

---

CHANGELOG.md
internal/admission/validation/gateway/httproute.go
internal/admission/validation/gateway/httproute_test.go
internal/dataplane/translator/subtranslator/httproute.go

Use "whitelist" to check filters in HTTPRoutes in validation webhook and translator. For filters not listed in the supported filters, return error (reject by webhook or generate translation error event).
fixes #7581 

Fix(validation): Use whitelist to check HTTPRoute filters in validation webhook

---

CHANGELOG.md

chore: 3.4.8 changelog

---

CHANGELOG.md

chore: fix 3.4.8 changelog

---

.github/test_dependencies.yaml
test/kongintegration/inmemory_update_strategy_test.go
test/kongintegration/kongupstreampolicy_test.go

I will complete two tasks in this PR.  
fixes: https://github.com/Kong/kubernetes-ingress-controller/issues/7604

fix integration EE tests with Kong 3.11

---

CHANGELOG.md

Update changelog for release 3.5.1.
Part of #7653

chore(docs): update changelog for 3.5.1

---

test/internal/helpers/ktf.go

`bitnami/postgres` image repo is gone and the old images are moved to `bitnamilegacy/postgresql`. So we update the image repo to `bitnamilegacy/postgresql` in integration tests to make them run.
Quick fix of #7709 

test(integration) Set postgresql image repo to bitnamilegacy/postgresql

---

test/internal/helpers/ktf.go

(cherry picked from commit 7342711be211b52fe7bef04c67b0a8247f748d4f)

[Backport release/3.4.x] set postgresql image repo to bitnamilegacy/postgresql (#7710)

---

test/internal/helpers/ktf.go

(cherry picked from commit 7342711be211b52fe7bef04c67b0a8247f748d4f)

[Backport release/2.12.x] set postgresql image repo to bitnamilegacy/postgresql (#7710)

---

CHANGELOG.md
internal/dataplane/testdata/golden/tcproute-example/default_golden.yaml
internal/dataplane/testdata/golden/tcproute-example/expression-routes-on_golden.yaml
internal/dataplane/testdata/golden/tlsroute-example/default_golden.yaml
internal/dataplane/testdata/golden/tlsroute-example/expression-routes-on_golden.yaml
internal/dataplane/testdata/golden/udproute-example/default_golden.yaml
internal/dataplane/testdata/golden/udproute-example/expression-routes-on_golden.yaml
internal/dataplane/translator/translate_utils.go
internal/dataplane/translator/translate_utils_test.go

Cherry-pick commits in PR #7700 and address  the comments.
fixes #7699
How to add changelog entry here? Which PR link should we ref, #7700 or this one?

[Cherry-pick] fix: Do not add request-termination on TLSRoute / TCPRoute (#7700)

---

CHANGELOG.md

Update changelog for KIC 3.5.2.
Part of #7716 

docs(changelog): update changlog for KIC 3.5.2

---

CHANGELOG.md
hack/generators/cache-stores/spec.go
internal/controllers/gateway/gateway_controller.go
internal/controllers/gateway/gatewayclass_controller.go
internal/dataplane/fallback/graph_dependencies.go
internal/dataplane/kong_client_golden_test.go
internal/dataplane/translator/translate_certs.go
internal/dataplane/translator/translator.go
internal/dataplane/translator/translator_test.go
internal/manager/run.go
internal/store/fake_store.go
internal/store/store.go
internal/store/zz_generated.cache_stores.go
internal/store/zz_generated.cache_stores_test.go

Requires #7715 to make integration tests pass

[Backport release/3.4.x] fix(translator): check gateway class and do not skip listeners when gateway class is not managed by KIC 
