.github/workflows/_e2e_tests.yaml
`TEST_KONG_KONNECT_ACCESS_TOKEN` was missing and Konnect tests were skipped on GKE.
=> chore(ci): run konnect e2e tests on gke

CHANGELOG.md, go.mod, go.sum, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go
Uses the `FillID` function from `go-kong` to assign deterministic IDs for `Service`, `Route`, and `Consumer` Kong entities that are generated in the K8s -> Kong translation process.
Closes #3906.
=> feat: assign Service, Route and Consumer entities stable IDs

CHANGELOG.md, config/rbac/leader_election_role.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
This PR addresses an issue which doesn't manifest itself when the leader election role is used straight from the manifest file it is defined in but it does when e.g. the role is unmarshalled in code where api groups and resources from those its policy rules might get mixed up.
That for instance, caused problems where the gateway operator generates control plane (cluster) roles and parses the role manifests.
The net result of this PR should be a noop for KIC users but it should fix the above mentioned issue for those that unmarshal the manifests or use them otherwise in code.
Related: https://github.com/Kong/gateway-operator/issues/727
Complete these before marking the PR as `ready to …
=> fix(rbac): fix leader election policy rules

internal/license/agent.go, internal/license/agent_test.go, internal/manager/run.go
Cleans up `license.Agent`, adds a unit test and removes dead code with TODOs that are no longer relevant.
=> chore(konnect): cleanup license agent

internal/dataplane/parser/translate_ingress.go, internal/dataplane/parser/translate_ingress_test.go, internal/dataplane/parser/translators/ingress.go, internal/dataplane/parser/translators/ingress_test.go, internal/dataplane/parser/translators/translator_vars.go
Reorganizes `ingressRulesFromIngressV1` `Parser`'s method so that we can clearly see the boundary between the code called when `CombinedRoutes` feature flag is enabled or not. It also adds missing unit tests for `CombinedRoutes=on` that will be useful for further work on #3777.
Preparation for #3777.
=> refactor: reorganize ingressRulesFromIngressV1 into smaller pieces

Makefile
In local runs of `make test.integration.*`, when `JUNIT_REPORT` is not set, the junit report is redirected to the file named `-set-exit-code`, because it left a space between `-out` and `-set-exit-code`. Here we add a default value `/dev/null` for the env `JUNIT_REPORT` to discard junit report when it is not set, to avoid the incorrect setting when running integration and conformance tests.
~~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~~
=> chore(test): set default junit report output file to null

internal/dataplane/parser/parser_test.go
This PR fixes assertion (and not properly configured test cases) for `TestGetEndpoints` to check not only the number of endpoints, but theirs content too. Moreover for `TestKnativeSelectSplit` switches to assertion library instead of combination of `reflect.DeepEqual` & `t.Errorf`.
It's been spotted during working on https://github.com/Kong/kubernetes-ingress-controller/issues/3916
=> chore(tests): fix assertion for TestGetEndpoints and refactor assertion for TestKnativeSelectSplit

internal/dataplane/parser/translate_ingress.go, internal/dataplane/parser/translate_ingress_test.go
- fixed the generated matcher for default backends in expression routes and added unit tests (exact match of `/` to prefix match of `/`)
- changed `TestGetDefaultBackendService` into table driven format
~~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~~ The fix does not affect released features
=> fix: correct catch-all matcher for translating default backend of ingresses to expression routes

test/integration/webhook_test.go
This PR copies code for helpers `waitForServiceLoadBalancerAddress` & `waitForConnectionOnServicePort` from already merged PR https://github.com/Kong/kubernetes-testing-framework/pull/643 in KTF project. **This is a temporary solution.** The purpose is to have helpers that use EndpointSlices API without upgrading the KTF version. Currently, upgrading is hard due to a dependencies mismatch. If you would like to learn more check issue #3981. It will be reverted when we are able to upgrade KTF.
It's needed to finish https://github.com/Kong/kubernetes-ingress-controller/issues/3916
=> chore(tests): workaround to not rely on helpers from KTF

.github/workflows/_integration_tests.yaml, CHANGELOG.md, internal/dataplane/parser/translate_grpcroute.go, internal/dataplane/parser/translators/atc_utils.go, internal/dataplane/parser/translators/atc_utils_test.go, internal/dataplane/parser/translators/grpcroute.go, internal/dataplane/parser/translators/grpcroute_atc.go, internal/dataplane/parser/translators/grpcroute_atc_test.go, internal/dataplane/parser/translators/grpcroute_test.go, internal/dataplane/parser/translators/httproute_atc.go, internal/dataplane/parser/translators/ingress_atc.go, internal/dataplane/parser/translators/ingress_atc_test.go, test/integration/examples_test.go, test/integration/grpcroute_test.go
translate `GRPCRoute` to expression based kong routes.
fixes #3752 
=> feat: translate grpcroute to expression based routes

go.mod, test/e2e/konnect_test.go, test/internal/helpers/http.go
Adds `helpers.RetryableHTTPClient` that can be used for calling external services that might temporarily fail, and we do not want them to affect tests results.
=> tests: add RetryableHTTPClient util function

CHANGELOG.md, internal/adminapi/backoff_strategy_konnect.go, internal/adminapi/backoff_strategy_konnect_test.go
Makes use of `Retry-After` HTTP header when 429 is returned from Konnect RG's Admin API.
Part of #3959.
=> feat(konnect): propagate 429's retry-after header value

config/rbac/role.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, internal/controllers/configuration/object_references.go, internal/controllers/configuration/secret_controller.go
This PR remove rbac permissions for `secrets/status` subresource, because they are redundant. [According to docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#secret-v1-core) secrets don't contain this field.
It's been spotted during work on https://github.com/Kong/kubernetes-ingress-controller/pull/3997
Issue https://github.com/Kong/charts/issues/795 to covers it in Helm Chart
=> chore(rbac): get rid of rbac permissions for secrets/status

.github/workflows/_e2e_tests.yaml, .github/workflows/e2e_nightly.yaml, .github/workflows/e2e_targeted.yaml, test/e2e/helpers_test.go, test/e2e/utils_test.go
This PR aims to fix the Gateway version override in e2e tests that used an incorrect env variable: `TEST_KONG_KONG_IMAGE_OVERRIDE` instead of `TEST_KONG_IMAGE_OVERRIDE`.
~Currently blocked by #4014 because we cannot run with Gateway versions that report SHA in Admin API `/` response's: `.version` field.~
The above was mitigated by using `kong/kong-gateway-dev:nightly` instead which includes a semver (well not a semver but a 4 segment version instead of SHA which is parsable by `go-kong`'s `kong.ParseSemanticVersion`)
=> fix(ci): fix kong image override

CHANGELOG.md, Makefile, config/base/kustomization.yaml, config/rbac/crds/kustomization.yaml, config/rbac/crds/role.yaml, config/rbac/crds/role_binding.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, internal/controllers/crds/dynamic_controller.go, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/httproute_controller_envtest_test.go, internal/manager/controllerdef.go, internal/manager/scheme/scheme.go, test/e2e/features_test.go
Adds a `crds.DynamicController` that ensures that RequiredCRDs are installed in the cluster and only then sets up all of its Controllers that depend on them. In case the CRDs are not installed at start-up time, DynamicController will set up a watch for CustomResourceDefinition and will dynamically set up its Controllers once it detects that all RequiredCRDs are already in place.
It's used for both the beta and alpha parts of the Gateway API.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3029.
=> feat(gwapi): setup controllers dynamically when required CRDs get installed

test/e2e/features_test.go
Missing `Gateway` and `HTTPRoute` will no longer output the log that was expected in the `TestMissingCRDsDontCrashTheController` as they are using now the `DynamicCRDController` that was introduced in https://github.com/Kong/kubernetes-ingress-controller/pull/3996.
=> tests: align E2E to dynamic handling of GW API CRDs

.github/workflows/e2e_nightly.yaml
k8s-maintainers wants to be notified about  failures of e2e tests run automatically at night on a dedicated Slack channel
I decided not to send notifications in case running those tests manually to avoid unnecessary spamming of a dedicated channel.
The true verification of it will be when we get or do not get a notification in case of failure 🙃
=> chore(ci): Notify on Slack for failures of e2e tests run at night

.github/workflows/_integration_tests.yaml, .github/workflows/e2e_targeted.yaml, .github/workflows/validate_kong_image.yaml
Resolves #4018.
This PR does two things (please review commit by commit):
- refactors the integration tests reusable workflow (`_integration_tests.yaml`) so that the caller can override the "non-enterprise tests" and the "enterprise tests" container images. This is intended to be a non-breaking interface-compatible change.
- adds a workflow that runs the reusable E2E and integration tests workflows. It is intentionally opinionated so as to leave no ambiguity about the desired level of validation.
=> CI workflow for Gateway validation

.github/workflows/_integration_tests.yaml
follow-up to #4028
fixes the misspelled `kong-enterprise-container-repo` param name :grimacing:
=> fix(ci): workflow param name typo

.github/workflows/validate_kong_image.yaml
This makes the parameters printed e.g. in https://github.com/Kong/kubernetes-ingress-controller/issues/4013#issuecomment-1551889541 to be wrapped in a code block
Example how it might look like: https://github.com/pmalek/test/issues/1#issuecomment-1551918124
=> chore(ci): add code block when posting comment in validate kong issue

CHANGELOG.md, internal/dataplane/parser/parser.go, internal/dataplane/parser/translate_failures_test.go, internal/dataplane/parser/translate_knative.go, internal/dataplane/parser/translate_kong_l4.go, internal/dataplane/parser/translate_tcproute.go, internal/dataplane/parser/translate_tlsroute.go, internal/dataplane/parser/translate_udproute.go, test/integration/translation_failures_test.go
When expression router is enabled, we disable translation of the following unsupported objects:
- `knative.Ingress`
- `TCPIngress`
- `UDPIngress`
- `TCPRoute`
- `UDPRoute`
- `TLSRoute`
And generate a translation failure event to each of the objects.
Also, this PR adds an integration test to verify it.
fixes #4000 
=> feat: attach translation failure events to unsupported objects when ExpressionRoutes enabled

.github/workflows/_integration_tests.yaml, .github/workflows/validate_kong_image.yaml
I noticed that the latest test run of the validate kong image workflow hasn't set the expected Kong image for integration tests: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5007227425/jobs/8973545997 
```
if [ "" == "true" ]; then
echo "TEST_KONG_IMAGE=" >> $GITHUB_ENV
echo "TEST_KONG_TAG=" >> $GITHUB_ENV
else
echo "TEST_KONG_IMAGE=" >> $GITHUB_ENV
echo "TEST_KONG_TAG=" >> $GITHUB_ENV
fi
```
This PR aims to solve this issue by referring to inputs correctly. 
Also:
-  adds a comment explaining why we set the same image for enterprise and regular images when we pass inputs to `_integration_tests.yaml` in `validate_kong_image.yaml` as I found this confusing when reading it.
- fixes the URL to workflow embedded in the comment
=> fix(ci): access inputs in integration tests workflow correctly

CHANGELOG.md, internal/clients/config_status.go, internal/clients/config_status_test.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/konnect/node_agent.go, internal/konnect/node_agent_test.go, internal/konnect/nodes/types.go
It extends the config sync status reported to Konnect's Node API with values that take into account failures of syncing configuration with Konnect RG, effectively extending it with three new values (on the API surface level):
- `INGRESS_CONTROLLER_STATE_OPERATIONAL_KONNECT_OUT_OF_SYNC`
- `INGRESS_CONTROLLER_STATE_PARTIAL_CONFIG_FAIL_KONNECT_OUT_OF_SYNC`
- `INGRESS_CONTROLLER_STATE_INOPERABLE_KONNECT_OUT_OF_SYNC`
There's no strict contract for allowed values on the API level, however, there's an implicit contract between KIC and Konnect UI that directly consumes the `Node` object, therefore we're keeping the old values unchanged to make them backward-compatible.
Internal reference: …
=> feat(konnect): account for config sync failures in reported node status

test/integration/suite_test.go, test/internal/helpers/kong.go, test/internal/helpers/ktf.go
This PR will make the custom kong image and tag (specified by the [relevant env variables](https://github.com/Kong/kubernetes-ingress-controller/blob/7ba7e2c15be2696433b6f75a3ad6a1c933aa1d79/test/internal/testenv/testenv.go#L28-L36): `TEST_KONG_IMAGE` and `TEST_KONG_TAG`) visible during integration tests execution.
It also adds a log, printing a version as retrieved from the Admin API when Kong is up and running. This should help (hopefully) catch issues like [this](https://github.com/Kong/kubernetes-ingress-controller/issues/4013#issuecomment-1552998225) faster.
=> tests(integration): more visibililty into customized kong images

CHANGELOG.md, internal/adminapi/endpoints.go, internal/adminapi/endpoints_test.go, internal/controllers/configuration/kongadminapi_controller_envtest_test.go
This changes the implementation Gateway Discovery in a way that it now produces DNS names instead of IP address of Kong's pods.
There are 2 formats that this implementation can use:
- `pod-ip-address.service-name.my-namespace.svc` - when a Kong's `EndpointSlice` that we're trying to convert into an address (that will be used for sending the configuration) contains an owner reference of type `Service` then we use that reference to build the DNS name
- `pod-ip-address.my-namespace.pod` when that `Service` owner reference is missing
Ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
Closes: #3934 
This will be required for Kong Gateway Operator to use TLS …
=> feat: Gateway Discovery produce DNS names instead of IP addresses

.github/workflows/e2e_nightly.yaml
Notification was not sent for the last [e2e tests (nightly)](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5035826541), because `needs` condition is evaluated to [false for skipped jobs too](https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs), and there was no overwrite of it in  in `if`. Now the job executes always after jobs required by `needs` and evaluate `if` anything previously failed to fire an alert on Slack. This is the approach inspired by [this snippet](https://github.com/benjamin-bergia/github-workflow-patterns/blob/master/.github/workflows/ignore-skipped.yml).
Fixes notifications introduced in PR …
=> chore(ci): fix notifications for failures of e2e nightly tests

internal/adminapi/backoff_strategy_konnect.go, internal/adminapi/backoff_strategy_konnect_test.go, internal/dataplane/kong_client.go
Do not log `{Failed, Skipped} pushing configuration to Konnect` one after another, print hex encoded config hash.
=> chore(konnect): improve logging

CHANGELOG.md, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go
Since we did not implement the translator for ingresses and httproutes to expression based routes, we disable expression routes mode of parser when `ExpressionRoutes` is enabled but `CombinedRoutes` is disabled.
fixes #4043 
=> feat: disable expression routes mode when ExpressionRoutes is on but CombinedRoutes is off

examples/gateway-tcproute.yaml, examples/gateway-tlsroute.yaml, test/consts.go
Use the newest image of `kong/go-echo` everywhere in KIC
=> chore(deps): bump go-echo to 0.3.0 everywhere

.github/workflows/validate_kong_image.yaml
Expand #4028
A "validate Kong image (targeted)" workflow run, before this PR:
- on startup, creates an issue comment.
After this PR:
- the same as before, and additionally:
- on __successful__ completion
- creates another issue comment
- closes the issue.
=> ci: add auto issue close and comment to validate kong image workflow

CHANGELOG.md, internal/manager/utils/kongconfig/root.go, internal/manager/utils/kongconfig/root_test.go
Kong with version below 3.0 (2.8.x) does not have `router_flavor` field in configurations. We need to treat them as using `traditional` router flavor, instead of raising an error, because they can only use the traditional router. This PR returns the default `traditional` router flavor if Kong version is below 3.0. 
fixes #4068 
=> fix: assume router_flavor to default value according to kong version if missing

.github/workflows/_integration_tests.yaml, CHANGELOG.md, FEATURE_GATES.md, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/manager/featuregates/feature_gates.go
Adds a default-off `FillIDs` feature gate to allow opting in for the https://github.com/Kong/kubernetes-ingress-controller/issues/3906.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4074
=> feat: add FillIDs feature gate

test/consts.go, test/e2e/features_test.go, test/e2e/helpers_gateway_test.go, test/e2e/helpers_test.go, test/e2e/istio_test.go, test/expressionrouter/generate_test.go, test/integration/config_error_event_test.go, test/integration/consumer_test.go, test/integration/gateway_test.go, test/integration/httproute_test.go, test/integration/ingress_https_test.go, test/integration/ingress_regex_match_test.go, test/integration/ingress_test.go, test/integration/knative_test.go, test/integration/kongingress_test.go, test/integration/plugin_test.go, test/integration/tcpingress_test.go, test/integration/tcproute_test.go, test/integration/tlsroute_test.go, test/integration/translation_failures_test.go
Initial refactor - do not use magic strings and numbers to refer images and their ports used in tests.
This is a part of implementing e2e tests that verifies proper handling of EndpointSlices https://github.com/Kong/kubernetes-ingress-controller/issues/4026
This is the part of implementing strategy proposed in this one too big PR https://github.com/Kong/kubernetes-ingress-controller/pull/4084.
In `test/integration/tlsroute_test.go:765` const `tlsEchoPort` and its usage is a little bit mysterious to me. I backchannelled it to the author to gain more understanding (and maybe handle in different PR).
Labelled with `ci/run-e2e` to be sure, result has to be examined.
**PR Readiness …
=> refactor(tests): use constants for referencing images and ports

test/consts.go, test/integration/tlsroute_test.go
During working on https://github.com/Kong/kubernetes-ingress-controller/pull/4088, I spotted `TestTLSRouteEssentials` that relies on the usage of `TLS_PORT` env variable to configure `go-echo` (it's easy to overlook when you just skim through it). This PR makes it easier to follow for newbies in the codebase.
=> refactor(tests): make TestTLSRouteEssentials easier to follow

test/e2e/helpers_test.go
Since KIC should work with multiple EndpointSlices, it should be covered with tests too. By default `100` endpoints are allowed per `EndpointSlice` thus having `Deployment` with `Service` that uses multiple `EndpointSlice`s is not feasible in CI tests.  This PR configures Kind clusters with `--max-endpoints-per-slice 2` to make possible to test KIC against Services with multiple EndpointSlices.
Next PRs will focus to ensure that test cases actually test it.
This is a part of implementing e2e tests that verifies proper handling of EndpointSlices https://github.com/Kong/kubernetes-ingress-controller/issues/4026.
This is the part of implementing strategy proposed in this one too big PR …
=> feat(tests): set --max-endpoints-per-slice=2 in K8s Kind clusters used in e2e tests

Makefile
For some reason, despite the `-set-exit-code` flag, the `go-junit-report` fails to propagate the error once the tests fail to compile. 
Adding `.SHELLFLAGS := -eu -o pipefail -c` to the Makefile will make all targets using pipes propagate errors as expected.
Sample run that should fail the GH workflow but the exit code was 0 for integration tests (reason for this PR): https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5089899978/jobs/9148069971
**Note**: I have no idea why `.SHELLFLAGS` doesn't work for me on Mac, but it seems it works as expected on GH runners: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5091603544/jobs/9151854177.
=> tests: propagate exit code from makefile targets using pipes

test/e2e/all_in_one_test.go, test/e2e/upgrade_test.go, test/e2e/utils_test.go
In the current setup, the existing upgrade test for DB-less manifests is never executed (sample runs of [e2e nightly](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5041834863/jobs/9041892003) and [e2e targeted](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5025607446/jobs/9013457853)).
This PR aims to fix this by explicitly setting the version of the manifest we'd like to test upgrading from. It also adds one more test case for all-in-one-postgres manifests.
=> tests: make upgrade tests run, add one for postgres

internal/dataplane/kongstate/consumer.go, internal/dataplane/kongstate/consumer_test.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_utils.go, internal/dataplane/parser/translate_utils_test.go, internal/dataplane/sendconfig/inmemory.go, internal/dataplane/sendconfig/inmemory_test.go, internal/dataplane/sendconfig/strategy.go, internal/manager/run.go, internal/versions/deck.go, internal/versions/deck_test.go, internal/versions/versions.go, test/integration/config_error_event_test.go, test/integration/httproute_test.go, test/integration/ingress_regex_match_test.go, test/integration/ingress_test.go, test/integration/plugin_test.go, test/integration/tcpingress_test.go, test/integration/version_test.go, test/internal/helpers/kong.go
This PR removes the usage of kong version singleton. In its place we use kong's version explicitly where needed. Additionally this adds several test helpers which run tests conditionally based on the kong version as from Kong Admin API.
The only place that parser takes Kong Version into account it for Gateway API http regex header matching:
https://github.com/Kong/kubernetes-ingress-controller/blob/1af68ca36af74ae6c60be20c63b0badc9ddf13ae/internal/dataplane/parser/translate_utils.go#L36-L40
=> refactor: don't use kong version singleton

CHANGELOG.md, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gateway_utils_test.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go, internal/util/builder/allowedroutes.go, test/integration/helpers_test.go, test/integration/httproute_test.go
We need to update and keep up to date the `Gateway`'s `AttachedRoutes` field, with the actual number of routes accepted by it.
Fixes #3120 
=> keep Gateway's `AttachedRoutes` field up to date

test/e2e/all_in_one_test.go, test/e2e/compatibilities_test.go, test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/konnect_test.go, test/e2e/kuma_test.go, test/e2e/upgrade_test.go
This PR proposes enhanced approach for testing KIC e2e tests
- Kind clusters have configuration `--max-endpoints-per-slice 2` to make possible to test KIC against Services with multiple EndpointSlices (introduced in #4091)
- basic Ingress deployment and its verification is enhanced to ensure that traffic is routed to every backend by Kong gateway (IPs are in many multiple EndpointSlices)
Rationale - the proper discovery of IP addresses of all backends and setting routings in Kong gateway are the core feature of KIC, thus it should be covered with tests that verify it. Having K8s Kind cluster with such config and enhanced tests allows ensure that KIC with Kong gateway do it properly.
closes #4026, it's the last from the …
=> feat(tests): verify routing to every backend in e2e tests

test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/upgrade_test.go
To prevent failures caused by not being allowed to update jobs' spec when upgrading with `kubectl apply -f` to a newer version of all-in-one manifests, delete the job just before the upgrade. 
Fixes #4097.
We agreed to use `generateName`, but unfortunately it's not supported by Kustomize (see the issue: https://github.com/kubernetes-sigs/kustomize/issues/641). I also tried going with using Kustomize's `replacements` to use the deployment's image tag to append a version-dependent suffix to the migration job's name, but it didn't work either due to deployment not being rendered at that stage yet. I decided to not spend more time on it and just go with a simple delete in the test.
=> tests: delete migrations job before upgrade in e2e test

internal/manager/utils/kongconfig/root.go
This PR addresses the potential lockup situation where KIC is being restarted and provided Admin API addresses (or discovered via Gateway Discovery) have different versions (potential upgrade scenario).
Up until now the KIC would detect this as non homogenous versions and report an error (which would eventually prevent it from getting ready.
This PR relaxes that check by only enforcing the same DB setting detect in Gateways' config on startup.
Closes #4085 
=> chore: relax uniform Gateway version check

CHANGELOG.md, config/variants/postgres/migration.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
`kong migrations bootstrap` alone works fine when installing a fresh instance of KIC with DB-backed Kong. It doesn't work though when we'd like to upgrade and keep the DB state between the upgrades, because it only bootstraps a fresh database - when there is one already in existence, it just returns. 
This PR aims to solve this issue by adding additional commands to the migrations job: `kong migrations up && kong migrations finish` which will make the job detect new migrations that need to be run after the upgrade and finish them. 
It was discovered when writing E2E tests for https://github.com/Kong/kubernetes-ingress-controller/issues/4025.
Complete …
=> feat: all-in-one manifests migrations job improvement

test/e2e/helpers_test.go, test/e2e/konnect_test.go, test/e2e/upgrade_test.go, test/e2e/utils_test.go
It introduces two main changes to the upgrade tests that should make them more reliable:
1. Ensure that after the controller deployment is upgraded, we actually wait until all new replicas are rolled out and become ready so that we're sure that we're testing against the new version.
2. Add a new path to the Ingress after the upgrade is done and test against it to make sure that the new configuration is processed correctly (without that we were only verifying that the old Kong Gateway instance was configured, but it could be the configuration pushed by the old controller).
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5142252037/jobs/9255887769 test failure proves that if we set the feature gate `FillIDs=true`, the upgrade will …
=> tests: make upgrade tests more robust

test/internal/helpers/http.go
Trim trailing `/` s of proxy URL and leading `/` s of path before concatenate the URL to avoid duplicate `/` s .
like: `http://kong.proxy/` + `/foo` -> `http://kong.proxy/foo`
=> test: trim prefix / of path and suffix / of proxy URL in MustHTTPRequest

.github/workflows/_e2e_tests.yaml, .github/workflows/release.yaml
K8s versions
Below versions are not yet available as [kindest:node](https://hub.docker.com/r/kindest/node) thus for them older are used
- `1.26.5`    -> `1.26.4`
- `1.25.10`  -> `1.25.9`
- `1.24.14`  -> `1.24.13`
Istio versions
You can see that `K8s 1.27` is not specified, but we'll test with it anyway.
The newest versions are
**Related issue**:
https://github.com/Kong/kubernetes-ingress-controller/issues/4098
**Notes for reviewer**:
Tests with label `ci-run/e2e` have been run too
=> chore(release): bump K8s & Istio versions for 2.10 release

CHANGELOG.md, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Release of KIC 2.10.0 - bumping KIC image to 2.10.0 and final small adjustments to CHANGELOG
It's a part of https://github.com/Kong/kubernetes-ingress-controller/issues/4098
=> chore(release): prepare release/2.10.0

internal/manager/config_validation.go
We can use `(*regexp.Regexp).MatchString` to avoid an unnecessary byte slice conversion and reduce allocation.
Benchmark code using `(*regexp.Regexp).MatchString`:
```go
func matchString(flagValue string) (string, error) {
re := regexp.MustCompile(`^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*\/[A-Za-z0-9\/\-._~%!$&'()*+,;=:]+$`)
if !re.MatchString(flagValue) {
return "", errors.New("the expected format is example.com/controller-name")
}
return flagValue, nil
}
func match(flagValue string) (string, error) {
re := regexp.MustCompile(`^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*\/[A-Za-z0-9\/\-._~%!$&'()*+,;=:]+$`)
if !re.Match([]byte(flagValue)) {
return "", errors.New("the expected format is …
```
=> perf(config_validation): make regex a global variable and avoid `[]byte` conversion

.github/workflows/release.yaml
For the user checkbox latest is available instead of the manually typed string. Manually typed string is error prone, because when you type true  (with space at the end) it evaluates to false.
closes https://github.com/Kong/kubernetes-ingress-controller/issues/4145
=> chore(ci): make `toggle` latest in release workflow a boolean

.github/workflows/_integration_tests.yaml, CHANGELOG.md, FEATURE_GATES.md, internal/manager/featuregates/feature_gates.go, internal/manager/telemetry/telemetry_test.go
Enables CombinedServices by default and updates test matrix to reflect this.
Fix #3979
See https://github.com/Kong/kubernetes-ingress-controller/issues/3979#issuecomment-1577388487. It looks like we meant to do this for 2.11, but the original issue only requests part of this change.
=> chore(features) enable CombinedServices by default

internal/dataplane/parser/golden_test.go, internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/default_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/default_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/default_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/default_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/regex-path-prefix-off_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/default_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/default_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/default_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/default_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/default_golden.yaml
Updates golden following https://github.com/Kong/kubernetes-ingress-controller/pull/4138
Removes the mysterious `-update-golden` flag that exists only in the comment mentioning it (and very much does not work when passed to `go test` or what have you.
Broken tests in main.
=> Update golden and test hint

CHANGELOG.md, internal/dataplane/parser/parser.go
The message `no active endpoints` is logged often at least once during normal operation due to eventual consistency of the whole K8s ecosystem.
```log
2023-06-12T12:51:30.065792925Z stderr F time="2023-06-12T12:51:30Z" level=info msg="successfully synced configuration to Kong" update_strategy=InMemory url="https://10.244.0.7:8444"
2023-06-12T12:51:30.070302425Z stderr F time="2023-06-12T12:51:30Z" level=info msg="successfully synced configuration to Kong" update_strategy=InMemory url="https://10.244.0.6:8444"
2023-06-12T12:51:30.877209092Z stderr F time="2023-06-12T12:51:30Z" level=info msg="successfully synced configuration to Konnect" update_strategy="WithBackoff(DBMode)" url="https://us.kic.api.konghq.tech/kic/api/runtime_groups/ea93254c-5c46-4b2d …
```
=> chore(logs): `no active endpoints` is logged at debug instead of warning level

.github/workflows/_envtest_tests.yaml, .github/workflows/pr_checks.yaml, Makefile, TESTING.md, config/crd/bases/configuration.konghq.com_kongingresses.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, go.mod, go.sum, internal/controllers/gateway/gateway_utils_test.go, test/envtest/httproute_controller_test.go, test/envtest/manager_debugendpoints_test.go, test/internal/mocks/dataplane.go
This PR continues the effort to document testing practices and expand with explicitly documenting as per #4099.
This also adds:
- separate `test.envtest` `Makefile` target
- related CI job which runs it
Related: #4099
This PR moves some tests to `test/envtest/` but not all of them. This might be done if we agree to pursue this route.
=> tests: separate envtest directory and makefile target

CHANGELOG.md, examples/gateway-grpcroute.yaml, go.mod, go.sum, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/grpcroute_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/translators/httproute.go, internal/util/builder/httproutematch.go, internal/util/conditions.go, internal/util/conditions_test.go, test/conformance/gateway_conformance_test.go, test/consts/zz_generated_gateway.go, test/e2e/helpers_gateway_test.go, test/envtest/httproute_controller_test.go, test/integration/gateway_test.go, test/integration/helpers_test.go
GWAPI upgrades and a conformance fix.
Fix #3726
Fix #2953
Fix #3990 
https://github.com/kubernetes-sigs/gateway-api/pull/1888 and https://github.com/kubernetes-sigs/gateway-api/issues/1832#issuecomment-1483974578 change expectations around statuses. This PR includes changes that adhere to the 0.7.1 conformance test informed by these changes, but it's possible we missed something not covered in conformance. GWAPI doesn't really provide an expected state flowchart for statuses (we have to go off individual condition descriptions in the API docs), which makes it a bit difficult to determine if our state changes are truly correct absent conformance tests.
Changes to conformance suite …
=> chore(deps) update to GWAPI 0.7.1

CHANGELOG.md, internal/dataplane/parser/ingressrules.go, internal/dataplane/parser/ingressrules_test.go, test/integration/translation_failures_test.go
Emit errors for every Service in a multi-Service backend when an annotation is inconsistent.
Previously, the parser would arbitrarily choose one annotation value as the correct value and only log errors for Services with a different value. There was no basis for choosing this as the correct value, it was just the first observed value, and there was no indication which Service was the source of the value. Logging for each informs users of the complete set of Services.
Shortens the log to remove the "review the Route" string, as we're now listing all Services of interest.
Fix #3032
The original request in #3032 was already addressed by a previous change. We were already including …
=> feat(parser) error for all inconsistent services

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, docs/api-reference.md, internal/dataplane/kongstate/util.go, internal/dataplane/kongstate/util_test.go, pkg/apis/configuration/v1/kongclusterplugin_types.go, pkg/apis/configuration/v1/kongplugin_types.go
Adds instance_name to the plugin CRDs and translation functions.
Fix #4140 
No library bumps; this was already added to go-kong and deck earlier.
Basic validation past the units:
```
16:26:49-0700 esenin $ grep -A6 KongPlugin /tmp/instance.yaml
kind: KongPlugin
metadata:
name: kong-id
config:
header_name: kong-id
plugin: correlation-id
instance_name: grapes
16:26:55-0700 esenin $ kubectl apply -f /tmp/instance.yaml   
service/httpbin unchanged
deployment.apps/httpbin unchanged
ingress.networking.k8s.io/httpbin unchanged
kongplugin.configuration.konghq.com/kong-id unchanged
16:26:57-0700 esenin $ grep instance_name /tmp/all-in-one-dbless.yaml -A2 …
```
=> Support plugin instance name

CHANGELOG.md, internal/adminapi/konnect.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/konnect/license/client.go, internal/konnect/license/client_test.go, internal/konnect/license/types.go, internal/license/agent.go, internal/license/agent_test.go, internal/manager/config.go, internal/manager/run.go
Adds `--konnect-initial-license-polling-period` and `--konnect-license-polling-period` CLI flags that allow configuring periods at which we poll license from Konnect.
Changes the `license.Agent`'s behavior so that if it fails to fetch a license at the first attempt, it will retry with the initial period (which by default is `1m`) instead of the regular period (which is `12h`). It will make it possible to perform smoother upgrades from free to higher Konnect tiers with no KIC restart required.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4147.
=> feat(konnect): allow configuring license polling periods

.github/workflows/benchmarks.yaml, Makefile, internal/dataplane/deckgen/deckgen_test.go
This PR adds benchmarking code using https://github.com/benchmark-action/github-action-benchmark.
The [CI workflow](https://github.com/Kong/kubernetes-ingress-controller/blob/214773b81c9c2c2df925b6da313429034944f97c/.github/workflows/benchmarks.yaml)  will run all benchmark in the codebase and save the results in gh-pages so that they are available for developers to see the trend and results.
This workflow will also issue a comment in case it detect a regression by a certain threshold (currently set to 150%). 
Form the action README:
> Percentage value like "150%". It is a ratio indicating how worse the current benchmark result is. For example, if we now get 150 ns/iter and previously got 100 ns/iter, it gets 150% worse.
---
The chart (1 for now …
=> feat(ci): add benchmarking code

internal/adminapi/backoff_strategy_konnect.go, internal/adminapi/client.go, internal/license/agent.go, internal/license/agent_test.go, internal/util/clock/clock.go, internal/util/clock/ticker.go, test/mocks/ticker.go, test/mocks/ticker_test.go
This PR introduces a `Ticker` interface within the license agent and uses that to mock time 🕐 .
This should help us fix #4200.
Fixes #4200.
=> tests: fix flaky TestAgent

CHANGELOG.md, internal/dataplane/kong_client.go, internal/dataplane/sendconfig/backoff_strategy.go, internal/dataplane/sendconfig/backoff_strategy_test.go, internal/dataplane/sendconfig/sendconfig.go
This fixes an issue where KIC crash due to a stack overflow when a broken config is applied in dbmode.
The problematic piece was:
```
func (e ErrUpdateSkippedDueToBackoffStrategy) Is(err error) bool {
return errors.Is(err, ErrUpdateSkippedDueToBackoffStrategy{})
}
```
which didn't work as intended. `.Is()` is meant to compare errors, as in compare their values, not types.
Where this was called we intended to check the type of an error, not it's value.
The stack overflow is prevent by removing the `.Is()` method from `UpdateSkippedDueToBackoffStrategyError` as it's not needed now.
The test that failed due to a stack overflow before this change was introduced and passes now:
```
skippedErr := …
```
=> fix: fix incorrect .Is() method on update skipped due to backoff error

internal/dataplane/kong_client.go, internal/dataplane/sendconfig/backoff_strategy.go, internal/dataplane/sendconfig/backoff_strategy_test.go, internal/dataplane/sendconfig/sendconfig.go
Backporting #4213 
No changelog entry. We'll add it in `main` when we release 2.10.1.
=> fix: fix incorrect .Is() method on update skipped due to backoff error (#4213)

CONTRIBUTING.md, Makefile
Direct usage of 
- [fmt](https://github.com/Kong/kubernetes-ingress-controller/blob/7f4ab1902f113b3864095b9042ba56c0ee216660/Makefile#L149-L151)
- [vet](https://github.com/Kong/kubernetes-ingress-controller/blob/31b1ba2fe4cb5f37119e0ab299743b07e04e1098/Makefile#L153-L155)
is redundant, since we have [lint](https://github.com/Kong/kubernetes-ingress-controller/blob/7f4ab1902f113b3864095b9042ba56c0ee216660/Makefile#L157-L159) that invokes golangci-lint with configuration that includes [govet](https://github.com/Kong/kubernetes-ingress-controller/blob/7f4ab1902f113b3864095b9042ba56c0ee216660/.golangci.yaml#L34) (it uses [stdlib vet](https://pkg.go.dev/cmd/vet)) & [gofmt](https://github.com/Kong/kubernetes-ingress-controller/blob/7f4ab1902f113b3864095b90 …
=> chore(ci): remove redundant vet and fmt commands

internal/adminapi/konnect.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/konnect/license/client.go, internal/konnect/license/client_test.go, internal/konnect/license/types.go, internal/license/agent.go, internal/license/agent_test.go, internal/manager/config.go, internal/manager/run.go
Backporting #4178.
No changelog entry. We'll add it in `main` when we release 2.10.1.
=> [backport] feat(konnect): allow configuring license polling periods

.github/workflows/_test_reports.yaml
GH action [Workshop64/buildpulse-action](https://github.com/BuildPulseLLC/buildpulse-action) is effectively deprecated, has been moved to [buildpulse/buildpulse-action](https://github.com/buildpulse/buildpulse-action), hence this is the recommended way of using it.
=> chore(ci): replace deprecated buildpulse GH Action

.github/workflows/benchmarks.yaml, .github/workflows/pr_checks.yaml
This should fix #4221 since github uses path like matching using `*` and `**` and `release/N.M.x` branches do contain a `/`.
Additionally add a regex filter to run PR checks against pushes on release branches.
Fixes #4221.
=> ci: run PR checks on PRs against all branches

.github/workflows/cleanup.yaml, hack/cleanup/gke_clusters.go, hack/cleanup/konnect_runtime_groups.go, hack/cleanup/main.go, internal/konnect/roles/client.go, internal/konnect/roles/client_test.go, test/e2e/konnect_test.go
Extends the cleanup workflow by adding a step in the script removing orphaned Konnect runtime groups and roles created for them (to ensure we do not hit the issue with degraded performance and unreliable APIs when we have too many orphaned roles). Also adds the roles removal step to the cleanup function in E2E tests.
Fix #4225.
=> chore(ci): cleanup orphaned Konnect RGs and roles in cleanup job

CHANGELOG.md
Adds the 2.10.1 changelog entry. It's to be backported to `release/2.10.x`. 
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/4227.
=> chore(release): add 2.10.1 entry to the changelog

CHANGELOG.md
Backports #4228 to `release/2.10.x` branch.
=> [backport] chore(release): add 2.10.1 entry to the changelog (#4228)

CHANGELOG.md, go.mod, internal/dataplane/deckgen/deckgen.go
Use [`gojson`](https://github.com/goccy/go-json) to marshal config to JSON to get config SHA.
This speeds up the marshalling of config to JSON by about 35%, using roughly the same amount of memory and the same amount of memory allocations.
Results (run locally):
```
$ benchstat /tmp/old /tmp/new
goos: darwin
goarch: arm64
pkg: github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane/deckgen
│  /tmp/old   │              /tmp/new               │
│   sec/op    │   sec/op     vs base                │
DeckgenGenerateSHA-10   31.32µ ± 0%   20.25µ ± 1%  -35.36% (p=0.000 n=10)
│   /tmp/old   │              /tmp/new               │
│     B/op     │     B/op      vs base               │
DeckgenGenerateSHA-10   10.95Ki ± 0%   10.87Ki ± 0%  -0.70% …
```
=> refactor: use gojson to marshal config for SHA

.github/workflows/_e2e_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/release.yaml
Bumps:
- Istio to v1.18 (which now officially supports K8s v1.27) 
- Kind's patch versions
- GKE version to v1.26.5 
Part of #4227.
=> chore: bump test dependencies

config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Bumps KIC version to 2.10.1 in all-in-one manifests.
Part of #4227
=> chore(release): bump KIC version in manifests

.github/workflows/e2e_targeted.yaml, .github/workflows/e2e_trigger_via_label.yaml
Currently label `ci/run-e2e` runs GKE-based tests with a `nightly` image (instead of one from PR). It is pointless because you want to test the PR code. Change in this PR ensures that only KIND-based clusters are used for tests and proper comment 
> E2E (targeted) tests with KIND-based clusters were started at ${URL}
is added. For implementing it for GKE clusters (building image from PR and loading it to a cluster) separate issue exists https://github.com/Kong/kubernetes-testing-framework/issues/587.
=> chore(ci): do not run e2e tests triggered by label on GKE clusters

test/e2e/environment.go, test/e2e/konnect_test.go
current retry logic on creating test konnect RGs will fail when the RG is created, but the request timed out to get response. This caused e2e test cases fail when creating RGs on the situations above.
This PR checks for existence of RG with specified name before sending the creation request. 
fixes #4193 
=> test(e2e): fix retry on create konnect RG

CHANGELOG.md, internal/dataplane/parser/testdata/golden/grpcroute-example/default_golden.yaml, internal/dataplane/parser/testdata/golden/grpcroute-example/in.yaml, internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_golden.yaml, internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_settings.yaml, internal/dataplane/parser/translate_grpcroute.go, internal/dataplane/parser/translators/grpcroute.go, internal/dataplane/parser/translators/grpcroute_test.go
Do not add `~` prefix on paths generated from GRPCRoutes if kong version < 3.0 to generate correct Kong config.
fixes #4237 
Question: Do we need to backport it to 2.10/2.9?
=> fix: do not prepend ~ before regex paths for Kong < 3.0

TESTING.md
Adds a section about Konnect-specific E2E tests to the `TESTING.md`.
=> chore(docs): mention konnect tests in TESTING.md

.github/workflows/e2e_nightly.yaml
Message on Slack does not use a template (red color, etc.) for failure events, because to the field status current
`${{ job.status }}` is assigned that is always `success`. The whole job is triggered on `failue` of previous jobs (the `if` statement ensures it), so it should be hardcoded to `failure`.
=> chore(ci): mark as failure notifications from e2e nightly tests

.github/workflows/e2e_nightly.yaml
Ensure that a nightly image for a current day exists in the nightly e2e workflow.
CI run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5413037620/jobs/9838008102
To avoid situations like #4251.
=> chore(ci): ensure nightly image is built in nightly e2e

.github/workflows/cleanup.yaml, hack/cleanup/main.go
Makes it possible to run the cleanup script in  `gke`, `konnect`, or `all` mode. Also splits the cleanup job into two separate jobs for `gke` and `konnect`.
=> chore(ci): make running gke/konnect cleanup separately possible

.github/workflows/cleanup.yaml
Use proper `gke` `./hack/cleanup` script's argument.
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5413757425/jobs/9839795934
=> chore(ci): fix gke cleanup

CHANGELOG.md, internal/dataplane/parser/testdata/golden/grpcroute-example/default_golden.yaml, internal/dataplane/parser/testdata/golden/grpcroute-example/in.yaml, internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_golden.yaml, internal/dataplane/parser/testdata/golden/grpcroute-example/regex-path-prefix-off_settings.yaml, internal/dataplane/parser/translate_grpcroute.go, internal/dataplane/parser/translators/grpcroute.go, internal/dataplane/parser/translators/grpcroute_test.go
** Original PR info *** 
* fix: do not prepend ~ before regex paths for Kong < 3.0
* add tests for translating grpcroute
* add CHANGELOG
(cherry picked from commit 1b59a9bbeedeace8a1d3f800ec26681493b2fa6d)
manual backport of fixing translator of `GRPCRoute` #4238  to 2.10.x.
fixed conflicts on `CHANGELOG.md` .
=> [Backport release/2.10.x] Backport #4238 to 2.10.x

pkg/apis/configuration/v1beta1/ingress_rules.go, pkg/apis/configuration/v1beta1/tcpingress_types.go, pkg/apis/configuration/v1beta1/udpingress_types.go
This PR removes redundant `// +optional` comment for fields in CRDs, check [the docs](https://book.kubebuilder.io/reference/markers.html?highlight=omitempty#difference-between--optional-and--kubebuildervalidationoptional). Moreover nothing is regenerated after this change thus this comment is ineffectual for our code.
=> chore: remove redundant // +optional for CRDs' fields

test/integration/ingress_https_test.go
The validation on `kong/kong-gateway-dev:2.8.4.2-rc2`  still fails on integration test `TestHTTPSIngress` . 
The PR adds the common name to SANs in the certificates used, after that, the case passes. 
=> test: add common name to SANs in certificate used in TestHTTPSIngress

internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, test/mocks/events_recorder.go
Instead of getting a pod reference every time we attempt to publish configuration apply events, we read it once in the `KongClient` constructor - it's safe as the env variables are not expected to change during the runtime. It allows logging the error once instead of one error per update. Also adds a test case for publishing these events.
=> refactor: don't log missing pod reference in every update

CHANGELOG.md
`GRPCRoute` was missed to be included in the changelog entry for https://github.com/Kong/kubernetes-ingress-controller/pull/4267.
=> chore: add grpcroute to changelog entry

test/e2e/all_in_one_test.go, test/e2e/compatibilities_test.go, test/e2e/features_test.go, test/e2e/konnect_test.go, test/e2e/kuma_test.go, test/e2e/utils_test.go
The default dbless manifest uses gateway discovery by specifying `CONTROLLER_ADMIN_SVC`, which is not supported by KIC with versions below 2.9. This PR adds check for overriding KIC image and use the legacy manifest if KIC version < 2.9.
This PR also adds a helper function to skip tests if KIC version below a certain version.
fixes #4069 
=> test(e2e): use legacy manifest and skip tests for KIC version < 2.9

.github/workflows/e2e_targeted.yaml, .github/workflows/e2e_trigger_via_label.yaml
=> [Backport release/2.10.x] chore(ci): do not run e2e tests triggered by label on GKE clusters

.github/workflows/_integration_tests.yaml, .github/workflows/pr_checks.yaml
This backports #4223 to 2.9.x release branch so that CI tests can run there and fulfil a required `passed` check.
=> [Backport release/2.9.x] ci: run PR checks on PRs against all branches (#4223)

config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
(cherry picked from commit 8f031ed6271b4b66802a7ac4beb827dfe96887ca)
manual backport manifest updates to `release/2.10.x`
=> [backport-to-2.10.x] update KIC image version to 2.10.2 in manifests (#4288)

examples/ingress.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-ingress-class-annotation/default_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-ingress-class-annotation/in.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/in.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/in.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/in.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/in.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/in.yaml, internal/store/store_test.go, test/integration/examples_test.go
Since we're now supporting only Ingress v1 let's get rid of the references and usages of deprecated `kubernetes.io/ingress.class` annotation.
As per kubernetes docs:
> Deprecated annotation
> Before the IngressClass resource and ingressClassName field were added in Kubernetes 1.18, Ingress classes were specified with a kubernetes.io/ingress.class annotation on the Ingress. This annotation was never formally defined, but was widely supported by Ingress controllers.
> The newer ingressClassName field on Ingresses is a replacement for that annotation, but is not a direct equivalent. While the annotation was generally used to reference the name of the Ingress controller that should implement the Ingress, the field is a reference to an IngressClass …
=> chore: update ingress examples and test code using deprecated `kubernetes.io/ingress.class` annotation to use `spec.ingressClassName` instead

internal/adminapi/client.go, internal/adminapi/endpoints.go, internal/adminapi/endpoints_envtest_test.go, internal/adminapi/endpoints_test.go, internal/clients/manager.go, internal/clients/manager_test.go, internal/controllers/configuration/kongadminapi_controller.go, internal/controllers/configuration/kongadminapi_controller_envtest_test.go, internal/manager/config.go, internal/manager/controllerdef.go, internal/manager/run.go, internal/manager/setup.go, internal/manager/setup_test.go, test/mocks/admin_api_client_factory.go, test/mocks/admin_api_discoverer.go
Extracts `adminapi.Discoverer` and thanks to that, covers `AdminAPIClientFromServiceDiscovery` with unit tests.
Refactor required for https://github.com/Kong/kubernetes-ingress-controller/issues/3499.
=> refactor: extract adminapi.Discoverer and add tests

.github/ISSUE_TEMPLATE/release.yaml, .github/workflows/release.yaml
This PR introduces a new part of the release mechanism where [`latest` branch](https://github.com/Kong/kubernetes-ingress-controller/tree/latest) is updated to point to just released tag if the release was marked as [`latest` in the release workflow](https://github.com/Kong/kubernetes-ingress-controller/blob/b6d3994cf2089c60b4cf4a33fa6bce1624df6032/.github/workflows/release.yaml#L15-L19).
This will allow usage of `latest` branch in e.g. README so that users would always get latest released artifacts installed:
```
kubectl apply -f https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/latest/deploy/single/all-in-one-dbless.yaml
```
=> feat(ci): release workflow updates the latest branch to point to latest tag

README.md
Remove last bit.ly link from README.md and replace it with github links that's based on `latest` branch that points to latest release tag.
=> chore(docs): remove bit.ly link from README.md

CHANGELOG.md, internal/dataplane/deckgen/deckgen.go, internal/dataplane/deckgen/deckgen_test.go, internal/dataplane/deckgen/generate.go, internal/dataplane/deckgen/generate_test.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/config_change_detector.go
When a translated configuration is empty, the controller adds an empty `Upstream` named `kong` to a Kong configuration. It will happen for Gateways in DB-less mode only.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3499.
=> feat: add stub upstream when config is empty in dbless mode

CHANGELOG.md, internal/clients/manager.go, internal/clients/manager_test.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/konnect/mock_node_api_test.go, internal/konnect/node_agent.go, internal/konnect/node_agent_test.go
Makes sure that:
- `NodeAgent` calls Konnect APIs only when the config status actually changes (enforce that on both ends of the notification channel - in `NodeAgent` and in `KongClient`). **This was an actual reason for KIC updating nodes every 3s**.
- `NodeAgent` calls Konnect APIs only when a set of Gateway clients actually changes (enforce that on `ClientsManager` side)
Also improves debug logging to make it visible when the calls are made.
After this change, `NodeAgent` will call Konnect APIs in the following cases:
- configuration status has changed,
- gateways' clients have changed (Gateway deployment scaling, Pod eviction, etc.),
- every 30s.
Fixes #4322.
Complete these before …
=> fix(konnect): update nodes status only when it actually changes

test/e2e/features_test.go, test/e2e/kustomizations_test.go, test/e2e/utils_test.go, test/envtest/crds_envtest_test.go, test/envtest/k8s_objects_status_envtest_test.go, test/envtest/run.go
Spotted this test when doing another refactor in E2E tests and noticed it should be easily convertible to an envtest.
=> tests: transform TestMissingCRDsDontCrashTheControler into envtest

.gitattributes
Give GH a hint that the content of `deploy/single/` dir is autogenerated. As described in [docs](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github).
This is leftover from the PR https://github.com/Kong/kubernetes-ingress-controller/pull/4326
=> chore: mark content of deploy/single/ dir as autogenerated

.gitattributes
Since
https://github.com/Kong/kubernetes-ingress-controller/blob/399eef2002a6dfa7fa758d214ec6df54924e1de8/docs/api-reference.md#L1
it should be added to `.gitattributes` too.
=> chore: mark file docs/api-reference.md as autogenerated

internal/adminapi/backoff_strategy_konnect.go, internal/adminapi/client.go, internal/license/agent.go, internal/license/agent_test.go
Backport #4203 to release/2.10.x.
=> [Backport release/2.10.x] tests: fix flaky TestAgent (#4203)

CHANGELOG.md, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Adds changelog entry for 2.10.3 release and changes KIC version used in manifests from `2.10.2` to `2.10`. 
Part of #4329.
=> chore: changelog and manifests for 2.10.3 release

CHANGELOG.md, internal/controllers/gateway/grpcroute_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/manager/controllerdef.go, internal/util/builder/httproutematch.go, internal/util/kubernetes/object/status/queue.go, internal/util/kubernetes/object/status/queue_test.go
Backports #4267 to release/2.9.x. Doesn't port an envtest due to discrepancies in setup code and controller-runtime version.
=> [Backport release/2.9.x] fix: make status queue not block when no sub exists (#4267)

CHANGELOG.md, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Prepares release/2.10.x release branch for 2.10.3 release.
Part of #4329
=> chore: prepare release 2.10.3

.github/workflows/release.yaml
Expect the tag used in manifests to be `{major}.{minor}` part of the version pased to `release.yaml` workflow.
Verified in workflow run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5542897078
=> chore(ci): require major.minor in manifests

.github/workflows/release.yaml
Same as https://github.com/Kong/kubernetes-ingress-controller/pull/4339 for release/2.10.x branch.
=> [release/2.10.x] chore(ci): require major.minor in manifests

CHANGELOG.md
Adds missing 2.9.4 links in changelog.
=> chore: add missing changelog links

test/conformance/gateway_conformance_test.go
https://github.com/Kong/kubernetes-ingress-controller/pull/4296 was supposed to fix `HTTPRouteHeaderMatching` conformance test but is failing consistently, affecting other PRs as well. This PR disables such a test.
=> test(conformance): disable HTTPRouteHeaderMatching

CHANGELOG.md, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Prepares the 2.5.1 release.
The checklist has items that appear not valid for LTS/backport releases:
- It doesn't look like we should update the Kubernetes/Istio versions. Unclear if we're going to target newer Kubernetes versions than the release originally supported. 2.5.1 does not include changes to do so AFAIK, so I've left those as-is.
- Kong versions have been left as-is.
- FOSSA should be updated for this, but isn't letting me select `release/2.5.x` in the branch dropdown--or _any_ branches other than main, for that matter. The cron job that we have only applies to main. Changing that needs to be PRed to main rather than here.
Complete these before …
=> chore(release) date changelog and generate manifests

CHANGELOG.md, internal/dataplane/parser/translators/httproute.go, internal/dataplane/parser/translators/httproute_test.go, test/conformance/gateway_conformance_test.go
This PR support ResponseHeaderModifier Gateway API filter.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/3683
=> feat: support ResponseHeaderModifier filter

.github/workflows/release.yaml
For some reason when releasing 2.5.1, https://github.com/ncipollo/release-action marked it as `latest` in GH releases. I had to manually assign the label to `2.10.3` again. This PR makes this setting explicit using the input we already have in place.
Part of #4330.
=> chore(ci): make github release latest only when asked for

.github/workflows/release.yaml
Uses the reusable workflow to enable running E2Es in `release.yaml` workflow in parallel jobs. This should reduce the release workflow time from ~1-2h to ~30min. 
Tested in workflow run (with publishing jobs commented-out ): https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5545392883/jobs/10124268023
As part of #4329.
=> chore(ci): make release e2e tests run in parallel jobs

internal/adminapi/client_test.go, internal/adminapi/kong.go, internal/adminapi/kong_test.go, test/envtest/adminapimock.go, test/mocks/admin_api_handler.go
Makes `NewKongClientForWorkspace` verify the status before calling other endpoints. Returns a new `KongClientNotReadyError` when the client is not ready yet. It gives callers a context of whether it makes sense to retry while awaiting for readiness (will be used in the next PRs for #3499).
It's part of #3499. Changelog entry will be added in the final PR swapping the readiness endpoint.
=> feat: make NewKongClientForWorkspace first verify status + tests

test/e2e/all_in_one_test.go, test/e2e/compatibilities_test.go, test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/konnect_test.go, test/e2e/kuma_test.go, test/e2e/upgrade_test.go, test/e2e/utils_test.go
Makes E2E tests more restrictive about deployments' readiness before proceeding with configuring any resources. It's to ensure that both Gateway and KIC deployments are ready in a default idle state after installation. This is the behavior we want to preserve while implementing #3499.
Part of #3499.
=> tests: verify all deployments are ready after installation

Makefile, skaffold.yaml
Remove outdated `debug` skaffold profile and make `debug_multi_gw` a default one for `make debug.skaffold`.
=> chore: remove outdated debug skaffold profile

hack/generators/controllers/networking/main.go, internal/controllers/configuration/object_references.go, internal/controllers/configuration/secret_controller.go, internal/controllers/configuration/zz_generated_controllers.go, internal/controllers/dataplane.go, internal/controllers/gateway/grpcroute_controller.go, internal/controllers/gateway/referencegrant_controller.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/controllers/knative/knative.go, internal/dataplane/kong_client.go, internal/manager/controllerdef.go, test/mocks/dataplane.go
This PR decouples controllers from concrete `*dataplane.KongClient` in favor of using interface `controllers.DataPlane.`. 
closes https://github.com/Kong/kubernetes-ingress-controller/issues/3794
The interface has to be extended to fit all use cases.
The only usage of concrete `*dataplane.KongClient` is left in 
https://github.com/Kong/kubernetes-ingress-controller/blob/70df8f674b77741e5f9a77cd42c995db5106a0f2/internal/manager/run.go#L326-L367
that is ok, otherwise, interface would have to be extended with the method
```go
SetConfigStatusNotifier(clients.ConfigStatusNotifier)
```
that is only used in the above function. It would pollute the interface.
=> refactor: use controllers.DataPlane interface instead of concrete *dataplane.KongClient

CHANGELOG.md, config/variants/multi-gw/base/gateway_deployment.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless.yaml, internal/adminapi/client.go, internal/adminapi/endpoints.go, internal/adminapi/endpoints_test.go, internal/clients/config_status_test.go, internal/clients/manager.go, internal/clients/manager_test.go, internal/clients/readiness.go, internal/clients/readiness_test.go, internal/controllers/configuration/kongadminapi_controller.go, internal/controllers/configuration/kongadminapi_controller_envtest_test.go, internal/manager/run.go, test/e2e/helpers_test.go, test/e2e/kuma_test.go, test/e2e/upgrade_test.go
Changes the Gateway's Pod readiness probe from `/status` to `/status/ready`. `/status/ready` returns 200 after receiving the first non-empty configuration. That allows to make Gateway pods to serve proxy traffic only after they're initially configured by KIC.
In KIC's Gateway discovery, instead of relying on `EndpointSlices` `Endpoints`' being ready, we use the discovered endpoints despite their readiness (we only discard terminating ones) and verify their readiness on our own with the use of the Admin API's `/status` in the `ReadinessChecker`. It requires running a periodic readiness reconciliation loop to check whether the endpoints that were ready should be moved to the pending list and vice versa.
Fundamental changes that were made in this PR:
- …
=> feat: use /status/ready as readiness probe of gateway for gateway discovery

test/consts/misc.go, test/internal/helpers/ktf.go
This PR gets rid of the hardcoded magic string `notdefault` and replaces it with the usage of a const `KongTestWorkspace` that makes it consistent with the password and ingresclass used in the test and easily discoverable.
=> refactor: introduce KongTestWorkspace constant

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/controllers/utils/conditions.go, internal/controllers/utils/conditions_test.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/manager/controllerdef.go, internal/metrics/metrics_envtest_test.go, pkg/apis/configuration/v1/conditions.go, pkg/apis/configuration/v1/kongconsumer_types.go, test/envtest/manager_debugendpoints_test.go, test/envtest/programmed_condition_envtest_test.go, test/envtest/telemetry_test.go
Populates `Programmed` condition for `KongConsumer` objects.
Part of #3344.
=> feat: populate Programmed condition for KongConsumer

internal/adminapi/endpoints_envtest_test.go, internal/controllers/configuration/kongadminapi_controller_envtest_test.go, test/envtest/controller.go, test/envtest/gatewayclass_envtest_test.go, test/envtest/httproute_controller_test.go, test/envtest/k8s_objects_status_envtest_test.go, test/envtest/kongstate_consumer_failures_test.go, test/envtest/programmed_condition_envtest_test.go, test/envtest/scheme.go
To prevent race conditions adds `envtest.Scheme` function to get a scheme for every test separately. It also allows customizing the scheme with `WithGatewayAPI` and `WithKong` options.
=> tests: do not use global scheme in envtests

CONTRIBUTING.md, Makefile, TESTING.md
This PR updates testing related docs and cleans up `Makefile` targets that are unused.
=> chore(docs): update testing docs

CHANGELOG.md, internal/dataplane/deckgen/generate.go, internal/dataplane/kongstate/consumergroup.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/parser/parser.go, internal/store/fake_store.go, internal/store/fake_store_test.go, internal/store/store.go, internal/versions/versions.go, test/integration/consumer_group_test.go
In https://github.com/Kong/kubernetes-ingress-controller/pull/4325 Consumer Group CRD and the boilerplate controller has been introduced. This PR continues that effort - applied Consumer Group will be configured in Kong Gateway. Validation webhook, adding Consumers, and scoping Plugins will be introduced in the next PRs.
This is a part of #3728 and closes https://github.com/Kong/kubernetes-ingress-controller/issues/4358
The introduced integration test `TestConsumerGroup` will evolve in the future to cover all features of it e.g. adding Consumers to Consumer Group. Since Consumer Group doesn't do anything useful yet for now check directly in Gateway if it was created. Later it will …
=> feat: Consumer Group can be configured

config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, pkg/apis/configuration/v1/kongclusterplugin_types.go, pkg/apis/configuration/v1/kongplugin_types.go
Adds kubebuilder annotations to the `Conditions` field for `KongClusterPlugin` and `KongPlugin`. 
Part of #3344.
=> feat: add kubebuilder annotations to programmed conditions

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, pkg/apis/configuration/v1/kongclusterplugin_types.go, pkg/apis/configuration/v1/kongconsumer_types.go, pkg/apis/configuration/v1/kongplugin_types.go
Adds `additionalPrinterColumns` entry for a `Programmed` condition to be displayed for `KongConsumer`, `KongPlugin`, and `KongClusterPlugin`.
```shell
$ k get kongplugins
NAME   PLUGIN-TYPE   AGE   PROGRAMMED
auth   key-auth      9s    True
```
Part of #3344.
=> feat: add printer columns for programmed condition

.gitattributes, internal/dataplane/parser/testdata/golden/grpcroute-example/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/grpcroute-example/expression-routes-on_settings.yaml, internal/dataplane/parser/testdata/golden/httproute-example/default_golden.yaml, internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_settings.yaml, internal/dataplane/parser/testdata/golden/httproute-example/in.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/expression-routes-on_settings.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_settings.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/expression-routes-on_settings.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/expression-routes-on_settings.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/expression-routes-on_settings.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/expression-routes-on_settings.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/expression-routes-on_settings.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/expression-routes-on_settings.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/expression-routes-on_settings.yaml
Adds settings to cover `ExpressionRoutes: true` to the existing Ingress and GRPCRoute tests, adds a new `HTTPRoute` test.
=> tests: add parser golden tests covering expression routes

internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go
@programmer04 has found that when creating two `Consumer`s at once, only one gets its `Programmed` condition properly set to `True`, and the other one stays `False` forever. This PR fixes the root cause of the bug.
Part of #3344.
=> fix: do not use address to a loop variable in parser

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, docs/api-reference.md, internal/dataplane/deckgen/generate.go, internal/dataplane/kongstate/consumer.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/parser/testdata/golden/consumer-group-example/default_golden.yaml, internal/dataplane/parser/testdata/golden/consumer-group-example/in.yaml, pkg/apis/configuration/v1/kongconsumer_types.go, pkg/apis/configuration/v1/zz_generated.deepcopy.go, test/integration/consumer_group_test.go
Introduce the optional field `ConsumerGroups` to `KongConsumer` CRD that allows configuring Consumer Groups for Consumer. Add implementation and enhance integration test to cover it.
part of https://github.com/Kong/kubernetes-ingress-controller/issues/3728
Integration test `TestConsumerGroup` is executed for two set-ups:
- DBMode (Postgres) - it passes without problems 🟢 
- DBLess - [it doesn't pass](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5681303005/job/15397189359?pr=4419#step:6:13746) due to a bug in Kong Gateway reported by me to them in [FTI-5264](https://konghq.atlassian.net/browse/FTI-5264) (thus the status of this PR is `blocked`) 🔴 **so test is …
=> feat: Consumer Groups can be configured in Consumer

Makefile, internal/admission/server_test.go, internal/admission/validator.go, internal/controllers/gateway/grpcroute_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/dataplane/deckgen/generate.go, internal/dataplane/kongstate/route_test.go, internal/dataplane/kongstate/service_test.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/translate_ingress.go, internal/dataplane/parser/translators/ingress.go, third_party/go.mod, third_party/go.sum, third_party/looppointer.go
Adds a restrictive `looppointer` linter that prevents getting a pointer to a loop variable. It may have false positives (as taking an address without storing it and using later can be fine), although I think it's better to be safe than sorry.
Fixes the issues found by the new linter.
It's not enabled in golangci-lint, because it hasn't been included into this suite of linters yet because of [reasons](https://github.com/golangci/golangci-lint/issues/1404).
=> chore: add looppointer linter and fix found issues

CHANGELOG.md, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/util.go, internal/dataplane/parser/parser.go, test/envtest/programmed_condition_envtest_test.go
Instead of just logging an error in case of an invalid `KongPlugin` or `KongClusterPlugin`'s configuration, bubble up the translation failure so that the `Programmed` condition is populated with `False` and reason `Invalid` and an event is emitted. 
Also drops unnecessary validation of `plugin.PluginName` which is handled on the Kubernetes API level thanks to the CRD validation ([KongPlugin](https://github.com/Kong/kubernetes-ingress-controller/blob/964f9d264246955a11e4a8bbe778e84c66b09a3c/pkg/apis/configuration/v1/kongplugin_types.go#L66), [KongClusterPlugin](https://github.com/Kong/kubernetes-ingress-controller/blob/964f9d264246955a11e4a8bbe778e84c66b09a3c/pkg/apis/configuration/v1/kongclusterplugin_types.go#L67)). …
=> feat: propagate translation failures for KongPlugin and KongClusterPlugin

Makefile
Removes dependency on `test.integration.cp` (that doesn't exist) from `test.integration` Makefile target.
```shell
$ make test.integration
...
ok      github.com/kong/kubernetes-ingress-controller/v2/test/integration       1434.591s       coverage: 14.5% of statements in ./pkg/..., ./internal/...
make: *** No rule to make target `test.integration.cp', needed by `test.integration'.  Stop.
```
=> chore: remove non-existent makefile test.integration dependency

.github/workflows/pr_checks.yaml
Use https://github.com/Kong/public-shared-actions/tree/main/pr-previews#up-to-date to save CI time when assessing refs that already got checked in up to date PR branches.
=> feat(ci): use up-to-date shared action

.github/workflows/pr_checks.yaml
Extends https://github.com/Kong/kubernetes-ingress-controller/pull/4433 and https://github.com/Kong/kubernetes-ingress-controller/pull/4441 to prevent building the image if PR branch was up to date with `main`.
=> ci: don't build the image on main when PR branch was up to date

.github/workflows/pr_checks.yaml
#4443 forgot the `needs` clause for `build-docker-image`.
=> ci: add missing up-to-date needs for build job

.github/workflows/e2e_nightly.yaml
Adds an integration job against unreleased Kong images to the nightly test workflow.
Dispatched test on this branch: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5744744206
Does not rename the workflow. I'm reluctant to do this because it breaks continuity with the result list and Github doesn't have a built-in cleanup mechanism to stop showing old results under the original name. I think I wrote a script to purge those at one point and lost it :(
=> chore(ci) run nightly integration against dev kong

.golangci.yaml, internal/controllers/configuration/kongadminapi_controller_envtest_test.go, internal/dataplane/configfetcher/config_fetcher.go, internal/dataplane/sendconfig/config_change_detector.go, internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/sendconfig/sendconfig.go, internal/manager/utils/kongconfig/root_test.go, pkg/apis/configuration/v1/conditions.go
Remove redundant configuration for `skip-dirs` from `.golangci.yaml`. It's not needed since auto-generated Go code is marked with comments and omitted by golangci-lint. Furthermore, this redundant config leads to omitting files that should be checked.
Adding a dot in `pkg/apis/configuration/v1/conditions.go` is questionable, but let's do it to satisfy the linter, it doesn't make "serious harm".
=> chore(ci): adjust golangci-lint config, fix reported

go.mod, go.sum, internal/dataplane/parser/parser_test.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translate_routes_helpers_test.go, internal/dataplane/parser/translate_utils_test.go, internal/dataplane/parser/translators/grpcroute_atc_test.go, internal/dataplane/parser/translators/grpcroute_test.go, internal/util/objectmeta_test.go, test/integration/tcproute_test.go, test/integration/tlsroute_test.go, test/integration/udproute_test.go, third_party/go.mod, third_party/go.sum
Bump some dependencies versions (e.g. those without a semver which are not being bumped by dependabot).
=> chore(deps): bump dependencies versions in go.mod

examples/consumer-groups.yaml, internal/dataplane/deckgen/deckgen.go, internal/dataplane/sendconfig/inmemory.go, internal/dataplane/sendconfig/inmemory_schema.go, internal/dataplane/sendconfig/inmemory_schema_test.go, internal/dataplane/sendconfig/strategy.go, test/integration/consumer_group_test.go
Introduces `ContentToDBLessConfigConverter` used by `UpdateStrategyInMemory` to adapt decK's `file.Content` to match DBLess schema constraints.
It extracts the already existing conversions from `UpdateStrategyInMemory` (dropping `Info` field, cleaning up nulls in plugins' configs), and also adds cleanups for `ConsumerGroups` related fields (dropping `Plugins[i].ConsumerGroup`, `Consumers[i].Group`, `ConsumerGroups[i].Plugins`, `ConsumerGroups[i].Consumers`, filling relationships).
Also adds an example config for `ConsumerGroup`.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/4448.
=> fix: introduce deck content to dbless config converter

.github/dependabot.yml
This reverts commit 59e67144a433b1e6c9ca2c3e60e85eb33b8ceed2.
The reason for this revert is to prevent dependency bump lock ups like https://github.com/Kong/kubernetes-ingress-controller/pull/4460
Commented about this in here: https://github.com/Kong/kubernetes-ingress-controller/pull/4455#issuecomment-1667817979
=> Revert "ci(deps): group updates of several dependencies (#4455)"

.github/workflows/test_nightly.yaml
Running KIC integration tests on demand with the latest version of Kong Gateway is useful, thus updating the respective workflow.
- currently nightly builds can be found in the registry [kong-gateway-dev](https://hub.docker.com/r/kong/kong-gateway-dev), so let's use it
- PR https://github.com/Kong/kubernetes-ingress-controller/pull/4389 introduces running tests for enterprise dbless, so let's run them
- add a comment to PR that tests were triggered and remove the label `ci/run-nightly` from PR
- fix names of coverage reports to upload 
It unblocks PRs that have to be tested with newer Gateway images than the last stable version e.g. https://github.com/Kong/docs.konghq.com/pull/5865 …
=> chore(ci): update test_nightly.yaml GH workflow

test/conformance/suite_test.go, test/consts/misc.go, test/helpers/certificate/certificate.go, test/integration/gateway_test.go, test/internal/helpers/ktf.go
use namespace `kong` instead of `kong-system` for integration tests, and change the hard coded namespace `kong-system` to `const.ControllerNamespace`.
fixes #4431 
=> use namespace kong for integration tests

.github/workflows/release.yaml
Fixes the latest push job.
The job was failing:
```
Run git checkout latest
git checkout latest
git reset --hard v2.11.0
git push latest
shell: /usr/bin/bash -e {0}
Switched to a new branch 'latest'
branch 'latest' set up to track 'origin/latest'.
HEAD is now at 46f0739c chore(deploy) bump manifest versions
fatal: 'latest' does not appear to be a git repository
fatal: Could not read from remote repository.
```
Changes are what I ran locally to handle it outside CI.
Git indicated that my `latest`, after resetting to v2.11.0, was missing commits from `origin/latest`. I'm not sure if this should be the case (the succession of latests should be entirely linear unless we accidentally …
=> fix(ci) correct latest push

.github/workflows/_e2e_tests.yaml, test/e2e/istio_test.go
kind has removed the tags of `kindest/node` image we uses in e2e tests, so we have to update the tags to existing ones in the same kubernetes minor version. 
fixes #4483 
=> fix: update kind k8s versions because tags of kindest/node removed

test/e2e/features_test.go, test/helpers/certificate/certificate.go
- fix typo for `Ceritificate` -> `Certificate`
- get rid of hardcoded TLS certificates in test `TestWebhookUpdate` 
part of https://github.com/Kong/kubernetes-ingress-controller/issues/4118
The original comment describing `openssl` command for generating hardcoded certs is misleading because the second cert has `CN=second.example` instead of `CN=first.example` (and this is further checked like this in the test).
=> refactor: use helpers for certificates in TestWebhookUpdate, fix typo

.github/ISSUE_TEMPLATE/release.yaml
New step in the release steps template. Missed this in 2.11 initially because we'd never added any new CRDs since adding generated references.
=> chore(release) add description file step

internal/adminapi/kong_test.go, test/helpers/certificate/certificate.go
Make dealing with certs consistent across the codebase. Use common helpers for certs from package `certificate` in `TestMakeHTTPClientWithTLSOpts`.
part of https://github.com/Kong/kubernetes-ingress-controller/issues/4118
=> refactor: use common helpers for certs in TestMakeHTTPClientWithTLSOpts

internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, test/helpers/certificate/certificate.go
Make dealing with certs consistent across the codebase. Use common helpers for certs from package `certificate` in `parser_test.go`. Improve function `getCertFromSecret(...)` to do operations and byte string conversion more idiomatic.
part of https://github.com/Kong/kubernetes-ingress-controller/issues/4118
**Special notes for your reviewer:**
In tests e.g. `internal/dataplane/parser/parser_test.go:3019` is required to do the below
```go
Cert: kong.String(strings.TrimSpace(string(crt))),
Key:  kong.String(strings.TrimSpace(string(key))),
```
because key&crt returned by helper (Golang stdlib) ends with `\n`, but KIC trims leading&trailing whitespaces in `getCertFromSecret(...)`. It could be easily fixed, by adding …
=> refactor: use helpers for certs in parser_test.go and improve getCertFromSecret

test/consts/helm.go
Fixes failures in installing Kong in nightly integration tests by a workaround to use 2.25 charts.
workaround before we fixed the behavior of parsing semver in charts: https://github.com/Kong/charts/issues/856
=> test: fix parse semver error in integration tests

CHANGELOG.md, internal/dataplane/parser/parser.go, internal/dataplane/parser/testdata/golden/httproute-example/default_golden.yaml, internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-routes-off_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/combined-services_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/default_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/same-name-services-single-backend/default_golden.yaml
Uses the Service port from the Ingress(like) backend for the Kong service port. Previously we used `80` as a universal default.
This is a cosmetic change. As all KIC-generated services use upstreams, the service port is ignored in favor of the upstream's targets' ports, which are set to the Service's Endpoints' ports.
Fix #4470
This change still uses the `80` default when initially generating services, e.g. [in the Ingress translator](https://github.com/Kong/kubernetes-ingress-controller/blob/8db8ef5d91852985e27ee130ce1df634ebe5936b/internal/dataplane/parser/translate_ingress.go#L169). Because Ingress(like) backends may use port names instead of numbers, we don't necessarily know …
=> Use Service port in generated Kong services

CHANGELOG.md, internal/dataplane/parser/translate_grpcroute.go, internal/dataplane/parser/translate_grpcroute_test.go, internal/dataplane/parser/translators/grpcroute.go, internal/dataplane/parser/translators/grpcroute_atc.go, internal/dataplane/parser/translators/grpcroute_atc_test.go, internal/dataplane/parser/translators/grpcroute_test.go
generate routes matching hostnames only when a `GRPCRoute` rule does not contain a match, covering both traditional and expression routes.
fixes #4154 
=> fix: generate routes with hostname match only when GRPCRoute rule does not have matches

go.mod, go.sum
This bumps deck to 1.26 for 2.11.x release branch to get full consumer group support in 2.11.x
=> chore: bump github.com/kong/deck to 1.26

internal/util/test/crds.go, internal/util/test/rbacs.go
In logs for `make test.conformance` the below entry is presented as one line
```log
INFO: deploying Kong RBACs to clusterINFO: deploying Kong knative RBACs to clusterINFO: deploying Kong gateway RBACs to clusterINFO: deploying Kong CRDs RBACs to clusterINFO: deploying Kong CRDs to clusterINFO: deploying Gateway CRDs to cluster    gateway_conformance_test.go:127: creating GatewayClass for gateway conformance tests
```
change in this PR breaks it in separate lines
```log
INFO: deploying Kong RBACs to cluster
INFO: deploying Kong knative RBACs to cluster
INFO: deploying Kong gateway RBACs to cluster
INFO: deploying Kong CRDs RBACs to cluster
INFO: deploying Kong CRDs to cluster
INFO: deploying Gateway CRDs to cluster
```
**Special notes for your …
=> chore(ci): improve logs for test.conformance

.github/workflows/_integration_tests.yaml, config/image/enterprise/kustomization.yaml, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, internal/dataplane/parser/golden_test.go
Both Kong OSS and Enterprise are available in version `3.4`, so set it everywhere. Please cherry-pick this change to KIC release `2.11.1`.
=> chore: bump Kong Gateway to 3.4

.github/workflows/_integration_tests.yaml, config/image/enterprise/kustomization.yaml, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, internal/dataplane/parser/golden_test.go
Backports #4534 to `release/2.11.x`
=> chore: bump Kong Gateway to 3.4 (#4534)

CHANGELOG.md, internal/dataplane/parser/translate_grpcroute.go, internal/dataplane/parser/translate_grpcroute_test.go, internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translators/atc_utils.go, internal/dataplane/parser/translators/grpcroute_atc.go, internal/dataplane/parser/translators/httproute_atc.go, internal/dataplane/parser/translators/httproute_atc_test.go
Generate a wildcard route that matches any HTTP/GRPC requests for rules in `HTTPRoute`/`GRPCRoute` with no matches and no hostnames in their parent objects.
fixes #4526
TODO: add integration tests?
=> fix: gernerate a catch-all route for rules with no matches and no hostnames in HTTPRoute and GRPCRoute

CHANGELOG.md, internal/dataplane/parser/atc/field.go, internal/dataplane/parser/translate_failures_test.go, internal/dataplane/parser/translate_tcproute.go, internal/dataplane/parser/translate_tcproute_test.go, internal/dataplane/parser/translate_utils.go, internal/dataplane/parser/translators/l4route_atc.go, internal/dataplane/parser/translators/tcproute_atc.go, test/integration/tcproute_test.go
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/4312
=> feat: support expression route for TCPRoute.

test/e2e/features_test.go, test/e2e/konnect_test.go
- get rid of the redundant type (nowhere used) `TLSPair` defined in the package `e2e` (file `test/e2e/features_test.go`)
- in `test/e2e/konnect_test.go` for generating certificate to be used with connect for authentication use helper `certificate.MustGenerateSelfSignedCertPEMFormat()`
Last from the series, closes #4118
I think everywhere in tests now helpers are used for certs if you know omitted place please point me at it.
Since the proposed change modifies `e2e` tests, they are run for this PR with the label `ci/run-e2e` to verify the proposed change.
=> refactor: use helpers for certs in konnect_test.go, remove redundant type TLSPair

CHANGELOG.md, internal/dataplane/parser/translate_failures_test.go, internal/dataplane/parser/translate_grpcroute_test.go, internal/dataplane/parser/translate_tcproute.go, internal/dataplane/parser/translate_tcproute_test.go, internal/dataplane/parser/translate_udproute.go, internal/dataplane/parser/translate_udproute_test.go, internal/dataplane/parser/translators/translator_errors.go, internal/versions/versions.go, test/integration/examples_test.go, test/integration/helpers_test.go, test/integration/tcproute_test.go, test/integration/udproute_test.go, test/integration/version_test.go, test/internal/helpers/kong.go
support `UDPRoute` with expression router when Kong version is >3.4, and add tests for it.
fixes #4539 
=> feat: support `UDPRoute` when expression router enabled

internal/controllers/gateway/gateway_utils.go
#2558 is an old issue about setting all the needed conditions into the Gateway API resources. Since the issue was created, many conditions have been added and enforced in KIC. The conformance tests are supposed to check all those conditions, and since we are compliant with them, we can safely assume that the issue is now fixed.
Fixes #2558 
=> chore: remove out of date TODO comment

hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/manager/controllerdef.go, test/envtest/programmed_condition_envtest_test.go
Disables Kong(Cluster)Plugin status updates. Add TODOs for the relevant bug.
Multiple KIC instances in the same cluster [will fight over plugin statuses](https://github.com/Kong/kubernetes-ingress-controller/issues/4578) because plugins have no class. We don't want them to have class, unless they're global.
Double duty as a release PR for https://github.com/Kong/kubernetes-ingress-controller/issues/4582. AFAIK we're no longer doing updates other than the fixes themselves since we're now using relative tags, so the manifests remain unchanged.
A proper fix for this probably requires breaking out the plugin controller, so I think we want a hotfix for now. The feature isn't critical. …
=> fix: disable Kong(Cluster)Plugin Programmed status

CHANGELOG.md, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/parser/testdata/golden/kongplugin-instance-name/default_golden.yaml, internal/dataplane/parser/testdata/golden/kongplugin-instance-name/in.yaml, test/integration/plugin_test.go
Attach a short hash (or full hash, in the event of a short hash collision) of the attached entity to generated plugin `instance_name` values.
instance_name must be unique. Applying the same KongPlugin to multiple resources, or resources that generate multiple Kong entities, would violate this rule otherwise.
Fix #4516 
Although not covered in the original issue, the suffixes need to be consistent to avoid constant config updates in DB mode, so random suffixes or counters (the iteration order can vary and changes when new plugins are added) aren't an option. I initially did the entity name verbatim, but this is indeed quite long. Full hashes are actually longer, but should be …
=> fix(plugins) add suffix to instance_name

test/envtest/gateway_envtest_test.go, test/envtest/metrics_envtest_test.go
This moves `TestMetricsAreServed` envtest based test to `test/envtest`.
Additionally this also fixes error logs emitted in `TestGatewayReconciliation_MoreThan100Routes` which were caused by a missing backend service
```
can't add target for backend backend-svc: no kubernetes service found
```
```
E0831 10:39:17.938573   12044 event.go:240] Unable to write event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"9969e54d-6c3d-484c-9b7e-1d7b5dabd0c9.17806b0b1d7f0b40", GenerateName:"", Namespace:"0afe3c6d-0f4f-4f83-acd4-d5a9c76eef71", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, …
```
=> chore(tests): move metrics envtest to test/envtest

.github/workflows/_conformance_tests.yaml, .github/workflows/_e2e_tests.yaml, .github/workflows/_envtest_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_linters.yaml, .github/workflows/_unit_tests.yaml, .github/workflows/benchmarks.yaml, .github/workflows/cleanup.yaml, .github/workflows/codeql.yaml, .github/workflows/pr_checks.yaml, go.mod, go.sum, third_party/go.mod, third_party/go.sum
Embrace [native toolchain management](https://go.dev/blog/toolchain) introduced in Go 1.21.0. Moreover do not rely on the hardcoded Go version in GH workflows that has to be updated manually, use the version defined in `go.mod` instead, [read more].
To conclude when a new version of Go is released only update in `go.mod` to have the newest (and the same) version everywhere used (even locally).
**Special notes for your reviewer:**
Probably in the future usage of `actions/setup-go@v4` to set version based on `go.mod` can be ditched too, because the Go toolchain ensures the right version automatically. For now, it's required because GH runners have an older version of Go that does not support toolchain features.
=> chore(go): introduce usage of Go toolchain

test/integration/ingress_https_test.go, test/internal/helpers/kong.go
Kong gateway supports HTTPS redirect with expression router since 3.4: https://github.com/Kong/kong/pull/11166. We need to add the case back in integration tests.
=> test: enable HTTPS redirect tests with expression router

CHANGELOG.md, internal/admission/adminapi_provider.go, internal/admission/validator.go, internal/admission/validator_test.go, internal/dataplane/parser/translate_httproute.go, internal/manager/run.go, internal/manager/setup.go, internal/validation/gateway/httproute.go, internal/validation/gateway/httproute_test.go, test/integration/gateway_webhook_test.go, test/integration/helpers_test.go, test/integration/httproute_webhook_test.go, test/integration/kongingress_webhook_test.go, test/integration/skip_helpers_test.go, test/integration/webhook_test.go
It introduces better validation for `HTTPRoute` object:
- uses the Kong Gateway endpoint for validating `KongRoute` by calling method [RouteService.Validate](https://pkg.go.dev/github.com/kong/go-kong/kong#RouteService.Validate)
- stops rejecting
- regex path matching rules (implemented https://github.com/Kong/kubernetes-ingress-controller/issues/2153)
- regex header matching rules (implemented https://github.com/Kong/kubernetes-ingress-controller/issues/2154)
- still reject - query parameters matching (not implemented yet https://github.com/Kong/kubernetes-ingress-controller/issues/3679)
- introduces test coverage for both  expressions based routers and old ones
This is part of …
=> feat(admission): validate regex supplied in HTTPRoute (stop rejecting)

Makefile, test/envtest/adminapi_discoverer_envtest_test.go, test/envtest/crds_envtest_test.go, test/envtest/k8s_objects_status_envtest_test.go, test/envtest/kongadminapi_controller_envtest_test.go, test/envtest/telemetry_test.go
Move all `envtest` based tests into `test/envtest` directory and removing `envtest` dependency from `test.unit` (and related) targets.
=> chore(tests): move all envtest based tests into test/envtest

.gitignore, .golangci.yaml, Makefile, internal/manager/metadata/metadata.go, internal/manager/metadata/metadata_test.go, test/conformance/gateway_conformance_test.go, test/conformance/gateway_expermimental_conformance_test.go, test/conformance/suite_test.go, test/internal/testenv/testenv.go
Add the experimental conformance suite to KIC tests. Create `Makefile` target `test.conformance-experimental` to run them. Since it's still experimental leave it as a separate target. The generated report is saved in the root of the repository `conformance-tests-report.yaml` (it's added to `.gitignore`). Those tests are run only for KIC with expression routes enabled. In the future (probably when gateway-api reaches 1.0.0) it will stop being experimental and it will be the default and only way of running conformance tests.
Generated report on code from this PR `make test.conformance-experimental` looks like that
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2023-09-06T11:13:41+02:00"
gatewayAPIVersion: TODO
implementation:
contact:
- …
```
=> tests: add experimental conformance test suite

.golangci.yaml
Three is no option `exclude_godoc_examples` in `forbidigo` config, the valid one is `exclude-godoc-examples`, check [the docs](https://golangci-lint.run/usage/linters/#forbidigo).
=> chore(linter): fix golangci-lint forbidigo config

CHANGELOG.md, internal/dataplane/configfetcher/config_fetcher.go, internal/dataplane/configfetcher/config_fetcher_test.go, test/mocks/admin_api_handler.go
When last known configuration fetcher gets a `nil` status from `Client.Status()` in https://github.com/Kong/kubernetes-ingress-controller/blob/25d37902dd781924cf7604a333449fad31ae905c/internal/dataplane/configfetcher/config_fetcher.go#L69 the controller panic as can be observed when downloading one of the last E2E failure runs: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6114470254
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x19f329a]
goroutine 198 [running]:
github.com/kong/kubernetes-ingress-controller/v2/internal/dataplane/configfetcher.(*DefaultKongLastGoodConfigFetcher).TryFetchingValidConfigFromGateways(0xc0008dabe0, …
```
=> fix: fix panic when last known configuration fetcher gets a nil status

test/integration/gateway_webhook_test.go, test/integration/httproute_webhook_test.go, test/integration/kongingress_webhook_test.go, test/integration/webhook_test.go
- get rid of redundant settings like e.g. `TypeMeta`
- refactor functions that start with `ensureXXX` to take `t *testing.T` as a parameter and use `t.Cleanup` instead of returning
Spotted during CR for 
- https://github.com/Kong/kubernetes-ingress-controller/pull/4608
=> refactor(tests): improve code for webhooks

test/integration/httproute_webhook_test.go
For Kong Gateway `< 3.0` error message returned is a little bit different
```
schema violation (paths.2: invalid regex: '/foo[[[[' 
```
vs
```
schema violation (paths.3: invalid regex: '/foo[[[['
```
for Kong `>= 3.0`
thus assert only on 
```
invalid regex: '/foo[[[['
```
as good enough.
- [CI run](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6121766620/job/16616198424#step:6:6770)
- fix for changes introduced in https://github.com/Kong/kubernetes-ingress-controller/pull/4608
=> fix(tests): validate regex supplied in HTTPRoute for Kong < 3.0

test/integration/gateway_webhook_test.go, test/integration/httproute_webhook_test.go, test/integration/kongingress_webhook_test.go, test/integration/webhook_test.go
Registered admission webhook is scoped to the namespace passed as an argument to function `ensureAdmissionRegistration`, it introduces better separation for our tests. 
Closes #4621
=> chore(tests): add namespace selector in ensureAdmissionRegistration

.github/ISSUE_TEMPLATE/release.yaml, .github/workflows/conformance_tests_report.yaml
Introduces CI workflow that can be run for a specific version of code (specified by tag or commit hash) and generates the report as an artifact for submitting to https://github.com/kubernetes-sigs/gateway-api/tree/main/conformance/reports. This is still in an experimental phase, hence it's not run automatically as a part of the release workflow. 
It can be run only for code that includes 
- https://github.com/Kong/kubernetes-ingress-controller/pull/4551
Thus it will be used to generate such a report for `KIC 2.12.0`.
This is part of
- https://github.com/Kong/kubernetes-ingress-controller/issues/4402
=> tests: add CI workflow for generating conformance tests report

CHANGELOG.md, internal/dataplane/parser/translate_failures_test.go, internal/dataplane/parser/translate_kong_l4.go, internal/dataplane/parser/translators/l4route_atc.go, internal/dataplane/parser/translators/l4route_atc_test.go, test/integration/tcpingress_test.go, test/integration/udpingress_test.go
Adds expression routing for TCPIngress and UDPIngress.
Adds a unit test for the L4 kongstate.Route translator.
Fix #4541 
Fix #4542 
https://github.com/Kong/kubernetes-ingress-controller/pull/4385 is still setting the traditional `protocols` field. Is this correct? https://docs.konghq.com/gateway/latest/reference/router-expressions-language/#main indicates there's a `net.protocol` expression field.
https://github.com/Kong/kubernetes-ingress-controller/pull/4385 added a test for TCPRoute specifically, but I don't think we need a per-resource unit test for these. We already test kongstate.Route creation for resources, and the expression translator operates on kongstate.Routes, so I …
=> Support TCPIngress and UDPIngress expression routes

go.mod
This unbreaks the CI. Reason for this is that FOSSA Github action doesn't support go 1.21's `toolchain` directive.
Related issue: https://github.com/Kong/kubernetes-ingress-controller/issues/4635
This aims to prevent failures like this: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6141226981/job/16661215380
=> chore(ci): disable toolchain in go.mod

internal/cmd/rootcmd/run.go, internal/manager/conditions.go, internal/manager/conditions_test.go, internal/manager/controllerdef.go, internal/manager/run.go, internal/manager/setup.go, test/envtest/run.go
Instead of using the global `ctrl.Log` and setting it with `ctrl.SetLogger`, let's pass it along in context. This allows injecting logger in tests without interference with other test cases run in the same test binary.
`ctrl.SetLogger` is effective only once. If we set the logger in one test case, it can never be overridden later, making it impossible to dump/verify logs from a test case that was run not as a first one. I discovered this when working on https://github.com/Kong/kubernetes-ingress-controller/pull/4619 where I'm expecting logs in tests.
=> chore: don't use global controller-runtime logger

internal/controllers/crds/dynamic_controller.go, internal/manager/conditions.go, internal/manager/conditions_test.go, internal/manager/controllerdef.go, internal/manager/run.go, test/envtest/crds_envtest_test.go, test/envtest/gateway_envtest_test.go, test/envtest/kongstate_consumer_failures_test.go, test/envtest/manager_envtest_test.go, test/envtest/programmed_condition_envtest_test.go, test/envtest/run.go, test/envtest/setup.go, test/internal/helpers/tcp.go, test/internal/helpers/tcp_test.go
It introduces a Kubernetes API status check on start-up to prevent issues like https://github.com/Kong/kubernetes-ingress-controller/issues/4603 and https://github.com/Kong/kubernetes-ingress-controller/issues/4207. With the connectivity ensured, we may rely on controller-runtime default behavior (cache sync timeout will be triggered in case of missing CRDs) and drop our manual checks for Kong's CRD existence.
Adds envtests:
- `TestManagerDoesntStartUntilKubernetesAPIReachable` to ensure the manager will not start its runnables (including the config sync loop) until the Kubernetes API is reachable.
- `TestNoKongCRDsInstalledIsFatal` to ensure that in case of missing Kong CRDs installation, the controller will eventually crash. 
- …
=> fix: ensure connectivity with Kubernetes API on start-up

CHANGELOG.md, internal/admission/handler.go, internal/admission/server_test.go, internal/admission/validator.go, internal/dataplane/parser/translate_ingress.go, internal/util/builder/ingress.go, internal/validation/gateway/httproute.go, internal/validation/ingress/ingress.go, internal/versions/versions.go, test/integration/httproute_webhook_test.go, test/integration/ingress_webhook_test.go
Introduce custom validation for `Ingress` object:
- uses the Kong Gateway endpoint for validating KongRoute by calling method [RouteService.Validate](https://pkg.go.dev/github.com/kong/go-kong/kong#RouteService.Validate)
- the above allows validating regex expressions configured by users in `Ingress` paths
- introduces test coverage for both expressions router and old ones
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4557
Run also test suit manually for Kong Gateway `< 3.0` - `kong-gateway:2.8.4.2` on this branch to ensure that integration tests that rely on messages returned from the Gateway are compatible
- …
=> feat(admission): validate path with regex supplied in Ingress

internal/util/test/controller_manager.go
For integration tests the below is logged (it's not a problem for running KIC normally)
```log
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
>  goroutine 623 [running]:
>  runtime/debug.Stack()
>  	/opt/hostedtoolcache/go/1.21.0/x64/src/runtime/debug/stack.go:24 +0x67
>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/log/log.go:60 +0xed
>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithValues(0xc00074be00, {0x0, 0x0, 0x0})
>  	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/log/deleg.go:168 +0x55
>  github.com/go-logr/logr.Logger.WithValues(...)
> …
```
=> chore(tests): get rid of "log.SetLogger(...) was never called..." log

CHANGELOG.md, hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/controllers/gateway/gateway_controller.go, internal/controllers/knative/knative.go, internal/controllers/reference/indexer.go, internal/controllers/reference/indexer_test.go, internal/controllers/reference/reference.go, internal/manager/controllerdef.go, internal/store/store.go, test/envtest/gatewayclass_envtest_test.go
The PR sets type meta for objects when adding them to cache stores and reference indexers, and fetching objects referred by when the object gets deleted. This PR is added because cache indexers to store reference relations needs object kind(GVK) for indexing, and this comes from `TypeMeta` of the k8s resource. 
If we do not set the `TypeMeta`, the object kind of objects are always empty so we could not find them correctly in reference indexers. 
It also adds logs when setting or deleting reference relations between objects.
fixes #3201 
=> fix: add type meta when saving them to cache and reference indexer

CHANGELOG.md, internal/dataplane/sendconfig/error_handling_test.go, internal/dataplane/sendconfig/inmemory.go, internal/dataplane/sendconfig/inmemory_error_handling.go
When Kong client fails to get response from reloading declarative configuration (`POST /config`), do not parse the error body and directly return the error for not getting response, to produce less misleading error log (than `could not unmarshal config error: unexpected end of JSON input`) for the situations.
fixes #4665
=> fix(log): do not parse error body when response is empty in reloading config

CONTRIBUTING.md
Add a section in `CONTRIBUTING.md` to tell usage of `Draft` PRs and `do not merge` or `work in progress` labels on PRs:
- Draft PR: not ready for review
- `do not merge` label: ready for review, but not ready to merge
=> docs: add sections to tell usage of Draft PR

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongingresses.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, pkg/apis/configuration/v1/kongingress_types.go
This adds `latency` as a supported value for `KongIngress` `upstream.algorithm` field.
This is only support in Kong Gateway 3.2+
With this change users will be able to use it as such:
```yaml
apiVersion: v1
kind: Service
metadata:
annotations:
konghq.com/override: algo
name: svc
spec:
...
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
name: algo
upstream:
algorithm: latency
```
Closes #4616.
Is `konghq.com/override` the only way to specify this? I believe we wanted to go away from using that, OTOH though [docs](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/#konghqcomoverride) mention that `upstream` field related config …
=> feat: add `latency` to supported values of KongIngress upstream.algoritm field

test/integration/gateway_test.go
Since `gateway-api` is in version `0.8.1` the bug has been fixed in upstream
- https://github.com/kubernetes-sigs/gateway-api/pull/2370
thus previously problematic configuration can be re-enabled in our tests. 
closes https://github.com/Kong/kubernetes-ingress-controller/issues/4597
=> chore(tests): re-enable gateway config (bug fixed in upstream)

CHANGELOG.md, internal/dataplane/deckgen/generate.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/kongstate/license.go, internal/dataplane/parser/parser.go
We missed adding `Licenses` and `ConsumerGroups` to the sanitized copies. This PR adds them, as well as improves tests to catch such cases in the future automatically.
=> fix: include Licenses and ConsumerGroups in sanitized copies of config

.github/workflows/_e2e_tests.yaml
Bumps istio in the E2E test, per the release instructions in #4699
Part of #4699
=> test(e2e): include istio 1.19, drop istio 1.15

CHANGELOG.md, LICENSES, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
KiC v2.12 release chores.
- Adds the 2.12 entry in the changelog
- Bumps KIC version to 2.12 in kustomize
Part of #4699 
=> Release PR for 2.12.0

deploy/manifests/sample-apps/grpc.yaml, examples/gateway-grpcroute.yaml, test/consts.go, test/integration/grpcroute_test.go, test/integration/ingress_test.go
Instead of using the original, unmaintained one, use the fork maintained by Kong.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/3659
We still use [github.com/moul/pb](https://github.com/moul/pb) as a client for [github.com/Kong/grpcbin](https://github.com/Kong/grpcbin), it wasn't in the scope of the original issue, and Kong does not mirror this dependency. Maybe is something to consider - mirroring or including it in [github.com/Kong/grpcbin](https://github.com/Kong/grpcbin)
=> chore(tests): replace image moul/grpcbin with kong/grpcbin

test/conformance/gateway_expermimental_conformance_test.go
Since the report in [gateway-api](https://github.com/kubernetes-sigs/gateway-api/tree/main/conformance/reports/v0.7.1) is expected to have be named `kong-kubernetes-ingress-controller.yaml` change to it to reduce friction.
Enable test `GatewayClassObservedGenerationBump` as it has been fixed in 
- #4645 
[Related run](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6301443503) of CI workflow for generating a report.
=> tests(conformance): for experimental enable test and change report name

hack/deploy-admission-controller.sh
Add Ingress and GWAPI v1beta1 to the admission webhook creation script.
Existing checks weren't running for current GWAPI resources.
New (as of 2.12) checks for Ingress regex paths weren't running at all.
Smoke test against standard good examples and @mheap's broken Ingress. Also copied the path into the HTTPRoute example:
[log.txt](https://github.com/Kong/kubernetes-ingress-controller/files/12732283/log.txt)
The script lives on Github main and isn't part of release artifacts: https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/admission-webhook/
=> Add Ingress and GWAPI v1beta1 to admission webhook

CHANGELOG.md, internal/manager/setup.go
Getting rid of the message that complains about a missing call to `SetLogger()` when KIC is killed or shutdown.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4736
Unfortunately, controller-runtime expects it to be called always, it was spotted in tests, and the fix was provided
- https://github.com/Kong/kubernetes-ingress-controller/pull/4661
but only in the test helper. Now it is in both places. Efforts relating to streamlining logging in KIC may help us with having all the configurations in one place. 
=> fix: no more "log.SetLogger(...) was never called..." log entry during shutdown

CHANGELOG.md, internal/dataplane/kongstate/kongstate.go, internal/store/fake_store_test.go, internal/store/store.go
`KongClusterPlugin` supports the label `global: true`, [see the docs](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-kongplugin-resource/#configuring-global-plugins) and it is not changed.
For a long time (since `KIC v0.10.0`) for `KongPlugin` with the label `global: true` KIC logs a warning about unsupporting. This PR gets rid of everything related to the support of label `global` for `KongPlugin`, including a warning.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/3873
=> chore: remove everything related obsolete global KongPlugins

internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go, test/e2e/utils_test.go, test/integration/httproute_test.go
Removes `RouteReasonNoMatchingParent` const and uses the one from upstream.
=> chore: use upstream RouteReasonNoMatchingParent

.github/workflows/_integration_tests.yaml
Save around 3 minutes of integration tests run time by pulling the invalid config test suite into a separate integration tests matrix entry.
Currently running with default `traditional` router flavour. That's right isn't it? Before this change it was running with all routers in all [matrix entries](https://github.com/Kong/kubernetes-ingress-controller/blob/edfd7e2b1c2f7e2b9866c3ca7dd08c956a4a0866/.github/workflows/_integration_tests.yaml#L48-L79) but that should really be the case.
=> tests(integration): run invalid confg tests in parallel with all other

test/integration/ingress_test.go, test/integration/suite_test.go, test/integration/utils_test.go
Code that was using `clusterVersion` was mostly around skipping tests for k8s `<=1.21` or `<1.19` and since we don't tests on those versions anymore we can get rid of that.
=> tests(integration): remove clusterVersion and test skipping code for EOLd k8s versions

CHANGELOG.md, internal/admission/handler.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/route.go, internal/dataplane/kongstate/route_test.go, internal/dataplane/kongstate/service.go, internal/dataplane/kongstate/service_test.go, internal/dataplane/kongstate/util.go, test/e2e/helpers_test.go, test/integration/kongingress_test.go, test/integration/kongingress_webhook_test.go
Stops respecting deprecated `KongIngress` `Proxy` and `Route` fields and aligns tests to use annotations in favor of `KongIngress`.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/3018 and https://github.com/Kong/kubernetes-ingress-controller/issues/4740.
=> chore: remove deprecated KongIngress functionality

CHANGELOG.md, internal/manager/telemetry/reports.go, test/envtest/telemetry_test.go
Includes the router flavor in reports.
Tests normally can't run telemetry against a real instance, so an example with that flipped in `KONG_TEST_EXPRESSION_ROUTES=true KONG_TEST_CLUSTER=kind:kind GOFLAGS="-tags=integration_tests" dlv test ./test/integration`
```
(dlv) p cfg["router_flavor"]
interface {}(string) "traditional"
(dlv) n
> github.com/kong/kubernetes-ingress-controller/v2/internal/manager/telemetry.SetupAnonymousReports() ./internal/manager/telemetry/reports.go:82 (PC: 0x3e0a70a)
77:		kongDB, ok := cfg["database"].(string)
78:		if !ok {
79:			return nil, fmt.Errorf("malformed database configuration found in Kong client root")
80:		}
81:		routerFlavor, ok := cfg["router_flavor"].(string)
=>  82:		if !ok …
```
=> feat(telemetry) add Kong router flavor

CHANGELOG.md, internal/adminapi/konnect.go, internal/konnect/license/client.go, internal/konnect/nodes/client.go, test/e2e/konnect_test.go
replace the `runtime_groups` in paths to `control_planes` in konnect APIs.
fixes #4466
Still WIP. There are still hundreds appearances of the word "runtime group". Except for the "historical" part, CHANGELOG entries for the older version, they should ALL be replaced to "control plane".
Question: In the envs/config flags, should we support both `runtime_group` and `control_plane` to specify the ID of konnect RG/CP? I suppose to support both, but `control_plane` takes higher priority, for compatibility of old charts/deployments.
=> chore: replace "runtime_group" with "control_plane" in konnect APIs

CHANGELOG.md, internal/manager/config.go
Remove previously deprecated flags for 3.0 release.
=> chore: remove deprecated flags for 3.0

test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/istio_test.go, test/integration/config_error_event_test.go, test/integration/consumer_group_test.go, test/integration/consumer_test.go, test/integration/ingress_https_test.go, test/integration/ingress_test.go, test/integration/kongingress_test.go, test/integration/plugin_test.go, test/integration/translation_failures_test.go
To prevent warning logs like:
```
W1002 22:46:30.055335   14658 warnings.go:70] annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
```
which are prevalent in integration and e2e tests let's use the spec field which has the same behaviour and is the recommended (not-deprecated) way of setting the ingress class on a net v1 `Ingress`.
=> tests: use `ingressClass` spec field instead of a deprecated `kubernetes.io/ingress.class` annotation

Makefile, docs/cli-arguments.md, hack/cleanup/konnect_runtime_groups.go, hack/cleanup/main.go, internal/adminapi/backoff_strategy_konnect.go, internal/adminapi/client.go, internal/adminapi/konnect.go, internal/adminapi/konnect_test.go, internal/clients/manager.go, internal/dataplane/kong_client.go, internal/dataplane/sendconfig/sendconfig.go, internal/dataplane/sendconfig/strategy.go, internal/dataplane/sendconfig/strategy_test.go, internal/konnect/controlplanes/client.go, internal/konnect/controlplanesconfig/client.go, internal/konnect/license/client.go, internal/konnect/node_agent.go, internal/konnect/node_agent_test.go, internal/konnect/nodes/client.go, internal/konnect/roles/client.go, internal/konnect/roles/client_test.go, internal/manager/config.go, internal/manager/config_validation_test.go, internal/manager/run.go, test/e2e/konnect_test.go
Refactors non-user-facing code to use `control plane` instead of `runtime group` naming for Konnect control planes.
Part of #4466.
=> chore: use 'control plane' instead of 'runtime group' naming

internal/cmd/rootcmd/run.go, internal/manager/config.go, test/envtest/ingress_test.go, test/envtest/manager_debugendpoints_test.go, test/envtest/run.go, test/envtest/setup.go, test/integration/ingress_test.go, test/mocks/admin_api_handler.go
This migrates the `TestIngressWorksWithServiceBackendsSpecifyingOnlyPortNames` integration test to `envtest` suite.
It also performs some refactoring in the `envtest` suite to ensure all tests pass, among others
- it adds holding the config by the API mocks and returning it in subsequent `GET /config` requests
- it disables the diagnostics server and profiling by default in `envtest` suite
- adds several test configuration functions like `WithProxySyncSeconds`, `WithDiagnosticsServer`
- it makes `TestDebugEndpoints` use the `RunManager` to start the controller manager instead of using hand rolled code for that
- adds `t.Logf("got config: %v", string(b))` log to Admin API mock to print the received config
=> tests: migrate `TestIngressWorksWithServiceBackendsSpecifyingOnlyPortNames` integration tests to envtest suite

internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go, internal/admission/validator.go, internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_utils.go, internal/dataplane/parser/translate_utils_test.go, internal/versions/versions.go, test/integration/httproute_test.go
This PR removes the redundant version guard - `RegexHeaderVersionCutoff`.
PR https://github.com/Kong/kubernetes-ingress-controller/pull/4766 introduced a global check for KIC `3.0.0` that allows only using Kong Gateway in version `>= 3.4.1`
=> chore: remove RegexHeaderVersionCutoff check

Makefile, test/envtest/crds_envtest_test.go, test/envtest/gateway_envtest_test.go, test/envtest/k8s_objects_status_envtest_test.go, test/envtest/manager_envtest_test.go, test/envtest/setup.go, test/envtest/telemetry_test.go
This PR makes the tests in `envtest` suite run in parallel.
Additionally it adds the `test.envtest.pretty` which prints only the test names and test output logs only when those fail.
=> tests: run envtest suite in parallel, add test.envtest.pretty

internal/versions/versions.go
**What this PR does / why we need it:**
This PR removes the redundant version guard - ConsumerGroupsVersionCutoff.
PR https://github.com/Kong/kubernetes-ingress-controller/pull/4766 introduced a global check for KIC 3.0.0 that allows only using Kong Gateway in version >= 3.4.1.
Leftover from 
- https://github.com/Kong/kubernetes-ingress-controller/pull/4795
=> chore: remove TLSPassthroughCutoff leftover

internal/admission/errors.go, internal/admission/validator.go, internal/admission/validator_test.go, internal/versions/versions.go, test/integration/consumer_group_test.go
This PR removes the redundant version guard - `ConsumerGroupsVersionCutoff`.
PR https://github.com/Kong/kubernetes-ingress-controller/pull/4766 introduced a global check for KIC `3.0.0` that allows only using Kong Gateway in version `>= 3.4.1`
=> chore: remove ConsumerGroupsVersionCutoff check

.github/test_dependencies.yaml, .github/workflows/_e2e_tests.yaml, .github/workflows/_integration_tests.yaml
Extracts `Kind`, `GKE` and `Istio` versions definitions to a separate file: `.github/test_dependencies.yaml`. Uses `yq` and `jq` to extract versions from the file in workflows.
There was an [alternative attempt](https://github.com/Kong/kubernetes-ingress-controller/compare/main...chore/test-deps-file) not using `jq` nor `yq` but a separate dedicated Go script but I think it's better to keep it simple - `jq` gives us enough flexibility to extract values we're interested in for the workflows.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/4691.
=> chore: extract test dependencies to a separate file

test/integration/utils_test.go
This PR makes it so that integration tests will log the setup error when the cleanup logic is run but fails (which up until now didn't print anything).
This also prevents failures in dereferencing the `env` fields/methods when it's still unset.
=> tests(integration): log setup failure reason

internal/dataplane/sendconfig/inmemory.go, internal/dataplane/sendconfig/strategy.go
Removes unused `UpdateStrategyInMemory.version` field.
=> chore: drop unnecessary version field in UpdateStrategyInMemory

internal/dataplane/kongstate/consumer.go, internal/dataplane/kongstate/consumer_test.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/parser/parser.go, internal/versions/versions.go
This PR removes the redundant version guard - `MTLSCredentialVersionCutoff`.
PR https://github.com/Kong/kubernetes-ingress-controller/pull/4766 introduced a global check for KIC `3.0.0` that allows only using Kong Gateway in version `>= 3.4.1`
=> chore: remove MTLSCredentialVersionCutoff check

.golangci.yaml, Makefile, internal/dataplane/kongstate/util.go, internal/dataplane/parser/ingressclassparemeters_test.go, internal/dataplane/parser/translate_ingress.go, internal/dataplane/parser/translate_tlsroute.go, internal/store/errors.go, internal/store/fake_store_test.go, internal/store/store.go
Add [`errname`](https://github.com/Antonboom/errname) linter to ensure that the convention:
> Error types end in "Error" and error variables start with "Err" or "err":
is enforced.
https://github.com/golang/go/wiki/Errors#naming
=> ci: add errname linter

internal/dataplane/parser/atc/expression_test.go, internal/dataplane/parser/atc/predicate.go, internal/dataplane/parser/atc/predicate_test.go, internal/dataplane/parser/translators/l4route_atc.go
Adds validation on creating ATC predicates in `NewPredicate`.
fixes #3822.
~- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ No user facing part changed.
=> feat(expression router) add validation to creating predicates

CHANGELOG.md, internal/dataplane/sendconfig/error_handling_test.go, internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/sendconfig/sendconfig.go, test/envtest/configerrorevent_envtest_test.go, test/integration/config_error_event_test.go
When an error in the flattened errors response is related to a whole entity (its `type=entity`), we can generate a more descriptive key for this kind of problem by building it from the entity type and name instead of accidentally using an empty string.
```json
{
"fields": {},
"flattened_errors": [
{
"errors": [
{
"type": "field",
"message": "value must be null",  
"field": "path"
},
{
"type": "entity",  <-- Make use of that to determine if the error is associated with a single field or a whole entity.
"message": "failed conditional validation given value of field protocol"
}
],
"entity": {
"host": "konghq.com",
"name": "test-service",
"port": 80,
"path": "/test",
"tags": [
"k8s-name:test-service",
"k8s-namespace:default",
"k8s-kind:Service", …
```
=> fix: handle flattened errors related to whole entities

test/expressionrouter/generate_test.go, test/integration/consumer_group_test.go, test/integration/consumer_test.go, test/integration/gateway_test.go, test/integration/httproute_test.go, test/integration/ingress_regex_match_test.go, test/integration/ingress_test.go, test/integration/plugin_test.go, test/internal/helpers/http.go
- Add `host` parameter to `MustHTTPRequest` to make it easier to generate an HTTP request with certain host
- Add `DefaultHTTPClientWithProxy` to create a client proxying to Kong gateway
- Modify affected test code
fixes #3788 
~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ No CHANGELOG required.
=> test: add host to MustHTTPRequest and implement HTTP client with proxy

CHANGELOG.md, docs/cli-arguments.md, internal/manager/config.go, internal/manager/config_test.go, internal/manager/config_validation.go, internal/manager/config_validation_test.go, internal/manager/run.go
When deploying Kong Enterprise in Kubernetes we need another option to secure the Kong admin token. The existing feature to provide the kong-admin-token via the environment variable CONTROLLER_KONG_ADMIN_TOKEN which can be backed as a Kubernetes secret does not fit for us.
Providing Kong admin token via file #4789
=> feat: provide Kong admin token via file

internal/util/test/webhooks.go, test/conformance/suite_test.go, test/integration/webhook_test.go
Running
```sh
make test.integration.dbless GOTESTFLAGS='-count 1 -run TestIngressValidationWebhook'
```
doesn't work locally with Lima based environment. This PR fixes it. It adds a similar workaround as previously added by @czeslavo (who pointed me to this code, thx) for Colima. 
There is an outstanding question about the stability of those hardcoded IPs, but with a single environment run on a local machine they seem to be stable. To consider - enforcing those IPs in set-up scripts.
=> fix: allow run validation webhook tests with Lima based env

.github/test_dependencies.yaml
In https://github.com/Kong/kubernetes-ingress-controller/pull/4822 I missed adding Renovate annotations for Kind in Istio test matrix.
Part of #4692.
=> chore: add missing kind renovate annotations

.github/test_dependencies.yaml, renovate.json
Sets up a [Custom Datasource](https://docs.renovatebot.com/modules/datasource/custom/) using https://github.com/Kong/gke-renovate-datasource that will make Renovate automatically update GKE versions.
Part of #4692.
=> chore: setup GKE Renovate custom datasource

.github/ISSUE_TEMPLATE/release.yaml
As https://github.com/Kong/kubernetes-ingress-controller/issues/4692 has introduced automatic updates of the dependencies mentioned in the release template test matrix checkup, we can now remove this step from the template.
Effect of https://github.com/Kong/kubernetes-ingress-controller/issues/4692.
=> chore: remove test matrix checkup from release template

hack/generators/controllers/networking/main.go, internal/controllers/configuration/kongadminapi_controller.go, internal/controllers/configuration/secret_controller.go, internal/controllers/configuration/zz_generated_controllers.go, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gatewayclass_controller.go, internal/controllers/gateway/grpcroute_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/referencegrant_controller.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/controllers/reference/indexer.go, internal/manager/controllerdef.go, internal/manager/type_meta_setting_client.go, internal/util/types.go, internal/util/types_test.go, test/integration/consumer_test.go
Review suggestion: instead of having to remember to call `util.PopulateTypeMeta` in every controller, we can decorate the client to always do it. Also, use the client's schema instead of building it on every call.
=> review: decorate client instead of calling multiple times

CHANGELOG.md, internal/controllers/gateway/udproute_controller.go
Fixes a typo in UDPRoute controller's watch which is set to watch status updates.
This should fail a test or 2, how come this didn't 🤔 ?
=> fix: fix typo in UDPRoute controller's watch

.github/test_dependencies.yaml, .github/workflows/_conformance_tests.yaml, .github/workflows/_e2e_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_kongintegration_tests.yaml, Makefile, renovate.json, test/conformance/suite_test.go, test/consts/helm.go, test/integration/suite_test.go, test/internal/testenv/testenv.go
Add Renovate config for helm chart
Based on
- https://docs.renovatebot.com/user-stories/maintaining-aur-packages-with-renovate/#updating-versions-with-renovate
- https://docs.renovatebot.com/modules/datasource/gitlab-releases/
Exemplar working PR: https://github.com/pmalek/kubernetes-ingress-controller/pull/1
=> feat(ci): add renovate config for kong helm chart

test/conformance/gateway_conformance_test.go, test/consts.go, test/envtest/programmed_condition_envtest_test.go, test/integration/httproute_test.go, test/integration/suite_test.go, test/integration/version_test.go, test/integration/webhook_test.go, test/internal/helpers/kong.go, test/kongintegration/containers/kong.go
PR https://github.com/Kong/kubernetes-ingress-controller/pull/4766 introduces a global check on KIC startup for the Kong Gateway version to allow only `>= 3.4.1`. Tests that use Kong Gateway are run in separation (and do not include the aforementioned check), hence let's enforce during test environment creation Kong Gateway in version `3.4.1` to be consistent everywhere. 
The update of the Helm chart version should be handled automatically by #4846 (which will put this into `.github/test_dependencies.yaml`), so after it and rebase tests should pass. The Helm chart version will be `2.29.0` (it includes Kong …
=> chore(tests): enforce Kong Gateway in the version >= 3.4.1

test/kongintegration/containers/kong.go
Run code that retrieves the kong version in `.Eventually()`.
This should fix e.g. https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6528638258/job/17725109637?pr=4859#step:5:580
```
kong.go:74: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/kongintegration/containers/kong.go:74
/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/kongintegration/parser_golden_tests_outputs_test.go:86
making HTTP request: Get "http://localhost:32772/": read tcp [::1]:44440->[::1]:32772: read: connection reset by peer
Test:       	TestParsersGoldenTestsOutputs/default
```
=> tests(kongintegration): make kong version retrieval run in .Eventually()

internal/manager/controllerdef.go
The ReferenceGrant is in beta but we treat its controller as an alpha one. This resource should be reconciled by default.
=> fix: enable by default referenceGrant controller

test/e2e/helpers_gateway_test.go, test/integration/examples_test.go, test/integration/tcproute_test.go, test/integration/tlsroute_test.go, test/tcp_utils.go
Simplify API of helpers `TCPEchoResponds` and `tlsEchoResponds`, returning an error is enough, the boolean value was redundant. Furthermore inspecting any returned value when a returned error is not nil is considered mostly as a bad practice in Go. Moreover they are consistent with `grpcEchoResponds` now.
=> chore(refactor): simplify API of TCPEchoResponds and tlsEchoResponds

.github/test_dependencies.yaml, renovate.json
Configures Renovate to bump minors only for the entries that we'd like it to update (typically only one entry in the test matrix that is treated as the latest version we want to test against). 
It builds on Renovate's [`packageRules`](https://docs.renovatebot.com/configuration-options/#packagerules) where we can specify various matches (`matchUpdateTypes`, `matchDatasource`, etc.) and settings that should apply to their matches (e.g. `enabled: false`).
In our case, we match `updateTypes=minor` with depNames pattern `.*@only-patch` and disable minor updates for those. We can explicitly specify another `depName` in the annotation (e.g. `depName=kindest/node@only-patch`) to make an entry match this rule. `depName` can be treated as a "display name", …
=> chore(deps): make Renovate bump kind/istio minors only for latest

.github/workflows/_conformance_tests.yaml, CHANGELOG.md, internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go, internal/dataplane/parser/atc/field.go, internal/dataplane/parser/atc/predicate.go, internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translators/httproute_atc.go, internal/dataplane/parser/translators/httproute_atc_test.go, internal/gatewayapi/aliases.go, internal/util/builder/httproutematch.go, test/conformance/gateway_conformance_test.go, test/conformance/gateway_expermimental_conformance_test.go, test/integration/httproute_test.go
implement query parameter matching in `HTTPRoute`.
fixes #3679 
=> feat(expression router): implement query parameter match of HTTPRoute

test/integration/examples_test.go, test/integration/gateway_test.go, test/integration/kongingress_test.go, test/integration/kongingress_webhook_test.go, test/integration/skip_helpers_test.go, test/integration/tcpingress_test.go, test/integration/translation_failures_test.go
use `skipTestForRouterFlavors` instead of `skipTestForExpressionRouter` to skip tests not expected to run with expression router, and remove the skip for unnecessary cases.
part of #4719 
=> test(integration): remove skipTestForExpressionRouter helper in tests

test/e2e/helpers_test.go
Set the full version when selecting GKE cluster version in E2E tests.
This prevents issues like specifying 1.28.1 in test dependencies matrix https://github.com/Kong/kubernetes-ingress-controller/blob/2089f87b924a0d4c7faff6a074f8426792bbe588/.github/test_dependencies.yaml#L17 and then shortening it to 1.28.0 by not specifying the patch version via `clusterBuilder.WithClusterMinorVersion()`
=> fix(tests): fix setting GKE cluster version setting

test/e2e/environment.go, test/e2e/features_test.go, test/e2e/helpers_test.go, test/internal/testenv/testenv.go
Use `testenv.ClusterVersion()` for cluster version in E2E tests
=> tests: use testenv.ClusterVersion() for cluster version in E2E tests

internal/annotations/annotations.go, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, test/conformance/gateway_conformance_test.go, test/conformance/suite_test.go, test/e2e/helpers_gateway_test.go, test/envtest/gatewayclass_envtest_test.go, test/integration/gateway_test.go, test/integration/gateway_webhook_test.go, test/integration/helpers_test.go
Create a new annotation for indicating the Gateway publish Service.
Add helpers to retrieve and update values from that annotation.
Fix #3849
This was flagged as a breaking change, but probably has limited impact. This annotation is managed by the controller and there is no user action needed following this change unless you had some other application consuming the annotation. Given its functional area overlap with official spec features (the Gateway status addresses) and our lack of documentation for it I expect that external usage is likely minimal.
This is at odds with https://github.com/Kong/kubernetes-ingress-controller/issues/4518. It uses `publish-service` for the annotation, …
=> chore(gateway) use dedicated publish annotation

CHANGELOG.md, internal/admission/handler.go, internal/admission/validation/consumers/credentials/validation.go, internal/admission/validation/consumers/credentials/validation_test.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/parser/parser.go, internal/labels/labels.go, internal/util/credential.go, internal/util/credential_test.go, test/envtest/kongstate_consumer_failures_test.go
Adds a label alternative to the `kongCredType` Secret field. Setting `konghq.com/credential: CREDTYPE` is now equivalent to setting a `kongCredType=CREDTYPE` Secret field.
Fix #2502
https://github.com/Kong/kubernetes-ingress-controller/issues/2502#issuecomment-1758213596 contains a migration script that will eventually go in docs. There isn't a clear place in 3.x docs to stick an upgrade section, so https://github.com/Kong/kubernetes-ingress-controller/issues/4854 to follow up. As a stopgap, the changelog links to the comment.
Adds new system, does not remove old system. Not sure we want to single release breaking change this; I think we can do the final removal after 3.0 unless we …
=> Determine credential type from label

internal/manager/config.go, internal/manager/setup.go, test/envtest/run.go
This PR adds `GracefulShutdownTimeout` option to manager config to allow customizing it in tests.
It doesn't expose this as a CLI flag so there's no user facing change but it will allow to configure this in tests to e.g. extend the graceful timeout on CI where the manager sometimes doesn't manage to shutdown in time (30s is the default timeout).
Example: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6571082626/job/17849593971?pr=4892#step:4:754
```
run.go:177: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/run.go:177
/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/asm_amd64.s:1650
failed waiting for all runnables to end within grace …
```
=> tests: add `GracefulShutdownTimeout` option to manager to extend it in tests

.github/ISSUE_TEMPLATE/release.yaml, renovate.json
Enables `renovate` manager in Kustomize that will handle image updates in `config/image/(enterprise|oss)/kustomize.yaml`. That allows dropping the manual step of updating those from the release issue template.
Tested on fork, created PRs:
- https://github.com/czeslavo/kubernetes-ingress-controller/pull/27 
- https://github.com/czeslavo/kubernetes-ingress-controller/pull/26
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4836.
=> chore(deps): enable kustomize manager in Renovate

CHANGELOG.md, hack/deploy-admission-controller.sh, internal/admission/handler.go, internal/admission/validator.go, internal/admission/validator_test.go, test/integration/webhook_test.go
Runs `credsvalidation.ValidateCredentials` just after ensuring the `Secret` has the `kongCredType` key. It will make the admission webhook validate credentials' Secrets' schema even if they're not associated with any `KongConsumer` yet.
Fix for #4885.
=> fix: run basic credentials validation despite relation with consumers

CHANGELOG.md
Adds the changelog entry for release 2.12.1.
Result of discussion in https://github.com/Kong/kubernetes-ingress-controller/pull/4904.
=> chore: add changelog for 2.12.1

CHANGELOG.md, hack/deploy-admission-controller.sh, internal/admission/handler.go, internal/admission/validator.go, internal/admission/validator_test.go, test/integration/webhook_test.go
Backports #4887 to release/2.12.x.
=> [backport release/2.12.x] fix: run basic credentials validation despite relation with consumers (#4887)

.github/workflows/_integration_tests.yaml, CHANGELOG.md, FEATURE_GATES.md, internal/dataplane/parser/golden_test.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/manager/featuregates/feature_gates.go, internal/manager/run.go, test/conformance/suite_test.go, test/consts/feature_gates.go, test/envtest/telemetry_test.go
remove feature gate `ExpressionRoutes` and enable KIC to translate k8s objects to expression based Kong routes when Kong gateway is using `expressions` router.
part of #4719.  
=> chore: remove feature gate ExpressionRoutes

internal/util/logging.go, test/envtest/run.go
Use the same log encoder for manager logs in `envtest` suite as when running the manager.
=> tests(envtest): use comming log encoder in envtest suite when printing logs

internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_httproute_test.go
Separate validation and translation of `HTTPRoute` and do not run validation inside translation functions of `HTTPRoute`.
fixes #4321 
~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ No user facing changes
=> chore: separate validation and translation for HTTPRoute

.github/workflows/regenerate_on_deps_bump.yaml, renovate.json
Renovates is capable of bumping `kustomize` images, but we cannot force it to regenerate manifests. This PR adds Renovate config `packageRule` that will add a `renovate/auto-regenerate` label to every `kustomize` manager-triggered PR, and a workflow that will regenerate manifests for PRs with this label. 
Tested with my fork: https://github.com/czeslavo/kubernetes-ingress-controller/pull/32
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/4836.
=> chore(deps): auto-regenerate manifests on Renovate manifests bumps

.golangci.yaml, internal/admission/handler.go, internal/controllers/gateway/gateway_utils.go, internal/manager/setup.go, test/e2e/utils_test.go, test/integration/helpers_test.go
This PR adjusts configuration of golangci-lint, to get rid of `//nolint:exhaustive`. It is sensible to always treat `switch` statements that include case `default` as exhaustive
=> chore(linter): in switch case default signifies exhaustive match

CHANGELOG.md, config/variants/multi-gw/oss/kustomization.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless.yaml
Excludes controller->admin API comms from meshes.
Part of #4698 
=> chore: exclude admin API comms from mesh

config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml, docs/api-reference.md, internal/dataplane/parser/translators/kongupstreampolicy.go, internal/dataplane/parser/translators/kongupstreampolicy_test.go, pkg/apis/configuration/v1beta1/kongupstreampolicy_types.go, pkg/apis/configuration/v1beta1/zz_generated.deepcopy.go
Adds `KongUpstreamPolicySpec` -> `kong.Upstream` translation function along with unit tests. 
Also, changes `hostHeader`'s JSON tag to match convention and adds missing `cookiePath` field.
Part of #4929.
=> feat: add KongUpstreamPolicySpec translation

internal/dataplane/parser/translators/portdef.go
`PortDefFromIntStr` is unused (an in `internal/`) so remove it
=> chore: remove unused PortDefFromIntStr

.golangci.yaml, Makefile, internal/admission/errors.go, internal/annotations/annotations.go, internal/dataplane/kong_client.go, internal/dataplane/kongstate/types.go, internal/dataplane/parser/atc/predicate.go, test/consts/exit_codes.go
This config change removes some unused defaults (by disabling the `--exclude-use-default`) and hence enforces correct comments and some more.
=> build: expand golangci-lint config to verify comments etc

config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml, docs/api-reference.md, internal/dataplane/parser/translators/kongupstreampolicy.go, internal/dataplane/parser/translators/kongupstreampolicy_test.go, pkg/apis/configuration/v1beta1/kongupstreampolicy_types.go, pkg/apis/configuration/v1beta1/zz_generated.deepcopy.go, test/envtest/crds_envtest_test.go
Adds `KongUpstreamPolicy` CRD validations (both CEL rules as well as regular min/max for HTTP status codes). It will allow us to make assumptions on data validity in the controller.
Closes #4951.
=> feat: add KongUpstreamPolicy CRD validation rules

internal/util/test/controller_manager.go
Before the change, any panic in the controller results in user-facing panic in logs, e.g. for unsupported feature gate
```log
...
2023-10-23T11:00:44+02:00       info    setup   found configuration option for gated feature    {"v": 0, "feature": "ExpressionRoutes", "enabled": true}
2023-10-23T11:00:44+02:00       info    diagnostics server is starting to listen        {"v": 0, "addr": 0}
panic: failed to configure feature gates: XXX is not a valid feature, please see the documentation: https://github.com/Kong/kubernetes-ingress-controller/blob/main/FEATURE_GATES.md
goroutine 516 [running]:
github.com/kong/kubernetes-ingress-controller/v2/internal/util/test.DeployControllerManagerForCluster.func1() …
```
=> fix(tests): print message instead of controller panic for expected errors

config/crd/bases/configuration.konghq.com_kongupstreampolicies.yaml, internal/dataplane/parser/translators/kongupstreampolicy_test.go, pkg/apis/configuration/v1beta1/kongupstreampolicy_types.go, test/envtest/crds_envtest_test.go, test/kongintegration/kongupstreampolicy_test.go
Adds kongintegration test that verifies the translated Upstreams are accepted by Kong instance and all of their fields are propagated as expected.
Also, adds CRD validation rules that were discovered during the development of the tests.
Closes #4929.
=> chore: add kongintegration test for KongUpstreamPolicy translation

CHANGELOG.md, internal/dataplane/parser/parser.go, internal/dataplane/parser/translate_routes_helpers.go, internal/dataplane/parser/translate_routes_helpers_test.go, internal/dataplane/parser/translate_tcproute.go, internal/dataplane/parser/translate_tcproute_test.go, internal/dataplane/parser/translate_tlsroute.go, internal/dataplane/parser/translate_udproute.go, internal/dataplane/parser/translate_udproute_test.go, test/integration/tcproute_test.go, test/integration/tlsroute_test.go
As described in https://github.com/Kong/kubernetes-ingress-controller/issues/4864 `TCPRoute` sets the incorrect destinations port on the Routes it creates (sets the desired backend service port instead of the listener port). The same happens for `UDPRoute`. It ignores the port set by specifying `SectionName`, it always requires the same port for the backend service as for the listener.
This PR fixes it for both cases. When `SectionName` is specified take config from it. Otherwise, it works now as described (a little bit vague) in spec 
> When unspecified (empty string), this will reference the entire resource. ([src](https://github.com/kubernetes-sigs/gateway-api/blob/ebe9f31ef27819c3b29f698a3e9b91d279453c59/apis/v1/shared_types.go#L107))
so every …
=> fix: set proper destination port for TCPRoute and UDPRoute

CHANGELOG.md
Moves a change listed under 3.0 breaking changes to added.
It looks like https://github.com/Kong/kubernetes-ingress-controller/pull/4808 misplaced this and we didn't notice because the subsection isn't obvious from the diff.
`--kong-admin-token-file` is a new feature, but `--kong-admin-token` is still available and functions the same.
=> chore: move misplaced change entry

FEATURE_PREVIEW_DOCUMENTATION.md
Update the feature preview doc by removing Gateway API
=> chore(docs): update feature preview docs by removing mention to alpha Gatway API

Makefile, docs/cli-arguments.md, internal/manager/config.go, internal/manager/controllerdef.go, test/envtest/crds_envtest_test.go, test/envtest/gateway_envtest_test.go, test/envtest/k8s_objects_status_envtest_test.go, test/envtest/kongstate_consumer_failures_test.go, test/envtest/manager_envtest_test.go, test/envtest/metrics_envtest_test.go, test/envtest/programmed_condition_envtest_test.go, test/envtest/run.go
This introduces 3 new CLI flags for enabling/disabling Gateway API controllers:
```
--enable-controller-gwapi-gateway                   Enable the Gateway API Gateway controller. (default true)
--enable-controller-gwapi-httproute                 Enable the Gateway API HTTPRoute controller. (default true)
--enable-controller-gwapi-reference-grant           Enable the Gateway API ReferenceGrant controller. (default true)
```
It's needed for https://github.com/Kong/kubernetes-ingress-controller/pull/4968 which will remove the `Gateway` feature flag (the only way of controlling whether the Gateway API controllers are enabled as of today).
Additionally it adjusts the `envtest` suite.
In #4968 the controller enablement conditions 
```
Enabled: …
```
=> chore: add CLI flags for enabling and disabling Gateway API controllers

.golangci.yaml
Extended `golangci-lint` timeout from 5m to 10m to prevent CI failures like: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6642225481/job/18046592773?pr=4975
```
Wed, 25 Oct 2023 15:01:09 GMT
/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/bin/golangci-lint run --verbose --config /home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/.golangci.yaml
Wed, 25 Oct 2023 15:01:09 GMT
level=info msg="[config_reader] Used config file .golangci.yaml"
Wed, 25 Oct 2023 15:01:09 GMT
level=info msg="[lintersdb] Active 36 linters: [asasalint asciicheck bodyclose contextcheck dogsled durationcheck errcheck errname errorlint exhaustive exportloopref forbidigo gci godot gofmt gofumpt goimports …
```
=> chore(ci): increase lint timeout to prevent CI failures

CHANGELOG.md, go.mod, go.sum, test/conformance/gateway_conformance_test.go, test/consts/zz_generated_gateway.go
bump gateway API to `1.0.0-rc2` and set skip of conformance tests in 1.0.0-rc2.
fixes #4916 
related conformance failures (skips):
- #4982 
- #4983 
- #4984 
=> chore: bump gateway APIs to 1.0.0-rc2

internal/konnect/nodes/client.go, internal/konnect/nodes/types.go
This change updates KIC's `Client.ListAllNodes()` method, which pulls down all nodes from Konnect within a control plane, to use cursor pagination instead of offset pagination.
For control planes with a large number of nodes, performance improvements may be observed by result of this change.
- No significant user-facing changes as a result of this change.
=> feat: listing nodes from Konnect using cursor pagination

.github/test_dependencies.yaml
According to https://endoflife.date/kubernetes and other sources 1.23 is already unsupported for several months now.
The latest version available in GKE is 1.24 so leaving this kind version in for now. (even though [we test on GKE 1.28.2](https://github.com/Kong/kubernetes-ingress-controller/blob/b6809f5ff9a6ee58fb52b6411dfb63ffb5eeca0a/.github/test_dependencies.yaml#L13-L15))
=> chore(ci): remove k8s 1.23 from testing matrix

CHANGELOG.md, FEATURE_GATES.md, internal/manager/controllerdef.go, internal/manager/featuregates/feature_gates.go, internal/manager/featuregates/feature_gates_test.go, internal/manager/telemetry/manager_test.go, test/envtest/run.go, test/envtest/telemetry_test.go
This PR:
- Removes the `Gateway` feature gate. It was enabled by default for a while now, 3.0 is a good opportunity to remove it.
- Updates the https://github.com/Kong/kubernetes-ingress-controller/blob/main/FEATURE_GATES.md
- Moves the graduated or removed features gates from https://github.com/Kong/kubernetes-ingress-controller/blob/main/FEATURE_GATES.md#feature-gates-for-alpha-or-beta-features to https://github.com/Kong/kubernetes-ingress-controller/blob/main/FEATURE_GATES.md#feature-gates-for-graduated-or-deprecated-features
We do not have CLI flags for enabling/disabling Gateway API controllers. We only did that with the feature flags up until now hence this PR flips the enable criteria on those controllers …
=> chore: update features gates for v3, remove Gateway feature gate

test/e2e/compatibilities_test.go, test/e2e/helpers_test.go
Noticed during debugging e2e test failures from  https://github.com/Kong/kubernetes-ingress-controller/pull/4934
~Make `TestKongRouterFlavorCompatibility` run tests for all 3 router flavors.~ This was already done as part of #4934. This PR here adds deployment of echo backends (which were not added in #4934) to allow test to pass.
~Previous scaffolding didn't allow to add `expressions` because when a rolling upgrade is performed KIC is not able to transition from 1 router flavor into another.~ This was already done as part of #4934
This also adds cleanup of resources deployed in each subtest so that they can each deploy their own without conflicts.
This will fix failures as in https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6654763 …
=> tests: fix `TestKongRouterFlavorCompatibility` e2e test and make it test all Kong Gateway flavors

docs/cli-arguments.md, internal/manager/config.go, scripts/cli-arguments-docs-gen/main.go
This PR makes more consistent CLI flags' descriptions, ensures that each starts with a capital letter and ends with a period, etc. not only in `cli-arguments.md`, but also in the help, by providing validation in `scripts/cli-arguments-docs-gen/main.go` to enforce consistency. 
In scope of this PR is to remove obsoleted/deprecated flags too, after examination nothing seems suitable for removing/deprecating (please double-check).
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4729
Deprecating flags, etc. is not in the scope of this PR.
=> chore: more consistent CLI flags' descriptions, improve generation of cli-arguments.md

config/components/konnect/manager.yaml, config/variants/konnect/base/manager.yaml, config/variants/konnect/debug/manager_debug.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml
Konnect seems not to support expression routes. We need to set router flavor to `traditional_compatible` to pass e2e tests for integration with Konnect.
fixes #4993 
=> fix: set router flavor to traditional_compatible in konnect related manifests

test/e2e/upgrade_test.go
This PR changes the target router flavor in `TestDeployAndUpgradeAllInOneDBLESS` to `traditional` to keep the upgrade use the same router flavor in deployed Kong Gateway as the base and target of the upgrade.
Related issue which aims to use `helm` in e2e tests: https://github.com/Kong/kubernetes-ingress-controller/issues/4973
=> tests: fix `TestDeployAndUpgradeAllInOneDBLESS` tests by using traditional router in upgrade tests

CHANGELOG.md, internal/dataplane/configfetcher/config_fetcher.go, internal/dataplane/configfetcher/kongrawstate.go, internal/dataplane/configfetcher/kongrawstate_test.go
When KIC receives a broken config from Gateway (e.g. like the one described in https://github.com/Kong/kubernetes-ingress-controller/issues/4990) with route's priority in scientific notation:
```
routes:
- request_buffering: true
expression: ((http.path == "/echo") || (http.path ^= "/echo/")) && (http.method == "GET")
preserve_host: true
name: default.echo.echo..1027
response_buffering: true
updated_at: 1698340425
https_redirect_status_code: 426
ws_id: 0dc6f45b-8f8d-40d2-a504-473544ee190b
id: 6ece5df4-2c97-5372-a840-47e222d4ea9d
created_at: 1698340425
tags:
- k8s-name:echo
- k8s-namespace:default
- k8s-kind:Ingress
- k8s-uid:6eb54997-0c70-4a68-918b-935a356f14cd
- k8s-group:networking.k8s.io
- k8s-version:v1
priority: 3.3820977671045e+15 # <- this …
```
=> fix: fix a panic when receiving a broken config from Gateway

CHANGELOG.md
Adds a single changelog entry for `KongUpstreamPolicy`.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3174.
=> chore: add changelog entry for KongUpstreamPolicy

Makefile, internal/manager/health_check_test.go, test/e2e/utils_test.go, test/envtest/ingress_test.go, test/envtest/manager_debugendpoints_test.go, test/envtest/run.go, test/helpers/ports.go, test/kongintegration/containers/httpbin.go, test/kongintegration/containers/kong.go, test/kongintegration/containers/ports.go, test/kongintegration/parser_golden_tests_outputs_test.go
Docker's bug described in https://github.com/moby/moby/issues/42442 causes `testcontainers-go` used in `kongintegration` tests to create containers with port mappings that may overlap if created at the same time by parallel test cases. This PR works this around by explicitly specifying host ports to be used.
Should fix https://github.com/Kong/kubernetes-ingress-controller/issues/4940.
=> tests: workaround docker bug affecting kongintegration flakiness

internal/manager/config.go
This sets KIC's user agent so that it can be easily identified in Kubernetes Audit logs:
```
{
"kind": "Event",
"apiVersion": "audit.k8s.io/v1",
"level": "Request",
"auditID": "0f4fafa0-6f44-4c3a-b937-717a9cc6b042",
"stage": "ResponseStarted",
"requestURI": "/api/v1/services?allowWatchBookmarks=true&resourceVersion=362177&timeoutSeconds=367&watch=true",
"verb": "watch",
"user": {
"username": "kubernetes-admin",
"groups": [
"system:masters",
"system:authenticated"
]
},
"sourceIPs": [
"172.18.0.1"
],
"userAgent": "kubernetes-ingress-controller/v2.12.0-189-g5a4d76638",
"objectRef": {
"resource": "services",
"apiVersion": "v1"
},
"responseStatus": {
"metadata": {},
"code": 200
},
"requestReceivedTimestamp": "2023-10-30T17:16:50.566806Z", …
```
=> feat: set KIC's UserAgent

CHANGELOG.md, internal/dataplane/parser/testdata/golden/grpcroute-example/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/expression-routes-on_golden.yaml, internal/dataplane/parser/translators/atc_utils.go, internal/dataplane/parser/translators/grpcroute_atc.go, internal/dataplane/parser/translators/grpcroute_atc_test.go, internal/dataplane/parser/translators/httproute_atc.go, internal/dataplane/parser/translators/httproute_atc_test.go, internal/dataplane/parser/translators/ingress_atc_test.go
Use only 46 bits in calculated `priority` of generated Kong routes when expression router is enabled. This prevent Kong gateway to decode it to scientific notation that will cause precision loss in dumping and comparing the configurations.
fixes #5009 and also #4990.
Review on changelog: should this change be notated as a `Breaking change`?
=> fix: use only 46 bits for priorities of Kong routes

CHANGELOG.md
Add a changelog entry for https://github.com/Kong/kubernetes-ingress-controller/pull/5019.
=> chore(docs): add CHANGELOG for adding UserAgent in 3.0

CHANGELOG.md, internal/clients/readiness.go, internal/dataplane/sendconfig/backoff_strategy.go
It turns out `s.logger.V(util.DebugLevel).Error(err, "...")` doesn't result in a log message with a debug, but an error level. The PR fixes logs that were intended to use debug-level with the error as a log field.
Customer reported 
```
{"error":"making HTTP request: Get \"https://172.17.1.180:8444/status\": context deadline exceeded","level":"error","logger":"setup.readiness-checker","msg":"already created client for \"https://172.17.1.180:8444/\" is not ready, moving to pending","time":"2023-10-31T09:52:17Z"}
```
kind of logs presence repeating quite often. Error logs should not be used for that kind of message as they're signaling expected situations that users should not be worried about.
**PR Readiness …
=> fix: use debug level for readiness checks logs

internal/clients/readiness.go
Backports #5029 to the release/2.12.x feature branch.
Changelog: https://github.com/Kong/kubernetes-ingress-controller/pull/5031
=> Backport #5029 to release/2.12.x

internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/manager/run.go
Seems that this is unused to remove it.
=> chore: remove unused KongClient's ingressClass field

.github/workflows/conformance_tests_report.yaml, .gitignore, Makefile, README.md, go.mod, go.sum, test/conformance/gateway_conformance_test.go, test/conformance/gateway_expermimental_conformance_test.go, test/conformance/suite_test.go, test/consts/zz_generated_gateway.go
Bump gateway-api to the release 1.0.0 and all related stuff
- gateway-api bump
- fix `Makefile` targets `test.conformance` and `test.conformance-experimental` (for now maintain both, because experimental doesn't become the default one with the release of GWAPI 1.0.0)
- reuse hack for passing test `GatewayClassObservedGenerationBump` for experimental-conformance
- adjust versions in README.md (for now link to the conformance report is broken until submitting it to GWAPI repo)
- reflect in `.gitignore` changing the generated report name (introduced in https://github.com/Kong/kubernetes-ingress-controller/pull/4726)
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4998
**Special notes for your …
=> chore: bump GWAPI to 1.0, fix target test.conformance-experimental

internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go, internal/admission/validation/ingress/ingress.go, internal/admission/validator.go
more about admission.
<s>
</s>
=> chore(logs): modifying the capitalization consistency of the logs - Part 2

CHANGELOG.md, Makefile
- remove the temporary `go-get-gatewayapi` in `Makefile`
- Add changelog entry for bumping gateway api to 1.0.0
=> chore: remove temp go-get-gatewayapi and update CHANGELOG

internal/adminapi/backoff_strategy_konnect.go, internal/adminapi/backoff_strategy_konnect_test.go, internal/admission/validation/consumers/credentials/validation_test.go, internal/clients/readiness.go, internal/controllers/configuration/kongadminapi_controller.go, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gatewayclass_controller.go, internal/dataplane/sendconfig/sendconfig.go, internal/manager/run.go, test/envtest/manager_envtest_test.go
=> chore(logs): modifying the capitalization consistency of the logs

CHANGELOG.md, docs/cli-arguments.md, internal/manager/config.go
Remove the HTTP port names from the default list of accepted Service ports for discovery. 
Discovery is [hard-coded to support HTTPS only](https://github.com/Kong/kubernetes-ingress-controller/blob/513db87cbf94ce66207f74365b502e8cde841357/internal/adminapi/endpoints.go#L186), and would unsuccessfully attempt to use HTTP ports when available. The client generator code [builds clients for all admissable port names](https://github.com/Kong/kubernetes-ingress-controller/blob/c102cea90961347259846b134c958a4f155b2af3/internal/adminapi/endpoints.go#L101-L151) and has no filters by protocol.
In DB mode this could prevent the controller from talking to Kong at all if it chose an HTTP port from the list, as it only selects a …
=> fix: remove HTTP ports from discovery config

internal/dataplane/kongstate/kongstate.go
It will make sure that a log entry is emitted for every Service that's annotated with deprecated `konghq.com/override`, but not when it's not.
Fixes #5056.
- ~[ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ No need for changelog entry as that wasn't released yet.
=> fix: log KongIngress deprecation errors only when needed

examples/kong-upstream-policy-httproute.yaml, examples/kong-upstream-policy-ingress.yaml
Fix `KongUpstreamPolicy` example manifests so that they pass CRD validation.
=> fix: fix `KongUpstreamPolicy` example manifests

config/variants/multi-gw-postgres/gateway_admin_service.yaml, config/variants/multi-gw/base/gateway_admin_service.yaml, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml
Ports in the test manifests used HTTP names although they were HTTPS. After 
https://github.com/Kong/kubernetes-ingress-controller/pull/5043 port names must reflect their protocol, as discovery will not attempt to connect to non-HTTPS ports and uses the port name to determine the protocol.
=> fix: use HTTPS port name for HTTPS port

examples/kong-consumer-key-auth.yaml, internal/admission/validation/consumers/credentials/validation.go, internal/admission/validator_test.go
After introducing credential type labels in https://github.com/Kong/kubernetes-ingress-controller/pull/4825, it seems that webhook wasn't checked for letting the Secrets with only said label (where it should).
This PR fixes it by fixing the webhook logic in `KongHTTPValidator.ValidateCredential`.
Fixes: https://github.com/Kong/kubernetes-ingress-controller/issues/5069
No CHANGELOG entry since the change regarding `keyCredType` wasn't released yet.
=> fix: fix webhook validation of `KongConsumer`s referring Secrets with `konghq.com/credential` label

CHANGELOG.md, internal/dataplane/kong_client.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/route.go, internal/dataplane/parser/backendref.go, internal/dataplane/parser/ingressrules.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/dataplane/parser/translate_grpcroute.go, internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_tlsroute.go, internal/dataplane/parser/translate_udproute.go, internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/sendconfig/kong.go, internal/dataplane/sendconfig/sendconfig.go, internal/dataplane/synchronizer.go, internal/diagnostics/server.go, internal/license/agent.go, internal/manager/health_check.go
fixes: #3708 
This PR more about `internal/dataplane`
=> chore(logs): The log format starts with a capital letter in internal/dataplane

test/envtest/run.go
To prevent these errors:
```
failed waiting for all runnables to end within grace period of 30s: context deadline exceeded
```
Set `GracefulShutdownTimeout` to 0 to prevent `controller-runtime` from returning an errors from controller manager `.Run()`.
https://github.com/kubernetes-sigs/controller-runtime/blob/e59161ee8f41b2f24953419533dca84d30262c21/pkg/manager/internal.go#L543-L548
=> tests: set GracefulShutdownTimeout to 0 to prevent context cancellation errors

.github/workflows/_envtest_tests.yaml, Makefile, test/envtest/controller.go, test/envtest/crds_envtest_test.go, test/envtest/log.go, test/envtest/run.go
This PR unifies the log dumping mechanism used in `envtest` suite when run using `StartReconcilers` and `RunManager` in a way that log entries are properly encoded using the `text` encoder.
It also changes the Makefile target used on CI so that only the failed tests outputs are printed for easier debugging.
On top of that it doesn't use the `ctrl.SetLogger()` to allow running tests more than once (`-count N` with `N` > 1). Specifically this allows tests like `TestGatewayAPIControllersMayBeDynamicallyStarted` check controller logs when run more than once.
Logs (when test fails) before this change (for tests using `StartReconcilers()`)
```
=== CONT  TestHTTPRouteReconcilerProperlyReactsToReferenceGrant
httproute_controller_test.go:39: starting envtest …
```
=> tests: fix logs encoding in envtest suite

CHANGELOG.md, internal/admission/handler.go, internal/admission/server_test.go, internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go, internal/admission/validator.go, internal/admission/validator_test.go, test/integration/httproute_webhook_test.go, test/integration/webhook_test.go
Uses the same failure policy (`Ignore`) in the test admission webhook configuration as the one used in [charts](https://github.com/Kong/charts/blob/179f76c1757747396b023c1b0b6ad32946a34257/charts/kong/values.yaml#L565) and [deploy-admission-controller.sh](https://github.com/Kong/kubernetes-ingress-controller/blob/2fccacbaeae94467fa381c8b952c0c2f016c97dc/hack/deploy-admission-controller.sh#L45) script. 
The policy tells Kubernetes what to do in case status 500 is returned from the webhook:
- `Ignore` - accept the object. 
- `Fail` - do not accept the object.
Given that we're using `Ignore` in production, we should use the same in tests. Without that, we may have test cases where we expect an object to be rejected, but we returned status 500, which in …
=> fix(admission): use `Ignore` failure policy in tests (same as charts)

.github/workflows/check_fixed_issues_references.yaml
Limit the scope of the GITHUB_TOKEN used in issue status check to `issues`  read-only.
Ref: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
Example workflow run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6746666425
=> ci: use restricted GITHUB_TOKEN istead of GITHUB PAT for issue state check

CHANGELOG.md
Removes the `-rc1` tags and updates the date for 3.0.
=> chore: finalize 3.0

.github/workflows/backport.yaml
Uses non-default GH PAT to create backport PRs which should allow triggering CI checks (that didn't happen with the default one: https://github.com/Kong/kubernetes-ingress-controller/pull/5078).
=> fix(ci): use k8s-team-bot GH PAT in backport workflow

hack/deploy-admission-controller.sh
as title, we should enable `v1` for Gateway API 
ref: https://github.com/Kong/kubernetes-ingress-controller/issues/5090
<s>
</s>
Since this change does not affect to user/devs, I will not update the CHANGELOG.md file.
=> chore(admission): enable admission for GatewayAPI v1

scripts/apidocs-gen/post-process-for-konghq.sh, scripts/cli-arguments-docs-gen/post-process-for-konghq.sh
Aligns the autogenerated references for CLI arguments and CRDs API with what konghq.com docs use now:
- use `include` directive instead of `include_cached`
- align wording
=> docs: align auto-generated references with konghq.com

go.mod, test/internal/testenv/testenv.go
Attempt to read the Helm chart test version from the Renovate file if none is specified via the environment. Proceed with no version (effectively using whatever's installed on the machine running the test) if both fail.
Alternative to https://github.com/Kong/kubernetes-ingress-controller/pull/4867 that tries for greater consistency.
This forces tests on older release branches to whatever chart version they had unless you override it to another version. This may not be desirable.
The path is relative to the `test/integration` directory and won't work if tests are invoked on another directory. However, `test/integration` currently has a flat file structure, and the failure is …
=> chore: pull Helm test version from Renovate

CHANGELOG.md
Reorganises the 3.0.0 changelog entry in a way that we discussed during the last team sync: 
- adds a highlights section,
- groups bullet points related to each other.
Also, adds missing links for 2.12.1 release.
=> chore(docs): reorganise 3.0.0 changelog entry

.golangci.yaml, internal/clients/manager.go, internal/dataplane/client.go, internal/dataplane/config/dbmode.go, internal/dataplane/config/router.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/dataplane/synchronizer.go, internal/dataplane/synchronizer_test.go, internal/manager/run.go, internal/manager/setup.go, internal/manager/utils/kongconfig/root.go, internal/manager/utils/kongconfig/root_test.go, test/integration/version_test.go, test/internal/helpers/kong.go
Review suggestion to #5092.
- Moved DBMode and RouterFlavor enums from internal/util/dataplane to internal/dataplane/config.
- Added a linter rule for internal/dataplane/config alias to be enforced to dpconf
- Changed DBMode's helper functions to methods
=> review suggestion: move types to `internal/dataplane/config`

scripts/check-container-environment.sh
There are some incompatibilities between different versions of kind and the old version can't work with Kubernetes v1.28.
We have not encountered any issues because the GitHub Actions environment has already upgraded kind to the latest version by default.
https://github.com/actions/runner-images/pull/7747
<s>
</s>
Since this change does not affect to  user/devs, I will not update the CHANGELOG.md file.
=> chore(test): bump kind version to v0.20.0

.github/workflows/regenerate_on_deps_bump.yaml
The location of all-in-one manifests used for tests changed in https://github.com/Kong/kubernetes-ingress-controller/pull/4970, hence the path for committing regenerated ones in `.github/workflows/regenerate_on_deps_bump.yaml` needs adjustment.
=> fix(ci): change path for regeneration of manifests for e2e tests

.golangci.yaml, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gateway_utils_test.go, internal/gatewayapi/aliases.go, internal/gatewayapi/consts.go
This adds KIC v3 module and Gateway API v1 into golangci-lint config to enforce the same rules as previously but on mentioned modules
=> build: update golangci-lint config with Gateway API v1 and KIC v1 modules

CHANGELOG.md
Remove non user facing changelog entry as discussed in https://github.com/Kong/kubernetes-ingress-controller/pull/5089/files/a17fb1ae74bf3601e38ea18215177f637701ff98#r1383038333
=> chore: remove a non user facing CHANGELOG entry

.github/workflows/regenerate_on_deps_bump.yaml
Uses k8s team bot's PAT instead of a default one to make sure the commit will trigger CI checks.
Fixes problems with https://github.com/Kong/kubernetes-ingress-controller/pull/5113 alike that hasn't its checks run after the GH actions' `chore: regenerate manifests`.
=> chore: use k8s team GH PAT in regenerate on deps bump

internal/dataplane/parser/testdata/golden/grpcroute-example/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/httproute-example/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-empty-path/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-multiple-ports-for-one-service/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-ports-defined-by-name/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefix-exact-rule/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-regex-prefixed-path/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-rule-with-tls/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-single-service-in-multiple-ingresses/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-acme-like-path/expression-routes-on_golden.yaml, internal/dataplane/parser/testdata/golden/ingress-v1-with-default-backend/expression-routes-on_golden.yaml, internal/dataplane/parser/translators/atc_utils.go, internal/dataplane/parser/translators/grpcroute_atc.go, internal/dataplane/parser/translators/grpcroute_atc_test.go, internal/dataplane/parser/translators/httproute_atc.go, internal/dataplane/parser/translators/httproute_atc_test.go, internal/dataplane/parser/translators/ingress_atc_test.go
(cherry picked from commit b2475f344850bf9b6722d0cac508a8a2866b8fee)
=> [backport] fix: use only 46 bits for priorities of Kong routes (#5024)

CHANGELOG.md
Updates 2.12.1 changelog to include all backported fixes + release date.
=> chore: update 2.12.1 changelog

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, internal/admission/errors.go, internal/admission/validator.go, internal/admission/validator_test.go, pkg/apis/configuration/v1/kongclusterplugin_types.go, pkg/apis/configuration/v1/kongplugin_types.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml, test/envtest/crds_envtest_test.go
This PR adds CRD validation expression to `KongPlugin` and `KongClusterPlugin` to enforce only one of `config` and `configFrom` fields to be set using the CRD validation expressions.
Related to #5062 (just a small part of it).
=> feat: add CRD validation expression for `KongPlugin` and `KongClusterPlugin` `config` and `configFrom` fields

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, examples/kong-consumer-key-auth.yaml, internal/admission/errors.go, internal/admission/validator.go, internal/dataplane/kongstate/kongstate.go, pkg/apis/configuration/v1/kongconsumer_types.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml, test/envtest/kongstate_consumer_failures_test.go, test/envtest/programmed_condition_envtest_test.go
According to https://docs.konghq.com/gateway/latest/admin-api/#consumer-object either of `username` or `custom_id` has to be set (both are also allowed) so update the CRD validation rules to enforce those rules.
Part of #5062
=> feat(crd): enforce setting `KongConsume`r's either of `username` of `custom_id` via CRD validation rules

internal/adminapi/endpoints.go, internal/adminapi/endpoints_test.go
Include IPv6 address bound markers in discovery so as not to incorrectly include the port as part of the address.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/5138 for the IP strategy.
IDK what's needed to fix the hostname strategies. https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records-1 is not very helpful for IPv6 address records despite the mention of AAAA records. They presumably do not use `[` and `]` because hostnames.
Integration tests lack the ability to test discovery behavior at present, and we don't do an IPv6 test run to boot, so only a unit. Building an image and running it through the configuration that [found …
=> fix: bound IPv6 addresses for discovery

.github/workflows/_e2e_tests.yaml, .github/workflows/validate_kong_image.yaml
- Support specifying effective semantic version of tested Kong gateway image to avoid "failed to parse semver" error.
part of #5045 
expected to fix partial integration tests. For e2e tests, I used `3.0.0-rc1` KIC image and most cases passed: 
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6741008630
=> Fix: add `kong-effective-version` input in validate Kong image tests and skip enterprise cases if enterprise not enabled

internal/controllers/gateway/grpcroute_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/dataplane/translator/subtranslator/grpcroute_atc.go, test/integration/examples_test.go, test/integration/grpcroute_test.go, test/internal/helpers/http.go
Small improvements:
- add space after `,` for debug-level log messages about requeueing
- fix typo in function name `generateMathcherFromGRPCMatch` -> `generateMatcherFromGRPCMatch`
- reuse `helpers.EventuallyGETPath(...)` in `TestHTTPRouteExample`
- improve docs for `helpers.EventuallyGETPath(...)`, comments next to arguments are not displayed by VSCode. Golang doesn't have a convention for documenting arguments, so I just described them.
Opportunistic improvements spotted during the work on 
- https://github.com/Kong/kubernetes-ingress-controller/issues/4273
extracted to this PR for clarity.
=> chore: fix typos in log entry and function identifier, reuse helper in test

internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/translator/translate_grpcroute.go
In `ingressRulesFromGRPCRoute(...)` branch for expression router is redundant, because it's already checked in line `26`. Iterating over `nil` or 0 elements length slice is safe, not precheck is required. 
Opportunistic improvements spotted during the work on 
- https://github.com/Kong/kubernetes-ingress-controller/issues/4273
extracted to this PR for clarity.
=> chore: remove redundant if statements

config/base/kustomization.yaml, config/certmanager/kustomization.yaml, config/crd/kustomization.yaml, config/variants/enterprise-postgres/kustomization.yaml, config/variants/enterprise/kustomization.yaml, config/variants/multi-gw-postgres/base/kustomization.yaml, config/variants/multi-gw-postgres/oss/kustomization.yaml, config/variants/multi-gw/oss/kustomization.yaml, config/variants/postgres/kustomization.yaml
When I run `make manifest`, I receive the following warnings:
```
```
The content is generated automatically via `kustomize edit fix`
<s>
</s>
=> chore(kustomize): resolve Warning: 'patchesJson6902' is deprecated.

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongconsumergroups.yaml, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, pkg/apis/configuration/v1/configsource.go, pkg/apis/configuration/v1/kongclusterplugin_types.go, pkg/apis/configuration/v1/kongconsumer_types.go, pkg/apis/configuration/v1/kongingress_types.go, pkg/apis/configuration/v1/kongplugin_types.go, pkg/apis/configuration/v1beta1/ingress_rules.go, pkg/apis/configuration/v1beta1/kongconsumergroup_types.go, pkg/apis/configuration/v1beta1/tcpingress_types.go, pkg/apis/configuration/v1beta1/udpingress_types.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml
remove the incorrect usage of annotations `// +kubebuilder:validation:Optional` on type defintions and reserve one `// +kubebuilder:validation:Optional` in packages `v1` and `v1beta1` (in file `docs.go`).
fixes #5061 
The `// +kubebuilder:validation:Optional`  comments above types are first imported in this PR: https://github.com/Kong/kubernetes-ingress-controller/pull/1757/. I do not know the purpose here, but kept the generated CRDs identical to previous versions. @rainest Do you have more context of that PR? 
=> fix: make `secretKeyRef` a required field in plugins' `configFrom`

internal/admission/validator.go
Don't check `Gateway`'s `gatewayClassName` because that's already enforced at the Gateway API field level: `Gateway`'s `GatewayClassName` field is of type `ObjectName` which cannot be empty:
https://github.com/kubernetes-sigs/gateway-api/blob/faba2585346ef0806585f8ce2ee458e9cd70ec7b/apis/v1/shared_types.go#L578-L584
=> chore(admission): don't check Gateway's gatewayClassName in admission webhook

.github/ISSUE_TEMPLATE/release.yaml, .github/workflows/release_docs.yaml
The 3.0 doc reorg dropped the `s` from `references`:
https://github.com/Kong/docs.konghq.com/blob/main/app/_src/kubernetes-ingress-controller/reference/cli-arguments.md
https://github.com/Kong/docs.konghq.com/blob/main/app/_src/kubernetes-ingress-controller/reference/custom-resources-3.0.x.md
Unclear how the update was run for the initial 3.0 rollout, but those do appear up to date (`--konnect-control-plane-id` and `KongUpstreamPolicy` are indeed present), and AFAIK we do not need to run this workflow after.
=> chore: use current generated doc path

CHANGELOG.md, internal/dataplane/translator/subtranslator/ingress.go, internal/dataplane/translator/subtranslator/ingress_test.go, internal/dataplane/translator/translate_ingress_test.go, test/integration/ingress_test.go
Fixes misbehavior when multiple Ingresses point to the Same service, some of them have `konghq.com/rewrite` and some do not (or a different path specified in it):
- commit 1cfe0285be86be497f69975cf45416ce37fa84f8 improves integration test `TestIngressRewriteURI` to catch situation reported in https://github.com/Kong/kubernetes-ingress-controller/issues/5021
- commit 857cdbb4507ac86311ac3bb05f1ceeb95b7a3070 contains fix - `request-transformer` is attached to the Kong route instead of Kong service
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5021
One case that is not covered by a test is `Ingress` which uses only the default backend and annotation …
=> fix: annotation konghq.com/rewrite for multiple Ingresses routing to the same Service

test/integration/version_test.go
Skip the test cases requiring enterprise features when `TEST_KONG_ENTERPRISE ` is not set to `true`. This prevents the enterprise test cases to run if enterprise version of Kong image used, but  `TEST_KONG_ENTERPRISE ` is not set thus fails on the tests, because license is not initialized in such case.
fixes #5045 
~- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ CHANGELOG not required
=> test: skip enterprise tests when image is enterprise but TEST_KONG_ENTERPRISE not enabled

internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gatewayclass_controller.go, internal/gatewayapi/consts.go
Fix an outdated reference to v1beta1 version after the migration to v1.
=> chore: fix GatewayClass controller and logger names after v1 GW API migration

Makefile
PR https://github.com/Kong/kubernetes-ingress-controller/pull/5095 renamed `parser` to `translator`, it was overlooked in `Makefile` target `test.golden.update`. This PR fixes it.
=> fix(Makefile): target test.golden.update works

CHANGELOG.md, internal/dataplane/translator/translate_ingress.go, test/integration/ingress_test.go
It covers Ingress's default backend with integration test and fixes behavior when the same Service is used in a routing rule and as the default backend. Although rather such config doesn't have much practical application, when someone configures something like that it should work as expected.  
Spotted during work on https://github.com/Kong/kubernetes-ingress-controller/pull/5171
For a default backend `konghq.com/rewrite` annotation does not have meaning, because it works on the level of capture groups specified in the URL path used in an ingress rule. [See the docs](https://docs.konghq.com/kubernetes-ingress-controller/latest/reference/annotations/#konghqcomrewrite).
**PR Readiness …
=> fix: Ingress with default backend targeting the same Service

.github/workflows/_integration_tests.yaml
Comment https://github.com/Kong/kubernetes-ingress-controller/pull/4934#issuecomment-1777350228 from the issue that update router default says that for DB mode `traditional_compatible` router should be used. This PR fixes overlooked integration tests, from a run e.g. 
- [postgres-gateway-alpha](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6890333836/job/18743265341#step:6:6)
- [postgres-rewrite-uris](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6890333836/job/18743265719#step:6:6)
that used to use `expressions` router.
There is a hope that it may resolve the flake mentioned in https://github.com/Kong/kubernetes-ingress-controller/pull/5171#issuecomment-1814372198
=> chore(tests): for DB backed use traditional_compatible router

.github/ISSUE_TEMPLATE/release.yaml
Add a bullet point in KIC release issue template to ensure that KGO works with KIC version that's being released.
=> chore: add mention of KGO in issue template

.github/workflows/_e2e_tests.yaml, .github/workflows/validate_kong_image.yaml, test/integration/version_test.go
backport fixes on validate Kong image test: #5074 and #5165 to fix the validate Kong image tests on 2.12 LTS.
part of #5211 
=> Backport/fix validate kong image 2.12

internal/dataplane/parser/translate_ingress_test.go, internal/dataplane/parser/translators/ingress.go, internal/dataplane/parser/translators/ingress_test.go, test/integration/ingress_test.go, test/internal/helpers/http.go
Backport of #5171. The `main` branch contains changes to `test/internal/helpers/http.go`, in this PR simple remediation is provided to be able to cherry-pick `TestIngressRewriteURI` without touching out-of-scope code.
It's part of
- https://github.com/Kong/kubernetes-ingress-controller/issues/5198
CHANGELOG.md on `main` will be updated accordingly during the above release.
=> [backport release/2.12.x] fix: annotation konghq.com/rewrite for multiple Ingresses routing to the same Service (#5171)

internal/dataplane/parser/translate_ingress.go, test/integration/ingress_test.go
Backport of #5188. The `main` branch contains rename `parser` -> `translator` thus file with a different path is touched in this PR.
It's part of
- https://github.com/Kong/kubernetes-ingress-controller/issues/5198
CHANGELOG.md on `main` will be updated accordingly during the above release.
=> [backport release/2.12.x] fix: Ingress with default backend targeting the same Service (#5188)

internal/dataplane/parser/translate_ingress_test.go, internal/dataplane/parser/translators/ingress.go, internal/dataplane/parser/translators/ingress_test.go, test/integration/ingress_test.go
Backport of #5171.
It's part of
- https://github.com/Kong/kubernetes-ingress-controller/issues/5196
CHANGELOG.md on `main` will be updated accordingly during the above release.
=> [backport release/3.0.x] fix: annotation konghq.com/rewrite for multiple Ingresses routing to the same Service (#5171)

internal/dataplane/parser/translate_ingress.go, test/integration/ingress_test.go
Backport of #5188. The `main` branch contains rename `parser` -> `translator` thus file with a different path is touched in this PR.
It's part of
- https://github.com/Kong/kubernetes-ingress-controller/issues/5196
CHANGELOG.md on `main` will be updated accordingly during the above release.
=> [backport release/3.0.x] fix: Ingress with default backend targeting the same Service (#5188)

internal/dataplane/parser/translate_ingress.go, internal/dataplane/parser/translate_ingress_test.go, internal/dataplane/parser/translate_knative.go
Since KIC 2.12 is an LTS release provide a fix for the bug described in https://github.com/Kong/kubernetes-ingress-controller/issues/3942. It only occurs when `CombinedRoutes` feature gate is not set to `true`. For KIC >=3.0 bug does not exist, because `CombinedRoutes` is enabled by default and it can't be changed.
Users may rely on a naming scheme of Kong routes, hence only provide descriptive message with remediation instead of changing it with this fix.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/3942
It's part of 
- https://github.com/Kong/kubernetes-ingress-controller/issues/5198
`CHANGELOG.md` on `main` will be updated accordingly during the above …
=> [release/2.12] fix: provide descriptive error for known bug with conflicting Kong Routes naming

CHANGELOG.md, internal/admission/validator.go, internal/admission/validator_test.go, internal/dataplane/kongstate/plugin.go
- Fix the validation of `KongClusterPlugin` to generate configuration using `configPatches`
- Do not share code of `ValidateKongPlugin` in `ValidateKongClusterPlugin`
fixes the problem of validator for `KongClusterPlugin` in #5158.
REVIEW: how do we write changelog here? This is a fix on a not yet released feature.
=> fix: validate configPatches for KongClusterPlugin

.github/workflows/benchmarks.yaml, .github/workflows/checks.yaml
This reverts commit 3d5935e96438f2e75555cb746e62e0c18e598144.
Job `passed` is set as required in [configuration of branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule) for the `main`. Hence when a file that matches pattern for skipping is edited in the PR it will get stuck forever as here
The above is a real-world case hit in PR https://github.com/Kong/kubernetes-ingress-controller/pull/5207. 
Revert it to get it run again, and reopen a related issue.
Reopens https://github.com/Kong/kubernetes-ingress-controller/issues/5221
=> Revert "chore(test): skip test when only docs be changed (#5207)"

CHANGELOG.md
Update `CHANGELOG` on the `main` branch to properly describe patch releases:
- https://github.com/Kong/kubernetes-ingress-controller/issues/5198
- https://github.com/Kong/kubernetes-ingress-controller/issues/5196
The target date for both of them is set to **2023-11-22**
> ❗ **Merge just in time when releases will be performed.**
=> chore: update CHANGELOG for patch releases 2.12.2 and 3.0.1

CHANGELOG.md
It removes from the section **Unreleased** two entries that have been already released and mentioned in [3.0.1](https://github.com/Kong/kubernetes-ingress-controller/blob/main/CHANGELOG.md#301)
=> chore: remove redundant entries from CHANGELOG

.github/workflows/_e2e_tests.yaml
Enable changing KIC image for e2e tests run on GKE. This is required for running validation test against Kong 2.8.x, because we need to use KIC 2.12.x in the tests.
fixes #5228 
=> test: check existence of input KIC image and use it if exists in gke tests

scripts/apidocs-gen/post-process-for-konghq.sh
Fixes the script to generate reference page of custom resources in the docs repo. 
create docs PR job run on the branch: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6977712012
=> Chore: Fix script to generate reference page of custom resources in docs

.github/workflows/_e2e_tests.yaml
backport #5230  to 2.12.x to enable changing images in e2e tests on GKE.
part of #5211.
=> enable setting KIC image for e2e on GKE clusters (#5230)

internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go, test/integration/tcproute_test.go
Added relevant tests to clarify the specific behavior of KIC in this scenario.
closes https://github.com/Kong/kubernetes-ingress-controller/issues/4958
Replace  https://github.com/Kong/kubernetes-ingress-controller/pull/5147 with this.
In fact, we have already implemented the relevant logic. If there is a scenario where sectionName and port do not match, it will not be processed by the translator.
=> chore(test): test SectionName and port do not match.

FEATURE_GATES.md, config/rbac/role.yaml, docs/cli-arguments.md, hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/manager/config.go, internal/manager/controllerdef.go, internal/manager/featuregates/feature_gates.go, internal/store/cache_stores.go, internal/store/cache_stores_test.go, internal/store/fake_store.go, internal/store/fake_store_test.go, internal/store/store.go, pkg/apis/incubator/doc.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml, test/envtest/telemetry_test.go
Adds `KongServiceFacade` controller along with the CLI flag and feature gate enabling it. Also extends stores to handle the new CRD appropriately.
Part of #5152.
=> feat: add KongServiceFacade controller and feature gate

.github/workflows/_conformance_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/e2e_nightly.yaml, .github/workflows/pr_checks.yaml, .github/workflows/validate_kong_image.yaml
Backport 2 PRs to dump and upload KIC's log produced during the integration tests to 2.12.x:
#5192 
#5236 
=> Backport kic log dump to release/2.12.x

test/e2e/all_in_one_test.go, test/e2e/helpers_test.go, test/e2e/kustomizations_test.go, test/e2e/upgrade_test.go, test/e2e/utils_test.go
Since we still need to test 2.12 against Kong 2.8.x, we need to update the proxy deployments if Kong gateway version < 3.0.0.
fixes #5212.
=> disable HTTP/2 of admin api in e2e if Kong < 3.0.0

test/integration/consts/consts.go, test/integration/consts_test.go, test/integration/ingress_test.go, test/integration/isolated/ctx.go, test/integration/isolated/ingress_test.go, test/integration/isolated/suite_test.go, test/internal/testlabels/labels.go
Kong allows to expose gRPC services over Ingress as [described in the docs](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/services/grpc/) (they will be updated accordingly as described in https://github.com/Kong/kubernetes-ingress-controller/issues/5134). It's a limited support, specific to Kong solution, it's not a part of any standard.
This PR migrates the integration test that verifies it to an isolated one. It increases coverage, to not only verify proper status setting but also proper traffic routing. Furthermore, it tests support for gRPC over HTTP (without TLS), which requires adjustment of Kong Gateway's setting (the rationale is described in https://github.com/Kong/kubernetes-ingress-controller/pull/5128). It works …
=> chore(tests): gRPC with Ingress over HTTP and HTTPS

internal/dataplane/translator/subtranslator/ingress.go, internal/dataplane/translator/subtranslator/ingress_atc_test.go, internal/dataplane/translator/subtranslator/ingress_test.go
Instead of repeating `kong.Int(int(defaultServiceTimeout.Milliseconds()))` everywhere, let's use a common helper that returns the timeout in the format expected by Kong.
Follow up to https://github.com/Kong/kubernetes-ingress-controller/pull/5234.
=> chore: add defaultServiceTimeoutInKongFormat helper

CHANGELOG.md, internal/dataplane/translator/subtranslator/grpcroute.go, internal/dataplane/translator/subtranslator/grpcroute_test.go
Adds source entity tags to GRPCRoute in the traditional translator.
We forgot to put source entity tags on GRPCRoute and were unable to attach admin API errors to them.
=> fix: set tags on GRPCRoute routes

CHANGELOG.md, examples/gateway-grpcroute-via-http.yaml, examples/gateway-grpcroute-via-https.yaml, internal/dataplane/translator/translate_grpcroute.go, test/integration/isolated/examples_grpc_test.go, test/integration/isolated/grpc_test.go, test/integration/isolated/ingress_test.go
Heuristic introduced in https://github.com/Kong/kubernetes-ingress-controller/pull/5128 for guessing whether for Kong Service `grpc` or `grpcs` protocol should be set breaks default behavior, that service without annotation for `GRPCRoute` is treated as `grpcs`.
Now documentation always mentions annotations for both `grpc` and `grpcs` see
- https://github.com/Kong/docs.konghq.com/pull/6567
but before when only gRPC over HTTPS was supported annotations weren't mentioned. Thus users probably haven't configured it and we have to avoid breaking their setups. This PR ensures that such a configuration will work.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/4273
- …
=> fix: restore defaulting to protocol "grpcs" for gRPC Service

internal/dataplane/translator/ingressrules.go, internal/dataplane/translator/subtranslator/ingress.go, internal/dataplane/translator/subtranslator/ingress_atc_test.go, internal/dataplane/translator/subtranslator/ingress_test.go, internal/dataplane/translator/testdata/golden/kong-service-facade/expression-routes-on_golden.yaml, internal/dataplane/translator/testdata/golden/kong-service-facade/feature-flag-on_golden.yaml
It fixes flaky `TestTranslateIngress_KongServiceFacade_used_in_multiple_Ingresses` by deterministically populating Kong Service `Parent` with `KongServiceFacade`'s originated ones (instead of Ingress) and sorting Service's routes in the test.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/5248.
=> fix: tag Services backed by KongServiceFacade correctly

internal/manager/config.go
Backport https://github.com/Kong/kubernetes-ingress-controller/pull/5270 to `release/3.0.x`
=> [backport release/3.0.x] fix: restore diagnostics server port (#5270)

CHANGELOG.md, internal/dataplane/translator/ingressrules.go, internal/dataplane/translator/ingressrules_test.go, internal/dataplane/translator/subtranslator/ingress.go, internal/dataplane/translator/testdata/golden/kong-service-facade/expression-routes-on_golden.yaml, internal/dataplane/translator/testdata/golden/kong-service-facade/feature-flag-on_golden.yaml, internal/dataplane/translator/testdata/golden/kong-service-facade/in.yaml, internal/dataplane/translator/translate_ingress.go, internal/dataplane/translator/translate_ingress_test.go, internal/dataplane/translator/translator_test.go, internal/util/builder/ingress.go, test/integration/isolated/ingress_test.go, test/integration/isolated/suite_test.go, test/internal/helpers/http.go
Adds support for `KongServiceFacade` as a default Ingress backend along with tests.
Part of #5152.
=> feat: add support of KongServiceFacade as default Ingress backend

CHANGELOG.md, internal/dataplane/translator/ingressrules.go, internal/dataplane/translator/ingressrules_test.go, internal/dataplane/translator/subtranslator/ingress.go, internal/dataplane/translator/subtranslator/ingress_atc_test.go, internal/dataplane/translator/subtranslator/ingress_test.go, internal/dataplane/translator/translator.go, test/envtest/programmed_condition_envtest_test.go, test/envtest/run.go, test/envtest/scheme.go, test/envtest/setup.go
Propagates `KongServiceFacade` to the `translatedObjectsCollector` in the `Translator` so that its `Programmed` condition is properly set.
Part of #5152.
=> feat: set KongServiceFacade's Programmed condition

.github/workflows/_e2e_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/test_nightly.yaml
This change is required to accommodate the forthcoming work in https://github.com/Kong/kong-license/pull/25
That work will change kong-license such that the license is sourced directly from 1Password, rather than it being sourced from Pulp using credentials from 1Password (as is the case today). Meaning that workflows needing to run Kong/kong-license's will require 1P credentials instead of the Pulp password.
This work is a necessary step in the deprecation of Pulp aka [KAG-2247](https://konghq.atlassian.net/browse/KAG-2247) / [KAG-3254](https://konghq.atlassian.net/browse/KAG-3254).
Leaving the Pulp password for now so that https://github.com/Kong/kong-license/pull/25 can be merged *after* this PR.
N/A
**Special notes …
=> chore(gha): preemptively add 1p creds

.github/test_dependencies.yaml
The version of 1.28.2-gke.1157000 no longer available in the Rapid channel ref: https://cloud.google.com/kubernetes-engine/docs/release-notes#December_04_2023
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7110214081/job/19356382978#step:7:520
```
=== Failed
=== FAIL: test/e2e TestDeployAllInOnePostgresWithMultipleReplicas (0.42s)
all_in_one_test.go:95: configuring all-in-one-postgres.yaml manifest test
all_in_one_test.go:97: building test cluster and environment
all_in_one_test.go:97: no existing cluster provided, creating a new one for "gke" type
all_in_one_test.go:97: creating a GKE cluster builder
all_in_one_test.go:97: creating GKE cluster, name: e2e-0b0abeb0-7672-44b0-8440-4303a9abd348
all_in_one_test.go:97: creating GKE …
```
=> fix(test): upgrade GKE version to v1.28.3

CHANGELOG.md, docs/cli-arguments.md, internal/manager/config.go, internal/manager/run.go
Changes the new `--emit-translation-events` flag name to `--emit-kubernetes-events` as it decides not only about the translation events but all the events we generate (including configuration application success and failure). 
Part of #5252.
=> fix: change events emit toggle name to --emit-kubernetes-events

CHANGELOG.md, config/crd/incubator/incubator.ingress-controller.konghq.com_kongservicefacades.yaml, config/crd/incubator/kustomization.yaml, config/rbac/role.yaml, hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/dataplane/translator/testdata/golden/kong-service-facade/expression-routes-on_golden.yaml, internal/dataplane/translator/testdata/golden/kong-service-facade/feature-flag-on_golden.yaml, internal/dataplane/translator/testdata/golden/kong-service-facade/in.yaml, internal/dataplane/translator/translator_test.go, pkg/apis/incubator/doc.go, pkg/apis/incubator/v1alpha1/doc.go, pkg/apis/incubator/v1alpha1/groupversion_info.go, pkg/clientset/typed/incubator/v1alpha1/incubator_client.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml
After a discussion regarding package naming, we've decided to use a better-namespaced pattern for new packages. In `configuration.konghq.com` we lacked a part that would namespace our packages specifically to KIC which is not perfect as that would be better to keep our APIs in Kong to be consistently namespaced. In KGO we've used `*.gateway-operator.konghq.com` pattern so using `incubator.ingress-controller.konghq.com` in KIC is consistent with that and the pattern we'd like to follow in the future is `<component-local-package-name>.<component-name>.konghq.com`.
Part of #5152.
=> feat: rename incubator package to incubator.ingress-controller.konghq.com

CHANGELOG.md, internal/dataplane/translator/subtranslator/grpcroute.go, internal/dataplane/translator/subtranslator/grpcroute_test.go, internal/dataplane/translator/translate_grpcroute.go, internal/dataplane/translator/translate_grpcroute_test.go
For `GRPCRoute` in GWAPI specs you can read 
- > If no matches are specified, the default is to match every gRPC request.
[src](https://gateway-api.sigs.k8s.io/api-types/grpcroute/#matches)
- > If no hostname is specified, traffic is routed based on GRPCRoute rules and filters (optional).
[src](https://gateway-api.sigs.k8s.io/api-types/grpcroute/#matches)
The above and the fact that both fields are optional in CRD leads to the conclusion that configuration without those fields shouldn't be rejected.
In Kong documentation, you can read that for Kong Route, the required fields are
> For `grpc`, at least one of `hosts`, `headers` or `paths`;
[src](https://docs.konghq.com/gateway/latest/admin-api/#route-object)
and to catch-all set paths to `/` …
=> fix: allow GRPCRoute without hostnames and matches

CHANGELOG.md, docs/cli-arguments.md, internal/manager/config.go, internal/manager/run.go
Backport #5296 #5299 to release/2.12.x branch.
=> Backport `--emit-kubernetes-events` to release/2.12.x

.github/workflows/_linters.yaml, Makefile
When `--fix` flag is on, `golangci-lint` returns a 0 exit code even if there are issues found and fixed. It's not desired in CI environment where we'd like to get a non-zero exit code always in the case there are any issues found.
Follow up to https://github.com/Kong/gateway-operator/pull/1230.
=> chore(ci): don't fix linting issues in CI

CHANGELOG.md, internal/admission/handler.go, internal/admission/handler_test.go, internal/admission/server_test.go, internal/admission/validator.go, internal/admission/validator_test.go, internal/controllers/configuration/object_references.go, internal/controllers/reference/indexer.go, internal/controllers/reference/indexer_test.go, internal/manager/controllerdef.go, internal/manager/run.go, internal/manager/setup.go, test/integration/webhook_test.go
validates secrets when they are referred by `KongPlugin` and `KongClusterPlugin` to check if they generate invalid Kong plugin configurations.
fixes #5190
=> feat: add validation on secrets on generated plugin cofigs

test/e2e/upgrade_test.go
Use the latest KIC release (v3.0.1) as a base for E2E upgrade tests.
=> chore: bump E2E upgrade manifests

internal/admission/validator.go, test/integration/webhook_test.go
- Remove the logging of generated plugin config to avoid sensitive information in debug logs
- Update names of integration tests on validating secrets  
following fix of #5203.
~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ I think No need to update CHANGELOG
=> fix: remove logs to print config and correct integration test names

CHANGELOG.md, internal/admission/handler.go, internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go, internal/admission/validator.go, internal/admission/validator_test.go, internal/gatewayapi/aliases.go
Validate features in spec of `HTTPRoute` and reject the HTTPRoutes using unspported features.
fixes #5253
=> feat: validate HTTPRoute features

go.mod, test/e2e/upgrade_test.go
~Adds `migrations finish` command before the `migrations up` to finish potential leftovers. Fixes failing `TestDeployAndUpgradeAllInOnePostgres` E2E test: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7190768562/job/19584462222~
Skips the upgrade E2E tests if the versions we're trying to migrate between are not two consecutive Kong minor versions.
Should fix https://github.com/Kong/kubernetes-ingress-controller/issues/5313.
=> fix(tests): skip upgrade tests if not upgrading between two consecutive Kong versions

internal/dataplane/deckgen/generate.go
Print the concrete error returned from `fillPlugin` function in logs.
part of #5341 
REVIEW: how to write changelog for this?
=> fix: print concrete error from fillPlugin in logs

.github/workflows/_e2e_tests.yaml, .github/workflows/_test_reports.yaml
Reverts Kong/kubernetes-ingress-controller#5350
Both 
- actions/upload-artifact - doesn't allow upload multiple times with the same name - [breaking change](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes)
- actions/download-artifact -  [breaking changes](https://github.com/actions/download-artifact/tree/v4/?tab=readme-ov-file#breaking-changes)
It requires changes in our workflows, because of the not allowing uploading multiple artifacts with the same name (what we do).
=> Revert "chore(deps): bump actions/download-artifact from 3 to 4"

hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/controllers/utils/conditions.go, internal/controllers/utils/conditions_test.go
Uses a custom message for the `Programmed` status condition generated when the configuration status of a `KongServiceFacade` is `Unknown`. We want to make it custom instead of generic one to make the message more meaningful for users.
Follow up to #5152.
=> feat: change message for Programmed Unknown KongServiceFacade condition

internal/dataplane/translator/ingressrules.go, internal/dataplane/translator/translator_test.go
If the translator finds a Service that requests a client cert for a non-TLS protocol, do not apply the client certificate and emit a translation failure event. This prevents the misconfigured Service from locking up configuration.
Reported in chat. Configuration similar to the below (note that the Secret isn't shown, it needs to be a TLS cert) results in an apply failure because client certificates are not allowed if the Service has no protocol annotation (default `http`) or has some non-TLS protocol annotation.
```
---
apiVersion: v1
kind: Service
metadata:
name: svc-test
annotations:
konghq.com/client-cert: cert
spec:
type: ExternalName
externalName: example.com
ports:
- protocol: TCP
port: 443
---
apiVersion: …
```
=> fix(translate) handle client cert issues early

.github/workflows/_kongintegration_tests.yaml, test/e2e/konnect_test.go, test/internal/helpers/konnect/access.go, test/internal/helpers/konnect/certificates.go, test/internal/helpers/konnect/control_plane.go, test/kongintegration/translator_golden_tests_outputs_test.go
Adds `TestTranslatorsGoldenTestsOutputs_Konnect` that verifies all `*_default` Translator's golden test outputs are accepted by Konnect Control Plane's Admin API. 
Moves Konnect-related helper functions (for creating test control planes, client certs, etc.) that were used before only in E2E tests to the test helpers package.
Closes #5162.
=> test: verify golden configs against Konnect

test/e2e/features_test.go, test/internal/testenv/feature_gates.go, test/internal/testenv/testenv.go
Due to the possibility of running tests between different versions,
it is necessary to adjust feature gates according to different KIC versions.
Versions below 3.1.x cannot recognize the KongServiceFacade feature gate.
We only need to set `GatewayAlpha=true`.
fixes: https://github.com/Kong/kubernetes-ingress-controller/issues/5373
=> test: Set different feature gates for versions before 3.1.x

internal/dataplane/kongstate/service_backend.go, internal/dataplane/kongstate/types.go, internal/dataplane/translator/backendref.go, internal/dataplane/translator/golden_test.go, internal/dataplane/translator/ingressrules.go, internal/dataplane/translator/ingressrules_test.go, internal/dataplane/translator/subtranslator/ingress.go, internal/dataplane/translator/subtranslator/ingress_atc_test.go, internal/dataplane/translator/subtranslator/ingress_test.go, internal/dataplane/translator/translate_grpcroute_test.go, internal/dataplane/translator/translate_httproute_test.go, internal/dataplane/translator/translate_ingress.go, internal/dataplane/translator/translate_ingress_test.go, internal/dataplane/translator/translate_kong_l4.go, internal/dataplane/translator/translate_tcproute_test.go, internal/dataplane/translator/translate_tlsroute_test.go, internal/dataplane/translator/translate_udproute_test.go, internal/dataplane/translator/translate_utils_test.go, internal/dataplane/translator/translator.go, internal/util/builder/kongstateservicebackend.go
Refactors `kongstate.ServiceBackend` by making its fields private (so they cannot be arbitrarily set outside of the package) and implementing constructors validating the data integrity to be used by the production code. Thanks to that, if we're interacting with the `kongstate.ServiceBackend` object anywhere outside of its package, we can be sure it's in a valid state (if it's not empty).
Closes #5258.
~- [] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~
=> chore: encapsulate ServiceBackend

CHANGELOG.md, internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go, internal/admission/validation/ingress/ingress.go, internal/admission/validation/ingress/ingress_test.go, internal/admission/validation/routelike.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/kongstate/service.go, internal/dataplane/kongstate/service_test.go, internal/util/protocol.go, internal/util/protocol_test.go
Accept the `wss` and `ws` protocols in the protocol annotation value filter. Enterprise added these at some point (see FT-2127 internally) for additional plugin capabilities (`https` and `http` accept WebSocket traffic also, but can't inspect the stream after the initial Upgrade request and 101 response) but we never updated the filter.
Reported by field teams in chat. Attempting to use `ws` or `wss` instead gets you a route with the default `http,https` in 3.0 and older.
Test tools for WebSockets seem annoyingly uncommon. There's not really an httpbin equivalent that I could find, so we'd probably need to add functionality to our echo server to do integration tests. Unit tests are …
=> fix(annotations) allow WebSocket protocols

internal/dataplane/failures/failures.go, internal/dataplane/failures/failures_test.go
Accept objects without namespaces in constructing a translation failure record in `NewResourceFailure`. This allows attaching translation failures to cluster scoped resources like `KongClusterPlugin` or `KongVault`. 
Fixes #5387
=> fix: remove check of namespace in generating translation failures

CHANGELOG.md, go.mod, go.sum, internal/dataplane/configfetcher/config_fetcher.go, internal/dataplane/configfetcher/config_fetcher_test.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/translator/golden_test.go, internal/dataplane/translator/translator.go, internal/dataplane/translator/translator_test.go, internal/manager/run.go
Add the `workspace` parameter in filling IDs of Kong entities to avoid generating the same ID for entities with same "key" (like `username` in consumers) in different workspaces.
Fixes #5389 
=> fix: add workspace in FillIDs

internal/controllers/configuration/kongupstreampolicy_utils.go, internal/controllers/configuration/kongupstreampolicy_utils_test.go
This ensures that the `Accepted` condition in `KongUpstreamPolicy` ancestor's status is set to `Conflicted` for a `Service` used in an `HTTPRoute` only if it is used together with a different `Service` in a single HTTPRoute's rule.
Before this change, we'd set `Conflicted` even if `Service`s using different `KongUpstreamPolicies` were used in separate rules in an HTTPRoute, which shouldn't be the case.
It fixes a problem discovered during work on https://github.com/Kong/kubernetes-ingress-controller/issues/5293. 
Changelog entry was omitted as it is a fix to a net new feature that hasn't been released yet.
Complete these before marking the PR as `ready to …
=> fix: properly detect UpstreamPolicy conflict in HTTPRoutes

CHANGELOG.md
As we haven't changed the router flavor default in the Helm chart, we should not advertise that in KIC's 3.0.0 changelog.
=> chore: do not announce expressions router as default in changelog

CHANGELOG.md, internal/dataplane/configfetcher/kongrawstate.go, internal/dataplane/configfetcher/kongrawstate_test.go
Support properly ConsumerGroups when fallback to the last valid configuration. Function `configfetcher.KongRawStateToKongState` now supports `ConsumerGroup` entities. It means that if KIC fetches the last valid configuration from Gateways, it will include all `ConsumerGroups` that a Gateway may return.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5377
Having explicitly omitted checking this in `internal/dataplane/configfetcher/kongrawstate_test.go:318` caused that the test hasn't caught it during the work on `ConsumerGroup`. **I thing the same may happen for `Vault`** 🤔 
=> fix: support ConsumerGroups in KongRawStateToKongState

CHANGELOG.md, internal/dataplane/translator/backendref.go, internal/dataplane/translator/backendref_test.go, internal/dataplane/translator/translate_grpcroute_test.go, internal/dataplane/translator/translate_httproute_test.go, internal/dataplane/translator/translate_tcproute_test.go, internal/dataplane/translator/translate_tlsroute_test.go, internal/dataplane/translator/translate_udproute_test.go, internal/dataplane/translator/translate_utils.go, internal/dataplane/translator/translate_utils_test.go, internal/dataplane/translator/wrappers_refchecker.go, internal/dataplane/translator/wrappers_refchecker_test.go
When route has the same namespace specified as the backendref, then it should be allowed without a `ReferenceGrant`.
Additionally this PR adds `Service` lookup in ` backendRefsToKongStateBackends()` to verify if the provided namespace exists.
The gist of this change is in `internal/dataplane/translator/backendref.go`. The rest is just adapting the tests basically.
Fixes: #5388
=> fix: fix refChecker when namespace is specified and is the same as route's namespace

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongvaults.yaml, docs/api-reference.md, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, pkg/apis/configuration/v1alpha1/kong_vault_types.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml, test/envtest/crds_envtest_test.go
Translate only one of `KongVault`s and record translation failure events for the others if they have the same `spec.prefix` to avoid generating vaults with the same prefix in Kong configuration. The "winner" is chosen by the following rules:
- The one created earlier (earliest `metadata.creationTimestamp`)
- The one having name in smaller lexical order if the creation timestamp is the same.
And the PR also sets `spec.prefix` to be immutable. 
fixes #5423 
=> feat: translate only one if multiple KongVaults with the same spec.prefix

CHANGELOG.md, internal/admission/validator.go, internal/admission/validator_test.go, internal/dataplane/kongstate/kongstate.go, test/integration/webhook_test.go
Check uniqueness of `spec.prefix` of `KongVault` in all "managed" KongVaults by listing all items in the storer.
fixes #5395 
=> feat: add uniqueness check of spec.prefix of KongVault

go.mod
With go 1.21.1 `golangci-lint` fails like so:
```console
ERRO [linters_context/goanalysis] nilness: panic during analysis: runtime error: index out of range [1] with length 1, goroutine 27331 [running]:
runtime/debug.Stack()
/home/yitao/go1.21/go/src/runtime/debug/stack.go:24 +0x5e
...
```
Upgrading Golang version to 1.21.6 version fixes that.
=> chore(deps): bump go in go.mod to 1.21.6

internal/util/kubernetes/object/status/queue.go, internal/util/kubernetes/object/status/queue_test.go
So far, we haven't had a case where we'd need two separate subscribers to receive channel status update notifications for a single GVK. https://github.com/Kong/kubernetes-ingress-controller/pull/5444 introduces a `Watch` in `KongUpstreamPolicy` controller that needs to receive status updates of `KongServiceFacade` which already has one subscriber in its controller. This PR mitigates issues that might occur because of multiple subscribers consuming notifications from a single channel by creating a separate channel for every `Subscribe` call. 
Follow up of https://github.com/Kong/kubernetes-ingress-controller/pull/5444.
=> feat: allow multiple subscribers on single GVK status updates

CHANGELOG.md, internal/controllers/configuration/kongupstreampolicy_controller.go, internal/controllers/configuration/kongupstreampolicy_utils.go, internal/controllers/configuration/kongupstreampolicy_utils_test.go, internal/controllers/dataplane.go, internal/dataplane/translator/ingressrules.go, internal/dataplane/translator/translator_test.go, internal/manager/controllerdef.go
Adds `Programmed` condition to `KongUpstreamPolicy` ancestors status for `Service` and `KongServiceFacade` based on their configuration status in the data plane.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/5249.
=> feat: add Programmed condition to KongUpstreamPolicy ancestors status

test/integration/isolated/kongupstreampolicy_test.go, test/internal/testlabels/labels.go
Adds an isolated integration test that covers setting KongUpstreamPolicy ancestors' status including `Accepted` and `Programmed` conditions for `Service` and `KongServiceFacade`.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5292.
=> tests: integrate populating UpstreamPolicy's ancestors status

CHANGELOG.md, internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go, internal/dataplane/translator/translate_httproute.go, internal/dataplane/translator/translate_httproute_test.go, test/conformance/gateway_conformance_test.go
fixes: https://github.com/Kong/kubernetes-ingress-controller/issues/4914
=> feat: add support for HTTPRouteTimeoutBackendRequest

CHANGELOG.md, go.mod, go.sum, internal/dataplane/deckerrors/api.go, internal/dataplane/deckerrors/api_test.go, internal/dataplane/kong_client.go
Include op type, entity kind and entity name in CRUD action when logging details of pushing config to Konnect. Based on GDR update https://github.com/Kong/go-database-reconciler/pull/42.
fixes #5274. 
Follow up of #5448. Adds `operation`, `entity_kind` and `entity_name` into the logs.
=> feat: include CRUD action message from go-database-reconciler in logging error details from Konnect

CHANGELOG.md, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/httproute_controller_test.go, test/envtest/httproute_controller_test.go
It ensures we leave no stale parent statuses in `HTTPRoute`s (e.g. after moving a route from one Gateway to another by changing its `spec.parentRefs`).
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5277.
=>  fix: remove stale parent statuses from HTTPRoute

CHANGELOG.md, FEATURE_GATES.md, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/kongstate/credentials.go, internal/dataplane/kongstate/license.go, internal/dataplane/sendconfig/kong.go, internal/dataplane/sendconfig/strategy.go, internal/manager/featuregates/feature_gates.go, internal/manager/run.go, test/envtest/telemetry_test.go
It allows users to enable data obfuscation before sending Kong configuration to Konnect control plane's Admin API.
Fixes #5467.
=> feat: allow sanitizing configuration sent to Konnect

test/e2e/helpers_test.go
As discussed internally, setting `appProtocol` to `HTTP` will make kuma to load balance at request level. While by default kuma may only load balance at the connection level. When Kong gateway changed the `upstream_keepalive_max_requests` from 1000 to 10000: https://github.com/Kong/kong/pull/12223, the upstream connection is reused during all the test which only send about 3000 requests. So the requests constantly go to the same backend pod from one Kong gateway pod. 
I changed `appProtocol` to `http`, the failure disappears in my local run.
maybe fix #5498 
~- [ ] the `CHANGELOG.md` release notes …
=> test(e2e): set appProtocol to HTTP for kuma tests

.github/ISSUE_TEMPLATE/release.yaml
https://github.com/Kong/docs.konghq.com/pull/6695 has changed the markdown location of KIC's and Gateway's support policy, therefore requiring the person releasing KIC to follow markdown includes in order to update the right place.
This PR fixes the above - by making the locations to update exactly accurate.
n/a
Please sanity-check this change for correctness.
=> Release checklist update - support policy markdown has new location

CHANGELOG.md, config/crd/bases/configuration.konghq.com_konglicenses.yaml, config/crd/kustomization.yaml, config/rbac/role.yaml, docs/cli-arguments.md, internal/controllers/configuration/konglicense_controller.go, internal/manager/config.go, internal/manager/run.go, internal/manager/setup.go, pkg/apis/configuration/v1alpha1/kong_license_types.go, pkg/clientset/typed/configuration/v1alpha1/configuration_client.go, pkg/clientset/typed/configuration/v1alpha1/fake/fake_configuration_client.go, pkg/clientset/typed/configuration/v1alpha1/fake/fake_konglicense.go, pkg/clientset/typed/configuration/v1alpha1/konglicense.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml, test/integration/isolated/license_test.go, test/integration/isolated/skip.go, test/internal/helpers/kong.go, test/internal/testlabels/labels.go
The PR implements a `KongLicense` controller which picks the newest `KongLicense` in the cluster and provides a `GetLicense` method for translator to inject Kong license into Kong configurations. 
The controller is enabled when `--enable-controller-kong-license` is set to `true` (by default) and sync license with Konnect disabled. When sync license with Konnect is enabled, the licenses from Konnect takes the precedence.
Major part of #5437.
Not fully finished yet, but can reconcile `KongLicense` resources and ready to receive some reviews. Major remaining part:
- When no `KongLicense` CRD in cluster, the controller will exit abnormally
- Maybe add validation of `KongLicense`?
- …
=> feat: implement KongLicense controller and inject to translator

CHANGELOG.md, FEATURE_GATES.md, internal/manager/featuregates/feature_gates.go, test/envtest/telemetry_test.go
@mheap suggested we might want to make this feature gate enabled by default.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/5467.
=> feat: enable Konnect config dumps sanitization by default

.github/workflows/_integration_tests.yaml, internal/controllers/configuration/konglicense_controller_test.go, test/envtest/konglicense_controller_test.go
Add unit tests, envtest tests and isolated integration tests for KongLicense controller.
fixes #5565.
This also sets enterprise to true in isolated integration tests to enable enterprise features because applying Kong licenses needs Kong gateway enterprise. Which is better, create an "enterprise" job or enable enterprise feature in all isolated integration test cases? I prefer the latter because the "enterprise" mode includes all cases.
~- [x] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ No need to …
=> test: Add unit tests and  envtest tests for KongLicense controller

CHANGELOG.md, go.mod, go.sum, test/kongintegration/translator_golden_tests_outputs_test.go
Bump `go-database-reconciler` to a version that fixes the issue with populating `regex_priority` and `path_handling` for expression routes. Starts running `kongintegration` tests against Konnect with all golden tests outputs (including the ones with expressions router which were disabled before).
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5148.
It's fixed thanks to the changes in `go-database-reconciler`: https://github.com/Kong/go-database-reconciler/pull/55
=> fix: don't populate fields disallowed for expressions router in Konnect

.github/workflows/performance_targeted.yaml, .github/workflows/performance_trigger_via_label.yaml
I've noticed that repo checkout took nearly a minute in https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7815845008/job/21321138776#step:2:52 so proposing to add `depth: 0` as in other places in the repository.
=> chore: use depth 0 when checking out repo in performance tests

.golangci.yaml, Dockerfile, Dockerfile.debug, Makefile, controllers/license/konglicense_controller.go, controllers/license/konglicense_controller_test.go, go.mod, go.sum, internal/manager/setup.go, test/envtest/konglicense_controller_test.go
> Start from https://github.com/Kong/gateway-operator-enterprise/pull/15 to have a big picture.
CRD `KongLicense` is not only used in KIC, the controller can be reused. Make it importable. Other projects can add it to their managers and use it. 
Part of:
- https://github.com/Kong/gateway-operator/issues/1312
=> chore(refactor): make KongLicense controller importable

CHANGELOG.md
For better UX, as @pmalek suggested, we can link to guides in the release highlights to make it easier for our users to hop into using the new features right away.
Part of #5443.
=> chore: link to guides in KIC 3.1 highlights

docs/api-reference.md, docs/incubator-api-reference.md, scripts/apidocs-gen/post-process-for-konghq.sh, scripts/apidocs-gen/template/gv_details.tpl, scripts/apidocs-gen/template/type.tpl
Splits the top-level CRDs and the types that they rely on into separate sections to make it clear which types are meant to be used to create objects in the Kubernetes API.
It mostly influences the way a page index is generated in docs.
Before (listing all types along with CRs):
After (only CRs listed + "Types" section):
Addresses @liyangau concern about the reference not signaling clearly which types are meant to be used to create objects in a cluster.
=> chore(docs): split CRDs and other types into sections in reference

.github/ISSUE_TEMPLATE/release.yaml
Add steps for minor/major releases to update charts' dependencies.
=> chore(docs): update release template with bumping charts' deps

internal/dataplane/translator/atc/expression_test.go, internal/dataplane/translator/atc/field.go, internal/dataplane/translator/atc/matcher.go, internal/dataplane/translator/atc/predicate.go
Update the ATC (expression) translator as the following features are added in Kong gateway's ATC(expression) router:
- Add `NOT` (`!`) operator for negating an expression
- Add the fields and predicates for HTTP path segments matching (`http.path.segments.len`,`http.path.segments.<index>`,`http.path.segments.<index>_<index>`)
First step of #5485 
=> feat: add path segment field and not operator in atc translator

CHANGELOG.md, internal/dataplane/translator/translator.go, internal/dataplane/translator/translator_test.go, internal/manager/run.go
Add an `EnterpriseEdition` feature flag in translator and disable the translation of licenses if `EnterpriseEdition` is not enabled. 
fixes #5638 
- Since we added the `EnterpriseEdition` flag, we can actually do more things on translation of "enterprise only" Kong configurations (like consumergroups). Should we do this in later PRs?
- Since Kong 3.6, an `edition` field is added in the response of root endpoint. Should we implement a dedicated function to fetch this field (and fall back to judge by version if the field does not present)?
=> fix: do not translate licenses if Kong gateway is not enterprise edition

scripts/cli-arguments-docs-gen/post-process-for-konghq.sh
Add a newline before the Vale directive comment. Without this, Jekyll tries to include the directive comment in the table and breaks formatting.
See https://github.com/Kong/docs.konghq.com/pull/6979
Upstream docs PR manually fixes the current files, this is for future ones.
=> chore(ci) fix CLI doc generator

controllers/license/konglicense_controller.go, internal/manager/setup.go, test/envtest/konglicense_controller_test.go
> Prerequisite for https://github.com/Kong/gateway-operator-enterprise/pull/20
This PR introduces API for the `KongLicense` controller that allows injecting a custom validator for a license and sets the additional condition accordingly. Moreover, the API for retrieving a license is enhanced with information about validity.
Part of
- https://github.com/Kong/kubernetes-ingress-controller/issues/5566
Prerequisite for (part of)
- https://github.com/Kong/gateway-operator/issues/1312
Know issue is that when a license expires, the condition in status will not be updated automatically - the user won't be able to spot this in real time. When a new reconciliation is triggered it will get an …
=> feat(license): add ability to validate KongLicense

.github/workflows/_integration_tests.yaml, Makefile, test/integration/isolated/license_test.go, test/integration/isolated/skip.go, test/integration/isolated/suite_test.go
- Fix election namespace used for isolated integration tests to make isolated tests able to run with DB backed Kong gateway
- Add a Makefile item to run isolated integration tests
Since there is still problems with `KongLicense` in DB mode, we would enable the postgres isolated integration tests after #5644.
=> test(integration): add postgres in isolated integration tests

CHANGELOG.md, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go
In single-Gateway mode, properly skip route parent references for other Gateways when determining whether to include a route.
Currently, single-Gateway mode doesn't actually restrict the controller to routes attached to that Gateway. The original work in https://github.com/Kong/kubernetes-ingress-controller/commit/2e22a101c8a962a4bf17eb3ec72f8845c598d320 doesn't actually filter other routes for two reasons:
- Although we change the controller map functions (via filters in `listHTTPRoutesForGateway()` and the like), controllers [actually queue _all_ route objects](https://github.com/Kong/kubernetes-ingress-controller/blob/7b732489a5e1ec80211e7f61a806bb1818401daf/internal/controllers/gateway/httproute_controller.go#L138-L …
=> fix(controllers) skip routes bound to excluded GWs

Makefile, config/webhook/manifests.yaml, internal/admission/handler.go, test/envtest/admission_webhook.go, test/envtest/admission_webhook_envtest_test.go
- Adds `+kubebuilder:webhook` annotations close to handlers implementing the webhook for given resources.
- Adds `manifests.webhook` Makefile target to generate `config/webhook/manifests.yaml` file with the `ValidatingWebhookConfiguration`
- Starts using the generated config in webhook envtests (created a follow up issue for doing so for integration tests: https://github.com/Kong/kubernetes-ingress-controller/issues/5660)
It's needed in KGO to be able to create relevant `ValidatingWebhookConfiguration` based on a single source of truth in KIC.
Prerequisite for https://github.com/Kong/gateway-operator/issues/1260.
=> chore: generate validating webhook config using controller-gen

test/helpers/certificate/certificate.go
Type `SelfSignedCertificateOptionsDecorator` is too verbose, typical in Go something like that is named `SelfSignedCertificateOption`. Furthermore `SelfSignedCertificateOptions` doesn't need to be exposed, so rename to `selfSignedCertificateOptions`.
=> chore: improve naming in package certificate

CHANGELOG.md, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gatewayclass_controller.go
All the gateways (managed and unmanaged) are pushed to the dataplane. The condition for it is to have them accepted.
Fixes: #5600 
=> feat: managed gateways config pushed when accepted

test/helpers/certificate/certificate.go
This is needed to fix unit test failures like https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8094320723/job/22118824077?pr=5668
The test requires to have an expired test. With this PR, the after date is way before `now`, instead of being `now`.
=> fix: notBefore and notAfter changed in CA test

config/webhook/manifests.yaml, internal/admission/handler.go
In https://github.com/Kong/kubernetes-ingress-controller/pull/5659 I added kubebuilder annotations that allow us generating webhook configuration. I mistakenly included `DELETE` verb in some of webhooks. This PR fixes that.
The manifests were only used in KGO so far. 
Not adding a changelog entry as the manifests for webhook configuration were not advertised in any way yet.
=> fix: do not include DELETE in any webhook operations

CHANGELOG.md, internal/dataplane/translator/translator.go, internal/dataplane/translator/translator_test.go, internal/manager/run.go
Backport #5640 to `release/3.1.x` to disable translating licenses when Kong is not enterprise edition.
Updated changelogs because #5640 is not included in 3.1.1. 
=> Backport "fix: do not translate licenses if Kong gateway is not enterprise edition (#5640)" to 3.1.x

CHANGELOG.md
Since the PR #5640 was not actually included in 3.1.1 release, moving the item from "3.1.1" to "Unreleased".
=> chore(docs): Move PR #5640 out of 3.1.1 changelogs

test/consts/consts.go, test/e2e/helpers_test.go, test/internal/testenv/feature_gates.go
The following can be observed in KIC logs in e2e tests (in downloaded diagnostics):
```
Error: unable to create controller "*crds.DynamicCRDController": failed to index KongServiceFacades on annotation konghq.com/upstream-policy: no matches for kind "KongServiceFacade" in version "incubator.ingress-controller.konghq.com/v1alpha1"
```
It seems that `KongServiceFacade` is not installed by default in e2e tests because it's not packaged in default CRD kustomization (nor is it packaged with all in one manifests that we use for e2e tests) but the default feature gates env flag used in tests does enable its usage:
https://github.com/Kong/kubernetes-ingress-controller/blob/96941c3014b72e1a73996829f5f0e0b58a30ed44/test/consts/feature_gates.go#L8
This PR …
=> tests: fix e2e tests by installing incubator CRDs

.github/workflows/_conformance_tests.yaml, .github/workflows/_docker_build.yaml, .github/workflows/_e2e_tests.yaml, .github/workflows/_envtest_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_kongintegration_tests.yaml, .github/workflows/_linters.yaml, .github/workflows/_performance_tests.yaml, .github/workflows/_test_reports.yaml, .github/workflows/_unit_tests.yaml, .github/workflows/check_fixed_issues_references.yaml, .github/workflows/checks.yaml, .github/workflows/cleanup.yaml, .github/workflows/conformance_tests_report.yaml, .github/workflows/performance_targeted.yaml, .github/workflows/performance_trigger_via_label.yaml, .github/workflows/release_docs.yaml, .github/workflows/test_nightly.yaml
Looking at the CI's logs it seems that we've been spending over 1 minute on each job's run
Example: 
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8329931649/job/22793502809?pr=5717
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8329931649/job/22793502809?pr=5717#step:2:52
According to https://github.com/actions/checkout 
```
fetch-depth: ''
```
Setting to 0 fetches the whole history which is in most cases unnecessary.
This PR sets the depth to 1 ( by using the default ).
=> ci: do not fetch all history on CI

.github/workflows/checks.yaml
Fix:  https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8330806855/job/22796286998
```
From https://github.com/Kong/kubernetes-ingress-controller
* branch              b70a95c8ff9743831d4b1c1833b0c080f0443085 -> FETCH_HEAD
fatal: ambiguous argument 'origin/main~1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
=> ci: fix main's up-to-date job by increasing fetch-depth

examples/gateway-udproute.yaml, test/e2e/helpers_gateway_test.go, test/integration/examples_test.go, test/integration/isolated/examples_udproute_test.go, test/integration/isolated/tcproute_test.go, test/integration/tcproute_test.go, test/tcp_utils.go
Tests for UDP in KIC are historically overall complex, they use CoreDNS for verification. This PR makes `TestExampleUDPRoute` much simpler, and uses the same approach as `TestTCPRouteExample`. Instead of CoreDNS it uses `kong/go-echo:0.3.0` furthermore it refactors `TCPEchoResponds` to `EchoResponds` which works with both TCP and UDP protocol.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/5715, contains the proposed resolution from https://github.com/Kong/kubernetes-ingress-controller/pull/5717 - making naming unique.
Making `test/integration/isolated/udproute_test.go` similar to `test/integration/isolated/tcproute_test.go` will be handled in a separate PR.
=> chore(tests): simplify TestExampleUDPRoute

.github/workflows/checks.yaml
https://github.com/Kong/kubernetes-ingress-controller/pull/5720 didn't fix the issue: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8333401781
So this PR revert the fetch depth to 0. This can probably be optimized but I failed to reproduce the failure in my fork so leaving this at 0 (which causes the somewhat unnecessary checkout of ~~ 1minute currently)
=> ci: fix main's up-to-date job by setting fetch-depth to 0

CHANGELOG.md, internal/admission/validation/consumers/credentials/validation.go, internal/admission/validation/consumers/credentials/validation_test.go
Do not requiere the `rsa_public_key` field in credential secrets when working with jwt HMAC credentials.
The `algorithm` values are compares against https://docs.konghq.com/hub/kong-inc/jwt-signer/configuration/#config-enable_hs_signatures
Fixes #5736
Related: https://github.com/Kong/kubernetes-ingress-controller/issues/5159
=> fix(webhook): do not require rsa_public_key field in credentials secrets when working with jwt HMAC algorigthms

test/integration/tcpingress_test.go
Test `TestTCPIngressTLSPassthrough` relies on an old Redis image, which adds complexity and it can't be run on a computer with an ARM processor without a hassle. See logs of this container
```log
exec /opt/bitnami/scripts/redis/entrypoint.sh: exec format error
```
This PR migrates it to use `kong/go-echo:0.3.0` image as the rest of similar tests.
=> chore(tests): do not rely on Redis in TestTCPIngressTLSPassthrough

examples/udpingress.yaml, internal/util/test/controller_manager.go, test/integration/examples_test.go, test/integration/isolated/examples_udpingress_test.go, test/internal/testlabels/labels.go
Tests for UDP in KIC are historically overall complex, they use CoreDNS for verification. This reworks `TestUDPIngressExample` to use an isolated tests framework and makes it much simpler. Instead of CoreDNS it uses `kong/go-echo:0.3.0`.
Done during work on https://github.com/Kong/kubernetes-ingress-controller/issues/5715.
There is also an initiative to get rid of CoreDNS in tests entirely.
**Special notes for your reviewer:**
Please verify whether the comment about the usage of the example `examples/udpingress.yaml` is up to date. Otherwise, I can improve it in this PR. 
<!--
Here you can add any links to issues that this PR is relevant for.
You can use Github keywords (like: closes, fixes or resolves) to auto-resolve …
=> chore(tests): migrate to isolated and simplify TestUDPIngressExample

test/integration/isolated/assertion_helpers.go, test/integration/isolated/tcproute_test.go, test/integration/isolated/udpingress_tcpingress_collision_test.go, test/integration/isolated/udpingress_test.go, test/integration/isolated/udproute_test.go
Keep test code DRY. We are currently migrating to isolated tests, but even now helpers for common assertions can be reused in isolated tests. Probably it will evolve in the future.
=> chore(tests): reuse assertion functions for TCP and UDP in isolated tests

.github/workflows/_conformance_tests.yaml, .github/workflows/_docker_build.yaml, .github/workflows/_e2e_tests.yaml, .github/workflows/_envtest_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_kongintegration_tests.yaml, .github/workflows/_linters.yaml, .github/workflows/_performance_tests.yaml, .github/workflows/_test_reports.yaml, .github/workflows/_unit_tests.yaml, .github/workflows/backport.yaml, .github/workflows/benchmarks.yaml, .github/workflows/check_fixed_issues_references.yaml, .github/workflows/check_pr_labels.yaml, .github/workflows/checks.yaml, .github/workflows/cleanup.yaml, .github/workflows/codeql.yaml, .github/workflows/conformance_tests_report.yaml, .github/workflows/e2e_nightly.yaml, .github/workflows/e2e_targeted.yaml, .github/workflows/e2e_trigger_via_label.yaml, .github/workflows/license.yaml, .github/workflows/nightly.yaml, .github/workflows/performance_nightly.yaml, .github/workflows/performance_targeted.yaml, .github/workflows/performance_trigger_via_label.yaml, .github/workflows/regenerate_on_deps_bump.yaml, .github/workflows/release.yaml, .github/workflows/release_docs.yaml, .github/workflows/validate_kong_image.yaml
There are [29 PRs](https://github.com/Kong/kubernetes-ingress-controller/pulls/team-eng-enablement) from @team-eng-enablement that set the default timeout for our GitHub workflows. This PR aims to do it in one shot.
Company wide `vars.GHA_DEFAULT_TIMEOUT = 10 minutes` for our use-case repo wide `vars.GHA_EXTENDED_TIMEOUT_MINUTES = 30 minutes` was defined too
I am wondering if I set it everywhere properly...
=> chore: update timeout for GitHub workflows

.github/test_dependencies.yaml
We need to keep using Kong EE in version `3.4.x` in the envtests until https://konghq.atlassian.net/browse/KAG-3699 gets released in `3.7.x` (see https://github.com/Kong/kubernetes-ingress-controller/pull/5605 for reference).
=> chore: downgrade Kong EE dependency used in envtests

.golangci.yaml, CHANGELOG.md, internal/adminapi/kong.go, internal/adminapi/konnect.go, internal/dataplane/kong_client_test.go, internal/konnect/controlplanes/client.go, internal/konnect/controlplanes/client_test.go, internal/konnect/controlplanesconfig/client.go, internal/konnect/controlplanesconfig/client_test.go, internal/konnect/license/client.go, internal/konnect/license/client_test.go, internal/konnect/nodes/client.go, internal/konnect/nodes/client_test.go, internal/konnect/roles/client.go, internal/konnect/roles/client_test.go, internal/konnect/useragent/user_agent_round_tripper.go, internal/manager/config.go, internal/manager/metadata/metadata.go, test/e2e/all_in_one_test.go, test/e2e/konnect_test.go, test/internal/helpers/kong.go, test/kongintegration/expression_router_test.go, test/kongintegration/inmemory_update_strategy_test.go, test/kongintegration/kongupstreampolicy_test.go, test/kongintegration/translator_golden_tests_outputs_test.go
It uses `go-kong` feature introduced in `v0.52.0`, see
- https://github.com/Kong/go-kong/pull/427
It allows setting `User-Agent` to ensure that KIC always uses the client with the proper `User-Agent` set. The linter configuration will enforce it across the whole repo.
For clients that live in the KIC repo `internal/konnect/*` `User-Agent` is also added. Those clients are considered as a temporary solution because they will be deprecated as fast as the proper SDK will be released. Thus it's not in the scope of this PR to make a bigger refactor, etc. of those clients, just add the missing `User-Agent`.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/5418
Complete these …
=> fix: set proper User-Agent for request made to Kong and Konnect

internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/sendconfig/inmemory_error_handling_test.go
This PR will fix an error when user does not have the admission webhook enabled and applies a configuration which has a cluster scoped resource being the offender, e.g. `KongClusterPlugin` with incorrect schema which up until now yields:
```
2024-02-04T18:19:55Z    error    Entity tags missing fields    {"name": "prometheus", "error": "no namespace"}
```
Since `KongClusterPlugin` is cluster scoped it does not have a namespace. This PR fixes that.
Fixes: #5555
=> fix: do not require namespaces when parsing errors about cluster scoped resources

internal/dataplane/kong_client.go
This PR will make KIC emit error logs for each error that is emitted as `KongConfigurationApplyFailed` event to help users discover errors in their configuration.
Example:
```
2024-03-28T11:09:33+01:00	error	recording a Warning event for object	{"name": "alice1", "namespace": "default", "kind": "KongConsumer", "apiVersion": "configuration.konghq.com/v1", "reason": "KongConfigurationApplyFailed", "message": "invalid consumer:: uniqueness violation: 'consumers' entity with username set to 'alice' already declared", "error": "object failed to apply"}
```
Part of #5431
=> feat: log an error when configuration fails to get applied and `KongConfigurationApplyFailed` is emitted

.tools_versions.yaml, Makefile, third_party/go.mod, third_party/go.sum, third_party/staticcheck.go
This reverts commit 3a700201ff0d50b8be6bf30a683dd13c1f25cfd6 (part of #5767) because it was merged with an accidental push due to branch protection misconfiguration.
=> Revert "ci: manage staticcheck with mise"

.github/workflows/nightly.yaml
#5768 missed adding those params to nightly pipeline which should in fact use `.github/workflows/_docker_build.yaml` but apparently it's still defined as a standalone job.
=> fix(ci): fix nightly build by adding missing GOCACHE and GOPATH build params

.github/workflows/_e2e_tests.yaml, .github/workflows/_performance_tests.yaml
~As we have already set a timeout for ORG, any job that does not specify its timeout will default to using the global 10 minutes.~
Company wide vars.GHA_DEFAULT_TIMEOUT = 10 minutes for our use-case repo wide vars.GHA_EXTENDED_TIMEOUT_MINUTES = 30 minutes was defined too
The e2e tests and performance tests running on GKE took more than 10 minutes, so I have set them to run for 30 minutes.
> [e2e-tests / gke (1.29.2, TestDeployAllInOnePostgresGatewayDiscovery$)](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8517470363/job/23328098244)
The job running on runner GitHub Actions 30 has exceeded the maximum execution time of 10 minutes.
ref: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8517470363
**Which issue …
=> ci: set timeout for e2e test and perf test

.github/ISSUE_TEMPLATE/enhancement.yaml
Let's add a checkbox to the enhancement issue template that will ensure that we add docs updates in the acceptance criteria. This is to ensure we properly track docs updates and do not postpone writing them just before a release happens.
This resolves an action item from a retro discussion about missed docs updated for KIC 3.1 release.
=> chore(docs): add checkbox for docs update in enhancement issue template

.dockerignore, .github/workflows/_docker_build.yaml, .github/workflows/checks.yaml, .github/workflows/nightly.yaml, .github/workflows/release.yaml, Dockerfile, Dockerfile.debug
This PR introduces usage of docker's `BUILDPLATFORM` build variable which allows to utilize Go's cross compilation instead of QEMU arm64 emulation.
Related: https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
This cuts down the build time from around 10 minutes (on a nightly build - https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8503447872/job/23288959082#step:12:677 - because up until now we have not been running arm64 builds on PRs so there's nothing to compare against until this gets merged) to around a 1m30s https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8521142792/job/23338780301?pr=5788#step:9:1905
---
This PR also adds several entries to .dockerignore to minimize …
=> build: do not use qemu for emulation when building docker images

CHANGELOG.md, internal/admission/validation/consumers/credentials/validation.go, internal/admission/validation/consumers/credentials/validation_test.go
Backport [c9978fa](https://github.com/Kong/kubernetes-ingress-controller/commit/c9978fabd5f82275db1cd0135608d8b7d7351891) from https://github.com/Kong/kubernetes-ingress-controller/pull/5737.
=> [Backport release/3.1.x] fix(webhook): do not require rsa_public_key field in credentials secrets when working with jwt HMAC algorigthms (#5737)

internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/sendconfig/inmemory_error_handling_test.go
Backports #5764 to `release/3.1.x`
=> [Backport release/3.1.x] fix: do not require namespaces when parsing errors about cluster scoped resources (#5764)

CHANGELOG.md, internal/controllers/configuration/konglicense_controller.go, internal/controllers/configuration/kongupstreampolicy_controller.go, internal/controllers/configuration/kongupstreampolicy_utils.go, internal/controllers/configuration/kongupstreampolicy_utils_test.go, internal/manager/controllerdef.go, test/envtest/adminapi_discoverer_envtest_test.go, test/envtest/kongupstreampolicy_test.go, test/envtest/setup.go
Backports https://github.com/Kong/kubernetes-ingress-controller/pull/5780 to release/3.1.x branch.
=> [backport release/3.1.x] fix: add check for existence of HTTPRoute in KongUpstreamPolicy controller

CHANGELOG.md, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/backoff_strategy.go, internal/dataplane/sendconfig/backoff_strategy_test.go, internal/dataplane/sendconfig/dbmode.go, internal/dataplane/sendconfig/inmemory.go, internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/sendconfig/sendconfig.go, internal/dataplane/sendconfig/strategy.go, internal/diagnostics/server.go, internal/diagnostics/server_test.go, internal/util/configdiag.go, test/kongintegration/inmemory_update_strategy_test.go, test/kongintegration/kongupstreampolicy_test.go, test/kongintegration/translator_golden_tests_outputs_test.go
Add a diagnostic endpoint for raw config errors to simplify problem identification when Kong does not return flattened errors.
Attempt to log the `message` field if we cannot unmarshal a config error into the proper type.
Fix #5762 
Logs from practical testing:
```
2024-03-28T19:45:41Z	error	could not fully parse config error	{"message": "declarative config is invalid: {targets={[2]=\"uniqueness violation: 'targets' entity with primary key set to '172fcf76-2116-5155-ae84-e534423f5354' already declared\"}}"}
2024-03-28T19:45:41Z	error	Failed parsing resource errors	{"url": "https://10.244.0.6:8444", "update_strategy": "InMemory", "error": "could not unmarshal config error: json: …
```
=> feat(diag) expose unparseable config errors

internal/controllers/gateway/gateway_controller.go
Discovered in one of the CI runs in during a failed test run:
```
2024-04-03T21:14:36.3000089Z     run.go:227: 2024-04-03T21:14:34Z	info	controllers.Gateway	Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler	{"reconcileID": "e58094f2-da9a-400c-abe5-f043b2f7ebb5"}
```
=> chore: do not return requeue true when err is not nil

CHANGELOG.md, internal/admission/validation/consumers/credentials/validation.go, internal/admission/validation/consumers/credentials/validation_test.go, internal/controllers/configuration/secret_controller.go, internal/controllers/configuration/secret_controller_test.go, internal/dataplane/kongstate/kongstate_test.go, internal/labels/labels.go, internal/util/credential.go, internal/util/credential_test.go
Do reconcile secrets with `konghq.com/credential` label.
Closes: #5398
=> fix: do reconcile secrets with `konghq.com/credential` label

test/integration/isolated/examples_udproute_test.go
For isolation tests generation of the test namespace may lead to conflict when tests are run in parallel. Ir results in the flake, see [buildpulse](https://app.buildpulse.io/@Kong/kubernetes-ingress-controller/tests/10411550846?filter_results_type=flaky) and related [CI run](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8594319438/job/23547213149) (grep by `ns-508-26f` to see the conflict). All other isolated tests, besides  `TestExampleUDPRoute` are currently not run in parallel, hence do not run this one too.
=> fix(tests): do not run TestExampleUDPRoute in parallel

.github/workflows/license.yaml
Pin fossa action to the newest tag available: [v1.3.3](https://github.com/fossas/fossa-action/releases/tag/v1.3.3).
This is to avoid the following warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: fossas/fossa-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8503018185
The reason for this is the fact that v1 of that action still points to a commit in 2021: https://github.com/fossas/fossa-action/releases/tag/v1
=> chore: pin fossa action to the newest 1.3.3 tag

CHANGELOG.md, internal/store/store.go, internal/store/store_test.go
Listing in `Store` apparently uses the `ListAll()` which doesn't preallocate the objects slice https://github.com/kubernetes/client-go/blob/v0.29.3/tools/cache/listers.go#L36-L50. This is especially relevant when using an empty label selector like what's used with the Gateway API objects.
This PR makes that code preallocate the objects slice.
The difference depends on the actual number of objects in the cache but:
- time wise this yields around 30% improvement (decreased time of listing)
- bytes allocated wise this yields 30% - 60% percent improvement (less bytes allocated)
- allocations per operation this yields ~~ 65% up to 95% less allocations 
```
benchstat -confidence 0.93 old.txt new.txt
goos: darwin
goarch: arm64
pkg: …
```
=> perf: preallocate when listing Gateway API objects in store

Makefile
This PR aims to fix compilation warnings which clutter the compilation or test console output on Mac:
```
make test.unit.pretty
GOTESTSUM_FORMAT=pkgname \
/Users/patryk.malek@konghq.com/code_/kubernetes-ingress-controller/bin/installs/gotestsum/1.11.0/bin/gotestsum -- \
-race  \
-tags envtest \
-covermode=atomic \
-coverpkg=./pkg/...,./internal/... \
-coverprofile=coverage.unit.out \
./internal/... \
./pkg/...
ld: warning: '/private/var/folders/0m/_63w01516tgf3cftmp9h7ylm0000gn/T/go-link-3731571908/000023.o' has malformed LC_DYSYMTAB, expected 98 undefined symbols to start at index 1626, found 95 undefined symbols starting at index 1626
ld: warning: '/private/var/folders/0m/_63w01516tgf3cftmp9h7ylm0000gn/T/go-link-1021094792/000023.o' has malformed …
```
=> chore: fix compilation warnings about malformed LC_DYSYMTAB

test/e2e/features_test.go
`TestDeployAllInOneDBLESSGateway` performs an update and sets KIC's feature gates to `testenv.GetFeatureGates()` which by default include the `KongServiceFacade=true` https://github.com/Kong/kubernetes-ingress-controller/blob/96941c3014b72e1a73996829f5f0e0b58a30ed44/test/consts/feature_gates.go#L7-L8.
This is problematic because `KongServiceFacade` CRD is not installed by default and the controller which watches it doesn't have a fallback mechanism and just fails to start when the aforementioned CRD is missing https://github.com/Kong/kubernetes-ingress-controller/blob/30a2991056044636804da46c7847b44e9497de50/internal/controllers/configuration/kongupstreampolicy_controller.go#L155-L164
This results in 
```
2024-04-08T14:42:33.009629453Z stderr F …
```
=> tests: fix feature gates used in TestDeployAllInOneDBLESSGateway

test/integration/isolated/namespace.go
To prevent failures in creating namespaces in isolated integration tests suite like this
```
=== RUN   TestTCPRouteEssentials/essentials
suite_test.go:184: Creating NS ns-a90-003 for test TestTCPRouteEssentials/essentials
suite_test.go:185: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/isolated/suite_test.go:185
/home/runner/go/pkg/mod/sigs.k8s.io/e2e-framework@v0.3.1-0.20231113122213-262cac32d35e/pkg/env/env.go:435
/home/runner/go/pkg/mod/sigs.k8s.io/e2e-framework@v0.3.1-0.20231113122213-262cac32d35e/pkg/env/env.go:449
object is being deleted: namespaces "ns-a90-003" already exists
Test:       	TestTCPRouteEssentials/essentials …
```
=> tests: use GenerateName for isolated integration tests namespaces

.github/workflows/_conformance_tests.yaml, .github/workflows/_envtest_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_kongintegration_tests.yaml, .github/workflows/_test_reports.yaml, .github/workflows/_unit_tests.yaml
Part of #5357
Relevant guide: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
=> chore(ci): migrate actions/upload-artifact and actions/download-artifact to v4

internal/dataplane/translator/translator.go, internal/dataplane/translator/translator_test.go
Combine targets with the same address or hostname by summing their weights into a single target. Previously, same address targets would result in duplicates and would be rejected by Kong.
Fix https://github.com/Kong/kubernetes-ingress-controller/issues/5761. Summing weights wasn't actually that hard!
=> fix(upstreams) deduplicate like targets

CHANGELOG.md, internal/dataplane/kong_client.go, internal/dataplane/sendconfig/sendconfig.go
Let's run KIC with DEBUG level logs for instance with `make debug.skaffold` and see
```log
...
[ingress-controller] 2024-04-09T15:45:39Z        debug   No configuration change, skipping sync to Kong  {"url": "https://10.244.0.24:8444", "v": 1}
[ingress-controller] 2024-04-09T15:45:39Z        debug   No change in config status, not notifying       {"v": 1}
[ingress-controller] 2024-04-09T15:45:39Z        debug   No configuration change; resource status update not necessary, skipping {"v": 1}
[ingress-controller] 2024-04-09T15:45:39Z        debug   events  failed to apply Kong configuration to https://10.244.0.24:8444: %!s(<nil>)      {"v": 1, "type": "Warning", "object": {"kind":"Pod","namespace":"kong","name":"ingress-kong-6949f45784-cfnhp","apiVersi …
```
=> fix(diag): get rid of wrongly logged errors

Makefile, test/consts/zz_generated_gateway.go, test/envtest/setup.go, test/internal/cmd/generate-gateway-api-consts/gateway_consts.tmpl, test/internal/cmd/generate-gateway-api-consts/main.go
There are two ways to install GWAPI CRDs in our testing:
* install from go mod https://github.com/Kong/kubernetes-ingress-controller/blob/28889089a48a6f0b99505967791b4618f2ab9a4b/test/envtest/setup.go#L130
* install from GitHub via kustomize https://github.com/Kong/kubernetes-ingress-controller/blob/28889089a48a6f0b99505967791b4618f2ab9a4b/test/e2e/features_test.go#L280
However, kustomize does not support the use of short commits generated by go mod, 
and go mod also does not support the use of full commit hashes.
This PR introduces a new variable, GATEWAY_API_PACKAGE_VERSION. It will automatically resolve the package version in dependencies through go mod and allow us to use the full commit hash to use the GATEWAY API package.
**Which issue this PR …
=> test: allow installation using a specified GatewayAPI commit

test/e2e/helpers_test.go, test/e2e/konnect_test.go
Add logs to Konnect license e2e test for easier debugging failures like https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8641557356/job/23691285205#step:8:98
```
konnect_test.go:98: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/e2e/konnect_test.go:98
Error:      	Condition never satisfied
Test:       	TestKonnectLicenseActivation
control_plane.go:68: deleting test Konnect Control Plane: "5eb8f77c-6890-4b2f-ad93-960f88a600d7"
2024/04/11 04:45:25 [DEBUG] GET https://global.api.konghq.tech/v2/users/me
2024/04/11 04:45:25 [DEBUG] GET https://global.api.konghq.tech/v2/users/515d12f2-aab2-42b3-a093-6ad793c0c7ab/assigned-roles?filter%5Bentity_type_name%5D=Runtime+Groups …
```
=> tests: add logs to konnect license test

README.md
As in KGO v1.2.0 we made managed gateways GA, we should remove the alpha warning from KIC readme. Also updates the link to the KGO + KIC guide to always point to the latest.
=> docs: remove KGO alpha note from readme

CHANGELOG.md, examples/gateway-httproute-rewrite-path-full.yaml, internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go, internal/dataplane/translator/subtranslator/httproute.go, internal/dataplane/translator/subtranslator/httproute_test.go, internal/gatewayapi/aliases.go, test/integration/isolated/exmples_httproute_rewrite_test.go, test/internal/testlabels/labels.go
This PR introduces support for `FullPathRewrite` for [`URLRewrite`](https://github.com/kubernetes-sigs/gateway-api/blob/35fe25d1384a41c9b89dd5af7ae3214c431f008c/apis/v1/httproute_types.go#L735-L740) filter for HTTPRoutes.
Separate PRs will introduce remaining features of `URLRewrite`.
Part of #3686.
=> feat(gateway-api): support ReplaceFullPath for URLRewrite

Makefile
Remove `-s -w` ldflags from debug build which:
```
-s
Omit the symbol table and debug information.
...
-w
Omit the DWARF symbol table.
```
Causing the debugger to fail to attach.
=> chore: remove -s -w ldflags from debug build

.github/workflows/_conformance_tests.yaml, .github/workflows/_e2e_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_kongintegration_tests.yaml, .github/workflows/_linters.yaml, .github/workflows/_performance_tests.yaml, .github/workflows/_unit_tests.yaml, Makefile
Add more verbose logs for `mise` calls to make debugging easier.
=> chore: add mise logs in CI

internal/manager/config.go, internal/util/test/controller_manager.go, test/conformance/suite_test.go, test/e2e/istio_test.go, test/integration/isolated/suite_test.go, test/integration/suite_test.go
This should help in recent errors on CI
```
ERROR: Problems with Controller Manager: failed waiting for all runnables to end within grace period of 30s: context deadline exceeded
```
This was already fixed similarly in envtest suite in 
https://github.com/Kong/kubernetes-ingress-controller/blob/459e10ba801bcded656cdfdfbdc1b2c4788de56f/test/envtest/run.go#L71-L74
This time around let's not disable graceful shutdown completely but instead, let's just disable the timeout.
=> tests: disable controller manager graceful shutdown timeout

test/helpers/ports.go, test/helpers/ports_test.go
Fix free ports assignment by using a lock between obtaining the free port and placing it in the local lookup cache to prevent a race where 2 tests running in parallel would possible get the  same port and not see it yet being used in the cache.
Attempt at fixing #5869
=> tests: fix free ports assignment

internal/store/store_test.go
Remove flaky benchmark case for listing 100 HTTPRoutes: 
https://github.com/Kong/kubernetes-ingress-controller/commit/09abf4a87f27a2ed733bebf8c0b7840476b6ee31#commitcomment-141065828
https://kong.github.io/kubernetes-ingress-controller/dev/bench/
=> chore: remove flaky HTTPRoute list benchmark

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, internal/admission/validator.go, internal/admission/validator_test.go, pkg/apis/configuration/v1/kongconsumer_types.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml, test/envtest/crds_envtest_test.go
I propose an alternative to the admission [webhook-based approach](https://github.com/Kong/kubernetes-ingress-controller/pull/5787) that annotates `credentials` and `consumerGroup` with `+listType=set` which enforces the uniqueness of the elements in the list.
I verified the following scenario to ensure that migrating from the old CRD manifests to the new ones (with `x-kubernetes-list-type: set`) is allowed:
1. Create a fresh cluster, and apply old CRD manifests.
2. Create a couple of KongConsumers (both with duplicate and non-duplicate credentials/consumerGroups).
3. Apply the new CRD manifests (with `x-kubernetes-list-type: set`).
4. Ensure it works as expected:
- Fetching the old KongConsumers works.
- New KongConsumers violating the constraints …
=> feat: enforce KongConsumer's credentials and consumerGroups uniqueness

Dockerfile, Dockerfile.debug, go.mod, third_party/go.mod, third_party/skaffold/go.mod
Upgrade golang version to 1.21.9 in `release/3.1.x` branch. 
The intention of this PR is to update ALL appearances of golang version to `1.21` to use the latest patch of golang 1.21. But when I run `go mod tidy` locally, it added `toolchain go1.22.2` which is my local golang version. (Is it affected by local config of golang?)
So I updated it to 1.21.9.
=> backport: upgrade golang to latest patch of go 1.21 in release/3.1.x

go.mod, third_party/go.mod
Go 1.22 requires the exact version to be specified in `go <version>` directive in go.mod. If only a `<major>.<minor>` is specified, it gives following output:
```terminal
$ go mod tidy
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
```
See: https://github.com/golang/go/issues/65568
=> chore: use specific version of go in go.mods

CHANGELOG.md, internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go
Do not constrain group/kind of `parentRef`s of `HTTPRoute` to be empty or `gateway.network.k8s.io/Gateway` to allow HTTPRoutes to use other resources (like using a service in kuma) as their parents. 
fixes #5912 
=> fix: remove check of parentRef group and kind in validating HTTPRoutes

internal/util/tls/tls_cert.go
Replace docstring that is leftover from review, make helper `ValueFromVariableOrFile` private because it's not used outside this package, and simplify its code.
=> chore: improve docstring for ExtractClientCertificates and other tweaks

Dockerfile, Dockerfile.debug, go.mod, third_party/go.mod
Bump golang version to 1.21.9 in release 2.12.x. 
Part of #5900
=> backport: bump golang to 1.21.9 in 2.12.x

CHANGELOG.md, internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go
(cherry picked from commit 14e51abf9038e085a5dfec2f06845b4fcf80965d)
=> [backport release/3.1.x] fix: remove check of parentRef group and kind in validating HTTPRoutes

CHANGELOG.md
Prepare for release 3.1.4, update CHANGELOG.
Part of #5911 
=> Prepare release/3.1.4

CHANGELOG.md, config/default/kustomization.yaml, config/webhook/additional_secret_hooks.yaml, config/webhook/kustomization.yaml, config/webhook/manifests.yaml, internal/admission/handler.go, internal/admission/handler_test.go, internal/admission/validation/consumers/credentials/validation.go, internal/admission/validation/consumers/credentials/validation_test.go, internal/admission/validation/consumers/credentials/vars.go, internal/admission/validator.go, internal/admission/validator_test.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/labels/labels.go, internal/util/credential.go, internal/util/credential_test.go, internal/util/types_test.go, test/envtest/admission_webhook.go, test/envtest/admission_webhook_envtest_test.go, test/envtest/kongstate_consumer_failures_test.go, test/integration/consumer_group_test.go, test/integration/consumer_test.go
Remove support for the kongCredType field in credential Secrets. Only honor the konghq.com/credential label.
Add a konghq.com/plugin-config label. This label indicates that a Secret contains plugin configuration and should be validated against its referrers when updated.
Add objectSelectors to the Secret blocks in the admission webhook definition. Admission will skip any Secrets without a label indicating they should be used by KIC.
Fix #4853 
Found during this that we were kinda abusing the blanket Secret ingest for updates to plugin config also. Those Secrets did not have any label to filter them in.
Per chat discussion the approach I've taken here is to leave the existing blanket …
=> feat(creds) remove kongCredType field support

CHANGELOG.md
Reverse changelog backport. See https://github.com/Kong/kubernetes-ingress-controller/pull/5920#issuecomment-2079052081
=> chore(docs) add 3.1.4 changelog to main

.github/workflows/validate_kong_image_trigger_via_label.yaml
Add `GH_TOKEN` env in step `check-and-remove-issue-label` as it is required for `gh` command.
=> fix: add GH_TOKEN in editing issue labels

internal/dataplane/kong_client.go
Change log level of Konnect sync backoff to `Info` to avoid "error flood" in logs.
fixes #5967 
=> chore: switch log level for Konnect sync backoff to info

CHANGELOG.md, internal/admission/handler.go, internal/admission/handler_test.go, internal/admission/server_test.go, internal/admission/validation/ingress/ingress.go, internal/admission/validation/ingress/ingress_test.go, internal/admission/validation/kongplugin/kongplugin.go, internal/admission/validator.go, internal/admission/validator_test.go, internal/util/builder/ingress.go
[KongPlugins can be attached to](https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/custom-resources/#kongplugin)
- `KongConsumer`
- `Ingress`
- `Service`
Introduce validation that prevents attaching many plugins of the same to an `Ingress`, `Service`, or `KongConsumer`, because it leads to invalid configuration for Kong Gateway. 
The validation is only possible when plugins have been already configured (accepted by K8s), for plugins mentioned in annotations but not yet configured it assumes that they're valid.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/5602
=> feat(validation): reject Ingress, Service and KongConsumer with many plugins of the same type attached

CHANGELOG.md, internal/dataplane/translator/subtranslator/httproute.go, internal/dataplane/translator/subtranslator/httproute_test.go, internal/dataplane/translator/testdata/golden/httproute-url-rewrite-path-prefix/expression-routes-on_golden.yaml, internal/dataplane/translator/testdata/golden/httproute-url-rewrite-path-prefix/expression-routes-on_settings.yaml, test/conformance/gateway_conformance_test.go, test/integration/isolated/examples_httproute_rewrite_test.go
Extends HTTPRoute's `URLRewrite` filter with path type `ReplacePrefixMatch` support to the `expressions` router. Adds `SupportHTTPRoutePathRewrite` feature to the Gateway API conformance tests for `expressions` router.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3686.
=> feat: implement rewrite path prefix filter for HTTPRoute in expressions router mode

CHANGELOG.md, internal/annotations/annotations.go, internal/annotations/annotations_test.go
This PR resolves real-world problems reported by the user that `konghq.com/headers.*` doesn't allow to specify headers that contain `,` which is permitted in header values, but can't be used because KIC uses it as a separator. 
HTTP specification is very permissive in terms of what is allowed as header value
https://datatracker.ietf.org/doc/html/rfc9110#name-field-values
> Field values are usually constrained to the range of US-ASCII characters [[USASCII](https://datatracker.ietf.org/doc/html/rfc9110#USASCII)].
see also [Cloudflare docs](https://developers.cloudflare.com/rules/transform/request-header-modification/reference/header-format).
Hence coming up with an escaping pattern for commas is hard and won't be easy to use/interpret by a user. So …
=> feat: introduce konghq.com/headers-separator annotation and make parsing more robust

CHANGELOG.md, internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go, internal/admission/validation/ingress/ingress_test.go, internal/admission/validator.go, internal/admission/validator_test.go, internal/manager/setup_test.go
Uses mechanism introduced in 
- https://github.com/Kong/kubernetes-ingress-controller/pull/5972
to prevent attaching many plugins of the same type to a `HTTPRoute` or `KongConsumerGroup`, because it leads to invalid configuration for Kong Gateway. Now for all entities that support `konghq.com/plugins` annotation uniqueness of plugins is validated. 
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/5749
=> feat(validation): reject HTTPRoute and KongConsumerGroup with many plugins of the same type attached

CHANGELOG.md, internal/dataplane/kong_client.go, internal/dataplane/kongstate/consumer.go, internal/dataplane/kongstate/consumer_test.go, internal/dataplane/kongstate/credentials.go, internal/dataplane/kongstate/credentials_test.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/kongstate/plugin_test.go, internal/util/uuid.go, test/mocks/uuid.go
Change the static redacted pretend Vault string to a function that generates a random pretend Vault string.
This avoids collisions for certain types of values when go-database-reconciler builds configuration. It uses an in-memory database that looks up Kong entities by unique fields. If these fields aren't actually unique, go-database-reconciler will detect a conflict and abort.
Reported by @mheap in chat.
Manual smoke testing: creating a key-auth with `{vault://04a84f95-91f0-4caa-87d1-91a2caa2a6ca}` as the `key` value to validate that UUIDs are valid Vault keys.
Originally did this for all redacted strings, but turns out that the random stuff needs accounting for in tests in less …
=> fix(konnect) avoid collisions when redacting

CHANGELOG.md, internal/dataplane/translator/subtranslator/httproute.go, internal/dataplane/translator/subtranslator/httproute_atc_test.go, internal/dataplane/translator/subtranslator/httproute_test.go, internal/dataplane/translator/translate_httproute_test.go, test/conformance/gateway_conformance_test.go
Extends support for `URLRewrite` filter with the `Hostname` field. Enables Gateway API conformance tests covering this feature.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/3685.
=> feat(httproute): handle URLRewrite filter's hostname rewrite

.github/workflows/_linters.yaml, CHANGELOG.md, docs/cli-arguments.md, go.mod, go.sum, internal/controllers/gateway/grpcroute_controller.go, internal/dataplane/kongstate/upstream.go, internal/dataplane/translator/translate_grpcroute_test.go, internal/gatewayapi/aliases.go, internal/gatewayapi/typemeta.go, internal/manager/config.go, internal/manager/controllerdef.go, internal/store/fake_store.go, test/conformance/gateway_conformance_test.go, test/conformance/suite_test.go, test/consts/zz_generated_gateway.go, test/envtest/telemetry_test.go, test/integration/isolated/grpc_test.go
* Bump GWAPI to v1.1
* Add support for GRPCRoute v1
fixes: https://github.com/Kong/kubernetes-ingress-controller/issues/5960
=> feat: bump GWAPI v1.1 and support for GRPCRoute v1

Makefile
Fix the `mise install` commands failure in CIs. The errors in CIs shows that 
```
asdf-staticcheck: Could not download https://github.com/dominikh/go-tools/archive/refs/tags/vv0.4.7.tar.gz
```
So I removed the leading `v` command of `$(MISE) install` commands.
=> chore: fix mise install in Makefile

internal/store/cache_stores_snapshot.go, internal/store/cache_stores_snapshot_test.go
PR introduces a new method `TakeSnapshotIfChanged` with a benchmark that allows making snapshots only when underlying `cacheStores` is changed. It yields significant performance improvements for big stores in terms of time and number of allocations. Since it's part of a broader initiative of generating partial/fallback configuration it may change to a certain degree in the foreseeable future. This PR is a starting point
Results
```log
BenchmarkCacheStores_TakeSnapshot
BenchmarkCacheStores_TakeSnapshot/Small_Without_Cache
BenchmarkCacheStores_TakeSnapshot/Small_Without_Cache-10         	   40017	     26269 ns/op	    7104 B/op	     163 allocs/op
BenchmarkCacheStores_TakeSnapshot/Big_Without_Cache
BenchmarkCacheStores_TakeSnapshot/Big_Without_Cache-10 …
```
=> feat: make a new snapshot of the store only when it's needed

.golangci.yaml
Get rid of 
```log
WARN [lintersdb] The linter named "megacheck" is deprecated. It has been split into: gosimple, staticcheck, unused.
```
by removing `megacheck` replacement as mentioned earlier has already been configured.
=> chore(ci): remove warning for deprecated megacheck linter

CHANGELOG.md, internal/dataplane/translator/translator.go, test/integration/ingress_test.go
Backport #5946 to `release/3.1.x`. This fixes a potential segfault.
Since the `targetWeightOrDefault` is moved to `traslator_upstreams.go` in `main`, the backporting requires to move the changes to the original file `translator.go`.
=> [Backport release/3.1.x] deduplicate nil-weight targets (#5946)

.github/workflows/_envtest_tests.yaml, CHANGELOG.md, config/webhook/manifests.yaml, go.mod, go.sum, internal/admission/adminapi_provider.go, internal/admission/errors.go, internal/admission/handler.go, internal/admission/server_test.go, internal/admission/validator.go, internal/admission/validator_test.go, internal/dataplane/kongstate/customentity.go, internal/dataplane/kongstate/customentity_test.go, test/envtest/admission_webhook_envtest_test.go, test/kongintegration/containers/kong.go
Fetch entity schema and validate `KongCustomEntity` against Kong gateway.
Added unit tests and envtest tests to verify the parsing of entity schema and validations.
fixes #5975
=> fetch Kong entity schema and validate KongCustomEntity resources

.github/test_dependencies.yaml
Reverts Kong/kubernetes-ingress-controller#6022. For temp fix of #6039 that KIC may not be compatible with istio 1.22, or some configuration required.
=> Revert "chore(deps): update istio/istioctl docker tag to v1.22.0"

internal/admission/validation/gateway/httproute.go, internal/admission/validation/gateway/httproute_test.go, internal/dataplane/fallback/graph_dependencies_kong.go
Fixes outdated TODO comments linking to already resolved issues:
- https://github.com/Kong/kubernetes-ingress-controller/issues/3686
- https://github.com/Kong/kubernetes-ingress-controller/issues/3685
- https://github.com/Kong/kubernetes-ingress-controller/issues/6026
Adds a unit test ensuring `filter.URLRewrite.Hostname` in HTTPRoute rule is allowed.
Makes https://github.com/Kong/kubernetes-ingress-controller/actions/runs/9122991555/job/25084686979 green.
=> chore: fix outdated TODO links

CHANGELOG.md, internal/dataplane/configfetcher/config_fetcher.go, internal/dataplane/configfetcher/kongrawstate.go, internal/dataplane/configfetcher/kongrawstate_test.go, internal/dataplane/translator/translator.go, internal/license/agent.go, internal/manager/run.go, internal/manager/setup.go
Include licenses (and Vaults) when sending fallback configuration.
Fix #5447 
License handling was left as an open question in the original criteria. I chose to always populate the current license from the license getter, which will (sort of) modify the last good config. I've left TODO comments explaining the rationale for doing that over attempting to pull the license from the original config struct.
Will need to either strip (or at least shorten) those if reviewer agrees with the rationale or change stuff if we actually want to use another approach.
=> feat(dataplane) include licenses with fallback

CHANGELOG.md, internal/dataplane/fallback/cache_to_graph.go, internal/dataplane/fallback/cache_to_graph_test.go, internal/dataplane/fallback/fallback.go, internal/dataplane/fallback/fallback_test.go, internal/dataplane/fallback/graph.go, internal/dataplane/fallback/graph_test.go, internal/dataplane/fallback/helpers_test.go
- Implements a fallback cache `Generator` with the `GenerateExcludingAffected` method. It depends on a `CacheGraphProvider` implemented by `DefaultCacheGraphProvider` (formerly `NewConfigGraphFromCacheStores` function). It's tested in isolation in the `TestGenerator_ GenerateExcludingAffected` test.
- Implements `ConfigGraph.SubgraphObjects` capable of finding all objects depending on a broken source object and tests that in `TestConfigGraph_SubgraphObjects`
- Moves `NewConfigGraphFromCacheStores` to `cache_to_graph.go` and refactors it into a struct implementing `CacheGraphProvider` interface (also moves its tests to `cache_to_graph_test.go` with no modifications). 
Closes …
=> feat: generate fallback cache snapshot excluding affected objects

internal/dataplane/fallback/graph_dependencies.go, internal/dataplane/fallback/graph_dependencies_common.go, internal/dataplane/fallback/graph_dependencies_kong.go, internal/dataplane/fallback/graph_dependencies_kong_test.go, internal/dataplane/fallback/graph_dependencies_service.go, internal/dataplane/fallback/graph_dependencies_service_test.go
It implements `ResolveDependencies` cases for
- `corev1.Service`
- `kongv1.KongConsumer`
- `kongv1beta1.KongConsumerGroup`
they used to be treated by mistake as objects without any dependencies.
Furthermore, it implements the correct behavior of plugin resolution in cases when `KongPlugin` and `KongClusterPlugin` with the same names exist in the cluster - only `KongPlugin` is considered. 
=> feat: resolve dependencies for Service, KongConsumer and KongConsumerGroup, improve for plugins

internal/dataplane/fallback/graph_dependencies_common.go, internal/dataplane/fallback/graph_dependencies_kong.go, internal/dataplane/fallback/graph_dependencies_kong_test.go, internal/dataplane/fallback/helpers_test.go
It implements `ResolveDependencies` cases for
- `kongv1.KongPlugin`
- `kongv1.KongClusterPlugin`
=> feat: resolve dependencies for KongPlugin and KongClusterPlugin

internal/annotations/annotations.go, internal/dataplane/fallback/graph_dependencies_common.go, internal/dataplane/fallback/graph_dependencies_kong.go, internal/dataplane/fallback/graph_dependencies_kong_test.go, internal/dataplane/fallback/graph_dependencies_service.go, internal/dataplane/fallback/graph_dependencies_service_test.go, internal/dataplane/fallback/helpers_test.go
It implements `ResolveDependencies` cases for `incubatorv1alpha1.KongServiceFacade`. Moreover, it improves resolving dependencies for `corev1.Service` - adds `kongv1beta1.KongUpstreamPolicy`, because [it can be attached to a Service](https://docs.konghq.com/kubernetes-ingress-controller/latest/reference/custom-resources/#kongupstreampolicy). 
=> feat: resolve dependencies for KongServiceFacade and improve for Service

internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/backoff_strategy.go, internal/dataplane/sendconfig/backoff_strategy_test.go, internal/dataplane/sendconfig/dbmode.go, internal/dataplane/sendconfig/errors.go, internal/dataplane/sendconfig/errors_test.go, internal/dataplane/sendconfig/inmemory.go, internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/sendconfig/sendconfig.go, internal/dataplane/sendconfig/strategy.go, test/kongintegration/inmemory_update_strategy_test.go, test/kongintegration/kongupstreampolicy_test.go, test/kongintegration/translator_golden_tests_outputs_test.go
Instead of returning multiple error-related values from `UpdateStrategy.Update`, return specific errors that downstream can cast if needed (`UpdateError`, `ResponseParsingError`).
Refactor needed for https://github.com/Kong/kubernetes-ingress-controller/issues/5931.
=> chore: simplify UpdateStrategy.Update signature

internal/dataplane/fallback/graph_dependencies_kong.go, internal/dataplane/fallback/graph_dependencies_kong_test.go, internal/dataplane/fallback/helpers_test.go
It implements `ResolveDependencies` cases for
- `kongv1.UDPIngress`
- `kongv1.TCPIngress`
There will be one more PR with small refactor to close this issue.
=> feat: resolve dependencies for UDPIngress and TCPIngress

.github/workflows/_integration_tests.yaml, CHANGELOG.md, config/variants/multi-gw/debug/manager_debug.yaml, internal/dataplane/fallback/fallback.go, internal/dataplane/fallback/fallback_test.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/manager/run.go
Makes `KongClient` try to recover from regular config update failures by generating a fallback configuration, excluding affected objects reported back by gateways.
Enables integration tests with the `FallbackConfiguration` feature gate enabled to ensure no existing scenarios are broken.
Adds only unit tests covering `KongClient`. More integration/E2E test coverage is expected to be added under https://github.com/Kong/kubernetes-ingress-controller/issues/5933.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/5931.
=> feat: generate and push fallback config on update failure

CHANGELOG.md, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go
Reverses the dataplane logic for the sensitive config check. If diagnostic dumps are set to include sensitive data, it will use the original target content. If they are set to not include sensitive data, they will use a redacted content.
Some refactor made `--dump-sensitive-config` backwards. I didn't bother digging into PR history to explain how. I noticed this while trying to use it.
There's a more complicated issue where you'll still get redacted config (by default) if you're using Konnect, whereas you probably don't want that for the diagnostic--you care what was sent to the gateway instances, not the read-only GUI copy. Lazily we can solve this by just always generating both, …
=> fix(diag) correct redaction toggle

CHANGELOG.md, internal/controllers/gateway/grpcroute_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_parent_status.go, internal/controllers/gateway/route_predicates.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/gatewayapi/aliases.go, test/envtest/httproute_controller_test.go, test/internal/helpers/gatewayapi.go
Fixes an issue when there's more than 1 KIC (or there are other controllers that reconcile ~HTTPRoutes~ Gateway API *Routes) and KIC then tries to clear status of ~`HTTPRoute`~  *Routes that it should not touch (anymore).
Fixes #6067
=> fix(gwapi): only clear status of Gateway API *Routes reconciled by KIC's gateway(s)

internal/dataplane/fallback/fallback.go, internal/dataplane/fallback/fallback_test.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/store/cache_stores_snapshot.go
Replaces usage of `TakeSnapshot` with `TakeSnapshotIfChanged` that was introduced in 
- https://github.com/Kong/kubernetes-ingress-controller/pull/6017
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/6080
=> feat: use TakeSnapshotIfChanged to avoid taking redundant snapshot

CHANGELOG.md, FEATURE_GATES.md, docs/cli-arguments.md, internal/dataplane/fallback/fallback.go, internal/dataplane/fallback/fallback_test.go, internal/dataplane/fallback/graph.go, internal/dataplane/fallback/graph_test.go, internal/dataplane/fallback/helpers_test.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/kong.go, internal/manager/config.go, internal/store/cache_stores_snapshot.go
Adds the `--use-last-valid-config-for-fallback` flag that changes the default behavior of `FallbackConfiguration` feature by backfilling broken objects using the last valid config cache instead of only excluding those.
Solves https://github.com/Kong/kubernetes-ingress-controller/issues/6096.
=> feat: backfill broken objects from last valid cache state

CHANGELOG.md, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, test/mocks/events_recorder.go
Starts emitting new Kubernetes events related to the `FallbackConfiguration` feature:
- `FallbackKongConfigurationSucceeded` - emitted on successful fallback configuration push (attached to Pod)
- `FallbackKongConfigurationTranslationFailed` - emitted when a fallback cache causes translation failures in the translator (attached to causing objects)
- `FallbackKongConfigurationApplyFailed` - emitted when a fallback configuration is rejected by Kong (attached to Pod and broken objects if any)
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/6081.
=> feat: emit fallback configuration events

go.mod, go.sum
Bump sigs.k8s.io/e2e-framework to [v0.4.0](https://github.com/kubernetes-sigs/e2e-framework/releases/tag/v0.4.0). Dependabot didn't want to bump it because it was set to a custom SHA.
=> deps: bump sigs.k8s.io/e2e-framework to v0.4.0

test/conformance/gateway_conformance_test.go
Enable `SupportHTTPRouteHostRewrite` in Gateway API conformance suite.
Closes #3685
=> conformance: enable HTTPRouteHostRewrite

CHANGELOG.md, internal/dataplane/kong_client.go, internal/dataplane/sendconfig/sendconfig.go, internal/metrics/prometheus.go, internal/metrics/prometheus_test.go, test/envtest/metrics_envtest_test.go, test/mocks/admin_api_handler.go
Adds new Prometheus metrics covering `FallbackConfiguration` feature:
- `ingress_controller_fallback_translation_count`
- `ingress_controller_fallback_translation_broken_resource_count`
- `ingress_controller_fallback_configuration_push_count`
- `ingress_controller_fallback_configuration_push_last`
- `ingress_controller_fallback_configuration_push_duration_milliseconds`
- `ingress_controller_fallback_configuration_push_broken_resource_count`
- `ingress_controller_fallback_cache_generating_duration_milliseconds`
- `ingress_controller_processed_config_snapshot_cache_hit`
- `ingress_controller_processed_config_snapshot_cache_miss`
Metrics reported after generating fallback configuration and pushing it successfully:
```text …
```
=> feat: add metrics for FallbackConfiguration

examples/gateway-httproute-broken-plugin-fallback.yaml, test/integration/examples_test.go, test/integration/isolated/examples_httproute_test.go, test/integration/isolated/suite_test.go
That PR simplifies and converts `TestHTTPRouteExample` to an isolated one and introduces a new test `TestHTTPRouteWithBrokenPluginFallback` that tests fallback configuration 
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/6077
=> chore(tests): introduce isolated TestHTTPRouteWithBrokenPluginFallback

Makefile, config/components/konnect/manager.yaml, config/variants/konnect/base/manager.yaml, config/variants/konnect/debug/manager_debug.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml
Reverts https://github.com/Kong/kubernetes-ingress-controller/pull/4994.
The support for expressions router in Konnect is already GA: https://docs.konghq.com/konnect/updates/#may-2024
Closes #4995
=> tests: use expressions router by default in test manifests

test/envtest/metrics_envtest_test.go
Skip until https://github.com/Kong/kubernetes-ingress-controller/issues/6125 is resolved.
=> tests: skip flaky `TestMetricsAreServed/with_push_error_and_FallbackConfiguration_enabled`

CHANGELOG.md, internal/controllers/configuration/kongadminapi_controller.go
This PR aims to fix an issue where non leader replicas would not get an up to date state of admin API endpoints and hence by an extension the admission webhook - which is started on each replica - would query the non existing admin API endpoints and thus cause failures.
Fixes #6008
=> fix: reconcile admin API endpoints on all replicas

CHANGELOG.md, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/kongstate/plugin.go, internal/dataplane/kongstate/plugin_test.go, internal/dataplane/kongstate/types.go
This reverts commit 2d615e3df5956d6ebd4e0b0137ff6dffc20294c1.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5692.
=> fix: do not sanitize plugins' config

config/base/kong-ingress-dbless.yaml, config/components/manager_dev_patch/kustomization.yaml, config/components/manager_dev_patch/manager.yaml, config/image/enterprise/kustomization.yaml, config/image/oss/kustomization.yaml, config/variants/multi-gw/dev/kustomization.yaml, renovate.json, skaffold.yaml, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml
This PR adds multi gw enterprise skaffold config which deploys `kong/kong-gateway` instead of `kong`
```
make run.skaffold SKAFFOLD_RUN_PROFILE=multi_gw_enterprise
```
It also introduced the changes so that kustomize images are updated by renovate. Config dump port (10256) is also exposed for ease of use.
=> chore: add skaffold config for multi gw enterprise

internal/dataplane/deckgen/generate_test.go
This PR adds a regression test which will guard the usage of go-kong versions which would incorrectly fill in the plugin defaults, specifically not fill in the field with defaults.
When this test is run with go-kong 0.52.0 (which is what KIC 3.1 uses) then it fails.
After merging to `main` this will be backported to `release/3.1.x` with bump of go-kong to 0.55.0.
Schema for Otel plugin was taken from Gateway 3.7 and converted using https://rodrigo-brito.github.io/json-to-go-map/ to a go struct.
=> tests: add UT for deckgen.fillPlugin

internal/util/relations.go, internal/util/relations_test.go
Optimizes `GetCombinations` + adds a testcase for consumer groups
old e6de62fc1
```
goos: darwin
goarch: arm64
pkg: github.com/kong/kubernetes-ingress-controller/v3/internal/util
BenchmarkGetCombinations/consumer_groups-10              3546044               346.5 ns/op           960 B/op          4 allocs/op
BenchmarkGetCombinations/consumer_groups-10              3691382               338.9 ns/op           960 B/op          4 allocs/op
BenchmarkGetCombinations/consumer_groups-10              3682710               366.5 ns/op           960 B/op          4 allocs/op
BenchmarkGetCombinations/consumer_groups-10              3747121               342.3 ns/op           960 B/op          4 allocs/op
BenchmarkGetCombinations/consumer_groups-10 …
```
=> perf: optimize `GetCombinations`

internal/dataplane/kong_client_golden_test.go, internal/dataplane/testdata/golden/fallback-config-ingress/default_golden.yaml, internal/dataplane/testdata/golden/fallback-config-ingress/in.yaml, internal/dataplane/testdata/golden/fallback-config-service/default_golden.yaml, internal/dataplane/testdata/golden/fallback-config-service/in.yaml
Adjusts golden tests to enable returning broken objects in `POST /config` Admin API responses and adds first two test cases for `Ingress` and `Service`.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/6076.
=> chore(tests): add fallback config golden tests for Ingress and Service

config/image/enterprise/kustomization.yaml, config/image/oss/kustomization.yaml, renovate.json
Validated using `npx --yes --package renovate -- renovate-config-validator`
Fixes #6148 
particularly user-facing) changes introduced by this PR
=> chore: fix renovate config

internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/kongstate/plugin.go, internal/dataplane/kongstate/plugin_test.go, internal/dataplane/kongstate/types.go
Manual backport of https://github.com/Kong/kubernetes-ingress-controller/pull/6138
=> [Backport release/3.1.x] fix: do not sanitize plugins' config (#6138)

internal/dataplane/testdata/golden/fallback-config-kong-cluster-plugin/default_golden.yaml, internal/dataplane/testdata/golden/fallback-config-kong-cluster-plugin/in.yaml, internal/dataplane/testdata/golden/fallback-config-kong-plugin/default_golden.yaml, internal/dataplane/testdata/golden/fallback-config-kong-plugin/in.yaml
Adds `KongClient` golden tests verifying fallback configuration behavior for broken:
- `KongPlugin`
- `KongClusterPlugin`
Test cases include all possible dependants of those and ensure they're excluded along with the broken objects.
Part of #6076.
=> chore(tests): add fallback golden tests for plugins

internal/dataplane/testdata/golden/fallback-config-gateway-api/default_golden.yaml, internal/dataplane/testdata/golden/fallback-config-gateway-api/in.yaml
Adds `KongClient` golden tests verifying fallback configuration behavior for broken:
- `HTTPRoute`
- `TCPRoute`
- `UDPRoute`
- `TLSRoute`
- `GRPCRoute`
Test cases include all possible dependants of those and ensure they're excluded along with the broken objects.
Part of #6076.
=> chore(tests): add fallback golden tests for gateway api

internal/manager/featuregates/feature_gates.go, test/integration/isolated/examples_httproute_test.go, test/internal/helpers/controller_manager_flag_opts.go
It introduces new isolated integration test `TestHTTPRouteUseLastValidConfigWithBrokenPluginFallback` that covers KIC which is run with feature gate `FallbackConfiguration=true` and flag `--use-last-valid-config-for-fallback` (there is already test that tests behavior only for feature flag). 
Additional to https://github.com/Kong/kubernetes-ingress-controller/issues/6077
=> chore(tests): introduce isolated TestHTTPRouteUseLastValidConfigWithBrokenPluginFallback

internal/dataplane/kong_client_golden_test.go, internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/testdata/golden/fallback-config-kong/default_golden.yaml, internal/dataplane/testdata/golden/fallback-config-kong/in.yaml, internal/dataplane/testdata/golden/fallback-config-kong/service-facade-on_golden.yaml, internal/dataplane/testdata/golden/fallback-config-kong/service-facade-on_settings.yaml, internal/store/cache_stores.go, internal/store/store.go
Adds `KongClient` golden tests verifying fallback configuration behavior for broken:
- `KongConsumer`
- `KongConsumerGroup`
- `TCPIngress`
- `UDPIngress`
- `KongServiceFacade`
- `KongVault`
Test cases include all possible dependants of those and ensure they're excluded along with the broken objects.
Part of #6076.
=> chore(tests): add fallback golden tests for kong resources

CHANGELOG.md
Fixes changelog for 3.1.5 which was [pushed to `release/3.1.x` branch](https://github.com/Kong/kubernetes-ingress-controller/pull/6049) but not to `main`.
=> chore: fix changelog for 3.1.5

Makefile
Get rid of 
```
ld: warning: '/private/var/folders/0m/_63w01516tgf3cftmp9h7ylm0000gn/T/go-link-757981869/000025.o' has malformed LC_DYSYMTAB, expected 98 undefined symbols to start at index 1626, found 95 undefined symbols starting at index 1626
```
warnings.
=> chore: fix golang warnings regarding linker

internal/dataplane/testdata/golden/fallback-config-ingress-class/default_golden.yaml, internal/dataplane/testdata/golden/fallback-config-ingress-class/in.yaml, internal/dataplane/testdata/golden/fallback-config-kong-upstream-policy/default_golden.yaml, internal/dataplane/testdata/golden/fallback-config-kong-upstream-policy/in.yaml, internal/dataplane/testdata/golden/fallback-config-kong-upstream-policy/service-facade-on_golden.yaml, internal/dataplane/testdata/golden/fallback-config-kong-upstream-policy/service-facade-on_settings.yaml, internal/dataplane/testdata/golden/fallback-config-secret/default_golden.yaml, internal/dataplane/testdata/golden/fallback-config-secret/in.yaml
Adds `KongClient` golden tests verifying fallback configuration behavior for broken:
- `IngressClass`
- `KongUpstreamPolicy`
- `Secret`
Test cases include all possible dependants of those and ensure they're excluded along with the broken objects.
Part of #6076.
=> chore(tests): add fallback golden tests for remaining resources

docs/cli-arguments.md, internal/manager/config.go, internal/manager/config_validation.go, internal/manager/config_validation_test.go
Adds validation for the `--use-last-valid-config-for-fallback` flag that is only relevant when the `FallbackConfiguration` feature gate is turned on.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/5854.
=> feat: validate --use-last-valid-config-for-fallback flag

scripts/apidocs-gen/post-process-for-konghq.sh
Fixing what fails: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/9397243008/job/25880039885
```
sed: -e expression #1, char 123: invalid reference \1 on `s' command's RHS
```
=> chore: fix docs post processing script

internal/dataplane/translator/subtranslator/grpcroute.go, internal/dataplane/translator/subtranslator/grpcroute_atc_test.go, internal/dataplane/translator/subtranslator/grpcroute_test.go, internal/dataplane/translator/translate_grpcroute.go, test/conformance/gateway_conformance_test.go
There is[ a test case ](https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/grpcroute-listener-hostname-matching.yaml)in the conformance test of GWAPI where hostname is not specified in GRPCRoute, but it is specified in Gateway. Therefore, when routing requests, the configuration for hostname needs to be obtained from Gateway and routes need to be generated accordingly so that request proxying can proceed normally.
fixes:  https://github.com/Kong/kubernetes-ingress-controller/issues/6136
This can be seen as a fix to the existing logic, or it can be seen as a feature enhancement. However, there won't be too much of a noticeable difference for users, so I didn't …
=> fix: handing GRPCRoute hostname from Gateway

internal/dataplane/fallback/fallback.go, internal/dataplane/fallback/fallback_test.go, internal/manager/run.go, test/integration/isolated/examples_httproute_test.go, test/internal/helpers/http.go
Changes the backfilling algorithm to attempt to backfill all affected (broken + directly and indirectly affected) objects from the last valid state instead of only the broken ones (the ones reported by Gateway).
Also 
- Passes the `UseLastValidConfigForFallback` flag value to `sendconfig.Config` (I could swear I tested that locally E2E and it was working 🤔) 
- Fixes the integration test that incorrectly assumed that headers that we pass to `EventuallyGETPath` are the expected response headers (no, they're not - these are request headers 🤦). It was passing, but wasn't really tested what it should test.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/5854.
=> fix(fallback): backfill all affected objects, not only broken

test/conformance/gateway_conformance_test.go
Skip `GRPCExactMethodMatching` which is flaky.
#6144 will reenable that and `GRPCRouteHeaderMatching` when the culprit is found and fixed.
=> chore: skip GRPCExactMethodMatching

internal/dataplane/fallback/fallback.go, internal/dataplane/fallback/fallback_test.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go
We should account for the situation where no last valid cache was preserved and avoid nil pointer dereferences.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/5854.
=> fix(fallback): guard for nil last valid cache

internal/dataplane/fallback/graph_dependencies_kong.go, internal/dataplane/fallback/graph_dependencies_kong_test.go
We missed this dependency resolver.
=> fix(fallback): resolve KongConsumer dependency on credentials

config/dev/manager_dev.yaml, config/variants/konnect/debug/manager_debug.yaml, config/variants/multi-gw-postgres/dev/kustomization.yaml, config/variants/multi-gw/debug/manager_debug.yaml, test/consts/feature_gates.go
Use feature flags in tests and dev manifests.
Also move from args to env since that's the recommended way to configure KIC.
=> chore: use feature flags in dev manifests

.tools_versions.yaml
https://github.com/kubernetes/code-generator doesn't publish releases so use [`github-tags` datasource for renovate instead of `github-releases`](https://docs.renovatebot.com/modules/datasource/github-tags/).
=> chore: fix renovate annotation for kubernetes/code-generator

config/image/enterprise/kustomization.yaml, config/image/oss/kustomization.yaml, renovate.json
Fix renovate config which was causing the following errors:
```
Dependency Lookup Warnings
Renovate failed to look up the following dependencies:
Failed to look up docker package https://charts.konghq.com/kong-gateway, Failed to look up docker package https://charts.konghq.com/kubernetes-ingress-controller, Failed to look up docker package kong/kong-gateway@regenerate, Failed to look up docker package kong@regenerate, Failed to look up docker package kong/kubernetes-ingress-controller@regenerate
Files affected:
config/image/enterprise/kustomization.yaml, config/image/oss/kustomization.yaml
```
This PR adds `packageName` annotation so that renovate properly looks up the dependencies by correct names.
=> Fix renovate config for kustomize images

internal/dataplane/fallback/cache_to_graph.go, internal/dataplane/fallback/cache_to_graph_test.go, internal/dataplane/fallback/fallback.go, internal/dataplane/fallback/fallback_meta.go, internal/dataplane/fallback/fallback_meta_test.go, internal/dataplane/fallback/fallback_test.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/diagnostics/api_types.go, internal/diagnostics/mapping.go, internal/diagnostics/server.go, internal/diagnostics/server_test.go, internal/diagnostics/types.go, test/integration/isolated/examples_httproute_test.go
- Extracts `GeneratedCacheMetadataCollector` for easier metadata collection (deduplication of excluded/backfilled objects was needed) and isolation
- Adds unit tests for the diagnostics server and fallback config generator
- Changes the response schema to include both excluded and backfilled objects at the same time (as that is a valid scenario: an object can be first excluded, then backfilled or not depending on the last valid cache state)
- Ensures we push diagnostics only if they're enabled (c.diagnostic.FallbackCacheMetadata is not nil)
- Extracts diagnostics server response schema types to a separate file for readability
- Extracts config dump and fallback diagnostics retrieval handling methods in the server
- Added `status` field to the response to clearly indicate whether the …
=> suggestion: fallback config diagnostics server

CHANGELOG.md
Rearrange the 3.2 changelog so that the highlight items are at the top. Adds the highlights section.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/6135.
=> chore: rearange changelog, add 3.2 highlights

CHANGELOG.md
Changelog entry. Artifact is out, this is just the docs.
Fix https://github.com/Kong/kubernetes-ingress-controller/issues/6153
=> chore(docs) add 3.1.6 changelog

.github/workflows/release.yaml
=> ci: add missing GOCACHE and GOPATH in release worflow

.github/ISSUE_TEMPLATE/release.yaml
As for the major/minor releases we're running the release workflow on main, we should branch off after the workflow is successfully run.
Follow up for #6135.
=> chore(docs): do not suggest creating release branch upfront

internal/dataplane/translator/subtranslator/httproute.go
Removes stale TODO comment. It's been implemented in https://github.com/Kong/kubernetes-ingress-controller/pull/5940.
=> chore: remove stale todo

.golangci.yaml, internal/admission/validation/ingress/ingress.go, internal/dataplane/address_finder.go, internal/dataplane/deckgen/deckgen.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/route.go, internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/translator/atc/matcher.go, internal/dataplane/translator/subtranslator/ingress.go, internal/dataplane/translator/translate_certs.go, internal/dataplane/translator/translate_kong_l4.go, internal/dataplane/translator/translate_secrets.go, internal/konnect/roles/client.go, internal/store/store.go, pkg/apis/configuration/v1/kongprotocol_types.go
Enable prealloc linter to easily spot places where we can preallocate.
=> chore: enable prealloc linter

.github/test_dependencies.yaml
Drops pinning Kong EE version in envtests to `3.4.3.4` as https://konghq.atlassian.net/browse/KAG-3699 has already been implemented and shipped.
=> chore: use latest kong in envtests

CHANGELOG.md, internal/dataplane/translator/translate_certs.go, internal/dataplane/translator/translate_certs_test.go, internal/dataplane/translator/translator.go, internal/dataplane/translator/translator_test.go
Re-fill the client certificate of Kong `Service`s after merging certificates to prevent service referring to non-exist client certificates.
fixes #6223 
=> fix(translator): Re-fill client certificates of services after merging certificate

CHANGELOG.md, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/dataplane/parser/translate_certs_test.go
(cherry picked from commit d410be40f1e93dbfd6a2c9c8421bbba0009ca378)
Backport the fix of #6223 (PR #6228) to KIC 2.12.x.
=> backport(2.12.x): fix: Re-fill client certificates of services after merging certificate (#6228)

config/variants/multi-gw/debug/kustomization.yaml
Include incubator CRDs in debug kustomize - it's required when the `KongServiceFacade` feature gate is on which is the case for the debug config. 
Fixes `make debug.skaffold` in a fresh cluster:
```text
Error: unable to create controller "*configuration.KongUpstreamPolicyReconciler": failed to index KongServiceFacades on annotation konghq.com/upstream-policy: no matches for kind "KongServiceFacade" in version "incubator.ingress-controller.konghq.com/v1alpha1"
```
=> chore: add incubator crds to debug skaffold config

go.mod, go.sum, internal/dataplane/sendconfig/inmemory.go, internal/dataplane/sendconfig/inmemory_test.go, test/kongintegration/kong_client_golden_tests_outputs_test.go
Don't rely on `ReloadDeclarativeRawConfig` to return the error body when `err != nil` as it might be considered a Go anti-pattern to use variables when an error is returned. Instead, rely on the `APIError` being returned in cases where the error body is available.
Follow up to https://github.com/Kong/kubernetes-ingress-controller/pull/6237#discussion_r1652781910.
=> chore: read admin api response body from error

hack/cleanup/konnect_runtime_groups.go, test/internal/helpers/konnect/control_plane.go
Workaround to unblock CI. https://github.com/Kong/kubernetes-ingress-controller/issues/6253 tracks fixing this.
=> chore: temporarily disable konnect roles cleanup

hack/cleanup/konnect_runtime_groups.go, test/internal/helpers/konnect/control_plane.go
Reverts Kong/kubernetes-ingress-controller#6254
Turns out it's still possible to create PATs for regular users, only the UI changed. 🤦
=> Revert "chore: temporarily disable konnect roles cleanup"

CHANGELOG.md
Prepares changelog for 3.2.1 release.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/6258.
=> chore: prepare release 3.2.1

CHANGELOG.md
Adds 3.2.1 changelog to main.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/6258.
=> chore: add v3.2.1 changelog

CHANGELOG.md, internal/adminapi/client.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_golden_test.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/sendconfig.go, internal/manager/run.go
We didn't take into account that when new gateways are discovered, we need to make sure they're all populated with the current configuration. We cannot skip config updates based only on the Kubernetes config cache not changing - we also need to ensure all the gateways are populated using it.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/6219.
=> fix(fallback): do not skip config update when gateways out of sync

CHANGELOG.md, internal/adminapi/client.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_golden_test.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/sendconfig.go, internal/manager/run.go
(cherry picked from commit 3b547a9feaba331763601cb87612480cf515f850)
=> backport: fix(fallback): do not skip config update when gateways out of sync (#6271)

.github/workflows/_conformance_tests.yaml, .github/workflows/_docker_build.yaml, .github/workflows/_e2e_tests.yaml, .github/workflows/_envtest_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_kongintegration_tests.yaml, .github/workflows/_linters.yaml, .github/workflows/_performance_tests.yaml, .github/workflows/_test_reports.yaml, .github/workflows/_unit_tests.yaml, .github/workflows/checks.yaml, .github/workflows/codeql.yaml, .github/workflows/regenerate_on_deps_bump.yaml
vars to not work on forks (see: https://github.com/orgs/community/discussions/44322).
Use a default if it isn't set so that PR originated from forks do work
- part of #3745
-->
For PRs from fork to work we'll still need to deal with secret access but that's the first step.
=> ci: fallback when using vars to a default

.github/test_dependencies.yaml, .github/workflows/_kongintegration_tests.yaml, test/internal/testenv/testenv.go, test/kongintegration/containers/kong.go, test/kongintegration/kong_client_golden_tests_outputs_test.go
Enables EE `kongintegration` tests so that golden tests EE variants are properly verified with the EE Gateway.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/4815.
=> chore(tests): enable ee kongintegration tests

internal/dataplane/translator/subtranslator/ingress.go, internal/dataplane/translator/subtranslator/ingress_atc.go, internal/dataplane/translator/subtranslator/ingress_atc_test.go, internal/dataplane/translator/subtranslator/ingress_test.go
Use `util.FromK8sObject` to carry type meta to `Route` in kongstate in sub-translator of ingress. This fixes the issue of missing type meta in checking reference of plugins.
Should fix #6294 (after #6295 merged)
=> fix(translator): Pass typemeta in ingress sub-translator

internal/dataplane/kongstate/util.go, internal/dataplane/kongstate/util_test.go, internal/dataplane/translator/translate_httproute_test.go, internal/util/objectmeta.go, internal/util/objectmeta_test.go
No need to deep copy the annotations:
```
goos: darwin
goarch: arm64
pkg: github.com/kong/kubernetes-ingress-controller/v3/internal/util
│   old.txt    │              new.txt               │
│    sec/op    │   sec/op     vs base               │
FromK8sObject-10   202.30n ± 3%   44.08n ± 0%  -78.21% (p=0.008 n=5)
│  old.txt   │             new.txt              │
│    B/op    │   B/op    vs base                │
FromK8sObject-10   384.0 ± 0%   0.0 ± 0%  -100.00% (p=0.008 n=5)
│  old.txt   │              new.txt               │
│ allocs/op  │ allocs/op   vs base                │
FromK8sObject-10   3.000 ± 0%   0.000 ± 0%  -100.00% (p=0.008 n=5)
```
=> perf: don't deep copy the annotations in FromK8sObject

test/integration/isolated/ctx.go, test/integration/isolated/gateway_https_test.go
User reported 
- https://github.com/Kong/kubernetes-ingress-controller/issues/6216
this PR introduces a test that verifies it. The problem can't be reproduced, everything works as expected. The issue raised in https://github.com/Kong/kubernetes-ingress-controller/issues/6216#issuecomment-2200377297 happens when a request is made to Kong Gateway without a specific hostname, default certificate is returned to a client. Think about this as
```sh
curl https://test.example.com --resolve test.example.com:443:172.18.128.3      
```
that works as expected (of course assuming that the certificate is trusted) vs
```sh
curl https://172.18.128.3
```
that leads to returning the default cert - https://github.com/Kong/kubernetes-ingress-controller/issues/6216#issue …
=> chore(tests): test Gateway with HTTPS wildcard domains

test/integration/plugin_test.go
Add test case for incorrect `ReferenceGrant` in `TestPluginCrossNamespaceReference`.
fixes #6314 
~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ Only changing tests
=> test: add case for incorrect reference in remote plugin test

CHANGELOG.md, internal/dataplane/kongstate/customentity.go, internal/dataplane/kongstate/customentity_test.go
Allow `KongCustomEntity` to refer to `KongPlugin`  in another namespace if `ReferenceGrant` allows.
fixes #6288 
=> feat(custom_entity) support cross-namespace reference for KongCustomEntity

CHANGELOG.md
3.2.3 changelog for cross-namespace plugin ref fix.
Cherry-picked https://github.com/Kong/kubernetes-ingress-controller/pull/6297 also; may as well. No changelog note for the perf fix since IDK how to write something meaningful for end users re internal memory alloc improvements for internal transient structures.
=> chore(docs) add 3.2.3 changelog

internal/konnect/config_synchronizer.go, internal/konnect/config_synchronizer_test.go, internal/metrics/prometheus_test.go
Add a Konnect configuration syncer that receives Kong configuration in `file.Content` format and runs a loop to upload the received configuration to Konnect in period. It also adds unit tests to verify the implementation of the methods.
This is the first step for #6325.
fixes #6337 
=> feat(konnect): Add Konnect config syncer

CHANGELOG.md, internal/clients/config_status.go, internal/clients/config_status_test.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/synchronizer_test.go, internal/konnect/node_agent.go, internal/konnect/node_agent_test.go
Prerequisite of #6325. Since we want to run sync of Konnect configuration in another loop, the Konnect node agent need to fetch status of sending config to Kong gateways and status of sending to Konnect from different channels. This PR implements the requirement.
fixes #6339 
=> feat: Separate channels to notify gateway and Konnect config status

.github/workflows/_e2e_tests.yaml
Bump k8s version to 1.28.11 in GKE based e2e tests since 1.26 is not supported.
- Which version should we bump to for GKE?
- Should we also bump k8s versions for kind?  
=> chore(ci): bump k8s version to 1.28 for GKE

CHANGELOG.md, internal/clients/manager_test.go, internal/clients/readiness.go, internal/clients/readiness_test.go
This adds to what #6347 has done:
- check pending clients concurrently
- check pending clients and already created clients lists in parallel
Since the readiness is checked concurrently now, this PR also increases the readiness timeout from 1s to 5s.
NOTE: Gateway client readiness is checked every [10s by default](https://github.com/Kong/kubernetes-ingress-controller/blob/8593248e3214144fa6a6a83d21d4448cdac3d70c/internal/clients/manager.go#L18-L20) (not configurable).
=> feat: check Gateway pending clients readiness concurrently

CHANGELOG.md, internal/dataplane/sendconfig/sendconfig.go
Adds `duration` field in logs after sent config to gateway or Konnect successfully.
Part of #6191
Fixes #6362
Used `Truncate()` to avoid the duration being too long and having unnecessary precision.
=> feat(log): log duration after sent config successfully to gateway or Konnect

test/e2e/all_in_one_test.go, test/e2e/helpers_test.go, test/helpers/ports.go
List `Services`, `Routes`, `Upstreams` and `Targets` to verify Kong configuration in gateway pods in `verifyIngressWithEchoBackendsInAdminAPI` instead of `dump.Get`. This could reduce the concurrency of streams to forwarded ports.
e2e run passes: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/10173800539. 
Fixes #6317 
~- [ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~  No need to update changelog.
=> Test(e2e): List entities instead of dump.Get to fetch Kong config in e2e tests

CHANGELOG.md, internal/dataplane/kong_client.go, internal/metrics/prometheus.go, internal/metrics/prometheus_test.go, test/envtest/metrics_envtest_test.go
Adds `ingress_controller_translation_duration_milliseconds` to collect duration of translating k8s resources to Kong configuration.
Part of #6191 
Fixes #6363 
Should we also add a metric for duration of translating fallback configuration?
=> feat(prometheus): Add translation duration metrics

CHANGELOG.md, docs/cli-arguments.md, internal/adminapi/client.go, internal/adminapi/konnect.go, internal/clients/config_status.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/konnect/config_synchronizer.go, internal/konnect/config_synchronizer_test.go, internal/manager/config.go, internal/manager/config_validation.go, internal/manager/config_validation_test.go, internal/manager/run.go, internal/manager/setup.go
Add a `konnect.ConfigSynchronizer` to manager in startup to run a separate loop for uploading config to Konnect.
Also added a `--konnect-upload-config-period` CLI flag to set the period of uploading config to Konnect.
fixes #6338 
=> Feat(konnect): Start Konnect config syncer to upload config to Konnect in separate loop

hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/controllers/utils/conditions.go, internal/controllers/utils/conditions_test.go
In sidecar deployment mode, when new pod KIC pod is up to reconcile resources like `KongConsumers`, the programmed condition in status would be `Unknown` before the first successful applying configuration to Kong gateway. This will cause flips of status of `KongConsumer` and races on updates. thus producing excessive reconciliation requests and heavy load to API server.
The PR ignores the update of `Programmed` condition when the status is `Unknown` and there are existing `Programmed` condition in the status. 
fixes #6386 
I did not update the changelog in the PR to prevent from conflicts on automatically created backport PRs.
Complete these before …
=> fix(controller): Do not update existing Programmed condition to Unknown

hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/controllers/utils/conditions.go, internal/controllers/utils/conditions_test.go
Backport https://github.com/Kong/kubernetes-ingress-controller/commit/4b0a44a4a7cfc158719a739eb78e8ca486e4fbaa from https://github.com/Kong/kubernetes-ingress-controller/pull/6395 to 2.12.x.
=> [Backport release/2.12.x] fix(controller): Do not update existing Programmed condition to Unknown

CHANGELOG.md, internal/controllers/configuration/secret_controller.go
Reconcile `Secret`s with `kongCredType` in data, which are used as Kong credentials. This is only for 2.12.x because in later versions, `kongCredType` in data is deprecated and removed.
fixes #6398 
Should mitigate FTI-6157 where secret may not get reconciled at the first rounds of reconciling.
=> fix(controller): reconcile secrets having kongCredType in data

internal/clients/manager_test.go, internal/clients/readiness.go, internal/clients/readiness_test.go
Backport https://github.com/Kong/kubernetes-ingress-controller/commit/b85dbb1fc36e7f24423447a91c1233144d7d6271 from https://github.com/Kong/kubernetes-ingress-controller/pull/6357.
=> [Backport release/3.2.x] feat: check Gateway pending clients readiness concurrently

CHANGELOG.md
Update changelog for 3.2.4. 
Part of #6377 
=> update changelog for release 3.2.4

CHANGELOG.md, docs/cli-arguments.md, internal/clients/manager.go, internal/clients/readiness.go, internal/clients/readiness_test.go, internal/manager/config.go, internal/manager/config_validation.go, internal/manager/config_validation_test.go, internal/manager/run.go
Add flags `--gateway-discovery-readiness-check-interval` and `--gateway-discovery-readiness-check-timeout` to configure reconciliation interval and timeout of readiness checks.
fixes #6425 
Naming problem: should we change `ReconciliationInterval` to `ReconciliationPeriod` to align with other `***Period`s?
=> Feat(gateway discovery): Add config for gateway readiness check intervals and timeouts

CHANGELOG.md, internal/controllers/configuration/kongupstreampolicy_controller.go, internal/controllers/configuration/kongupstreampolicy_controller_test.go, internal/controllers/configuration/kongupstreampolicy_utils.go, internal/controllers/gateway/grpcroute_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_predicates.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/manager/controllerdef.go, test/envtest/kongupstreampolicy_test.go, test/envtest/setup.go
Stop the reconciliation of `KongUpstreamPolicy` if it is not eventually used in `Ingress` or `HTTPRoute` with matching class. These `KongUpstreamPolicy`s are not loaded into config storage and their status are not updated to prevent races on updating status if there are multiple instances with different ingress classes/controller names are reconciling.  
fixes #6270 
This may not resolve the problem that in sidecar mode, multiple instances are reconciling the same `KongUpstreamPolicy`. Maybe we should use the similar thing done to other resources like #6395 ?
=> Fix(controller): Stop reconcilication if KongUpstreamPolicy not referred in reconciled Ingress/HTTPRoute

.github/workflows/_e2e_tests.yaml, .github/workflows/_envtest_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_kongintegration_tests.yaml, .github/workflows/_permission_check.yaml, .github/workflows/_test_reports.yaml, .github/workflows/checks.yaml, .github/workflows/e2e_trigger_via_label.yaml
It's hard to accept PRs from external contributors, e.g.
- https://github.com/Kong/kubernetes-ingress-controller/pull/6450
because some tests need access to secrets. They can't access them due to GH design. This PR implements the approach described in @mheap [blogpost](https://michaelheap.com/access-secrets-from-forks/) to overcome this limitation. It also makes `should-run-with-secrets` redundant, thus it's removed.
Fixes #3745
=> chore(ci): make PR checks workflow runnable for external contributors

.github/workflows/checks.yaml, .github/workflows/e2e_trigger_via_label.yaml
Due to GH limitation that `pull_request_target` can be triggered only for workflows that are already in `main` redundant trigger `pull_request` can be only removed after merging of 
- https://github.com/Kong/kubernetes-ingress-controller/pull/6459
to `main` so this PR does it. Furthermore, it makes running permission checks for e2e only when triggered by corresponding label
Followup for https://github.com/Kong/kubernetes-ingress-controller/issues/3745
=> chore(ci): remove redundant pull_request trigger and fix e2e trigger (#6462)

test/integration/isolated/tcpingress_test.go, test/integration/tcpingress_test.go
Migrate test integration `TestTCPIngressEssentials` to isolated. Avoiding locking a port cuts execution time.
#5757
=>  chore(tests): migrate TestTCPIngressEssentials to isolated

.github/workflows/_permission_check.yaml
To fix something like that
- https://github.com/Kong/kubernetes-ingress-controller/pull/6464
user for `dependabot` and `renovate` has to be trusted. 
Follow up for #3745
=> chore(ci): make dependabot and renovate trusted for CI

CHANGELOG.md, go.mod, go.sum, internal/dataplane/translator/subtranslator/grpcroute_atc.go, internal/dataplane/translator/subtranslator/grpcroute_atc_test.go, internal/gatewayapi/aliases.go, test/conformance/gateway_conformance_test.go, test/consts/zz_generated_gateway.go
Bumps version of `gateway-api` from `1.1.0` to `1.2.0` and makes required adjustments to make code compile and test pass (bump KTF to [v0.1.7](https://github.com/Kong/kubernetes-telemetry/releases/tag/v0.1.7)).
Furthermore, change the sorting of `headerMatches` by names from `slice.Sort` to `slice.StableSort` to fulfill the code commenter's desire always to have the same order. Bumping the Go version to `1.23` is required to make linitng pass.
Replaces https://github.com/Kong/kubernetes-ingress-controller/pull/6543
=> chore(deps): bump gateway-api from 1.1.0 to 1.2.0 and adjust code

internal/dataplane/testdata/golden/credentials/default_golden.yaml, internal/dataplane/testdata/golden/credentials/in.yaml
In https://github.com/Kong/kubernetes-ingress-controller/issues/6574 we suspected KIC doesn't set Kubernetes metadata tags for credential entities. This PR proves it's not the case by adding a KongClient golden test case that covers all credential types.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/6574.
=> chore: cover credentials in KongClient golden tests

internal/dataplane/kongstate/consumer.go, internal/dataplane/kongstate/consumer_test.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/kongstate/license.go, internal/dataplane/kongstate/types.go, internal/dataplane/kongstate/types_test.go
`SanitizedCopy()` functions unnecessarily allocate objects where it's not needed.
This PR removes those allocations in several places and adds a benchmark to prove the results of this optimization:
before
```
go test -benchmem -bench BenchmarkSanitizedCopy -count 1 ./internal/dataplane/kongstate
goos: darwin
goarch: arm64
pkg: github.com/kong/kubernetes-ingress-controller/v3/internal/dataplane/kongstate
cpu: Apple M1 Max
BenchmarkSanitizedCopy-10           1837            609341 ns/op         3216834 B/op       1036 allocs/op
PASS
ok      github.com/kong/kubernetes-ingress-controller/v3/internal/dataplane/kongstate   1.788s
```
after
```
go test -benchmem -bench BenchmarkSanitizedCopy -count 1 ./internal/dataplane/kongstate
goos: darwin
goarch: …
```
=> refactor: do not allocate for SanitizedCopy()

examples/gateway-tcproute.yaml, test/integration/examples_test.go, test/integration/isolated/examples_ingress_test.go, test/integration/isolated/examples_tcproute_test.go
All integration tests should be migrated to isolated one (furthermore we want to get rid of those two mutexes), this PR migrates
- `TestExampleTCPRoute`
- `TestIngressExample`
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/5757
=> chore(tests): migrate TestExampleTCPRoute and TestIngressExample to isolated

.github/test_dependencies.yaml
As per https://endoflife.date/kubernetes
this PR removes 1.27 and 1.28 from e2e testing matrix as those are unsupported at this point.
=> chore(ci): remove EOLd k8s versions (1.27 and 1.28) from e2e test matrix

test/envtest/specific_gateway_envtest_test.go
Fix a data race detected in https://github.com/Kong/kubernetes-ingress-controller/actions/runs/11691112734/job/32557672213?pr=6620
```
==================
WARNING: DATA RACE
Write at 0x00c002944830 by goroutine 21544:
reflect.Value.SetString()
/opt/hostedtoolcache/go/1.23.2/x64/src/reflect/value.go:2516 +0x87
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).literalStore()
/home/runner/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20221116044647-bc3834ca7abd/internal/golang/encoding/json/decode.go:1070 +0x108e
sigs.k8s.io/json/internal/golang/encoding/json.(*decodeState).value()
/home/runner/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20221116044647-bc3834ca7abd/internal/golang/encoding/json/decode.go:415 +0x224 …
```
=> tests: fix data race in TestSpecificGatewayNN

.github/workflows/_conformance_tests.yaml
GitHub's `actions/upload` doesn't allow uploading artifacts with the same name.
This PR fixes the problem for conformance tests workflow where this would happen.
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/11720599834/job/32646382112?pr=6620
```
Run actions/upload-artifact@v4
with:
name: tests-report-conformance
path: conformance-tests-expressions-router.xml
if-no-files-found: warn
compression-level: 6
overwrite: false
include-hidden-files: false
env:
TEST_KONG_HELM_CHART_VERSION: [2](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/11720599834/job/32646382112?pr=6620#step:7:2).42.0
MISE_LOG_LEVEL: info
MISE_TRUSTED_CONFIG_PATHS: /home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller …
```
=> chore(ci): fix conformance test reports re-using the same artifact name

.github/workflows/_conformance_tests.yaml
#6636 made a type in artifact name. This fixes it 😬 
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/11722905565/job/32653776096?pr=6620#step:2:11
```
Error: No artifacts found matching pattern 'test-report-conformance-*'
```
=> chore(ci): fix typo in conformance report artifact name

CHANGELOG.md, internal/dataplane/translator/subtranslator/ingress.go, test/integration/ingress_test.go
Fixes bug reported by user description of the problem and steps to reproduce it robustly are here https://github.com/Kong/kubernetes-ingress-controller/issues/6542#issuecomment-2459793831
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/6542
This feature was covered with a quite complicated integration test `TestIngressRewriteURI` designed to catch exactly such a bug, but it failed to do so. Why?
- https://github.com/Kong/kubernetes-ingress-controller/pull/6626/commits/8e5f88370d3bc941f0fcc491c75ab58e78842dcc
Changes in the test have no effect (it's just an opportunistic cleanup not to have redundant stuff). The bug was hard to catch due to the order of items in …
=> fix: annotation konghq.com/rewrite always works

config/variants/multi-gw/debug/kustomization.yaml
Running
```
make debug.skaffold
```
leads to 
```log
...
Checking cache...
- kic-placeholder: Found Locally
WARN[0001] Failed to render :running [kubectl --context kind-kong-test kustomize /Users/jakub.warczarek@konghq.com/Documents/work/kubernetes-ingress-controller/config/variants/multi-gw/debug]
- stdout: ""
- stderr: "# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.\nerror: accumulating resources: accumulation err='accumulating resources from '../../../crd/incubator': '/Users/jakub.warczarek@konghq.com/Documents/work/kubernetes-ingress-controller/config/crd/incubator' must resolve to a file': recursed merging from path …
```
=> chore(Makefile): fix target debug.skaffold

CHANGELOG.md, internal/controllers/configuration/kongupstreampolicy_controller.go, internal/controllers/configuration/kongupstreampolicy_controller_test.go
Fix panic in KongUpstreamPolicyReconciler when using with Ingress having a nil HTTP rule
Fixes #6649
=> fix: fix panic in KongUpstreamPolicyReconciler when using with Ingress having a nil HTTP rule

test/integration/httproute_test.go
Fix assertion in `TestHTTPRouteEssentials` that reuses the HTTPRoute variable incorrectly overwriting the name for the subsequent lookups in case of a failure.
Observed in https://github.com/Kong/kubernetes-ingress-controller/actions/runs/11800387959/job/32874484699?pr=6660#step:7:383
```
httproute_test.go:332: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/httproute_test.go:334
/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/asm_amd64.s:1700
resource name may not be empty
httproute_test.go:332: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/httproute_test.go:332
Error:      	Condition …
```
=> tests: fix assertions in TestHTTPRouteEssentials

.github/workflows/_conformance_tests.yaml, .github/workflows/_docker_build.yaml, .github/workflows/_unit_tests.yaml, internal/dataplane/kongstate/credentials_conflicts.go, internal/dataplane/kongstate/credentials_conflicts_test.go
Fixes main workflows by:
- fixing a compilation problem that was caused by concurrent merges of https://github.com/Kong/kubernetes-ingress-controller/pull/6619 and https://github.com/Kong/kubernetes-ingress-controller/pull/6585
- checking out PR references in reusable workflows called from `checks.yaml` that uses `pull_request_target`
=> fix: unbreak main workflows

hack/cleanup/konnect_control_planes.go
Due to https://github.com/Kong/sdk-konnect-go/issues/20 we need to set the URL for each operation that would hit the global endpoint. Otherwise we will get it overwritten with prod's global endpoint which we do not want.
Broke on CI: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/11819442161/job/32929360130#step:4:2832
=> chore: fix konnect cleanup

CHANGELOG.md, internal/dataplane/deckgen/deckgen.go, internal/dataplane/sendconfig/inmemory.go, internal/dataplane/testdata/golden/ingress-v1-rule-with-tls-and-consumer/default_golden.yaml, internal/dataplane/testdata/golden/ingress-v1-rule-with-tls-and-consumer/expression-routes-on_golden.yaml, internal/dataplane/testdata/golden/ingress-v1-rule-with-tls-and-consumer/expression-routes-on_settings.yaml, internal/dataplane/testdata/golden/ingress-v1-rule-with-tls-and-consumer/in.yaml, internal/dataplane/testdata/golden/ingress-v1-rule-with-tls/default_golden.yaml
This PR adds SNI's certificate ID ref to be set in generated config. This basically means that instead of:
```
{
"_format_version": "3.0",
"certificates": [
{
"id": "8aade13c-1470-46bd-9849-9a74e349214f",
"cert": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----",
"key": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----",
"snis": [
{
"name": "3.example.com"
},
{
"name": "4.example.com"
}
]
}
]
}
```
we generate
```
{
"_format_version": "3.0",
"certificates": [
{
"id": "8aade13c-1470-46bd-9849-9a74e349214f",
"cert": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----",
"key": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----",
"snis": [
{
"name": "3.example.com",
"certificate": {
"id": …
```
=> fix: set SNI's certificate ID ref

CHANGELOG.md, examples/kong-consumer-key-auth.yaml, internal/dataplane/deckgen/consumer_cmp.go, internal/dataplane/deckgen/consumer_cmp_test.go, internal/dataplane/deckgen/generate.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/testdata/golden/consumer-group-example-ee/default_golden.yaml, internal/dataplane/testdata/golden/kongconsumer-with-custom-id/default_golden.yaml, internal/dataplane/testdata/golden/kongconsumer-with-custom-id/expression-routes-on_golden.yaml, internal/dataplane/testdata/golden/kongconsumer-with-custom-id/expression-routes-on_settings.yaml, internal/dataplane/testdata/golden/kongconsumer-with-custom-id/in.yaml
Fix handling `KongConsumer` without `username` specified. Currently we allow to [set just the `custom_id` on the consumer](https://github.com/Kong/kubernetes-ingress-controller/blob/5bcd583300191c5b36daf18c32d22fae0c58d0c4/pkg/apis/configuration/v1/kongconsumer_types.go#L32) (as an alternative to setting just the `username`).
This PR fixes the former case where `username` is not specified.
Fixes #6552 
=> fix: fix panic when handling KongConsumer without username

Makefile, docs/api-reference.md, docs/incubator-api-reference.md, go.mod, go.sum, scripts/apidocs-gen/config.yaml, scripts/apidocs-gen/generate.sh, scripts/apidocs-gen/template/gv_details.tpl, scripts/apidocs-gen/template/type.tpl
Generate apidocs for CRDs from kong/kubernetes-configuration repo.
Dependent on https://github.com/Kong/kubernetes-configuration/pull/155 to include `KongServiceFacade`.
fixes #6618
=> chore: generate api docs from kubernetes-configuration repo

internal/dataplane/deckgen/deckgen.go, internal/dataplane/sendconfig/inmemory_error_handling.go, internal/dataplane/sendconfig/inmemory_error_handling_test.go
This makes the `Entity tags missing fields {"name": "", "error": "no name"}` errors, have a bit more context so that they are actually helpful in debugging:
```
2024-11-14T16:37:44+01:00	error	Entity tags returned in error API error from gateway is missing fields, Kubernetes Event cannot be created without them	{"name": "", "id": "c021ae7d-f985-40ad-9908-6c517a1d49d8", "tags": [], "type": "certificate", "raw_error": {"entity_id":"c021ae7d-f985-40ad-9908-6c517a1d49d8","entity_type":"certificate","errors":[{"message":"required field missing","type":"entity"}]}, "error": "resource error has no name tag"}
```
Related to #6660
=> chore: add more logs data when unparsable Gateway API error is received

.github/dependabot.yml, .github/workflows/regenerate_on_deps_bump.yaml, renovate.json
Disables `kong/kubernetes-configuration` go module updates from dependabot. It enables them in Renovate instead because it allows the addition of a custom label to a PR created by the tool. We need to add a `renovate/auto-regenerate` label to a PR to make sure that every time kconf dependency is updated, all generated files depending on it will be up-to-date (i.e. `config/crd/kustomization.yaml`).
Tested on a fork.
Follow up to https://github.com/Kong/kubernetes-ingress-controller/pull/6683#pullrequestreview-2442312936.
=> chore: let renovate handle kconf go.mod updates

CHANGELOG.md, internal/dataplane/translator/translate_upstreams.go
Reported by a user in 
- https://github.com/Kong/kubernetes-ingress-controller/issues/6535
Steps to reproduce - apply the YAML:
```yaml
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
name: kong
annotations:
konghq.com/gatewayclass-unmanaged: "true"
spec:
controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
name: kong
spec:
gatewayClassName: kong
listeners:
- name: http
protocol: HTTP
port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
name: route-name
spec:
hostnames:
- app.domain.example
parentRefs:
- group: gateway.networking.k8s.io
kind: Gateway
name: kong
rules:
- filters:
- requestRedirect:
hostname: app.domain.example
path: …
```
=> fix(log): false positive `No targets found to create upstream ...`

CHANGELOG.md, hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/controllers/utils/control_plane_reference.go, internal/controllers/utils/control_plane_reference_test.go, test/envtest/consts.go, test/envtest/control_plane_reference_test.go, test/envtest/konglicense_controller_test.go
Handles CP references in `KongConsumer`, `KongConsumerGroup`, and `KongVault` reconcilers so objects are only reconciled when they do not have a CP ref explicitly set, or it's explicitly set to `kic`. Otherwise, an object will get ignored (e.g. when it has a CP ref of `konnectNamespacedRef` type).
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/6581.
=> feat: handle CP refs in Consumer, ConsumerGroup and Vault reconcilers

test/envtest/admission_webhook_envtest_test.go
Fix the flake that was observed in https://github.com/Kong/kubernetes-ingress-controller/actions/runs/11857806653/job/33047028189?pr=6677#step:6:256
```
admission_webhook_envtest_test.go:666: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/admission_webhook_envtest_test.go:666
admission webhook "kongclusterplugins.validation.ingress-controller.konghq.com" denied the request: could not parse plugin configuration: Secret "cluster-conf-secret-valid-patch" not found
Test:       	TestAdmissionWebhook_KongClusterPlugins/should_pass_the_validation_if_the_secret_in_ConfigPatches_of_KongClusterPlugin_generates_valid_configuration
```
**Which issue this PR …
=> tests: fix  TestAdmissionWebhook by using Eventually()

CHANGELOG.md, internal/adminapi/kong.go, internal/adminapi/kong_test.go, internal/dataplane/configfetcher/config_fetcher.go, internal/dataplane/configfetcher/config_fetcher_test.go
This PR fixes an invalid status check in kong client which causes the client to report that it's ready while in reality it's not. The problem arises from an invalid check in `NewKongClientForWorkspace()`
```
if wsName == "" {
return NewClient(client), nil
}
```
which short circuits when the workspace is empty and [does not perform the checks that follow](https://github.com/Kong/kubernetes-ingress-controller/blob/c393bb5fcc88c9f924be48190ae79a304fa71845/internal/adminapi/kong.go#L71-L110).
The above causes the client manager to think that this client is ready to receive config where it's not.
This behavior can easily be tested with using Gateway Discovery and scaling up the Kong `Deployment`. This also prevents the `KongConfigurationApplyFailed` …
=> fix: fix Kong client's status check

CHANGELOG.md, internal/controllers/gateway/route_predicate_test.go, internal/controllers/gateway/route_predicates.go
Do not log errors when a `parentRef` item is not referencing a `Gateway`. It is possibly that the route is managed by some other controllers, like using service mesh.
fixes #6584 
=> fix(log): do not log errors when parentRef kind is not Gateway

CHANGELOG.md, internal/annotations/annotations.go, internal/annotations/annotations_test.go, internal/dataplane/kongstate/route.go
Uses a common `extractCommaDelimitedStrings ` function to extract values from a comma-delimited list of strings. Beside just splitting by a comma, it also sanitizes the output values by trimming whitespace and discarding empty values.
Follow up to https://github.com/Kong/kubernetes-ingress-controller/pull/6707#discussion_r1858292972.
=> feat: improve robustness of extracting comma-delimited annotations

CHANGELOG.md, internal/controllers/gateway/httproute_controller.go, internal/dataplane/translator/backendref.go
One of the cases mentioned in the original issue https://github.com/Kong/kubernetes-ingress-controller/issues/6540:
> When a resource is missing in the cluster, like a Service on which an HTTPRoute points
For verification, the below configuration was used
```yml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
name: kong
annotations:
konghq.com/gatewayclass-unmanaged: "true"
spec:
controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
name: kong
spec:
gatewayClassName: kong
listeners:
- name: http
protocol: HTTP
port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
name: rewrite-path-full
spec:
parentRefs:
- name: kong
rules:
- matches:
- …
```
=> chore(HTTPRoute): change level from ERROR to DEBUG for missing backend and enhance status

CHANGELOG.md, internal/controllers/configuration/kongupstreampolicy_utils.go, internal/controllers/configuration/kongupstreampolicy_utils_test.go
Set creationTimestamp of ancestor status in `KongUpstreamPolicy` to fix the sorting of ancestors in `KongUpstreamPolicy` status.
This fixes an issue where status of `KongUpstreamPolicy` is continuously updated even nothing changed.
fixes #6757 
=> fix(controller): set creationTimestamp of ancestors of KongUpstreamPolicy status

.github/workflows/_e2e_tests.yaml
Fix the issue that occurred in https://github.com/Kong/kubernetes-ingress-controller/actions/runs/12156398089/job/33900270172#step:13:19.
The culprit is that when workflow fails, `KONG_IMAGE_ARTIFACT` is not set so there's a duplicated artifact name across tests against released and unreleased Kong.
=> chore(ci): fix e2e's artifact name

CONTRIBUTING.md
Remove references to the `next` branch in the `CONTRIBUTING.md` docs; this branch is no longer used.
fix #4678
=> docs(CONTRIBUTING.md): remove references to `next` branch

CHANGELOG.md, internal/dataplane/testdata/golden/httproute-example/default_golden.yaml, internal/dataplane/testdata/golden/httproute-example/expression-routes-on_golden.yaml, internal/dataplane/testdata/golden/httproute-example/in.yaml, internal/dataplane/translator/subtranslator/httproute.go, internal/dataplane/translator/subtranslator/httproute_atc.go, internal/dataplane/translator/translate_httproute.go, internal/util/k8s.go, internal/util/k8s_test.go
Gateway API 1.2 released named route rules as a GA feature, see [GEP 995](https://gateway-api.sigs.k8s.io/geps/gep-995/#api). The closest equivalent of `HTTPRoute` in Kong is Route. They are translated to them; multiple `HTTPRoute`s can be translated to a single Kong Route, hence introduced tag has a format of 
```
k8s-named-route-rule:route1
k8s-named-route-rule:route1
k8s-named-route-rule:route2
k8s-named-route-rule:route3
```
So it contains single or multiple names (separated with `;`) from optional `spec.rules[*].name` of `HTTPRoute` YAML defined by a user. In case of absence, the tag is not populated at all.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/6582 with the same approach presented …
=> feat(HTTPRoute): propagate to Kong tag `k8s-named-route-rule`

CHANGELOG.md, internal/dataplane/translator/subtranslator/httproute_test.go, internal/util/builder/httproutefilter.go, internal/util/objectmeta.go, internal/util/objectmeta_test.go
Fixes an issue when declaring an `ExtensionRef` plugin on `HTTPRoute`.
Fixes #6761
Open to suggestions how to test this one further.
=> fix: fix ExtensionRef plugins for HTTPRoutes

test/e2e/all_in_one_test.go
Skip until `TestDeployAllInOneDBLESS` is resolved in #6769.
=> chore(tests): skip e2e TestDeployAllInOneDBLESS scaling proxy to 0

.github/workflows/performance_nightly.yaml, .github/workflows/performance_targeted.yaml
Migrating to `actions/upload-artifact@v4` and `actions/download-artifact@v4` missed the performance reports artifacts. This PR fixes it.
Working workflow run can be found in: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/12163549394, specifically: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/12163549394/job/33924218511#step:5:1
Failing workflow run in nightly: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/12153705270/job/33892614064#step:5:10
=> chore(ci): fix performance tests artifacts

CHANGELOG.md, internal/dataplane/translator/translate_upstreams.go
The first attempt to fix it https://github.com/Kong/kubernetes-ingress-controller/pull/6687 was unsuccessful, see https://github.com/Kong/kubernetes-ingress-controller/issues/6535#issuecomment-2517305897 and https://github.com/Kong/kubernetes-ingress-controller/issues/6535#issuecomment-2517981672.
It can be triggered with such configuration. 
```yml
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
name: kong
annotations:
konghq.com/gatewayclass-unmanaged: "true"
spec:
controllerName: konghq.com/kic-gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
name: kong
spec:
gatewayClassName: kong
listeners:
- name: http
protocol: HTTP
port: 80
---
apiVersion: configuration.konghq.com/v1
config: …
```
=> fix(log): get rid of `No targets found to create upstream ...`

.github/workflows/benchmarks.yaml
To reduce the noise a little bit, let's run benchmarks only 
- on `main`
- on PRs with `ci/run-benchmarks` label
Additionally limit the data points stored (and rendered at https://kong.github.io/kubernetes-ingress-controller/dev/bench/) to 50.
=> ci: only run benchmarks on main and labeled PRs

CHANGELOG.md, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/testdata/golden/kongplugin-instance-name/default_golden.yaml
#4588 introduced assigning instance names to plugins and handling collisions in generates names.
This missed the fact that plugins can be bound to multiple entities, e.g. routes **and** consumer groups.
This PR fixes it.
=> ci: fix assigning duplicated instance names to plugins bound to different entity types (e.g. route and consumer group)

renovate.json
[`ignoreUnstable`](https://docs.renovatebot.com/configuration-options/#ignoreunstable) by default is `true` so it doesn't update to `rc`, `beta` etc.
This PR changes it so that KIC can automatically get a new version of https://github.com/Kong/kubernetes-configuration.
=> chore(ci): renovate update kubernetes-configuration to unstable versions

CHANGELOG.md, docs/cli-arguments.md, internal/controllers/configuration/secret_controller.go, internal/manager/config.go, internal/manager/config_validation_test.go, internal/manager/controllerdef.go
As #6576 mentioned, we received a report about KIC's high memory usage.
We can reproduce this issue by the following steps:
* Create 300 secret resources with a size of 1M.
```
$ dd if=/dev/urandom bs=756439 count=1 | base64 > output.txt
$ for i in `seq 0 300`; do kubectl create secret generic "foo-${i}" --from-file=key=output.txt ; done
```
**Before this change:**
KIC will consume over 1G of memory within the first 3-5 minutes, but after 10 minutes, KIC's memory consumption will stay around 400M.
**With this change:**
KIC will consume over 1G of memory within the first 3-5 minutes, but after 10 minutes, KIC's memory consumption will stay around 360M.
fixes: https://github.com/Kong/kubernetes-ingress-controller/issues/6 …
=> feat: Add the flag `--secret-label-selector` to set the label selector for `Secrets` to ingest.

internal/dataplane/configfetcher/kongrawstate_test.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/sendconfig/dbmode.go
`TestDeployAllInOneEnterprisePostgres`
- [before](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/12218873131/job/34084868994#step:7:1303)
- [after](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/12236452121) 
Minimal, interactive example that reproduces the issue - https://go.dev/play/p/BI7vSuUQ996
Go sometimes makes questionable decisions regarding its API, and this is an example of one. Community reported exactly the same case as we encountered, see 
- https://github.com/golang/go/issues/46320
and read details. Any suggestion for improvement was unfortunately rejected, thus we have to live with it. Such rough edges make Go a not-so-safe language, IMHO. But on the other hand, creator discoureages usage of …
=> fix: resolve panic in resourceErrorFromEntityAction

CHANGELOG.md, internal/dataplane/failures/failures.go, internal/dataplane/failures/failures_test.go, internal/dataplane/kong_client.go, internal/dataplane/translator/ingressrules_test.go
One of the cases mentioned in the original issue https://github.com/Kong/kubernetes-ingress-controller/issues/6540:
> a Secret on which a Consumer depends
This PR addresses it by changing the log level of all messages related to registering failure and pushing K8s Event from `ERROR` to `DEBUG` because such events don't mean something is wrong with KIC itself. 
For user, it's reported inthe  status of `KongPlugin`
```yml
...
status:
conditions:
- lastTransitionTime: "2024-12-06T14:35:10Z"
message: Object failed to be configured in Kong - see its attached Events for
more information.
observedGeneration: 1
reason: Invalid
status: "False"
type: Programmed
username: consumer1
```
that points to an event
```txt
default     1s          Warning …
```
=> chore(logs): DEBUG instead of ERROR for K8s Event push

CHANGELOG.md, internal/dataplane/kongstate/customentity.go, internal/dataplane/kongstate/customentity_test.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/translator/translator.go, test/integration/isolated/custom_entity_test.go
Currently users cannot rely KIC for their custom entities schema validation.
This PR introduces feature.
When an invalid custom entity is created e.g. :
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
namespace: default
name: degraphql-example
plugin: degraphql
config:
graphql_server_path: /v1/graphql
---
apiVersion: configuration.konghq.com/v1alpha1
kind: KongCustomEntity
metadata:
namespace: default
name: degraphql-route-example
annotations:
a: a
spec:
type: degraphql_routes
fields:
uri: /contacts
queryy: "query{ contacts { name } }" # invalid key, missing required "query"
controllerName: kong
parentRef:
group: configuration.konghq.com
kind: KongPlugin
name: degraphql-example
```
Events with validation failures will be …
=> feat(custom_entity): introduce schema validation

CHANGELOG.md, internal/dataplane/testdata/golden/httproute-example/expression-routes-on_golden.yaml, internal/dataplane/testdata/golden/httproute-url-rewrite-path-prefix/expression-routes-on_golden.yaml, internal/dataplane/translator/subtranslator/httproute.go, internal/dataplane/translator/subtranslator/httproute_atc.go, internal/dataplane/translator/subtranslator/httproute_atc_test.go, internal/dataplane/translator/subtranslator/httproute_test.go, internal/dataplane/translator/translate_httproute.go, internal/dataplane/translator/translate_httproute_test.go
Second part of #5801. Generate combined Kong services for rules sharing the same bakends when expression based routes are used.
Fixes #6727
=> feat(translator): combine services across httproutes expression router

go.mod, go.sum
Passing `enterprise-postgres` against `3.9.0.0-rc.5` with go-kong 0.60.0: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/12293996547/job/34308934489
Related: #6823
=> chore: revert go-database-reconciler to 1.16.1 and go-kong to 0.60.0

examples/gateway-backendtlspolicy.yaml
Add an exemplar manifest for `BackendTLSPolicy`.
Part of #6374
=> chore(examples): add BackendTLSPolicy example manifest

examples/gateway-backendtlspolicy.yaml, internal/controllers/configuration/configmap_controller.go, internal/controllers/configuration/secret_controller.go
Those predicates should be changed from `And` to `Or` as we don't want to require users to specify e.g. both `konghq.com/ca-cert: "true"` **and** `konghq.com/configmap: "true"`. One will suffice to make KIC ingest the ConfigMap.
=> chore: predicate.And -> predicate.Or in secret and configmap controllers

CHANGELOG.md, internal/dataplane/deckgen/generate.go, internal/dataplane/kongstate/customentity.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/kongstate/plugin.go, internal/util/relations.go, internal/util/relations_test.go, test/envtest/configerrorevent_envtest_test.go
One of the cases mentioned in the original issue https://github.com/Kong/kubernetes-ingress-controller/issues/6540:
`a Plugin on which an HTTPRoute depends`
can be extrapolated to any plugin attachment referring to a nonexisting plugin leads to a logs message, but no K8s Event is sent.
Status for `HTTPRoute` that references non-existing plugin is
```yml
...
status:
parents:
- conditions:
- lastTransitionTime: "2024-12-12T16:06:22Z"
message: ""
observedGeneration: 1
reason: Accepted
status: "True"
type: Accepted
- lastTransitionTime: "2024-12-12T16:06:22Z"
message: ""
observedGeneration: 1
reason: ResolvedRefs
status: "True"
type: ResolvedRefs
- lastTransitionTime: "2024-12-12T16:06:22Z"
message: ""
observedGeneration: 1
reason: Unknown
status: …
```
=> feat(KongPlugin): generate K8s Events for misconfiguration

CHANGELOG.md, internal/controllers/gateway/backendtlspolicy_controller.go, internal/controllers/gateway/backendtlspolicy_utils.go, internal/controllers/gateway/backendtlspolicy_utils_test.go
Enqueue `BackendTLSPolicy` for `ConfigMap`s that are referenced in `spec.validation.caCertificateRefs`.
Additionally, update the `Accepted` status condition to `Invalid` if the referenced `ConfigMap` doesn't exist or cannot be retrieved.
=> feat(backendtlspolicy): enqueue for ConfigMaps

internal/dataplane/fallback/cache_to_graph.go, internal/dataplane/fallback/cache_to_graph_test.go, internal/dataplane/kong_client.go, internal/store/cache_stores.go, internal/store/cache_stores_snapshot.go
Check for `lock` and stores in `cacheStores` before using them to prevent panics.
Also added a check in `tryRecoveringWithFallbackConfiguration` to quit generating fallback config if cache is not initialized.
fixes #6775
=> fix(fallback): check for nil stores in `cacheToGraph` and recovering from fallback config to prevent panics 

test/envtest/metrics_envtest_test.go, test/envtest/run.go
Disable metrics by default in `envtest` suite to prevent ports exhaustion.
Add `WithMetricsAddr()` option to enable enabling them.
=> tests(envtest): disable metrics by default

CHANGELOG.md, internal/dataplane/kongstate/customentity.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/gatewayapi/contraints.go, test/envtest/configerrorevent_envtest_test.go
The previous PR
- https://github.com/Kong/kubernetes-ingress-controller/pull/6814
mentioned
> There are still logs that should be events and statuses related to plugins like in [this helper](https://github.com/Kong/kubernetes-ingress-controller/blob/67c8a9596a3ec1c8d1d87a269c12eb491dbf25da/internal/dataplane/kongstate/kongstate.go#L392-L429) for cross-namespace access, but it can be handled in a separate PR or issue.
this PR adresses it, now there is no error log in such situation and respective K8s Event is generated
```log
default     4m8s        Warning   KongConfigurationTranslationFailed   httproute/httproute-testing-2        no grant found to referenced "third:fourth" plugin in the requested remote KongPlugin bind
```
for …
=> feat(KongPlugin): generate K8s Events for missing grant

CHANGELOG.md, examples/ingress-upstream-tls.yaml, internal/annotations/annotations.go
Changes `konghq.com/ca-certificates-secret` and `konghq.com/ca-certificates-configmap` to use plural forms (secrets and configmaps) as they represent a list of CA certificates.
=> chore: make CA certificate annotations use plural form

CHANGELOG.md, internal/admission/validation/consumers/credentials/validation.go, internal/admission/validation/consumers/credentials/validation_test.go, test/envtest/admission_webhook_envtest_test.go
This PR makes JWT credential validation a bit more correct, not requiring `secret` field for credentials with algorithms different than HS256, HS384 or HS512.
This will also allow to make the guide at https://docs.konghq.com/hub/kong-inc/jwt/#create-a-jwt-credential cleaner (not requiring the note to add a dummy value for `secret` for other  algos)
=> fix(credentials): ignore missing secret field on secret validation for JWT credentials with non HMAC algo

.github/test_dependencies.yaml
Updates `test_dependencies.yaml` manually:
- edits `e2e.kind` so it includes `v1.31.x` (still leaving `v1.29.x` as it's not reached EOL yet)
- aligns `e2e.istio` matrix to match https://istio.io/latest/docs/releases/supported-releases/
=> chore(deps): update e2e tests deps

CHANGELOG.md, config/rbac/gateway/role.yaml, internal/annotations/annotations.go, internal/controllers/gateway/backendtlspolicy_controller.go, internal/controllers/gateway/backendtlspolicy_utils.go, internal/controllers/gateway/backendtlspolicy_utils_test.go, internal/dataplane/translator/ingressrules.go, internal/store/store.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml, test/integration/isolated/backendtlspolicy_test.go
`Secret`s can be set in the `BackendTLSPolicy` `CACertificateRefs` field.
**Which issue this PR fixes**: 
Fixes #6834
=> feat: allow `Secret`s as `BackendTLSPolicy` `CACertificateRefs`

CHANGELOG.md, internal/dataplane/translator/subtranslator/httproute.go, internal/dataplane/translator/subtranslator/httproute_atc_test.go, internal/dataplane/translator/subtranslator/httproute_test.go, internal/dataplane/translator/translate_httproute_test.go
As described in the reported issue https://github.com/Kong/kubernetes-ingress-controller/issues/6851 header (port `:443` is missing due to changes from https://github.com/Kong/kubernetes-ingress-controller/pull/6804)
```
Location:  https://demo.example.com/path
```
two spaces after colon instead of expected
```
Location: https://demo.example.com/path
```
Unfortunately, not all programs ignore whitespaces in headers (they should), thus it's problematic.
This PR fixes it. 
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/6851
The actual root cause was [here](https://github.com/Kong/kubernetes-ingress-controller/pull/6855/files#diff-df2a67c9ede8d32433f70281fa4979f7c97d …
=> fix: no redundant space in header `Location` for `HTTPRoute` with requestRedirect filter

internal/manager/controllerdef.go
The source of error is this function. 
https://github.com/Kong/kubernetes-ingress-controller/blob/6c787c10e85724d99b142737aaa0a9c2fe5aca75/internal/controllers/gateway/backendtlspolicy_controller.go#L182-L230
See that it requires not only `gatewayapi.BackendTLSPolicy` but also `gatewayapi.HTTPRoute`, thus this PR adds it to the list of `RequiredCRDs` for the start of this controller. In other words, the creation of the controller will start when all required CRDs are available in the cluster.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/6854
=> chore(tests): fix flake due to missing HTTPRoute CRD

CHANGELOG.md, config/image/oss/kustomization.yaml, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml
CHANGELOG update for v1.4.0.
Part of #6844 
=> chore: v3.4.0 CHANGELOG and config update

internal/dataplane/kong_client_test.go, internal/dataplane/kongstate/consumer_test.go, internal/dataplane/kongstate/credentials_test.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/kongstate/uuid_test.go, internal/konnect/config_synchronizer.go, internal/konnect/config_synchronizer_test.go, internal/manager/setup.go, test/mocks/configuration_change_detector.go, test/mocks/update_strategy.go, test/mocks/update_strategy_resolver.go
Extracts mocks common for `internal/konnect` and `internal/dataplane` packages to `test/mocks`.
=> chore: extract common mocks to mocks package

.github/workflows/release_docs.yaml
As there are no issues or labels associated with `Kubernetes Team` label in docs: https://github.com/Kong/docs.konghq.com/issues?q=label%3A%22Kubernetes+Team%22+ replace it with `team-k8s` which has been around for a while and it's still used.
=> chore: update docs pr label

CHANGELOG.md, go.mod, internal/dataplane/kong_client.go, internal/dataplane/kong_client_golden_test.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/sendconfig.go, internal/konnect/config_synchronizer.go, internal/konnect/config_synchronizer_test.go, internal/manager/run.go, internal/manager/setup.go, internal/metrics/prometheus.go, internal/metrics/prometheus_test.go, test/mocks/metrics_recorder.go
It fixes a bug discovered during a refactor in which metrics related to regular DPs are not collected when Konnect integration is turned on.
The root issue was caused by creating two separate instances of `CtrlFuncMetrics` (one for the [KongClient](https://github.com/Kong/kubernetes-ingress-controller/blob/425d3ef39a411fea73bd9c3b61a726d7254578a5/internal/dataplane/kong_client.go#L209) and another for the newly introduced [konnect.ConfigSynchronizer](https://github.com/Kong/kubernetes-ingress-controller/blob/844c2910951b12fc4564886fbf5122d5b9dc5928/internal/konnect/config_synchronizer.go#L57)) where the latter was [unregistering](https://github.com/Kong/kubernetes-ingress-controller/blob/12a4875cc97a84ae0ca58fb5e74356db3c260a9d/internal/metrics/prome …
=> fix: do not unregister Kong DPs metrics when Konnect integration is enabled

.github/workflows/_docker_build.yaml, .github/workflows/_e2e_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_linters.yaml, .github/workflows/_performance_tests.yaml, .github/workflows/nightly.yaml, .github/workflows/regenerate_on_deps_bump.yaml, .github/workflows/release.yaml, .github/workflows/release_docs.yaml, .github/workflows/validate_kong_image_trigger_via_label.yaml, .tools_versions.yaml, Makefile
Add [`actionlint`](https://github.com/rhysd/actionlint) in CI with [`shellcheck`](https://github.com/koalaman/shellcheck) integration.
=> ci: add actionlint in CI

internal/dataplane/kongstate/customentity.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/util/rels/relations.go, internal/util/rels/relations_test.go
Address comment/fulfill promise 
- https://github.com/Kong/kubernetes-ingress-controller/pull/6814#discussion_r1883719468
of putting relations-related code into a separate package. Name `rels` has been chosen to not be too long and not to steal great variable names like `relation`, `relations` and `rel`.
=> chore(refactor): dedicated rels package

go.mod, internal/dataplane/kong_client.go, internal/dataplane/kong_client_golden_test.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/sendconfig.go, internal/konnect/config_synchronizer.go, internal/konnect/config_synchronizer_test.go, internal/manager/run.go, internal/manager/setup.go, internal/metrics/prometheus.go, internal/metrics/prometheus_test.go, test/mocks/metrics_recorder.go
(cherry picked from commit 2c72b4079d8212741c15b8038ab93d51ed981eb0)
=> [backport release/3.3.x] fix: do not unregister Kong DPs metrics when Konnect integration is enabled (#6881)

go.mod, internal/dataplane/kong_client.go, internal/dataplane/kong_client_golden_test.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/sendconfig.go, internal/konnect/config_synchronizer.go, internal/konnect/config_synchronizer_test.go, internal/manager/run.go, internal/manager/setup.go, internal/metrics/prometheus.go, internal/metrics/prometheus_test.go, test/mocks/metrics_recorder.go
(cherry picked from commit 2c72b4079d8212741c15b8038ab93d51ed981eb0)
=> [backport release/3.4.x] fix: do not unregister Kong DPs metrics when Konnect integration is enabled (#6881)

.github/workflows/check_pr_labels.yaml
backport https://github.com/Kong/kubernetes-ingress-controller/commit/6533c42ef7582e7b169b342dcb1f1a7a77f08087 from https://github.com/Kong/kubernetes-ingress-controller/pull/6743
=> [Backport release/2.12.x] chore(ci): use pull_request instead of pull_request_target

.github/workflows/backport.yaml, .github/workflows/check_pr_labels.yaml, .github/workflows/e2e_trigger_via_label.yaml
backport https://github.com/Kong/kubernetes-ingress-controller/commit/6533c42ef7582e7b169b342dcb1f1a7a77f08087 from https://github.com/Kong/kubernetes-ingress-controller/pull/6743
=> [Backport release/3.2.x] chore(ci): use pull_request instead of pull_request_target

.github/workflows/backport.yaml
This is what is done in main and should have been fixed
as a part of the backport of https://github.com/Kong/kubernetes-ingress-controller/pull/6743
=> ci(github): use pull_request for backport

.github/workflows/backport.yaml, .github/workflows/check_pr_labels.yaml, .github/workflows/e2e_trigger_via_label.yaml
=> chore(ci): use pull_request instead of pull_request_target (#6743)

test/integration/isolated/httproute_filter_request_redirect_test.go
Since Kong 3.4/3.5 cannot support HTTP/1.1 requests when `http2` is configured on listened ports, we disable http2 listen on proxy for `RequestRedirect` tests.
=> Fix: Proxy do not listen http2 in request redirect tests

internal/adminapi/konnect.go, internal/clients/config_status.go, internal/clients/manager.go, internal/clients/manager_test.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/dbmode.go, internal/dataplane/sendconfig/strategy.go, internal/konnect/config_synchronizer.go, internal/konnect/config_synchronizer_test.go, internal/konnect/node_agent.go, internal/konnect/node_agent_test.go, internal/manager/run.go, internal/manager/setup.go, internal/util/clock/ticker.go, test/kongintegration/dbmode_update_strategy_test.go, test/kongintegration/kong_client_golden_tests_outputs_test.go, test/mocks/config_status_notifier.go, test/mocks/konnect_client_factory.go, test/mocks/konnect_kongstate_updater.go
Stop using `KonnectClient` in the clients' provider. Make `konnect.ConfigSynchronizer` create one using a factory on its startup instead. Also:
- moves tests related to Konnect-specific behavior to `konnect.ConfigSynchronizer`.
- moves the call to `deckgen.ToDeckContent` from `KongClient` to `konnect.ConfigSynchronizer` as it may reach out to Konnect APIs while for plugins schemas, and we don't want to spend time on Konnect-related stuff in the critical path
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/6340.
=> chore: don't use KonnectClient in ClientsProvider

.github/workflows/regenerate_on_deps_bump.yaml
This PR
- https://github.com/Kong/kubernetes-ingress-controller/pull/6951
does not pass checks, because there is inconsistency in `go.sum`
[src](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/12739717282/job/35503837372?pr=6951#step:5:221)
Enhance workflow that regenerates manifests and code with `go mod tidy` to avoid such situation in the future
=> chore(ci): run go mod tidy during regeneration

.github/workflows/regenerate_on_deps_bump.yaml
Follow up for 
- https://github.com/Kong/kubernetes-ingress-controller/pull/6954
to get such PRs like https://github.com/Kong/kubernetes-ingress-controller/pull/6951 automatically mergable.
Files to commit are added explicitly, so `go.mod` and `go.sum` was omitted. This PR fixes it
=> chore(ci): add go.mod and go.sum to commit for regenerate

.github/workflows/_conformance_tests.yaml, .github/workflows/_docker_build.yaml, .github/workflows/_e2e_tests.yaml, .github/workflows/_envtest_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_linters.yaml, .github/workflows/_test_reports.yaml, .github/workflows/_unit_tests.yaml, .github/workflows/benchmarks.yaml, .github/workflows/cleanup.yaml, .github/workflows/codeql.yaml, .github/workflows/conformance_tests_report.yaml, .github/workflows/e2e_targeted.yaml, .github/workflows/e2e_trigger_via_label.yaml, .github/workflows/license.yaml, .github/workflows/nightly.yaml, .github/workflows/pr_checks.yaml, .github/workflows/release.yaml, .github/workflows/release_docs.yaml, .github/workflows/test_nightly.yaml, .github/workflows/validate_kong_image.yaml
=> chore: pin actions to digests

internal/clients/manager.go, internal/clients/manager_test.go, internal/cmd/rootcmd/run.go, internal/manager/run.go, internal/manager/setup.go, internal/manager/telemetry/reports.go
Where possible, it leverages `ctrl.LoggerFrom(ctx)` instead of passing the logger explicitly. Besides that, there was no further improvement needed to pass the parent logger down.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/7045.
=> chore: ensure logger is passed down

internal/cmd/rootcmd/run.go, internal/manager/health/health_check.go, internal/manager/health/health_check_test.go, internal/manager/run.go, internal/util/test/controller_manager.go, pkg/manager/manager.go, test/envtest/crds_envtest_test.go, test/envtest/run.go
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/7044
**Special notes for your reviewer:**
The only run everywhere called should be [this one](https://github.com/Kong/kubernetes-ingress-controller/blob/95639d67f8d62992cfad3a51d38004f19306935f/pkg/manager/manager.go) the internal package should be only used in this import. I'm happy to address it in a separate PR. I think that in such a case ID can be hard coded to e.g. `KIC-classic`.
Further telemetry adjustments should be addressed in https://github.com/Kong/kubernetes-ingress-controller/issues/7038?issue=Kong%7Ckubernetes-ingress-controller%7C7048
=> chore: decouple health/readiness server from manager

test/integration/tlsroute_test.go
Accept both `connection reset by peer` and `io.EOF` errors in the case of no route matched in `TestTLSPassThrough` integration test case, since the returned errors changed after `kong/kong-gateway-dev:20250129`/
fixes #7082
=> test(integration): accept "connection reset by peer" error in error check where no routes matches in case TestTLSPassThrough

internal/dataplane/kong_client.go, internal/dataplane/kong_client_golden_test.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/dbmode.go, internal/dataplane/sendconfig/sendconfig.go, internal/dataplane/sendconfig/strategy.go, internal/diagnostics/collector.go, internal/diagnostics/collector_test.go, internal/diagnostics/diff.go, internal/diagnostics/diff_test.go, internal/diagnostics/http_handler.go, internal/diagnostics/http_handler_test.go, internal/diagnostics/mapping.go, internal/diagnostics/server.go, internal/diagnostics/server_test.go, internal/diagnostics/types.go, internal/manager/run.go, test/envtest/control_plane_reference_test.go, test/envtest/crds_envtest_test.go, test/envtest/ingress_test.go, test/envtest/kongupstreampolicy_test.go, test/envtest/manager_debugendpoints_test.go, test/mocks/update_strategy_resolver.go
Refactors the `diagnostics.Server` by splitting it into a `Collector`, `Handler`, and a `Server`. That will be needed to enable plugging multiple instances of an `HTTPHandler` into one mux when we run multiple instances of the manager. 
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/7042.
=> chore: decouple diagnostics server from collector and handlers

go.mod, pkg/manager/multiinstance/errors.go, pkg/manager/multiinstance/instance.go, pkg/manager/multiinstance/manager.go, pkg/manager/multiinstance/manager_test.go
It implements a multi-instance manager that will be responsible for running multiple `manager.Manager` instances and managing their lifecycle. It will also run servers that need to be shared between the running instances (i.e. diagnostics).
I try to design its API to match what most likely will be required on KO's reconcilers side (i.e. scheduling, stopping, checking readiness).
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/7042.
=> feat: implement multi-instance manager

.github/workflows/_e2e_tests.yaml
As GKE v1.28 is going out of support, we need to update it to keep tests passing.
=> [release/2.12.x] chore(deps): bump GKE version in e2e tests

internal/manager/run.go, pkg/manager/config/config.go, pkg/manager/manager.go, pkg/manager/multiinstance/diagnostics.go, pkg/manager/multiinstance/instance.go, pkg/manager/multiinstance/manager.go, pkg/manager/multiinstance/manager_test.go, pkg/manager/multiinstance/mocks_test.go, test/envtest/multiinstance_manager_diagnostics_test.go, test/envtest/run.go
Adds `multiinstace.DiagnosticsServer` and integrates it with `multiinstace.Manager` to register/unregister currently running instances and expose their config diagnostics data on `/{instanceID}/debug/config` endpoints.
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/7042.
=> feat: allow dynamically exposing diagnostics for multiple instances

go.mod, pkg/manager/multiinstance/diagnostics.go, pkg/manager/multiinstance/manager.go, test/envtest/multiinstance_manager_diagnostics_test.go
Add ability of running a pprof handler to the `multiinstance.DiagnosticsServer`. When running instances, wrap them in `pprof.Do` so their CPU profiling data is labeled with their ID. 
This allows to see where each instance spent most of its CPU time:
```text
go tool pprof cpu.pprof                                                 
File: ___TestMultiInstanceManager_Profiling_in_github_com_kong_kubernetes_ingress_controller_v3_test_envtest.test
Type: cpu
Time: Feb 7, 2025 at 4:32pm (CET)
Duration: 30.01s, Total samples = 870ms ( 2.90%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) tags
instanceID: Total 330.0ms
180.0ms (54.55%): cp-2
150.0ms (45.45%): cp-1
(pprof) tagfocus=instanceID:cp-2
(pprof) top10 -cum
Active …
```
=> feat: expose pprof endpoints from multiinstance diagnostics server

CHANGELOG.md, internal/admission/validation/gateway/httproute_test.go, internal/admission/validator_test.go, internal/controllers/configuration/kongupstreampolicy_utils_test.go, internal/controllers/gateway/route_predicate_test.go, internal/controllers/reference/indexer.go, internal/dataplane/translator/translator_test.go, internal/manager/run.go, internal/manager/scheme/scheme.go, internal/manager/setup.go, internal/store/cache_stores.go, internal/util/types_test.go, test/helpers/k8s_meta.go, test/mocks/events_recorder.go
Run `AddToScheme` in `scheme.Get` only once since `scheme.Get` is called very frequently and `AddToScheme` creates temporary objects. It causes large amount of creation and gc on these objects.
fixes #7104 
=> fix(manager): Run `AddToScheme` only once in `scheme.Get`

.golangci.yaml, internal/manager/consts/consts.go, internal/manager/record.go, internal/manager/run.go, test/envtest/configerrorevent_envtest_test.go
Each event generated by a controller has an annotation `konghq.com/instance-id` with the ID of a particular KIC instance making it identifiable. The actual format of ID (what this string contains) is not in the scope of this issue/PR. 
The interface of the standard K8s emitter is preserved but ensures that every event generated will have that annotation. 
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/7046
=> feat: associate KIC instance with Kubernetes event via annotation

internal/manager/run.go, pkg/metadata/metadata.go
Report `kong-ingress-controller/v3.4.0` instead of `v3.4.0` by `nodeAgent` to make indistinguishable `KIC` from `KO`. This PR implements the outcome of the discussion - https://github.com/Kong/kubernetes-ingress-controller/issues/7051#issuecomment-2653311277
Furthermore, verify that `User-Agent` is set in `konnect` clients.
Implementation
https://github.com/Kong/kubernetes-ingress-controller/blob/e61ca89eb0f4500b272a275805c277e185821c19/internal/konnect/useragent/user_agent_round_tripper.go#L1-L25
tests that verify
- https://github.com/Kong/kubernetes-ingress-controller/blob/88f5c51275cbe213a8859a4fc7c9e157d6addc69/internal/konnect/controlplanes/client_test.go#L28-L38
- https://github.com/Kong/kubernetes-ingress-controller/blob/88f5c51275cbe213a8859a …
=> feat: report not only version but project name too to konnect

CHANGELOG.md, internal/admission/validation/gateway/httproute_test.go, internal/admission/validator_test.go, internal/controllers/configuration/kongupstreampolicy_utils_test.go, internal/controllers/gateway/route_predicate_test.go, internal/controllers/reference/indexer.go, internal/dataplane/translator/translator_test.go, internal/manager/run.go, internal/manager/scheme/scheme.go, internal/manager/setup.go, internal/store/cache_stores.go, internal/util/types_test.go, test/helpers/k8s_meta.go, test/mocks/events_recorder.go
=> [Backport to release/3.4.x] fix(manager): Run AddToScheme only once in scheme.Get

internal/admission/server.go, internal/clients/manager.go, internal/clients/manager_test.go, internal/controllers/configuration/kongadminapi_controller.go, internal/konnect/node_agent.go, internal/konnect/node_agent_test.go, internal/manager/run.go, internal/manager/setup.go, test/envtest/kongadminapi_controller_envtest_test.go
Remove spawning of long-running goroutines from the `internalmanager.New` constructor.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/7099.
=> chore: do not run goroutines in manager.New

.golangci.yaml, internal/admission/server.go, internal/diagnostics/server.go, internal/manager/consts/consts.go, internal/manager/run.go, internal/manager/setup.go, test/envtest/admission_webhook_envtest_test.go, test/envtest/manager_envtest_test.go, test/envtest/run.go
Implements graceful shutdown for admission and diagnostics servers. Ensures no goroutines leak after cancelling the context passed to `Manager.Run`.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/7041.
=> chore: ensure no gouroutines leak after cancelling manager

CHANGELOG.md, internal/dataplane/kongstate/consumer.go, internal/dataplane/kongstate/consumer_test.go
KIC `3.0.3` was the last without feature gate `SanitizeKonnectConfigDumps=true` by default (everything works as expected).
For newer versions mapping of `KongConsumer`s to respective `KongConsumersGroup` is broken because the code responsible for sanitization omits consumer groups by mistake.
This field is crucial for proper mapping, see how the config is generated
https://github.com/Kong/kubernetes-ingress-controller/blob/ff2a3d9313651293084e36bafe7479494b3e88c8/internal/dataplane/deckgen/generate.go#L152-L166
fixes https://github.com/Kong/kubernetes-ingress-controller/issues/7143
=> fix: map `KongConsumer` to respective `KongConsumerGroup` in Konnect

.golangci.yaml, test/e2e/helpers_test.go
Log from `make lint` contains
```log
...
WARN The linter 'tenv' is deprecated (since v1.64.0) due to: Duplicate feature another linter. Replaced by usetesting. 
...
```
so this PR implements the advice and furthermore [enable all checks](https://golangci-lint.run/usage/linters/#usetesting) for `usetesting` linter
=> chore(linter): replace deprecated `tenv` with `usetesting`

internal/manager/run.go, pkg/manager/config/feature_gates.go
Due to the nature of Go maps, every iteration has a different order. This PR enforces the order for logs related to feature gates and the order of examination (and error return) in case they are wrongly configured. It makes logs easier to follow.
=> chore(logs): feature gate are logged always in the same order

pkg/manager/multiinstance/manager.go, pkg/manager/multiinstance/manager_test.go, test/envtest/multiinstance_manager_diagnostics_test.go
This is needed to make it run as a Runnable in KGO's manager.
=> chore: make multimanager implement Runnable interface

test/internal/helpers/konnect/control_plane.go
Remove deleting of roles after deleting Konnect control planes since they are now automatically cleaned up in Konnect.
=> test(helpers): remove cleanup of roles after deleting Konnect CPs

CHANGELOG.md, internal/admission/handler.go, internal/admission/handler_test.go, internal/admission/validation/consumers/credentials/validation.go, internal/admission/validation/consumers/credentials/validation_test.go, internal/admission/validation/consumers/credentials/vars.go, internal/controllers/configuration/secret_controller.go, test/envtest/admission_webhook_envtest_test.go
Ignore secrets with unsupported credential type in `konghq.com/credential` label like `konnect` in validating webhooks. This prevents rejection of `Secret`s used for credentials used in other places.
To keep the secrets with unsupported credential types out of the reconciliation, the PR also updated the predicate in secret controller to reject `Secret` with unsupported credential type in `konghq.com/credential` label.
fixes #7218 
=> fix(admission): ignore unsupported credential types in validating secrets

CHANGELOG.md, internal/adminapi/kong.go, test/mocks/admin_api_handler.go
When workspace is given, do not access `/status` endpoint for detecting whether Kong gateway is ready. Because in this scenario, KIC is likely to be permitted to only access the given workspace so it does not have the permission to access `/status` endpoint.
fixes #6901 
=> fix(kong_client): Do not check Kong gateway status by /status endpoint if workspace is given

CHANGELOG.md, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/utils.go, internal/dataplane/kong_client.go
Return an error when no ready clients in fetching listeners. It will trigger a `Reconciler Error` in setting listener status in reconciling `Gateway`s.
fixes #7015
=> fix(kong_client): return error in fetching listeners when no ready kong clients

CHANGELOG.md, examples/ingress-broken-plugin-fallback.yaml, internal/dataplane/kong_client.go, test/integration/isolated/examples_ingress_fallback_test.go
As described in https://github.com/Kong/kubernetes-ingress-controller/issues/7172 , when the FallbackConfiguration feature is enabled and an Ingress references a plugin with incorrect configuration, even the correct Ingress resource cannot update its status. This PR fixes that issue.
The changes include adding a new example configuration file, updating the client to report configured Kubernetes objects, and adding integration tests to verify the functionality.
Key changes:
* Added `examples/ingress-broken-plugin-fallback.yaml` to demonstrate the fallback configuration with a misconfigured plugin.
* Updated `tryRecoveringWithFallbackConfiguration` method in `internal/dataplane/kong_client.go` to report configured Kubernetes objects when fallback …
=> fix: fix the FallbackConfiguration object report

test/envtest/metrics_envtest_test.go, test/envtest/run.go
Refactor the `TestMetricsAreServed` envtest so it's stable. Make sure there are timeouts set to avoid hanging on HTTP requests. 
Stability tested with `GOTESTFLAGS="-count=200 -run=TestMetricsAreServed -timeout=3h" make test.envtest`.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/6125.
=> chore: re-enable metrics envtest

.github/workflows/release.yaml
This PR aligns the release workflow build and push steps in `release/2.12.x` branch to be the same as in `main`.
=> chore(ci): fix release workflow 2.12.x

.github/workflows/release.yaml
Fix 2.12's release workflow token permissions (to align them with `main`'s) so that this: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/14356924192/job/40264036011
```
Error: Error 403: Resource not accessible by integration
```
doesn't happen anymore.
=> chore(ci): fix token permissions in release workflow 2.12.x

CHANGELOG.md, internal/admission/validation/gateway/httproute.go, internal/admission/validation/ingress/ingress.go, internal/admission/validation/ingress/ingress_test.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/route.go, internal/dataplane/kongstate/route_test.go
Override translated Kong routes with annotations in validation webhooks for `Ingress`es and `HTTPRoute`s.
Fixes #7344
=> fix(validation): Override route by annotation in translation of ingresses and httproutes for validation

CHANGELOG.md, internal/dataplane/sendconfig/sendconfig.go, test/integration/consumer_group_test.go
Do not skip the update of config if the SHA is the same as last valid configuration when the update is performed by a fallback. This fixes the issue that in DB mode, if the fallback configuration is the same as the last  valid configuration, the entities that should be purged together with the invalid entities still remains.
fixes #7374 
=> fix(sendconfig): Do not skip when SHA is not changed if the update is performed by a fallback

CHANGELOG.md, internal/dataplane/sendconfig/dbmode.go, internal/dataplane/sendconfig/dbmode_test.go
Keep the plugin ID (identified by plugin name and attached service, route, consumer, consumer group) to prevent conflicts of two identical plugins (identified by the fields above) having the different ID
fixes #7440
We also needs to add integration tests/e2e tests for upgrading in DB mode: https://github.com/Kong/kubernetes-ingress-controller/issues/7448. Should we finish it also in this PR?
=> Fix(sendconfig): Keep ID of existing plugins

CHANGELOG.md, Makefile, config/rbac/role.yaml, docs/cli-arguments.md, internal/cmd/rootcmd/config/cli.go, internal/konnect/license/client.go, internal/konnect/license/client_test.go, internal/konnect/license/storage.go, internal/konnect/license/storage_test.go, internal/labels/labels.go, internal/manager/setup.go, pkg/manager/config/konnect.go, pkg/manager/config_test.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml
Store fetched Konnect license to `konnect-license-<cpid>`. When KIC failed to fetch the license from Konnect, it tries to load the stored license from the secret.
fixes #7421 
TODO:
~- Add cli arg here?~
Added cli flag `--konnect-license-storage-enabled` and enable it by default.
- Should we put it in 3.4.x or 3.5.x? 
=> feat(konnect): Store of konnect licenses to secrets

CHANGELOG.md, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gateway_utils_test.go
Count the `attachedRoutes` of a `Gateway` in the correct way in case of `HTTPRoute`s with multiple parent references.
fixes: #7516
=> fix(attachedRoutes): fixed count in case of HTTPRoute with multiple parentRefs

CHANGELOG.md, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gateway_utils_test.go
* fixing the attachedRoutes count in case of HTTPRoute with multiple parentRefs
* changelog update for #7517
(cherry picked from commit 1ff5b45a08a545b328b94c02d695dd863166b3e5)
=> backport(#7517): fixed count in case of HTTPRoute with multiple parentRefs

test/envtest/configerrorevent_envtest_test.go
During work on 
- https://github.com/Kong/kubernetes-ingress-controller/pull/7538
discovered that envtests 
- `TestConfigErrorEventGenerationInMemoryMode`
- `TestConfigErrorEventGenerationDBMode`
for checking K8s event generation does it in a best-effort manner and a little bit buggy way. 
This PR makes it robust, all generated events are collected and have to match explicit written predicates included in tests.
spotted during work on 
- https://github.com/Kong/kubernetes-ingress-controller/issues/7537
=> fix(tests): make envtests for K8s events generation robust

.github/test_dependencies.yaml, CHANGELOG.md, config/crd/incubator/kustomization.yaml, config/crd/kustomization.yaml, go.mod, go.sum, internal/dataplane/kong_client_golden_test.go, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go, internal/dataplane/translator/translate_upstreams.go, internal/dataplane/translator/translator.go, internal/dataplane/translator/translator_test.go, internal/manager/run.go, internal/versions/versions.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml, test/envtest/configerrorevent_envtest_test.go, test/envtest/kong.go, test/envtest/run.go
When `KongUpstreamPolicy` set algorithm to `sticky-sessions` and  Kong gateway version < 3.11, generate a `KongConfigurationTranslationFailed` event for services using the `KongUpstreamPolicy` and do not override translated `upstream` by `KongUpstreamPolicy`.
closes #7537
Generation of event for Kong Gateway `< 3.11.0` is covered by dedicated envtest `TestStickySessionsNotSupportedEventGeneration`. Big general envtest `TestConfigErrorEventGenerationInMemoryMode` to pass has to detect this event too, because `3.11.0` is not released yet, so there is no support. But `3.11.0` is around the corner, so when it is updated, this test will fail, and someone needs to adjust it as described …
=> feat(translator): Generate KongConfigurationTranslationFailed event when algorithm=sticky-sessions and kong version < 3.11

CHANGELOG.md, internal/manager/run.go
When konnect license synchronization is enabled, mark KIC pod as ready until there is a license available (fetched from Konnect or stored in secret).
fixes #7422
=> fix(konnect): Do not mark pod ready when no konnect licenses available

config/base/kong-ingress-dbless.yaml, config/variants/multi-gw/base/gateway_deployment.yaml, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres.yaml
Set limit of open files to at least `4096` to fix the flaky tests on GKE.
Kong gateway suggests to set the limit to at least 4096 but GKE has the default value of `1024` which is not enough for stream proxy: https://cloud.google.com/kubernetes-engine/docs/troubleshooting/known-issues
fixes #7242 
=> test(e2e): Add postStart hook to set open file limit to at least 4096

CHANGELOG.md, Makefile, config/crd/incubator/kustomization.yaml, config/crd/kustomization.yaml, docs/api-reference.md, go.mod, go.sum, internal/dataplane/kongstate/kongupstreampolicy.go, internal/dataplane/kongstate/kongupstreampolicy_test.go, test/e2e/manifests/all-in-one-dbless-k4k8s-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect-enterprise.yaml, test/e2e/manifests/all-in-one-dbless-konnect.yaml, test/e2e/manifests/all-in-one-dbless.yaml, test/e2e/manifests/all-in-one-postgres-enterprise.yaml, test/e2e/manifests/all-in-one-postgres-multiple-gateways.yaml, test/e2e/manifests/all-in-one-postgres.yaml, test/envtest/crds_envtest_test.go
Fix `KongUpstreamPolicy` hash on translation.
Currently when users specify cookie as hash fallback the rules are not translated correctly due to peculiar field usage in kong upstream (and `KongUpstreamHash`): cookie and cookie path is used both for hash_on and hash_fallback  in kong upstream but not in `KongUpstreamHash` so we can't simply look at hash_on to set the `KongUpstreamHash`'s `HashOn` to decide how to translate the config.
The way this PR changes the translation, is to retain the "no error" policy, so we rely on CRD validation rules (to be changed in https://github.com/Kong/kubernetes-configuration/pull/498).
In case somehow the invalid config gets pushed to Kong, we are generating `KongConfigurationApplyFailed` events and that's the case …
=> fix: fix KongUpstreamPolicy hash on translation

Dockerfile, Dockerfile.debug
=> [backport release/3.4.x] chore(deps): bump golang from 1.24.4 to 1.24.5

docs/api-reference.md, docs/cli-arguments.md, scripts/apidocs-gen/post-process-for-konghq.sh, scripts/cli-arguments-docs-gen/main.go
Fix errors like: https://app.netlify.com/projects/kongdeveloper/deploys/687dfe9cff316000097daabc#L493 during docs build:
```
10:53:12 AM:   Liquid Exception: On `kubernetes-ingress-controller/reference/configuration-options.md`, the following {% table %} block contains a malformed yaml: 0: columns: 1: - title: Flag 2: key: flag 3: - title: Type 4: key: type 5: - title: Description 6: key: description 7: - title: Default 8: key: default 9: rows: 10: - flag: '`--admission-webhook-cert`' 11: type: '`string`' 12: description: Admission server PEM certificate value. Mutually exclusive with --admission-webhook-cert-file. 13: default: "" 14: - flag: '`--admission-webhook-cert-file`' 15: type: '`string`' 16: description: Admission server PEM certificate …
```
=> chore: fix CLI args docs generation

CHANGELOG.md, internal/konnect/license/client.go, internal/labels/labels.go, test/e2e/konnect_test.go, test/e2e/utils_test.go
The `Secret` to store Konnect licenses was using an invalid label value causing that the `Secret` cannot be created/updated.
=> fix(konnect): Use correct label value of secret to store license

test/util/crds.go, test/util/gomod.go, test/util/gomod_test.go
`>= 2` was making the code to split the alpha/beta/rc versions (returning empty string from `DependencyModuleVersionGit` which when passed to `kustomize` gets the latest version of provided module) where in reality this was only meant to do so for Go mod pseudo versions.
Additionally now the version of a module from which the CRDs are being installed is printed in the logs:
```
INFO: deploying Kong CRDs (github.com/kong/kubernetes-configuration/config/crd/ingress-controller?ref=v2.0.0-alpha.1) to cluster
INFO: deploying Kong incubator CRDs (github.com/kong/kubernetes-configuration/config/crd/ingress-controller-incubator?ref=v2.0.0-alpha.1) to cluster
INFO: deploying Gateway CRDs …
```
=> chore: fix kubernetes-configuration CRD installation in integration tests

CHANGELOG.md, hack/generators/cache-stores/spec.go, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gatewayclass_controller.go, internal/dataplane/fallback/graph_dependencies.go, internal/dataplane/translator/translate_certs.go, internal/dataplane/translator/translator.go, internal/manager/run.go, internal/store/fake_store.go, internal/store/store.go, internal/store/zz_generated.cache_stores.go, internal/store/zz_generated.cache_stores_test.go
Do not skip checking certificates in gateway listeners that does not has "Programmed" condition if the `GatewayClass` is not managed by KIC. The change fixes an issue when KIC is deployed by gateway operator, certificates gets deleted when dataplane (Kong gateway) pods are changed.
fixes #7660 (then also https://github.com/Kong/kong-operator/issues/1769)
=> fix(translator): check gateway class and do not skip listeners when gateway class is not managed by KIC
