docs/annotations.md, internal/ingress/controller/kong.go
We had a stumbling block where plugins were not being added to routes if
we tried to reference the same `KongPlugin` k8s resource in more than
one service/ ingress annotation. Also fixed a few typos I noticed when debugging this problem.
=> Update annotations doc

Makefile, cli/ingress-controller/main.go, internal/apis/admin/kong_client.go, vendor/k8s.io/client-go/discovery/discovery_client.go, vendor/k8s.io/client-go/discovery/discovery_client_test.go, vendor/k8s.io/client-go/transport/cache.go, vendor/k8s.io/client-go/transport/cache_test.go, vendor/k8s.io/client-go/transport/transport.go, vendor/k8s.io/client-go/transport/transport_test.go
This PR aims at adding support for EE versions of Kong which is currently broken. The version signature of EE versions of Kong is different than CE versions, and it's like: `0.32-enterprise-edition`.
This PR identifies an EE version of Kong, adds a patch number to the version (default `x.x.0`) and checks that the version of Kong is either greater than `0.13.0` or `0.32.0`.
To be sure this is working as intended, I would like to have another person test this patch.
=> fix(*) support enterprise versions

internal/apis/admin/sni.go, internal/ingress/controller/kong.go
As seen in #75, if multiple Host reference the same certificate, only
one host is added as SNI in Kong. This was a bug due to early exit when
a GET request for a certificate succeded.
There were also edge-cases around change certificate for a Host or
updating SNI name. This commit covers those.
Fixes #75
=> fix: create multiple SNIs when same certificate is reused

internal/apis/configuration/v1/types.go, internal/ingress/controller/kong.go
This change allows specifying protocol (HTTP/HTTPS) to talk to upstream
via a KongIngress object.
Fixes #69
=> feat(KongIngress) allow upstream HTTPS

docs/custom-types.md
The document incorrectly mentions `ingress.plugin.konghq.com` as the
annotation used to pick up `KongIngress` object.
=> docs: fix the annotation for KongIngress

internal/ingress/controller/kong.go
Problem:
When KongConsumer custom resource is created, a consumer entity is
created in Kong. But when the custom resource is deleted in k8s, the
change is not propagated to Kong. This results in an odd and confusing
behavior(#58) where consumers can be created but never deleted in Kong via
ingress controller.
Solution:
Perform complete sync like we do for all other entities in Kong. This
means that after this change, consumers present in Kong but not present
in k8s will be deleted.
This reverses the past decision of allowing users to manage consumer entity in Kong via ingress controller and by other means outside the controller.
The long term solution will involve storing more metadata in Kong to
detect if an entity is created by the ingress controller or via another
mechanism.
Breaking …
=> feat(KongConsumer) delete consumers not present in k8s

deploy/manifests/dummy-application-openshift.yaml, deploy/manifests/dummy-application.yaml
Exposing ports helps in having an endpoint directly accessible in
minikube which eases on boarding for users using Kong Ingress Controller.
=> docs(yaml) update http-svc to use NodePort

internal/ingress/controller/kong.go
When KongIngress object is updated, the properties of affected routes in
Kong were not changed (#91). This was a known issue and was left as a future
TODO in the past.
This change picks up the changes from KongIngress and patches the routes
in Kong as needed.
=> fix: update routes in Kong when KongIngress object is updated

rootfs/Dockerfile
The ingress controller verifies TLS certs before using them.
See #94
=> chore(docker) install ca-certificates package

deploy/manifests/ingress-controller.yaml, deploy/manifests/kong.yaml, deploy/single/all-in-one-postgres.yaml, deploy/single/kong-resources-openshift.yaml
Breaking change:
Kong 0.14.0 introduces breaking changes in the Admin API for Certificate
and Consumer entities and hence, this commit will require a version bump
for the ingress controller in future.
This commit will break the ingress controller logic around the two
entities and should not be merged to master.
=> chore(deploy) bump up Kong to 0.14.0

internal/apis/admin/api_helper.go
This change helps in issuing PUT requests.
Newer versions of Kong now support specifying ID via PUT requests and
not POST and hence this is necessary.
=> feat(util) add PUT request helper

internal/ingress/controller/kong.go, internal/ingress/controller/kong_test.go
**What this PR does / why we need it**: Use `reflect.DeepEqual` to correctly compare CRD config and existing KongPlugin config
**Which issue this PR fixes** : fixes #102
=> fix(KongPlugin) compare CRD config and kongplugin config correctly

internal/ingress/controller/kong.go
**What this PR does / why we need it**: only send PATCH request to Kong when the kongIngress changed, this will solve a problem that may result in high database pressure in Kong.
**Which issue this PR fixes** : fixes #104
=> fix(KongService) only send PATCH request for services when necessary

internal/apis/plugin/v1/types.go, internal/ingress/controller/kong.go
This is a fix for the issue introduced in 32ca70f.
`name` is already a property defined for every resource in k8s, which is
unique across all objects of the same kind.
The `name` from metav1.objectMeta needs to be accessible in other parts
of code to correctly read the object.
This commit renames the `name` to `plugin` field.
=> fix: rename name to plugin in KongPlugin resource

internal/apis/admin/v1/types.go
Running the code on a 32bit platform - in this case a armhf causes a unmarshaling failure due to int not being 64bit.
~~~
I0909 14:34:11.012422       8 controller.go:127] syncing Ingress configuration...
E0909 14:34:11.133679       8 controller.go:130] unexpected failure updating Kong configuration: 
syncing targets: json: cannot unmarshal number 1536503123429 into Go struct field Target.created_at of type int
W0909 14:34:11.133820       8 queue.go:113] requeuing openfaas-fn/hello-python, err syncing targets: json: cannot unmarshal number 1536503123429 into Go struct field Target.created_at of type int
~~~
Resolution is to explicitly define created/updated as 64 bit.
=> breakage on 32bit platforms

internal/ingress/controller/kong.go
Problem:
KongPlugin custom resource defines a Plugin in Kong.
Currently, a KongPlugin resource exists for every Plugin entity in Kong.
The sync process ensures that KongPlugin and the corresponding Plugin
entitiy in Kong are in sync and diff them as they share the same ID
(UID/UUID). This is not a scalable or maintainable configuration. If
there are a large (100s) number of ingress rules or services, there will
be similar number of KongPlugin objects for each plugin that is enabled
on those routes/services.
See #6
See #83
Solution:
Decouple k8s KongPlugin and Plugin entities in Kong, there-by removing
the unnecessary duplication.
This solution implies that there is not a KongPlugin resource in k8s for every
Plugin entity in Kong. This is fine as long as there can exists only a
single …
=> feat: reuse KongPlugin resources across ingress resources

deploy/single/all-in-one-postgres.yaml, deploy/single/kong-resources-openshift.yaml
As best I know, there's no case where the proxy service should be a NodePort. It must be publicly accessible on normal HTTP ports. I've changed it to LoadBalancer in most of the deployment examples. `deploy/provider/baremetal/kong-proxy-nodeport.yaml` has been left as-is since it explicitly says it's a NodePort in the name, and I'm not entirely sure of its original purpose (it only contains the service definition and we don't appear to reference it in docs).
=> fix(deploy) change kong-proxy to LB

README.md
Supported versions are an often a source of confusion and a lot of
support tickets.
This change clearly communicates which versions of Kong
are supported with every releases of Kong Ingress Controller.
=> chore(README) add supported versions section to README

internal/apis/admin/kong_client.go, internal/apis/admin/kong_client_test.go
Kong Enterprise follows a version scheme
of `x.y-z` while Kong follow `x.y.z`.
Both products have an `rc` or other meta
appended without a `-`, which makes
semver unhappy.
For #141
=> fix(admin) handle minor number versioning scheme for Kong Enterprise

deploy/gke.md
the svc name from wget is kong-ingress-controller, not kong-admin
updates the correct service name from the README.md
=> updating README to reflect correct service name

internal/ingress/controller/kong.go
Host is not a required field in Kubernetes Ingress Spec.
This is a small change which instantiates routes in Kong based on path
only.
Fix #84
=> feat: add support for path only based routing

deploy/manifests/ingress-controller.yaml, deploy/manifests/migration.yaml, deploy/single/all-in-one-postgres.yaml, hack/build-single-manifests.sh
Using InitContainer can result in two Kong nodes running migrations
concurrently.
Job is the right way to run migrations.
=> feat(deploy) use Job to run Kong migration

deploy/manifests/postgres.yaml, deploy/single/all-in-one-postgres.yaml
Currently, the Postgres pod does not persist data across restarts
because the mount is done incorrectly.
This change uses `volumeMounts` in the StatefulSet spec to mount the
persistent volume at the $PGDATA path.
=> feat(deploy) mount pvc correctly on the Postgres pod

deploy/manifests/ingress-controller.yaml, deploy/manifests/kong.yaml, deploy/single/all-in-one-postgres.yaml
Kong can startup only if the DB schema is up to date.
If Postgres is not up or the schema is not up to date, then Kong
will fail to start, resulting in Pod restarts.
This change will wait for Postgres to be up and migrations to finish
running, avoiding restarts and failures in Kubernetes.
There is currently no way to verify if DB state is at the correct
version and hence we resort to a hack of actualling starting Kong and
stopping it in the init container.
With Kong >= 0.15.0, Kong will have a CLI command to check if migrations
are up to date or not.
=> feat(deploy) add initContainer to wait for DB state

docs/deployment/gke.md
Use documentation range IPs rather than actual GCE IPs. Best practice over using what's potentially someone else's live GCE IP.
=> Use doc IP ranges for GKE instructions.

internal/ingress/controller/kong.go, internal/ingress/controller/util.go, internal/ingress/controller/util_test.go
=> fix: avoid nil pointer reference when overriding route with KongIngress

deploy/manifests/custom-types.yaml, deploy/single/all-in-one-postgres.yaml
Newer releases of Kubernetes supports validations of Custom Resources
via OpenAPI v3 schema, which uses JSON schema.
This change adds support for validations and additionally, if the k8s
server supports server-side printing, then additional columns are
printed for some of the custom resources.
=> feat: add CRD validations and additional printing columns

internal/ingress/controller/kong.go
`strip_path` was set to false by default but was changed in 0.2.1
release to true.
See #193
=> fix: set strip_path to false by default

internal/ingress/controller/kong.go, internal/ingress/controller/kong_test.go
cherry-picked from 1f7ad0d7dff035464ed914b9a7b78adba9a48d8d
=> backport fix pluginDeepEqual when integer value is decoded as float64 for 0.1.x

Makefile
Also, skip `-a` flag to avoid rebuilding up-to-date packages.
=> chore(makefile) trim path info from the binary

Gopkg.lock, Gopkg.toml, deploy/manifests/ingress-controller.yaml, deploy/manifests/kong.yaml, deploy/manifests/migration.yaml, deploy/single/all-in-one-postgres.yaml, docs/faq.md, internal/ingress/annotations/class/main.go, internal/ingress/annotations/class/main_test.go, internal/ingress/controller/kong.go
Introduce support for Kong 1.0
=> Feat/kong 1.0 to next

cli/ingress-controller/flags.go, cli/ingress-controller/main.go, internal/ingress/controller/controller.go
Following options have been added to work with custom TLS certificates,
SNI names and to ignore a self-signed certificate:
- `--admin-tls-skip-verify`: to skip validation of a certificate, this
shouldn't be used in a production environment.
- `--admin-tls-server-name`: use this if the FQDN of Kong's Admin API
doesn't match the SNI name in the certificate.
- `--admin-ca-cert-file`: use this to specify a custom CA cert which is
not part of the bundled CA certs.
=> feat: add support for custom TLS certificate

docs/deployment/gke.md
Docs have a mistake in them, the current `curl` command should be replaced with `kubectl` to apply the manifest for the dummy service instead of downloading it.
=> Fix command for applying dummy svc

docs/deployment/aks.md
Signed-off-by: cbrgm <chris@cbrgm.net>
The `kubernetes.io/ingress.class` value in the example for the ingress deployment on Azure has a wrong value. This must be `kong` and not `nginx`. I had to debug for a long time until I found the error. Hopefully others won't have the problem in the future.
none
none
=> [Docs] Fix wrong values for ingress class in azure ingress deployment docs

deploy/manifests/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless.yaml, hack/build-single-manifests.sh
A config map based nginx.conf is included along with the deployment for
convenient health-check and exposing metrics.
Please note that the config map is not required and Ingress Controller
will still work fine without the ConfigMap, albeit some health-check
configs need to be updated.
=> feat(deploy) add deployment for DB-less mode

cli/ingress-controller/flag_test.go, cli/ingress-controller/flags.go, cli/ingress-controller/main.go, internal/ingress/controller/controller.go
The flag comes in from the era of NGINX ingress controller.
The default service is selected from the Ingress rules if any of the
Ingress rules contain a backend at the root level, meaning a service
which is the fallback is none of the Ingress rules actually match.
While this flag was present, it is not being used anywhere in the
codebase and will not be used in future.
This is a breaking change and users are advised to update their
YAML deployments to remove the flag, else the controller will fail to
boot up.
=> feat: drop --default-backend-service CLI flag

deploy/manifests/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless.yaml
Fix the deployment labels to be app=kong so that it will be
matched with kong-proxy service
=> fix(deploy) fix dbless yaml with correct labels

deploy/manifests/kong-ingress-dbless.yaml, deploy/manifests/kong.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres.yaml
k8s sends SIGTERM to the containers to terminate which results in nginx
dropping requests.
This ensures that nginx gets a SIGQUIT to gracefully shutdown before
getting a SIGTERM.
=> feat(deploy) introduce a preStop hook for graceful shutdown of Kong

deploy/manifests/rbac.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres.yaml
Role and RoleBinding resources are not needed if all ClusterRole
resource grants accesses to those resources at cluster level.
The ConfigMap resource used for leader election is now allowed
permission at the cluster level which shouldn't be a problem for most
installations.
=> feat(deploy) drop Role and RoleBinding resources

internal/ingress/controller/kong.go
Not assigning a certificate ID to the cert being added to deck's
target state results in only the most recently updated cert to be
persisted in Kong.
While we fix this issue by correcting the typo, we are not able to add a
unit or integration test at this point. This is being addressed with the
on-going work to refactor parser and store out of the controller logic
and also with integration tests and simpler API in deck for using deck
as a library.
Fix #285
=> fix: ensure multiple certs are created

internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
Ingress spec allows for an Empty Path in the rules, this results in a
schema violation in Kong.
When an empty path is found, Ingress Controller will add a harmless `/`
to it to avoid this schema violation.
See #298
=> fix: add / when Path in an Ingress is empty

internal/ingress/controller/kong.go, internal/ingress/controller/kong/dbless/kong_inmemory.go, internal/ingress/controller/parser/parser.go
Consumer level plugins can be configured using plugins.konghq.com
annotation on the KongConsumer resource.
See #250
=> feat: implement consumer-level plugins

internal/ingress/controller/plugin_schema_helper.go, internal/ingress/controller/plugin_schema_helper_test.go
The plugin fill logic will correctly respect nested configuration
values.
See #294
=> fix: ensure plugins with nested schema are configured correctly

internal/ingress/controller/controller.go, internal/ingress/controller/kong.go
If the hash of the configuration is same, then it is safe to assume that
the configuration has not changed.
This is similar to `check_hash` feature that comes with Kong 1.2, only
that we avoid the API call itself.
=> feat: skip a sync call if config has not changed in dbless mode

cli/ingress-controller/flags.go, cli/ingress-controller/main.go, internal/ingress/controller/controller.go
This commit adds the feature of configuring workspace to sync the
configuration to inside Kong Enterprise deployment model.
This opens up an array of possible deployment options for Kong
Enterprise:
- For each Ingress.class, configuration could be synced to separate
workspaces
- For each namespace, an Ingress Controller could be running, syncing
configuration of that particular namespace to a corresponding workspace
in Kong.
=> feat: implement Kong Enterprise workspace compatibility

docs/README.md, docs/concepts/deployment.md, docs/concepts/design.md, docs/concepts/ha-and-scaling.md, docs/concepts/security.md, docs/guides/getting-started.md, docs/troubleshooting.md
**What this PR does / why we need it**: Fixes a few miscellaneous typos in the documentation.
**Which issue this PR fixes**: N/A
I noticed that the repo's readme mentions:
`
⚠️ Kong Ingress Controller takes care of managing all entities in Kong's datastore as per the Ingress and custom resource definitions in k8s. Any entity created using Kong's Admin API will be deleted by the Ingress Controller.
`
however the [FAQ mentions that it is possible](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/faq.md#is-it-possible-to-create-consumers-using-the-admin-api) to create resources outside of the controller. I'm still looking into using Kong so I haven't yet tested it myself, but it would be great if these statements could be made …
=> Fix documentation typos

.travis.yml
Use GOPROXY=https://proxy.golang.org to speed up CI by a little bit.
=> chore(ci) use GOPROXY to speed up module download

internal/ingress/annotations/annotations.go, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
Problems
--------
1. Kong Ingress Controller configures targets in Kong based on the
endpoints of the corresponding Kubernetes service. This allows Kong
to be used a load-balancer, but Kong then by-passes kube-proxy.
There are use-cases where kube-proxy should handle load-balancing
and Kong should send traffic to kube-proxy instead of pods.
This was not possible.
2. In Kong, the `host` header sent to upstream is set to the IP
value of the target picked for the request (unless `preserve_host`
is set to true in the route selected for routing the request).
This breaks routing in certain cases(see #330) when the upstream
routes or responds based on the `host` header it receives in the
request.
Solution
--------
Both of these problems are being addressed by populating the target of
the service …
=> feat: introduce ingress.kubernetes.io/service-upstream annotation

internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
- Different certificates with the same TLS cert-key pairs are now
de-duplicated by the controller before pushing the configuration to
Kong/decK.
- If an SNI is seen multiple times, it will be associated with only a
single certificate (which one is not deterministic with this commit).
- If an empty secret of a secret with an invalid key-pair is seen, the
controller will reject that and not push the invalid configuration to
Kong.
Furthermore, this commit introduces the use of FakeStore for
unit-testing of the `Parser` module.
Fix #360
Fix #327
Fix #321
Fix #297
=> fix(parser) de-duplicate TLS certificate an SNIs

deploy/manifests/custom-types.yaml, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
Changelog:
- HTTP header based routing
- Load balancing algorithm selection per service; new `least-connections` load balancer
Fix #347
=> Feat/kong 1.3

cli/ingress-controller/flags.go, cli/ingress-controller/main.go, internal/admission/server.go, internal/admission/server_test.go, internal/admission/validator.go
Users frequently stumble onto situation where a misconfigured plugin
stops the entire controller from functioning.
It is now possible to setup an admission validation webhook to prevent
users from mis-configuring plugins and consumers.
Documentation on how to configure the controller will be published soon
and this controller will include KongCredentials in the future.
Fix #245
=> feat: implement admission controller for configuration.konghq.com group

cli/ingress-controller/main.go, internal/ingress/controller/controller.go, internal/ingress/controller/kong.go
Kong Enterprise 0.36 is based on Kong 1.2 core:
https://docs.konghq.com/enterprise/changelog/#036
`https_redirect_status_code` property was introduced in Kong 1.2 and
this needs to injected when Kong Enterprise is running.
This ensures that decK detects no change in state and fires no
Admin API requests while performing a full-sync during idle conditions
i.e. when there are no changes in the k8s cluster.
=> feat: ensure Kong Enterprise 0.36 compatiblity

README.md
The upcoming 0.6 release adds support for Kong 1.3 and Kong Enterprise 0.36.
=> docs(readme) update version support matrix with new releases

deploy/manifests/postgres/kong-ingress-postgres.yaml, deploy/manifests/postgres/migration.yaml, deploy/single/all-in-one-postgres.yaml
Since 4a94cb3 when you try to apply all-in-one-postgres.yaml you'll get at
proxy sidecar log:
nginx: [error] init_by_lua error:
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:25: New migrations
available; run 'kong migrations up' to proceed
stack traceback:
[C]: in function 'error'
/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:25:
in function 'check_state'
/usr/local/share/lua/5.1/kong/init.lua:358: in
function 'init'
init_by_lua:3: in main chunk
The reason behind this is that the migrations part of the manifest wasn't
bumped to 1.3
This PR bumps these parts of the manifests …
=> Fix "New migrations available" at proxy sidecar

docs/guides/getting-started.md
Some users deploy the in-memory version of Kong, which results in
errors if the storage policy is not set to `local`.
=> docs: use local policy for rate-limiting

deploy/manifests/base/kong-ingress-dbless.yaml, deploy/manifests/dummy-application.yaml, deploy/manifests/enterprise/kong-enterprise.yaml, deploy/manifests/postgres/kong-ingress-postgres.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Deployment is available under apps/v1 apiVersion since Kubernetes 1.9
(almost 2 years ago).
Deployments under extensions/v1beta1 apiVersion are no longer served by
default from kubernetes 1.16 onwards.
=> deploy: update apiVersion for Deployments to apps/v1

docs/deployment/README.md, docs/deployment/eks.md
Adds a guide for using KIC with EKS, which is a major demand.
Please verify that this [EKS guide](https://aws.amazon.com/getting-started/projects/deploy-kubernetes-app-amazon-eks/) is the best option Amazon has.
walk through -> walkthrough ("walkthrough" is a compound noun; "walk through" is a phrasal verb) 
setup -> set up ("set up" is a phrasal verb; "setup" is a compound noun)
=>  docs(deployment) add EKS deployment guide

deploy/manifests/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
In a containerized environment, `get_nprocs()` returns the same number
of CPUs as in the underlying physical host or Virtual Machine.
In a Kubernetes environment, users run larger hosts and pack multiple
workloads, including Kong into a small number of machines.
In such situations, Kong's underlying Nginx spawns up a larger number of
worker assuming that it is indeed running on a box with all the cores
for itself. This leads to two problems:
- having more workers than necessary leads to scheduling and
context-switching overhead; this has a direct impact on the latency
introduced by Kong as the request is proxied via it.
- Each worker process also aggressively caches configuration at the
process level, which frequently leads to memory exhaustion.
Due to these reasons, a default setting of …
=> deploy: use one worker process by default

internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
Adds port to Kong service hostnames, in turn adding the port to the associated upstream name.
This prevents collisions and/or misdirected traffic when a Kubernetes Service exposes multiple ports, and Ingress rules use two or more of those ports. Previously, rules for different ports on the same Service would attempt to use the same Kong service/upstream hostname.
Fixes #335
Tests cover Kong service generation only. I reviewed whether it would be useful to separately test `Parser.getUpstreams()` for this, but determined it unnecessary--we do not pass Kubernetes Services to it directly, but rather generate Kong services first and then get upstreams for each Kong service.
=> Fix upstream/service collisions for multi-port Kubernetes Services

cli/ingress-controller/main.go, cli/ingress-controller/util.go
If Kong Enterprise workspace doesn't exist, the controller simply errors
out.
With this change, the controller tries to create a workspace before
erroring out.
If the creation is successful, then it proceeds as usual.
=> feat: create Kong Enterprise workspace when not present

docs/deployment/admission-webhook.md
Fix cert names when creating the secret for validation webhook
Error saw before
```
E1024 15:00:41.568756       1 main.go:315] error running the admission controller server:open /admission-webhook/tls.crt: no such file or directory
```
It worked fine after my change
=> Fix secret cert names

cli/ingress-controller/flag_test.go, cli/ingress-controller/flags.go, cli/ingress-controller/main.go, cli/ingress-controller/main_test.go, go.mod, go.sum, internal/ingress/controller/controller.go
Revamps the CLI configuration and flags of the controller.
The controller can now be configured using environment variables and certain flags are marked as deprecated.
This also enables users to use k8s secrets for sensitive values like authentication header to use against Kong's Admin API, which had to be stored in plain-text previously.
=> feat: new cli parsing and environment variable

internal/ingress/task/queue.go
This can potentially lead to leaking of secrets and other sensitive
information in the logs.
=> fix(queue) do not log every item that is being queued

cli/ingress-controller/flag_test.go, cli/ingress-controller/flags.go, cli/ingress-controller/main.go, internal/ingress/controller/controller.go, internal/ingress/controller/kong.go
The new flag can be used to tweak the tag that is used by the Ingress
controller to filter entities it manages and also tag entities it
creates.
This is configurable and should not be changed once the Ingress
Controller is deployed with a database. If the need be, then the
database should be truncated before changing this.
=> feat(cli) implement --kong-admin-filter-tag flag

cli/ingress-controller/flag_test.go, cli/ingress-controller/flags.go
This is a breaking change from the last release, where the default was
set to `:8080` and the server would start up if the user mounted the TLS
cert-key pair.
This is to ask users to ask them to opt-in into the Admission
Controller.
=> feat(cli) admission webhook set to `off` by default

internal/admission/server.go, internal/admission/server_test.go, internal/admission/validator.go, internal/admission/validator_test.go
The validation currently consists of verifying if each and every
required field is provided by the user or not.
In future, the validation can be made smarter to include an Admin API
call to Kong to verify if the creation of such a credential will succeed
or not (see TODO in code).
=> feat(admission) implement validation for secret-based credentials

docs/guides/using-kongplugin-resource.md, docs/references/external-service/externalname.md
Fixes ExternalName; now the url is one that does not sit behind kong cloud.
=> update mockbin to httpbin

README.md
Adds Kong Enterprise 1.3 compatibility information to matrix.
So far as I know, Enterprise 1.3 does not add any features from core 1.3 that would make it incompatible with 0.6.x, and I did not find any existing issues indicating otherwise.
=> docs(readme) add Enterprise 1.3 to matrix

README.md
This README had a broken link to the Enterprise installation description
=> Fixed broken link to Enterprise documentation

deploy/manifests/base/custom-types.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Kong 1.4 ships with the capability to change the host header sent to the
upstream service. This commit adds the property to the CRD.
deck 0.6 adds the capability to configure the property in Kong.
=> deploy: introduce host_header property in KongIngress

internal/ingress/controller/kong.go
The `algorithm` in the `upstream` entity defaults to `round-robin`.
This field was introduced in Kong 1.3.0.
If this field is not set, decK finds a diff between the current state
and target state and issues a PUT request to Kong, updating the upstream
in Kong's database.
This leads to a cache invalidation and rebuilt of upstreams in Kong,
causing performance degradation.
The code now injects the algorithm based on the version of Kong (or Kong
Enterprise). Kong Enterprise 1.3.0.0 will also pick this change
correctly.
=> fix: populate algorithm of Upstream for Kong >= 1.3.0

cli/ingress-controller/flag_test.go, cli/ingress-controller/flags.go, cli/ingress-controller/main.go, internal/ingress/controller/controller.go, internal/ingress/controller/kong.go
This flag can be used to control the maximum number of concurrent
requests that are sent to Kong's Admin API in the DB-mode.
This can be used in debugging and to slow down the controller when Kong
is being backed by Cassandra (not recommended).
=> feat(cli) implement new --kong-admin-concurrency flag

internal/ingress/annotations/annotations.go, internal/ingress/annotations/annotations_test.go, internal/ingress/controller/kong/dbless/kong_inmemory.go, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
Kong can present a client certificate during a TLS handshake to the
upstream service. This is configurable for each service in Kong (each
kubernetes service maps to a service in Kong).
Users can use `configuration.konghq.com/client-cert` annotation on the
service resource in k8s to specify the secret which should be used by
Kong for client authentication.
Fix #348
=> feat: upstream client certificate for each service

go.mod
Standardise go version in go.mod and .travis.yaml. 
Currently, go.mod is still specifying 1.12, however, the CI build is running with go 13.
=> chore(ci) update to go 13 in go.mod

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Links in github PR template are broken
=> docs(template) correct broken github template links

docs/guides/cert-manager.md, docs/guides/getting-started.md, docs/guides/using-kongingress-resource.md, docs/guides/using-kongplugin-resource.md
bit.ly/echo-server has Deployment/v1beta1 which has been deprecated and
removed from new Kubernetes versions.
bit.ly/echo-service has Deployment/v1.
Fix #507
=> docs(guides) update Deployment version to v1

docs/guides/cert-manager.md
Example was using old version, updated with example from https://cert-manager.io/docs/configuration/acme/#creating-a-basic-acme-issuer
The cert-manager example is not doable without much investigation time.
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/cert-manager.md
PR requested by @rainest 
See discussion: https://kubernetes.slack.com/archives/CDCA87FRD/p1579287594005300
=> docs(guides) correct ClusterIssuer example script

docs/guides/preserve-client-ip.md
I was pretty caught up configuring proxy protocol. Harry suggested I
add some docs to make it a little clearer. Now the
`preserve-client-ip.md` doc references the `KONG_TRUSTED_IPS`
environment value in the "Proxy Protocol" section. 👍
I followed these instructions in an AWS environment and proxy protocol
worked. My client IP was preserved.
=> docs(guides) preserve-client-ip.md references KONG_TRUSTED_IPS

internal/admission/server.go, internal/admission/server_test.go
When a KongConsumer is updated, check for unique username violation only
if the username has has changed.
Fix #501
=> fix(admission) correctly handle updates to KongConsumer resources

internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
Protocols, Enabled and other fields are processed for global plugins as
well. This was ignored previously.
Fix #502
=> fix(parser) global plugins are processed same as regular ones

internal/ingress/controller/kong.go
Kong 2.0.0 removed the `run_on` property on the `plugins` entity.
Controller's code always injects it avoid false positives during diffs.
The change nils the property for kong 2.0 and above only to avoid any
effect on Kong Enterprise, which follows a different versioning scheme.
Fix  #521
=> fix: do not inject plugin.RunOn when Kong >= 2.0.0

internal/ingress/annotations/annotations.go, internal/ingress/annotations/annotations_test.go, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
Users can now use `configuration.konghq.com/strip-path` annotation on
Ingress resource  to  control the strip_path property of corresponding
routes in Kong.
=> feat: new annotation for path stripping on Ingress resource

internal/ingress/annotations/annotations.go, internal/ingress/annotations/annotations_test.go
This commit moves annotations from `configuration.konghq.com` to
`konghq.com`. Thre previous annotations are now deprecated and will be
removed in a future release.
The annotations are mostly the same with the exception of:
- `configuration.konghq.com` is changed to `konghq.com/override`
- `plugins.konghq.com` is changed to `konghq.com/plugins`
=> feat: new annotations group konghq.com

deploy/manifests/enterprise-k8s/kong-enterprise-k8s.yaml, deploy/manifests/enterprise/kong-enterprise.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, docs/deployment/k4k8s-enterprise.md, docs/deployment/kong-enterprise.md
Use separate names for the kong-enterprise-edition and kong-enterprise-k8s registry secrets in documentation and manifests.
Related to https://github.com/Kong/charts/pull/65 and https://github.com/Kong/docs.konghq.com/pull/1825
=> Split registry secrets

go.mod, internal/ingress/status/status.go
Knative controllers expect a few status conditions to be set in order to
detect that the Ingress has been correctly satisfied.
=> hotfix: correctly set Knative Ingress status

docs/concepts/security.md
=> Security concepts docs typo fix

docs/references/annotations.md
Remove "/" from the anchor links in annotation reference. The automatic anchor generation does not include most types of punctuation, so the existing links are broken.
=> docs: fix broken annotation anchors

internal/ingress/annotations/annotations.go, internal/ingress/annotations/annotations_test.go, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
Add a new konghq.com/regex-priority annotation for Ingress resources.
=> Add new konghq.com/regex-priority annotation

cli/ingress-controller/main.go, cli/ingress-controller/main_test.go, go.mod, internal/ingress/controller/controller.go, internal/ingress/election/election.go, internal/ingress/status/status.go
The leader election procedure that ensures no more than one Kong ingress controller will update _Ingress_ "status" subresources should run for the life of the process. However, if the leader renewal attempts take longer than the configured ["renewal deadline"](https://pkg.go.dev/k8s.io/client-go/tools/leaderelection?tab=doc#LeaderElectionConfig) (15 seconds) to succeed, the election procedure terminates.
Since the ingress controller continues running even after such repeated election failure, ensure that the procedure starts again. Delay each restart via exponential backoff.
Fixes #561.
**Special notes for your reviewer**
I found that _staticcheck_ is displeased with a lot of this code base. I resolved several of its …
=> Restart Ingress status leader election cycle after premature exit

internal/ingress/annotations/annotations.go, internal/ingress/annotations/annotations_test.go, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
Add a `konghq.com/host-header` annotation for Services. The annotation sets the `host_header` parameter on the upstream associated with the Service, similar to the equivalent KongIngress setting added in bc506ef.
I forgot documentation for `regex-priority` and held off adding it for this one. Currently next does not have the fixes from 36474a5, and adding new docs would probably create conflicts. Do you have a standard process for rebasing next off master, or does it make more sense to just cherry-pick it?
=> Add host_header annotation for Services

cli/ingress-controller/flags.go, cli/ingress-controller/main.go, internal/ingress/controller/controller.go, internal/ingress/controller/kong.go
Disable the optimization of reducing the number of syncs when this flag
is enabled.
This should be used only if there is any human who has write access to
Kong's Admin API or Kong Manager in case of Kong Enterprise.
Fix #559
=> feat: implement --enable-reverse-sync flag

docs/deployment/eks.md
Add documentation for EKS cipher suite requirements.
=> Add cipher suite info to EKS documentation

internal/ingress/controller/parser/parser.go, internal/ingress/status/status.go
Knative requires DomainInternal in the status to be populated as it is
used for in-cluster communication.
Also fixed a corner case which occurs in knative conformance test only
where no headers are added. Kong 500s if all fields in
config of request-transformer are empty. This is a bug in Kong but we
are working around it with this change.
=> fix: correctly set knative status

CONTRIBUTING.md, deploy/manifests/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, hack/dev/start.sh
Updates example deployments and similar to use `--kong-admin-url` instead of `--kong-url`.
=> Use modern admin URL argument for base kong-ingress-dbless manifest

internal/ingress/annotations/annotations.go, internal/ingress/annotations/annotations_test.go, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
Adds the `konghq.com/methods` annotation for Ingress resources.
This validates the methods array based on the [upstream schema validation](https://github.com/Kong/kong/blob/2.0.3/kong/db/schema/typedefs.lua#L204-L207). It follows the pattern used for protocol validation: if any element is invalid, all elements are discarded and the controller logs an error.
=> Add methods annotation

docs/guides/preserve-client-ip.md
To preserve client ip `ExternalTrafficPolicy` need to be set to `Local`
=> Fix preserve client ip docs: ExternalTrafficPolicy setting

docs/guides/prometheus-grafana.md, docs/guides/using-kongingress-resource.md
Two places that need adjustment after the default for `strip_path` changed to `false` in 0.8:
1. `prometheus-grafana.md`: Without setting it to `true`, the later traffic generation step will generate a lot of errors rather than be silent as intended.
2. `using-kongingress-resource.md`: The configurations are already adjusted, but the text needed to change as well.
=> docs: Further adjust guides to new strip_path default

deploy/manifests/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Environment variables are easier to manage and override in the k8s ecosystem.
This change also changes the the Kong URL from `localhost` to
`127.0.0.1` because some support tickets indicated that the DNS was
resolving the IPv6 loopback interface for some (unknown) reason.
=> deploy: change CLI flags to environment variables

cli/ingress-controller/main.go
Running the controller with cassandra has caused all sorts of pains for
users.
We already don't provide any tooling and documentation around
running ingress controller with kong and cassandra.
Helm chart removed easy cassandra mode a while ago, this change emits a
warning. In a future version, the controller will not startup if kong is
running with cassandra as it's data-store.
Based on the current statistics, there is a very small group of
users that will be affected by this change.
=> feat: deprecate cassandra compatibility

deploy/manifests/base/service.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Originally, the policy was set to `Local` in order to preserve client IP
address out of the box. It turns out that doing so has been more harmful
and frustrating for most users.
Managed k8s offerings other than GKE don't respect this setting.
Especially, traffic routing from an NLB/ELB breaks down terribly if the
policy is changed to `Local`. Google's implementation has/had a bug
where TCP connections are throttled if the policy is `Local`.
Due to these issues, the service will use the default value of
`Cluster`.
This patch only removes the property rather than changing it to avoid
affecting any existing installations.
No installation should use these manifests as is, but rather create a
copy. We don't know how users rely on this so we are going to err on the
safer side.
=> deploy: change externalTrafficPolicy to the default of `Cluster`

internal/ingress/controller/kong.go, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go, internal/ingress/store/fake_store_test.go, internal/ingress/store/store.go
CA certificate is a core entity in Kong that enables storing ca
certificates in kong to be used for mtls verification of client
certificates.
This patch adds the ability to configure CA certificates in Kong for
both DB and DB-less modes.
All secrets containing the label `konghq.com/ca-cert: "true"` are
processed. The secrets should contain `id` and `cert` keys, which should
contain UUID and PEM-encoded certificate respectively.
Please note that secrets need to be labelled and not annotated. This is
intentional to keep search for the relevant secrets efficient.
The secret UID is not used and instead an explicit UUID is required to
support declarative configuration. One can't specify the UUID of
Kubernetes objects during create time, which means, the secret UUID will
change from run-to-run. …
=> feat: implement secret based ca-certificates

cli/ingress-controller/flag_test.go, cli/ingress-controller/flags.go, cli/ingress-controller/main.go
Adds flags to provide the admin CA certificate and admission webhook cert/key pair as strings, as opposed to their existing file path flags.
Tests are for the flags only. I didn't see tests for the details of what main.go loads, or tests elsewhere that appear to set these flags and confirm the content of internal structures.
Manual debugger verification looked fine (insofar as the variables populated and didn't fatally abort), and the webhook listen returned the correct certificate. Didn't have a proper Kong setup for the CA cert part to confirm successful verification.
Ditto negative tests: the other failure cases for args don't appear to have tests in main.go, so none added for these. Manual checks look fine.
=> Add flags to provide certificate PEM string

.github/workflows/test.yaml
Travis has been unreliably and slow.
This is currently porting over only testing.
Master branch builds need to be still ported over to Github Actions.
The other Travis has been super helpful and I'm stoked that he is on the
team!
Fix #548
=> chore(ci) setup Github actions as CI

docs/references/annotations.md, docs/references/cli-arguments.md
Docs for #628, #591, #597, and #609 were previously missing because most of them needed something from master. Master has since been merged into next, and these can now be added.
=> Add missing docs for previous PRs

deploy/manifests/enterprise-k8s/kustomization.yaml, deploy/manifests/enterprise/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-postgres-enterprise.yaml
- Bump kong-enterprise-k8s to 2.0.4.1
Changelog: https://docs.konghq.com/enterprise/k8s-changelog/
- Bump kong-enterprise to 1.5.0.2
Changelog: https://docs.konghq.com/enterprise/changelog/
=> deploy: bump up enterprise image to the latest

docs/deployment/k4k8s-enterprise.md, docs/deployment/kong-enterprise.md
Enterprise users frequently run into problems with the current way the
secret is created. The files have extensions which cause problem later
on in the deployment and this has taken up a lot of time in debugging
several support tickets.
The new format makes it clear and avoids problems when the file has an
extension or is present in a different directory.
=> docs: specify key in --from-file parameter

cli/ingress-controller/flag_test.go, cli/ingress-controller/flags.go, cli/ingress-controller/main.go, internal/ingress/controller/controller.go, internal/ingress/controller/kong.go, internal/ingress/controller/kong_test.go
Problem
-------
As of today, there is no support in the controller
for custom entities inside Kong. The core custom entities related to
auth plugins are supported out of the box to cover all features that
Kong supports out of the box.
For Kong deployments backed by a database, a custom entity can be
populated via the Admin API and the controller will leave those entities
as is. These custom entities can then be referenced in plugin
configuration. While not perfect, this works currently.
For Kong deployments running without a database, there currently is no
way to setup custom entities.
Solution
--------
This patch adds the ability to add in custom entities into DB-less
instances via a Secret. The secret should have a JSON encoded
representation of he custom entities inside a key with the …
=> feat: implement support for custom entities in DB-less mode

internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go
A path with consecutive double slashes is considered invalid by Kong and
the reconcililation loop will break in Kong if such a route is added to
the configuration.
Fix #614
=> fix(parser) skip processing ingress rule with invalid '//' path

deploy/manifests/base/custom-types.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, hack/dev/common/custom-types.yaml
Despite https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#jsonschemaprops-v1beta1-apiextensions-k8s-io indicating that `properties` is a generic object (that presumably uses OpenAPI syntax), it is apparently instead a nested JSONSchemaProps and uses the same top-level array of required elements rather than the OpenAPI inline required booleans :shrug:
=> Fix CRD definition

cli/ingress-controller/flags.go
This reverts commit db0576642738d111bad71663a4ef517d8966a22b.
This actually doesn't error and works well. Removing this results in no
logs from glog.
=> Revert fix: remove statement that always errored"

docs/references/custom-resources.md
Adds documentation to KongConsumer reference indicating that `username` and `custom_id` need to be unique across namespaces.
This intentionally does not go into workspaces since we don't have much other documentation on that and because workspaces complicate consumer usage a lot. I've added a card to track this and other docs that need additions to account for workspaced workflows: https://trello.com/c/j8eiEszz/433-kic-with-workspaces
=> Warn about unique consumer fields in docs

docs/references/plugin-compatibility.md
Adds proxy-cache to the plugin matrix. I missed it before somehow.
=> Add proxy-cache to plugin matrix

hack/deploy-admission-controller.sh
BSD version of `base64` doesn't have `-w` flag and doesn't need any
options either because it doesn't wrap lines.
=> fix: make admission controller script compatible with macOS

deploy/manifests/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
`kong-ingress` is a service exposing low ports `tcp/80` and `tcp/443`. The implementation detail of `deploy/` is that these get NAT'ed by kube-proxy to high container ports `tcp/8000` and `tcp/8443` of the proxy container. Without knowledge of the externally exposed low ports, Kong puts those high ports in `X-Forwarded-Port` request headers which end-users can consider surprising, incorrect and unnecessarily exposing the implementation details of the Kong deployment.
This PR sets `KONG_PORT_MAPS` to enable Kong's feature to perform a reverse address translation for the purpose of identifying the actual port a request was received on by the service.
~This feature is present in Kong as of `2.1.0-beta.1`, hence also an upgrade of Kong.~ _edits per …
=> deploy: Define port_maps for Kong (OSS + Enterprise)

docs/guides/prometheus-grafana.md, docs/guides/redis-rate-limiting.md, docs/guides/using-kongplugin-resource.md, docs/references/custom-resources.md, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go, internal/ingress/store/fake_store_test.go, internal/ingress/store/store.go
* Removes support for global KongPlugins, in favor of allowing this on KongClusterPlugin only.
* Updates documentation using global KongPlugins to use KongClusterPlugins.
Fixes #681
This change only removes support. It does not do anything to warn about existing KongPlugins with the global label. Users will need to review (future) changelog documentation to know that they need to migrate configuration, and their existing global plugins will break (the controller will not look for them and they will no longer be applied to Kong/will be removed from Kong during …
=> Remove support for global KongPlugins

.editorconfig
GitHub displays tab characters in `*.go` files 8 characters wide. That makes viewing side-by-side diffs hungry for screen estate, and makes code reading exhausting (at least for me).
There's an editor-agnostic format for code styling, `.editorconfig`, which Github among others (e.g. JetBrains IDEs) respects.
This PR makes GitHub (and compatible editors) render tabs 2 letters wide. Affects code browsing and diffs/PRs/etc.
Proof that it works: [an example Go file](https://github.com/Kong/kubernetes-ingress-controller/blob/style/editorconfig/internal/admission/server_test.go). Compare with [this](https://github.com/Kong/kubernetes-ingress-controller/blob/edc272ad6316f82459a24efc4aabdc4df4fcd334/internal/admission/server_test.go).
Setting the width to 2 …
=> [proposal] style: set GitHub tab rendering to width 2 

cli/ingress-controller/flag_test.go, cli/ingress-controller/flags.go, cli/ingress-controller/main.go, cli/ingress-controller/main_test.go, docs/guides/using-oidc-plugin.md, go.mod, go.sum, internal/admission/server.go, internal/admission/server_test.go, internal/admission/validator.go, internal/ingress/controller/controller.go, internal/ingress/controller/kong.go, internal/ingress/controller/kong_test.go, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go, internal/ingress/election/election.go, internal/ingress/status/status.go, internal/ingress/status/status_test.go, internal/ingress/store/store.go, internal/ingress/store/store_test.go, internal/ingress/task/queue.go, internal/ingress/task/queue_test.go, internal/ingress/utils/reports.go, internal/ingress/utils/reports_test.go, pkg/apis/configuration/v1/types.go
This commit uses logrus to implement structured logging throughout the
repository.
Two new flags have been introduced for managing logging: `--log-level`
and `--log-format`.
Fix #712
Fix #506
=> feat: implement structured logging and remove glog

cli/ingress-controller/util.go, go.mod, internal/admission/server.go, internal/admission/server_test.go, internal/admission/validator.go, internal/ingress/controller/controller.go, internal/ingress/controller/kong.go, internal/ingress/controller/parser/parser.go, internal/ingress/controller/plugin_schema_helper.go, internal/ingress/status/status.go, internal/ingress/store/fake_store_test.go
Removes the use of github.com/pkg/errors package and instead uses error checking additions shipped in Go 1.13.
This is based on top of #748. Review the HEAD of the PR. I'll rebase once 748 is merged in.
=> refactor: replace pkg/errors with %w

CONTRIBUTING.md
=> docs: fix the building part in CONTRIBUTING.md

.github/workflows/master-mirrors-main.yaml
Adds a CI job triggered for pushes to `main` which pushes CI HEAD to `master`.
Does not rewrite `master` history for added defensiveness (`git push` without `-f`).
fixes #792
Tested manually with a different pair of branches.
=> ci: automatically move master to follow main

docs/deployment/k4k8s-enterprise.md
The Helm 3 command to install currently uses the `--name` flag, which was removed/is only available in Helm 2.
Fix #758
=> Correct broken Helm 3 command

internal/ingress/annotations/annotations.go, internal/ingress/annotations/annotations_test.go, internal/ingress/controller/parser/parser_test.go, internal/ingress/store/fake_store.go, internal/ingress/store/fake_store_test.go, internal/ingress/store/store.go
* Updates the last permissive legacy class matching logic (for Knative and CA certificate secrets) to their modern, exact match logic.
* Updates CA certificate tests to include class annotations.
* Use a reference to the default class exported by annotations rather than the literal `"kong"` string in tests.
* Explicitly sets global KongPlugin matching to ExactOrEmptyMatching.
fixes #739 
fixes #731 
Changes for #731 are a composite of this and the implementation for #732, which was merged in #767. See comments in #731 for additional details.
We had originally discussed also rolling removal of the `ListGlobalKongPlugins()` store function into this, but on further review, we should …
=> Update remaining resource ingress.class behaviors

internal/ingress/controller/controller.go
Delete code that instantiates a list of ingresses from Store,
sorts the list in place, and then discards that list.
My understanding is that this code has no effect.
=> fix(controller): remove a no-op sort of ingresses

internal/ingress/status/status.go, internal/ingress/status/status_test.go
This PR makes `statusSync` update the `status` of Ingress v1 resources in Store just like it does for Ingress v1beta1.
Includes a test (equivalent to the v1beta1 test).
Notes to reviewers:
- This implementation (and test) is an almost direct copy of the preexisting v1beta1 code, including todos and bugs (most notably #829). For review comments regarding v1 functionality, please think whether the same problem applies to v1beta1. For such (preexisting) problems, use your best judgment to tell if a fix should belong in scope of this PR (which I define as "introduce v1 syncing") or not (and be therefore reported as an issue affecting both v1beta1 and v1 to be fixed later)
- Consider not squashing when merging
=> ingress V1: implement status sync

docs/README.md, docs/concepts/custom-resources.md, docs/concepts/ingress-classes.md, docs/concepts/resource-classes.md, docs/deployment/admission-webhook.md, docs/guides/cert-manager.md, docs/guides/configure-acl-plugin.md, docs/guides/configuring-fallback-service.md, docs/guides/configuring-health-checks.md, docs/guides/configuring-https-redirect.md, docs/guides/getting-started.md, docs/guides/prometheus-grafana.md, docs/guides/redis-rate-limiting.md, docs/guides/using-consumer-credential-resource.md, docs/guides/using-external-service.md, docs/guides/using-ingress-with-grpc.md, docs/guides/using-kongclusterplugin-resource.md, docs/guides/using-kongingress-resource.md, docs/guides/using-kongplugin-resource.md, docs/guides/using-mtls-auth-plugin.md, docs/guides/using-oidc-plugin.md, docs/guides/using-rewrites.md, docs/guides/using-tcpingress.md, docs/references/annotations.md, docs/references/custom-resources.md
Adds documentation describing how the controller handles ingress.class annotations.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #677
- Changes indicate when class annotations are required, but not when they are not required. I don't think it's as important to call out the latter, since worst case a user adds an annotation and it does more or less nothing (the only point of confusion may be that adding a class annotation to those resources, e.g. KongPlugin, does not prevent their use by other controllers). The new resource-classes.md concept guide should cover that: it goes over how classless resources …
=> Add ingress class docs

internal/ingress/controller/parser/kongstate/types.go, internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go, internal/ingress/controller/parser/translate.go
Fixes #836
This PR:
- refactors KongState to use `PortDef` instead of `intstr.IntOrString` for the following benefits:
- Explicit semantics of port matching (by name, by number, or the only port of the service)
- Further decoupling of `package kongstate` from k8s APIs
- implements all port definition flavors from ingressv1 KEP (#836) in parser
- implements a test verifying that parser puts the right endpoints for all of the flavors mentioned above
Consider merging without squashing.
=> Ingress V1: port matching without port number

cli/ingress-controller/flags.go, cli/ingress-controller/main.go, cli/ingress-controller/main_test.go, internal/ingress/annotations/annotations.go, internal/ingress/annotations/annotations_test.go, internal/ingress/store/fake_store.go, internal/ingress/store/fake_store_test.go, internal/ingress/store/store.go
**Цо ПР ділать бы, и пошімў**:
This handles Ingress v1 class, as we need to handle Ingress v1 class.
**Пробрэма, хторюю хорректировяло ПР**: fixes #790
**Нёты**:
This is in very rough draft state, so it's bad, untested, and full of misery, but it should be :smile: 
- AFAIK we do indeed intend to have separate flags for ignoring class on v1 Ingress and v1beta1 Ingress--I think I remember that from previous discussions, and it seems a bit weird (SO MANY FLAGS), but eh, whatever.
- "annotations" is in a weird spot: the minimally invasive version of this adds a new function generator there, but it's for something that's no longer an annotation. Other option was to export `validIngress` and stick the Ingress V1 validator function in store, but eh, that's no good either.
- That the validation …
=> Handle Ingress v1 class

deploy/manifests/base/kong-ingress-dbless.yaml
This was mistakenly added during the merge of main branch into next.
=> deploy: drop security context from base manifest

docs/references/version-compatibility.md
closes #820
k8s 1.13 is not supported in KIC 0.9 or KIC 0.10 because we define `admissionReviewVersions` in our `ValidatingWebhookConfiguration` which was added to k8s in 1.14, and fails to apply in 1.13.
=> docs: define the KIC-Kubernetes compat matrix

.github/workflows/test.yaml, deploy/manifests/base/custom-types.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, hack/dev/common/custom-types.yaml, hack/verify-manifests.sh, pkg/apis/configuration/v1/types.go
Add status subresources to Kong CRDs, following the example at https://github.com/kubernetes/sample-controller/commit/ad67096f17e0ef1c48f761370cb2a2261fe84c42
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #824
**Notes/questions for reviewers**:
Searching for prior art on this brought me to https://book-v1.book.kubebuilder.io/basics/status_subresource.html also. Kubebuilder does some additional stuff on top where it adds `Status` to the struct as well, whereas this just strips the `+genclient:noStatus`  out of `types.go` and adds object statuses to `custom-types.yaml`.
It looks like that's where intend to go in the future (vaguely recalling …
=> Add status subresources to Kong CRDs

cli/ingress-controller/flag_test.go, cli/ingress-controller/flags.go, docs/concepts/security.md, docs/references/cli-arguments.md
Remove deprecated 0.x.x flags. Remove logic for giving deprecated flags
precedece. Update docs to mention modern flags only.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #840 
Related tests removed entirely, as we no longer have any deprecated flags. Will we have any in the future? Probably. Figured it made more sense to cut out the existing tests entirely for now rather than leaving no-op stubs. We can always retrieve the old diff assuming we need to re-add similar tests later for future deprecations.
=> chore(flags) remove deprecated flags

internal/ingress/controller/controller.go
There a few comments seem to be part of ingress-nginx's code.
It's unnecessary and confusing.
=> chore: remove ingress-nginx's comments

internal/ingress/controller/kong.go
This commit removes workarounds in the code to keep supporting Kong 1.x
series.
The controller is now compatible with Kong 2.x only.
Fix #701
=> feat: drop compatibility with Kong 1.x

docs/guides/upstream-mtls.md, docs/references/annotations.md, internal/ingress/annotations/annotations.go, internal/ingress/annotations/annotations_test.go, internal/ingress/controller/parser/kongstate/kongstate_test.go, internal/ingress/controller/parser/kongstate/route_test.go, internal/ingress/controller/parser/kongstate/service_test.go, internal/ingress/controller/parser/parser_test.go
Removes deprecated annotations.
Tests still use literal `"konghq.com/regex-priority": 3` style test values instead of `AnnotationPrefix + RegexPriorityKey: 3` package constants. We're kinda moving towards the latter in general, though you could make the argument that we want the literal strings so tests complain in the event that we change something: while that works in code using the constants, users won't have changed their annotations in advance if we release such a change, so those literals could serve as a useful canary to make sure that we call out breaking changes if we do change these in the future.
Several tests outside the annotations package referenced `annotations.DeprecatedPluginsKey` and now instead …
=> Remove deprecated annotations

docs/deployment/eks.md
Updates EKS deployment guide to make it more EKS-like
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #493 
The `PROXY_IP` name is now a misnomer, but shouldn't matter in practice as it'll resolve under the hood. Left as-is since we use that same variable name elsewhere and changing it would probably do more harm than good.
Github doesn't appear to want to let me add non-org member reviewers of my choice, but @harshal-shah does this look good to you? I don't have an EKS cluster ready to check myself, so this is a combination of the suggested change from the issue and a status that looks more or less like …
=> Use EKS-like status

CHANGELOG.md, CODEOWNERS, MAINTAINERS.md, Makefile, deploy/manifests/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, docs/deployment/eks.md, docs/references/cli-arguments.md, docs/references/version-compatibility.md, hack/dev/common/custom-types.yaml, internal/ingress/controller/controller.go
Merge main into next and release 1.0.0-rc.1
We have not previously released a release candidate version. Absent previous controller RC releases to mimic, I've attempted to follow the style conventions used by the `kong` repo, namely:
- The RC version format is x.y.z-rc.RCCOUNTER
- CHANGELOG.md stages expected 1.0.0 changes under a "1.0.0-rc.1" header. We will need to change this to "1.0.0" and update the anchor date before final release, and move any subsequent RC changelogs under the consolidated 1.0.0 changelog section. Slight deviation from `kong` here: at least for the 2.0.0-rc.1 release, it used [a "2.1.0rc1" header](https://github.com/Kong/kong/blob/2.1.0-rc.1/CHANGELOG.md#210rc1). I kept the `.` between …
=> Release 1.0.0-rc.1 to next

README.md
fixed links to latest bintray 'master' builds. the header still says "Master branch builds". Not sure what to change that to.
=> fix links to bintray builds

internal/ingress/controller/parser/parser.go
service.Name for this point is kong.String('') and it's pointer to string. As a result in logs I can see only RAM address:
`time="2020-10-20T12:39:52Z" level=warning msg="skipping service - getServiceEndpoints failed: no suitable port found" component=store service_name=0xc000bacaf0
time="2020-10-20T12:39:52Z" level=warning msg="skipping service - getServiceEndpoints failed: no suitable port found" component=store service_name=0xc000bac9a0`
And after fix:
`time="2020-10-20T14:35:02Z" level=warning msg="skipping service - getServiceEndpoints failed: no suitable port found" component=store service_name=default.kong-ingress-add-gcp-stg-zendesk-sso-gcp-stg-root.80
time="2020-10-20T14:35:02Z" level=warning msg="skipping service - getServiceEndpoints failed: no suitable port found" …
=> Log print memory address instead service.Name

docs/guides/upstream-mtls.md
Doc is incorrect and will prevent Kong from starting because it tries to use a bool for an int setting. This fixes it with a reasonable value for most environments.
=> Use number for verify depth

deploy/manifests/enterprise-k8s/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, docs/deployment/k4k8s-enterprise.md
- Updates Enterprise manifests to use kong-enterprise-edition at the current latest patch version.
- Updates registry secret instructions to use kong-enterprise-edition.
I missed the KIC repo version/registry in the course of updating various pieces of documentation to reflect the switch from kong-enterprise-k8s to kong-enterprise-edition, which broke instructions elsewhere that _were_ updated when attempting to deploy using the example Enterprise manifests here.
That may have been intentional when 2.1 Enterprise was still in beta. It no longer is, so everything should now reflect the current 2.1 kong-enterprise-edition guidance for new installs. I think this was the last of the holdouts :crossed_fingers:  …
=> Update Enterprise manifest examples and docs

docs/guides/configure-acl-plugin.md, docs/guides/using-kongclusterplugin-resource.md, docs/references/custom-resources.md
Several pieces of documentation still used the old `plugins.konghq.com` annotation. This change updates those to use the modern `konghq.com/plugins` resource.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #920 
Fixed several instances after the initial report of the one. Hurray for sed!
Performed a cursory check through the docs.konghq.com repo to see if we have any of the old annotation there; we do not.
=> Use modern plugins annotation in documentation

CONTRIBUTING.md
Updates CONTRIBUTING to instruct contributors to use Golang 1.15.
Updated following a review of community resources and realizing that this looked outdated re https://github.com/Kong/kubernetes-ingress-controller/pull/816
=> Udate CONTRIBUTING Golang version

.github/workflows/build-test.yaml
Fixes the build failure https://github.com/Kong/kubernetes-ingress-controller/actions/runs/342391558 .
The reason for the failure is that `git rev-parse` works only if the git repository has been cloned. This is not necessary there - GITHUB_REF gives us the information we need.
=> chore(ci): obtain ref without git cloning

.github/workflows/test.yaml, Makefile, hack/verify-tidy.sh
Add a CI check to confirm whether go modules are tidy. If they are not tidy, complain!
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #917 
Demo failure on https://github.com/Kong/kubernetes-ingress-controller/pull/948/checks?check_run_id=1366090329
Shamelessly copy-pastaed script from https://github.com/grafana/grafana/pull/27204 with minor modifications to add problem-correction instructions.
=> Add CI check for untidy go modules

deploy/manifests/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, hack/dev/dbless/base/kong.yaml
KIC version of https://github.com/Kong/charts/issues/227
=> chore(deploy) update default worker count to 2

internal/ingress/controller/parser/parser_test.go, internal/ingress/controller/parser/translate.go
**What this PR does / why we need it**: Add override support for Knative Services
**Which issue this PR fixes**: fixes #838
=> Add override support for Knative Services

.github/workflows/build-test.yaml
CI is sad; this makes it not sad.
push-public has
```
if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next'
```
so this doesn't actually execute until the commit lands in main. This should suffice to confirm it gets what we want:
```
$ export GITHUB_REF="refs/heads/main"   
$ REF=`sed -re "s/^refs\/[a-z]+\///" <<< $GITHUB_REF`; echo $REF 
main
```
IDK much about bash's built-in pattern matching language, but brief research suggests it doesn't support the `+` operator or the PCRE-style classes we're using. sed definitely does, so may as well use that.
=> Fix invalid tag generation in CI

internal/ingress/controller/parser/kongstate/consumer.go, internal/ingress/controller/parser/kongstate/consumer_test.go
This is the band-aid solution discussed in https://github.com/Kong/deck/pull/223#issuecomment-719042303
It's effectively the same set of checks on the go-kong structs, but in the controller instead of deck. This allows us to log richer information than we would if we delegated this check to either deck or go-kong.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: Fix #532
Per comments in deck#223, this is an imperfect stopgap solution to a complicated problem
No new tests, as there's not a whole lot to test here. We could add one with one or more broken credentials, but given the band-aid nature of the solution …
=> feat(consumer) validate credential secret fields

deploy/manifests/enterprise-k8s/kustomization.yaml, deploy/manifests/enterprise/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-postgres-enterprise.yaml
The prepared deployment YAML files for Kong Enterprise still used to be on 2.1.4 and 1.5. Updated to latest version 2.2.0.0
As the bit.ly in the documentation pointed to those files prospects and customers got old (and very old - see 1.5) version installed instead of the latest one available.
=> Updated Kong Enterprise to 2.2.0.0 in deployments

cli/ingress-controller/main.go
Cassandra-backed Kong instance support is going away in 1.1.0 after being deprecated in 0.9.0. This replaces the deprecation warning with a fatal error
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #968
=> Remove support for Cassandra-backed Kong

CHANGELOG.md, Makefile, deploy/manifests/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Releases 1.1.0 to next. Bumps manifest controller version and Makefile version; updates changelog.
This is predicated on both #975 and #863.
This includes both release changes and a merge from main to next, to incorporate the doc migration changes and Enterprise default tag update that occurred after the last merge. #863 will further need a rebase after that and another round of manifest regeneration, so drafting this for now.
=> Release 1.1.0 to next

internal/ingress/controller/parser/parser.go, internal/ingress/controller/parser/parser_test.go, test/integration/cases/08-externalname/ingress.yaml, test/integration/cases/08-externalname/verify.sh
ExternalName Services have no ports of their own. They only receive ports when combined with an Ingress rule that specifies them.
`findPort()` currently returns an error if no port is available on the Service. ExternalName Services will thus [always return the no port error](https://github.com/Kong/kubernetes-ingress-controller/blob/1.1.0/internal/ingress/controller/parser/parser.go#L183).
This change adds the [0.8 logic for ExternalName Services](https://github.com/Kong/kubernetes-ingress-controller/blob/0.8.0/internal/ingress/controller/parser/parser.go#L1447-L1450) to `findPort()`, which just builds a ServicePort from the requested port. It returns errors from the non-numeric port cases indicating that they are not valid for ExternalNames. …
=> Retrieve ports for rules that use ExternalName Services

CONTRIBUTING.md
Per planning, we want to codify our stale issue/PR policy for our team's major community-facing repos. This updates our contributing documentation to reflect that.
=> Add stale issue policy

deploy/manifests/base/custom-types.yaml, hack/dev/common/custom-types.yaml
TCPIngress already had a subresource block with status when it was originally added. I added an extra one when updating the other resources.
No functional change at the moment since manifest generation de-duplicates and sorts fields already, but would become an issue if we added additional subresources later and they got out of sync.
Thanks to @slacksach for pointing out the issue.
=> Prune extra subresource block in TCPIngress CRD

README.md
Remove about Helm v2 in README.md due to Helm v2 Deprecation.
After November 13, 2020,No further Helm v2 releases.
[ref. helm-v2-deprecation-timeline](https://helm.sh/blog/helm-v2-deprecation-timeline/)
=> remove Get started about Helm 2

cli/ingress-controller/main.go, internal/ingress/store/store.go, internal/ingress/utils/ingressapi.go, internal/ingress/utils/ingressapi_test.go
Check if KongClusterPlugins are available from the API Server. If not, do not create their informer or store, and handle the store's absence elsewhere:
- When getting a specific plugin, return a not found error. This is equivalent to existing behavior when no KongClusterPlugin with that name is found; we just now assume that no such KongClusterPlugin exists because we know no KongClusterPlugins exist.
- When listing global plugins, silently return an empty list.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #717
We only want the above no-ops if the resource isn't available, though it doesn't appear that …
=> feat(*) disable KongClusterPlugins if unavailable

internal/ingress/utils/ingressapi.go
We're not fixing that bug today because it only affects EOL versions of Kubernetes, and there's a known workaround available.
This PR documents the bug and workaround in code.
=> bug: document #918 in a comment

.github/workflows/test.yaml, .gitignore, Makefile, README.md
This adds [codecov](https://codecov.io) coverage to our CI for pushes and PRs.
Fixes #835
Configuration available for maintainers at: https://app.codecov.io/gh/Kong/kubernetes-ingress-controller
=> feat(ci) codecoverage

internal/ingress/controller/parser/kongstate/kongstate.go
`log.WithFields(...).Errorf()`  emits a log entry with all the recorded fields.
However, `log.WithFields(...).Logger.Errorf()` emits a log entry too, but without these fields.
This PR fixes the logger invocation by preventing it from dropping the recorded fields, by switching from calling the latter `Errorf` to the former.
fixes #1002
This logger invocation (and tens of others) includes the `error` in the message. With structured logging, the preferred way is to put an error in a field of its own. Filed #1013 to take care of that.
=> fix(kongstate): missing logger fields

.gitignore, deploy/manifests/base/custom-types.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, go.mod, go.sum, hack/dev/common/custom-types.yaml, internal/ingress/annotations/annotations.go, internal/ingress/annotations/annotations_test.go, internal/ingress/controller/parser/kongstate/route.go, internal/ingress/controller/parser/kongstate/route_test.go, internal/ingress/controller/parser/parser_test.go
Add options to `KongIngress` and ingress annotations for `request_buffering` and `response_buffering` options.
fixes #924
=> request response buffering options

CONTRIBUTING.md
While reviewing the `CONTRIBUTING.md` I noticed a dead link regarding submitting a patch, in its place I added a note about contributing a PR and how we use different base branches depending on the type of PR submitted.
=> fix(docs): add missing contributing docs related to PR base branches

.github/workflows/build-test.yaml, Makefile, test/integration/README.md, test/integration/util/create-cluster.sh
Makes it possible to specify the version of Kubernetes running KIC's integration test.
The choice is limited to available tags of the `docker/io/kindest/node` docker registry (which doesn't cover all releases at this moment). Asked `kind` maintainers (https://github.com/kubernetes-sigs/kind/issues/197#issuecomment-769034378) to increase coverage (specifically: start providing images for pre-release k8s builds as well)
=> test(integration): expose KUBE_VERSION

internal/ingress/controller/kong.go, internal/ingress/controller/parser/kongstate/consumer.go, internal/ingress/controller/parser/kongstate/consumer_test.go, internal/ingress/controller/parser/kongstate/credentials.go, internal/ingress/controller/parser/kongstate/credentials_test.go, internal/ingress/controller/parser/kongstate/kongstate.go, internal/ingress/controller/parser/kongstate/kongstate_test.go, internal/ingress/controller/parser/kongstate/types.go, internal/ingress/controller/parser/kongstate/types_test.go
Please review commit by commit and merge without squashing.
Inspired by #991.
This PR:
- defines Go types for credential types in KIC (as wrappers for `go-kong` types allowing for implementation of KIC business logic in those wrappers) consistently with wrappers for other `go-kong` types (`Consumer`, `Service`, `Route`, etc.)
- implements a recursive `Kongstate.SanitizedCopy()` produces a copy of `KongState` containing only a subset of `KongState` fields,
- refactors `SetCredential` by breaking its type-specific logic out to individual type creator functions `NewXXX()`
=> Implement recursive SanitizedCopy() for KongState, refactor SetCredential

cli/ingress-controller/main.go, internal/admission/validator.go
We don't currently support pulling configuration a KongPlugin's ConfigFrom configuration in the admission webhook. Some plugins have fields that must be populated and have no default, e.g. `issuer` for the OpenID Connect plugin. The only current remedy is to disable validation entirely, which isn't ideal.
This PR:
- Provides access to the store in the admission webhook, so that it can retrieve content from resources (in this case, a Secret) referenced by proposed resource.
- Validates that Secrets referenced by ConfigFrom exist, and uses the configuration in them when validating the plugin schema.
- Checks that a KongPlugin doesn't provide both Config and ConfigFrom.
- Uses the `configurationv1` import convention we use elsewhere for …
=> Let admission webhook check KongPlugins with secret configuration

Dockerfile
When I build kic in arm64 environment, I found GOARCH hard coded in Dockerfile.
=> fix: remove unnecessary GOARCH env in Dockerfile

test/integration/util/install-sut.sh
Addresses the CI issue @shaneutt noticed this morning. Latest kustomize changed the old `--load_restrictor` flag.
I'm not exactly sure what determines our kustomize version in test-k8s. I don't see anywhere we install it independently, so I'm guessing we get it from KIND? The KIND version didn't change, which suggests that it's pulling the latest kustomize down automatically. https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.0.1 is quite recent (12 days ago).
=> chore(ci) update kustomize flag

.github/dependabot.yml
Enables [Dependabot](https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates) for the KIC repository, so that we get PRs to `next` with Go module updates.
=> Enable Dependabot for KIC

railgun/test/integration/ingress_controllers_test.go
This PR adds a small integration test to validate upstream Ingress cleanup.
=> test: test upstream ingress route cleanup

railgun/keps/0004-kong-kubernetes-testing.md
This change adds more context and follow up to the KTF KEP which instigated the creation of [kong/kubernetes-testing-framework][ktf].
This is leading up to the first release version of v0.1.0 which is being tracked via [milestone 1][ms1].
[ktf]:https://github.com/kong/kubernetes-testing-framework
[ms1]:https://github.com/Kong/kubernetes-testing-framework/milestone/1
=> chore: moving the KTF KEP forward

.github/stale.yml
Our current stale[bot] config is way too restrictive. It has closed a lot of issues that shouldn't have been closed, which required manual intervention.
This PR follows a discussion among contributors. After this PR, stale[bot] will only act on issues labeled with `pending author feedback`
=> chore(stale): limit stale[bot] to issues labeled as "pending author feedback"

CONTRIBUTING.md, railgun/keps/0005-definition-of-done.md
fixes https://github.com/Kong/team-k8s/issues/39
Adds a section to CONTRIBUTING.md as described in the KEP https://github.com/Kong/kubernetes-ingress-controller/pull/1115
Also makes the KEP `implemented`.
=> chore(CONTRIBUTING): add the issue closing section in line with KEP#5

railgun/apis/configuration/v1/kongclusterplugin_types.go, railgun/apis/configuration/v1/kongconsumer_types.go, railgun/apis/configuration/v1/kongingress_types.go, railgun/apis/configuration/v1/kongplugin_types.go, railgun/apis/configuration/v1alpha1/udpingress_types.go, railgun/config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, railgun/config/crd/bases/configuration.konghq.com_kongconsumers.yaml, railgun/config/crd/bases/configuration.konghq.com_kongingresses.yaml
Adds the [storageversion kubebuilder tag](https://book.kubebuilder.io/multiversion-tutorial/api-changes.html#storage-versions) to the Railgun versions of our CRD types. Without this, manifest generation currently fails:
```
$ make test                                                                 
/home/traines/src/ingress-controller/railgun/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false,allowDangerousTypes=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
github.com/kong/kubernetes-ingress-controller/pkg/apis/configuration/v1:-: CRD for KongPlugin.configuration.konghq.com has no storage version
github.com/kong/kubernetes-ingress-controller/pkg/apis/configuration/v1:-: CRD …
```
=> Add storageversion tags to Railgun versions of CRD types

deploy/manifests/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
As part of the migration off Bintray, I've moved existing KIC images from Bintray to https://hub.docker.com/r/kong/kubernetes-ingress-controller/tags
This PR changes our manifests to use that Docker Hub repo.
Kong Enterprise images in manifests still use Bintray, as we're still waiting for Fast Track to migrate those.
=> Use Docker Hub KIC repo in manifests

.github/workflows/test.yaml
Replaces the existing `curl | bash` code coverage upload mechanism with an official GH Action.
Why?
- a GH action is more GitHub-native
- `curl | bash` is controversial
- the action is easier to parameterize
=> ci(coverage): switch to codecov GH action

.github/workflows/license.yaml
Adds a license change report workflow for PRs based on the spike in https://github.com/Kong/team-k8s/issues/40
The license checker tool is imperfect and cannot find licenses for everything, but it does still include lines for those packages:
```
github.com/xeipuuv/gojsonreference,Unknown,Unknown
```
We'd be alerted the first time those are added, but not if they change.
The workflow checks the PR for a license change after each commit until it finds one. Once it does find a change, it adds a `ci/license-status-change` label, and will not check again unless that label is manually removed. It adds a comment every time it runs and finds a diff, so without that label, it'd spam comments on commits since the start of …
=> ci(*) report if a PR results in a license change

.github/workflows/license.yaml
Handles the issue seen in https://github.com/Kong/kubernetes-ingress-controller/pull/1192/checks?check_run_id=2382616820
github-script is supposedly just JS, so [wrapping this in a try block](https://github.com/rainest/kubernetes-ingress-controller/actions/runs/764307898/workflow#L58-L68) _should_ handle this, but [doesn't](https://github.com/rainest/kubernetes-ingress-controller/runs/2382916706?check_suite_focus=true), hence the additional step.
=> ci(license) ignore unsuccessful label removal

.github/workflows/license.yaml
a435dc4 moved the wrong script block into the step that ignores errors.
This moves the "add changed label" call back into its original step
and the "remove unchanged label" into the step that ignores errors.
=> fix(ci) use the correct steps when license changes

.github/workflows/license.yaml
An earlier change from ci/license-status-unchanged to
ci/license/unchanged updated one instance of this label in the workflow
but not the other. This updates the remaining instance.
See failure in https://github.com/Kong/kubernetes-ingress-controller/runs/2392503019
=> fix(ci) correct license label

cli/ingress-controller/main.go, pkg/adminapi/client.go, pkg/adminapi/header_roundtripper.go, pkg/util/enablementstatus.go, railgun/cmd/rootcmd/rootcmd.go, railgun/manager/flagset.go, railgun/manager/manager.go
Fixes #1203 
Contributes towards #1097 
This PR does the following, in commit order:
- Extracts `cli/ingress-controller`'s Admin API `http.Client` creation logic to a function `makeHTTPClient`
- This preserves a bug: reported https://github.com/Kong/kubernetes-ingress-controller/issues/1233 and marked with a `// BUG` comment in the code. I decided not to touch the logic here, because avoiding regressions in KIC 1.x is the priority here.
- Changes the error handling mechanism inside `makeHTTPClient` from `log.Fatalf` to `return err`, for reusability in Railgun
- Decouples `makeHTTPClient` from `cliConfig` by introduction of `struct HTTPClientOpts`, for reusability in Railgun
- Moves `makeHTTPClient` to `pkg/adminapi` (I'm not particularly attached nor sure about this name - I'm open to …
=> KIC 2.0: introduce Admin API mtls and headers. Refactor and reuse KIC 1.x logic.

README.md
Add a notice in the top of the KIC README about the scheduled Bintray brownout and EOL, because this will impact existing users.
https://github.com/Kong/charts/issues/337
=> Readme: add Bintray notice

deploy/manifests/enterprise-k8s/kustomization.yaml, deploy/manifests/enterprise/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, test/integration/sut/kustomization.yaml
Use the new Docker Hub repo for Kong Gateway (aka Kong Enterprise), which became available today. Bump to the latest version.
Some documentation and build files still reference Bintray stuff. Those are left untouched in this since #1156 also touches them. The manifests are more critical as those will fail entirely if Bintray is unavailable; the rest is easier to work around.
=> deploy(*) update Gateway/Enterprise repo and tags

railgun/Dockerfile
This adds a workaround for `kubebuilder` validation of Dockerfiles, as we've moved our container build up one directory and this is not tolerated in kubebuilder `v3.0.0`. This will fix running `kubebuilder` commands in the `railgun/` project.
Relates to https://github.com/kubernetes-sigs/kubebuilder/issues/2165
=> fix: add a kb shim to work around Dockerfile validation

pkg/sendconfig/sendconfig.go, railgun/internal/proxy/clientgo_cached_proxy_resolver.go
This PR adds back the SHA update checks for updating the Kong proxy.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1280
=> fix: add kong update sha checks

cli/ingress-controller/main.go, go.mod, go.sum, pkg/util/logging.go, railgun/internal/proxy/clientgo_cached_proxy_resolver.go, railgun/manager/manager.go, railgun/test/integration/suite_test.go
Fixes #1224 
KIC 1.x uses logrus.
KIC 2.x:
- uses controller-runtime which uses logr.
- uses parts of KIC 1.x that use logrus.
- uses zap as the backend for logr.
This PR:
- makes all of the logging plumbed throughout the controller manager use logrus: the legacy parts use logrus directly, the controller-runtime parts use logrus through a shim that implements a logr frontend over logrus
- plumbs the structured loggers through (instead of using locally created loggers)
- ports the KIC 1.x log control flags over to KIC 2.x
- sets the log level and format for tests
Caveats:
- internals of client-go use klog that is not injected from anywhere, and it seems that we don't have control over it. So, this PR reduces the ecosystem of loggers in KIC 2.x from [zap, logrus, klog] to [logrus, klog]
=> logr backend: replace zap with logrus

cli/ingress-controller/flags.go
This PR is for correcting the typo on  cli/ingress-controller/flags.go line: 315: "// Rutnime behavior" ,Rutnime should be corrected to "Runtime".
**Which issue this PR fixes** : fixes #1302 
=> Fix: typo need to be corrected

railgun/manager/manager.go
Adds the `api-server` flag to Railgun.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: Part of #1097
=> Add apiserver-host flag to Railgun

railgun/manager/manager.go
Adds the kong-admin-token flag to Railgun.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: Part of #1097 
=> Add kong-admin-token flag to Railgun

railgun/controllers/configuration/zz_generated_controllers.go, railgun/hack/generators/controllers/networking/main.go, railgun/internal/ctrlutils/utils.go, railgun/manager/manager.go, railgun/test/integration/ingress_test.go, railgun/test/integration/kongingress_test.go, railgun/test/integration/tcpingress_test.go, railgun/test/integration/udpingress_test.go, railgun/test/integration/utils_test.go
This PR adds logic to our controllers which configures and handles the `ingress.class` during object reconcilation.
Highlights:
- `Ingress` style objects now require `kubernetes.io/ingress.class: ${CLASS}` in order to be resolved
- Removing the ingress class removes the object from cache/configuration
- Integration tests now prove the functionality above :point_up: 
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1220
=> fix: plug ingressclass into ctrls

railgun/Makefile, railgun/internal/ctrlutils/utils.go, railgun/internal/ctrlutils/vars.go, railgun/manager/run.go, railgun/test/integration/suite_test.go
- removes the ineffective `KONG_EXTERNAL_CONTROLLER` env variable (and its associated use in the makefile)
- removes the unused `CtrlNamespaceEnv` and its initialization in `manager.Run`
- since `DefaultNamespace` is no longer used by the configuration secret and the `IsAPIAvailable` function was unused:
- removed the `IsAPIAvailable` function (if it gets reintroduced, it should use the `default` namespace instead because `kong-system` is not guaranteed to exist in a cluster)
- moved the `DefaultNamespace` var to a const in the integration test
- removed the `ConfigSecretName` no longer relevant after we've deleted support for the config secret
- removed the unused `ProxyInstanceLabel`
=> Clean up unused railgun variables

railgun/manager/config.go, railgun/manager/run.go, railgun/test/integration/ingress_test.go, railgun/test/integration/suite_test.go
Implement the --watch-namespace flag for Railgun's manager. The initial commit implements the same behavior as the 1.x flag; the second commit implements additional support for watching multiple discrete namespaces (as requested internally in FTI-2395 and frequent chat requests) while maintaining compatibility with 1.x behavior.
The improved version is simple to implement (almost everything is handled by controller-runtime), so I suggest we go with it and squash these into a single commit before merging. The first commit is mostly just to showcase how we would implement this if we want to implement only the 1.x behavior.
Note that MultiNamespacedCacheBuilder does _not_ work independent of Namespace in Manager options, and [notably cannot handle the default "watch all namespaces" …
=> Implement --watch-namespace flag for Railgun

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, railgun/internal/proxy/clientgo_cached_proxy_resolver.go, railgun/manager/config.go, railgun/manager/run.go
This PR introduces the `KIC 2.0.0` CHANGELOG release notes and removes support for "class-less" ingress options.
fixes https://github.com/Kong/team-k8s/issues/78
fixes https://github.com/Kong/kubernetes-ingress-controller/issues/1293
=> KIC 2.0 - Add 2.0 CHANGELOG & Remove ClassLess Ingress Support

CHANGELOG.md, railgun/internal/proxy/clientgo_cached_proxy_resolver.go, railgun/internal/proxy/proxy.go, railgun/manager/config.go, railgun/manager/run.go, railgun/test/integration/suite_test.go
Add `--proxy-sync-seconds` and deprecates and changes the inner workings of `--sync-rate-limit` in a backwards-compatible manner.
Resolves #1300
=> feat: add --proxy-sync-seconds mgr cli flag

.github/workflows/license.yaml
Uses a separate checkout for the PR rather than trying to change the checked-out ref in the existing copy. I tried to economize on network requests originally, and it did not work.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1335
=> Pull from remote PR repos

go.mod, pkg/sendconfig/common_workflows.go, railgun/internal/proxy/clientgo_cached_proxy_resolver.go, railgun/internal/proxy/clientgo_cached_proxy_resolver_test.go, railgun/internal/proxy/proxy.go, railgun/internal/proxy/suite_test.go, railgun/manager/run.go
This adds unit tests to the client-go cached based proxy server implementation used to resolve cache to the Kong Admin API.
This was previous integration tested, but this PR adds some new KTF functionality that makes it simple to unit test so we can further validate the operations, tunables, and memory consumption of this implementation.
=> Client go proxy unit tests

railgun/cmd/rootcmd/env.go, railgun/cmd/rootcmd/env_test.go, railgun/cmd/rootcmd/rootcmd.go
Resolves #1221.
This PR implements a `PersistentPreRun` function that walks through all the flags and, for each of these flags, sets it from the environment if not set by the command line.
KIC 1.x used Viper for that purpose, which feels cumbersome to use with Cobra, and comes with extra features unnecessary for our use case (support for a configuration file). This PR proposes that we drop Viper for a more straightforward and less "magical" solution.
This PR aims for flag-wise compatibility with KIC 1.x. If there's any difference in env var naming, that should be considered a bug.
=> feat: implement environment variable substitution

railgun/pkg/config/config.go
Flip controller defaults on for (most) resources available in 1.x. Remainder of https://github.com/Kong/kubernetes-ingress-controller/issues/1199 with exceptions for known feature gaps that aren't planned for alpha.
=> chore(mgr) enable most controllers

CHANGELOG.md, Makefile
Since the v2.0.0-alpha.1 blockers milestone has been cleared, this PR adds some remaining changelog entries and bumps the makefile tag up.
=> v2.0.0-alpha.1 changelog and makefile version bump

CHANGELOG.md
Minor updates to the existing 2.0.0-alpha.1 changelog for formatting and date info, 1.3.0 changelog.
=> Update 2.0.0-alpha.1 and 1.3 changelogs for release

.github/workflows/docker-build-push.yaml
This upgrades metadata-action to the latest v3.3.0, but
also switches to the new upstream: https://github.com/docker/metadata-action
=> chore: upgrade gh action uses

.github/workflows/build-test.yaml, .github/workflows/docker-build-push.yaml, .github/workflows/integration_test.yaml, .github/workflows/license.yaml, .github/workflows/test.yaml
Dependabot has bad timing. Merge next into main again since the updates today were all for Github actions, which we want in both next and main.
=> Merge next into main

Makefile
Split the Makefile tags for the 1.x and 2.x builds to avoid mistagged builds.
=> fix(build) separate 1.x and 2.x build tags

.github/workflows/license.yaml
Accidentally clobbered one of the package filters in another PR.
Figured we'd filter out the Golang stdlib as well.
=> ci(license) fix filter

hack/get-github-actions-logs.sh
For the purpose of investigation of a flaky integration test, we needed a way to pull N recent GH Actions log outputs for the integration tests, to make it possible to grep through them.
This PR implements a Bash script which does exactly that, with a goal of it being flexible and reusable.
=> hack(github): GH Actions log scraper

CHANGELOG.md, pkg/sendconfig/common_workflows.go, pkg/sendconfig/sendconfig.go, pkg/sendconfig/sendconfig_test.go, railgun/internal/proxy/proxy.go, railgun/test/integration/suite_test.go
In CI there have been several problems that appear to be due to the high rate at which KIC 2.0 has been sending updates to the Kong Admin API at a regular interval. This PR includes some improvements that seemed to function better with minimal/no end-user impact, while making the defaults less noisy in testing/CI. This also adds an update to `sendconfig.SendUpdate()` which will stifle repetitive `nil` update warnings (you'll get one once for each update that would make no change now, rather than them repeating every few seconds).
This helps to resolve https://github.com/Kong/kubernetes-ingress-controller/issues/1390
=> Sendconfig update improvements

.github/workflows/test.yaml, railgun/test/integration/suite_test.go
This adds a local debugging tool I had been keeping in my local stash, but realized it's potentially generally helpful. "bring your own kic" options for debugging the integration tests using a self-supplied controller.
A follow up item exists to later iterate further on how options for the integration tests are handled: https://github.com/Kong/kubernetes-ingress-controller/issues/1406
=> feat: add BYOK to integration tests

.github/workflows/1x-docker-build-push.yaml, .github/workflows/2x-docker-build-push.yaml
Ensures that the right environment is set on GH Actions workflows that need to access docker push credentials.
Also makes a whitespace fix (automatically performed by my editor)
=> Set the GH Actions environment on docker push workflows

CHANGELOG.md, railgun/internal/proxy/clientgo_cached_proxy_resolver.go, railgun/internal/proxy/clientgo_cached_proxy_resolver_test.go, railgun/manager/run.go, railgun/pkg/config/config.go
Signed-off-by: Tharun <rajendrantharun@live.com>
**What this PR does / why we need it**: make the timeout seconds configurable in `cached_proxy_resolver`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1291
=> feat(config) make timeout configurable for the kong client

railgun/keps/0003-kic-kubebuilder-re-architecture.md, railgun/keps/0004-kong-kubernetes-testing.md
This PR adds some of the recent updates and improvements to KEPs related to the upcoming KIC 2.0 release.
This adds coverage only of things that have already occurred (out of sync with the KEP) and does not propose new functionality.
This resolves https://github.com/Kong/kubernetes-ingress-controller/pull/1423
=> KIC 2.0 Alpha.1 KEP Updates

.github/workflows/1x-integration-test.yaml, .github/workflows/2x-integration-test.yaml, .github/workflows/common-test.yaml
fixes #1414
Signed-off-by: Tharun <rajendrantharun@live.com>
**What this PR does / why we need it**:  So, In workflows, we are using an irrelevant `restore-key` for different steps ( lint, unit-test, integration-test), etc. So, caching dependencies won't work properly as when a cache hit-miss occurs, it won't take the previous cache as a base for updating the new cache.
This PR fixes this by updating the `restore-key` in work-flows.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1414
=> chore(ci) fix restore-cache keys for github workflows

.github/workflows/2x-integration-test.yaml, pkg/util/debug_logging.go, pkg/util/debug_logging_test.go, railgun/manager/run.go
This PR adds a new logger which can be used to reduce the noise emitted from Kubernetes controllers during integration tests.
This resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1427
=> feat: add redudancy reducing debug logr

railgun/scripts/setup-integration-tests.sh
Updates to the latest release of [Kind](https://github.com/kubernetes-sigs/kind) for CI.
=> chore: update kind to v0.11.1

test/integration/test.sh
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/1472
=> chore: bump kind version for legacy int tests

.github/workflows/2x-integration-test.yaml, railgun/manager/run.go, railgun/pkg/config/config.go, railgun/test/integration/suite_test.go
Follow-up to #1431 
This replaces the `KONG_TEST_ENVIRONMENT` environment variable (used by KIC as of #1431) with a setting in `config.Config` called `log-reduce-redundancy` (which maps to the `--log-reduce-redundancy` **hidden** flag, and the `CONTROLLER_LOG_REDUCE_REDUNDANCY` environment variable.
Also, moves the setting from the CI job to the place where all the configuration for the controller manager under test is initialized.
Why?
- for consistency with all the other settings: https://github.com/Kong/kubernetes-ingress-controller/issues/1182
- because the `KONG_` prefix is reserved for Gateway; KIC uses `CONTROLLER_`
Also note that there is a bug:
the integration test configures the logger the following way
https://github.com/Kong/kubernetes-ingress-controller/blob/07ae1516d0ac17efc6 …
=> Make duplicate log suppressing a setting in config

railgun/internal/proxy/clientgo_cached_proxy_resolver_test.go
This patch fixes a race condition in the tests, which was specific
to the mocking implementation and not a problem with the implementation
itself. Some additional validation and hardening of these tests were
added as well.
fixes https://github.com/Kong/kubernetes-ingress-controller/issues/1469
=> fix: timing issue in proxy tests

CHANGELOG.md, railgun/internal/ctrlutils/ingress-status.go, railgun/manager/run.go, railgun/pkg/config/config.go
This was originally added to #1451, but later removed. I thought that removal had been reverted, but it wasn't, and I got confused in the PR history and missed that before it went in.
Per #1305 we do want to include this in 2.x for 1.x flag parity. The flag is useful when IP information is missing from the publish service (e.g. bare metal clusters) or does not reflect the true external address of the proxy (e.g. when you chain proxies and have something else in front of Kong).
Lastly, this updates `--publish-status-address` to use a StringSlice, following the same logic as #1496. Note that 1.x `--publish-status-address` originally supported only a single IP, but we may as well allow multiple, as it's compatible.
fixes …
=> Add --publish-status-address to 2.x

CHANGELOG.md, railgun/pkg/config/config.go
=> chore: deprecate klog stderrthreshold flag

railgun/manager/run.go, railgun/pkg/config/config.go
This patch adds the `--sync-period` flag back and delivers
the provided time duration to controller runtime, which
now in v2 handles the relevant client-go configuration on
our behalf (whereas in v1 we used it directly).
This intentionally uses the same settings that V1 established
(instead of the defaults provided by `controller-runtime`) to avoid
change where we don't otherwise have any data influencing us
to pick a new setting.
More context can be seen in [this relevant comment](https://github.com/Kong/kubernetes-ingress-controller/issues/1309#issuecomment-875828600).
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/1309
=> fix: add back the --sync-period flag

pkg/util/debug_logging_test.go
This fixes a really ironic bug found in our unit tests.
=> fix: datarace in datarace test

Makefile
I noticed that Github Actions CI was failing over the last
day or so, and it seemed to be due to the components in the
Kind image never coming online properly. This isn't the first
time recently we found that the older images or KIND components
were breaking. This patch simply updates to the latest Kubernetes
v1.20.x patch release to try and fix CI.
=> fix: update kubernetes version for legacy tests

Makefile, railgun/scripts/setup-integration-tests.sh, test/integration/test.sh
This PR takes #1528 (which is a fix for our integration tests) that went to `next` and cherry-picks it over to `main` in order to resolve CI failures blocking other PRs from being merged.
=> cherry-pick #1528 (bump kind node version) to main

.github/workflows/1x-integration-test.yaml, .github/workflows/2x-integration-test.yaml
Up until recently we never really had a problem with
the fact that we were incidentally duplicating CI runs
for every PR that was pushed. As our test suite is growing
and we're nearing a 2.0 release now is as good a time as
any to fix this and ensure we're only running one copy
of the integration tests per PR.
=> fix: dont run ci twice for branch

pkg/store/store.go, pkg/store/store_test.go, pkg/util/debug_logging_test.go, railgun/Makefile, railgun/config/rbac/role.yaml, railgun/controllers/configuration/zz_generated_controllers.go, railgun/hack/generators/controllers/networking/main.go, railgun/internal/ctrlutils/utils.go, railgun/internal/ctrlutils/vars.go, railgun/internal/proxy/clientgo_cached_proxy_resolver.go, railgun/internal/proxy/proxy.go, railgun/test/integration/ingress_https_test.go, railgun/test/integration/ingress_test.go, railgun/test/integration/plugin_test.go, railgun/test/integration/suite_test.go, railgun/test/integration/tcpingress_test.go, railgun/test/integration/udpingress_test.go
- corrects issues with finalizers that's been holding over since early railgun prototypes
- improves consistency on object deletions
- adds tests to prove new finalizer logic works appropriately
fixes https://github.com/Kong/kubernetes-ingress-controller/issues/1515
=> [chore] finalizer removal & teardown logic cleanup

.github/workflows/2x-image-build-test.yaml, .github/workflows/2x-integration-test.yaml, Dockerfile.railgun
A recent PR made several packages private but the CI
that runs on each PR doesn't test the docker build.
This patch fixes the paths, but also adds a docker
build to the integration tests so that future PRs
will regression test against this kind of problem.
Fixes https://github.com/Kong/kubernetes-ingress-controller/runs/3077874445?check_suite_focus=true
=> fix: adjust docker image build paths

CHANGELOG.md
Documentation for the breaking finalizer changes in #1522. This change requires manual cleanup if you used previous 2.x alpha releases.
=> docs(change) add breaking finalizer change info

Makefile
Update the RG Makefile tag to 2.0.0-alpha.2.
We missed this during the 2.0.0-alpha.2 release.
=> chore(build) update RG tag

railgun/internal/manager/run.go
This removes some preliminary functionality we had put in
place to automatically load the Knative controller based
on the CRD showing up in the cluster during controller
manager runtime. This functionality is desired, but is
being temporarily pulled back so that we can consider it
as a feature again later for multiple CRDs.
See: https://github.com/Kong/kubernetes-ingress-controller/issues/1449
=> chore: temporarily disable auto ctrl loading

CHANGELOG.md, railgun/Makefile, railgun/config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, railgun/config/crd/bases/configuration.konghq.com_kongconsumers.yaml, railgun/config/crd/bases/configuration.konghq.com_kongingresses.yaml, railgun/config/crd/bases/configuration.konghq.com_kongplugins.yaml, railgun/config/crd/bases/configuration.konghq.com_tcpingresses.yaml, railgun/config/crd/bases/configuration.konghq.com_udpingresses.yaml, railgun/config/crd/patches/upgrade_compat.yaml, railgun/hack/generators/manifests/main.go
This PR adds a workaround for an upstream problem in upgrading `apiextensions.k8s.io/v1beta1` versioned `CustomerResourceDefinitions` to `apiextensions.k8s.io/v1` versioned `CustomResourceDefinitions` in support of making it seamless to upgrade CRDs from KIC v1.x to the new CRDs in KIC v2.x.
For the full details, see the contributed `main.go` which includes documentation to justify its existence.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1133
Supports https://github.com/Kong/kubernetes-ingress-controller/issues/1209
=> [feat] legacy CRD compatibility

railgun/test/integration/ingress_bulk_test.go, railgun/test/integration/suite_test.go, railgun/test/integration/utils_test.go
This adds some tests to protect us against performance
regressions when deploying large numbers of ingress
resources all within a single second or two.
=> feat: add some bulk ingress testing

.github/workflows/2x-kubernetes-version-matrix-test.yaml, RELEASE.md, pkg/sendconfig/sendconfig.go, railgun/test/integration/suite_test.go, railgun/test/integration/utils_test.go
Enables tests for `main` and `next` pushes to run tests for the KIC against a history of Kubernetes versions.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/1542
=> [feat] CI testing kubernetes version matrix

CHANGELOG.md, deploy/single-v2/all-in-one-dbless.yaml, deploy/single-v2/all-in-one-enterprise-dbless.yaml, deploy/single-v2/all-in-one-enterprise-postgres.yaml, deploy/single-v2/all-in-one-postgres.yaml, railgun/config/rbac/role.yaml, railgun/hack/generators/controllers/networking/main.go, railgun/internal/controllers/configuration/zz_generated_controllers.go
Changes the API group (URL) for the original v1beta1 Ingress from `apiextensions.k8s.io` to `extensions`.
AFAICT this was just wrong originally, and was never caught because integration tests only try against one Ingress version (V1). apiextensions contains the CRD definition, not Ingress. Caught while reviewing permissions differences between v1 and v2.
**Notes**
[First commit](4d24c8f5d06295b81908c91b93fdbacba193f320) is the actual change. Most of the diff is from running generators afer. 
=> Fix Ingress v1beta1 API resource group

CHANGELOG.md, internal/cmd/rootcmd/run.go, internal/cmd/rootcmd/servers.go, internal/diagnostics/server.go, internal/manager/config.go, internal/manager/run.go, internal/manager/setup.go, internal/proxy/clientgo_cached_proxy_resolver.go, internal/proxy/clientgo_cached_proxy_resolver_test.go, internal/proxy/proxy.go, internal/proxy/suite_test.go, internal/sendconfig/common_workflows.go, internal/util/configdiag.go, test/integration/controller_test.go, test/integration/suite_test.go
Adds `--dump-config` to 2.x. Expose successful and failed configurations via a new endpoint on the diagnostics server.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1308 
This intentionally introduces breaking changes from 1.x:
- Dumped configs are no longer saved to the filesystem. The diagnostic server is less cumbersome to use.
- Flag now accepts a boolean with an additional `--dump-sensitive-config` flag for redaction, rather than a single flag that accepts various string modes.
=> Add configuration dumps for 2.x

Makefile, test/integration/controller_test.go, test/integration/ingress_test.go, test/integration/knative_test.go, test/integration/suite_test.go, test/integration/udpingress_test.go, test/integration/webhook_test.go
- Remove the legacy integration tests from the main integration test Makefile target. They weren't there previously and aren't normally run, and slow local tests considerably.
- Remove the legacy KIC handling from the modern integration tests. After #1595 they are no longer usable on this branch.
=> Remove legacy tests from next

Makefile
This patch reduces the packages we want coverage
for to pkg/ and internal/ (where all our code lives
now minus scripts and some build tools) and turns
on unit tests during the integration test runs to
capture more coverage data.
=> chore: clean up coverage

CHANGELOG.md, internal/manager/config.go, internal/proxy/proxy.go
Increases the default proxy timeout based on experiences in GKE (which was failing).
Adds fixes that supports https://github.com/Kong/kubernetes-ingress-controller/issues/1095
Supports the analysis found in https://github.com/Kong/kubernetes-ingress-controller/issues/1519
=> fix: increase the default for proxy requests

internal/ctrlutils/ingress-status.go
If we're processing status updates for an object, but that object is _removed from the API_ while we're working on it, we should stop working on it.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1619
=> [fix] stop status updates on 404

.github/workflows/release.yaml
In another upcoming change we're switching testing
of older kubernetes releases onto GKE (from KIND)
so that they're running against conformant production
quality cluster configurations. This patch moves
the tests which must remain in kind (for now) into
their own job as a blocker for releases.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1616
=> chore: seperate latest k8s release tests

.github/workflows/release.yaml, go.mod, go.sum, hack/e2e/main.go, hack/e2e/run.sh, test/integration/ingress_bulk_test.go, test/integration/ingress_https_test.go, test/integration/ingress_test.go, test/integration/knative_test.go, test/integration/suite_test.go, test/integration/webhook_test.go
This adds testing of conformant, production grade Kubernetes clusters as a pre-requisite for any release.
Supports https://github.com/Kong/kubernetes-ingress-controller/issues/1095
This is only one iteration, there are several related and follow-up items:
- https://github.com/Kong/kubernetes-ingress-controller/issues/1613
- https://github.com/Kong/kubernetes-ingress-controller/issues/1614
- https://github.com/Kong/kubernetes-ingress-controller/issues/1617
- https://github.com/Kong/kubernetes-ingress-controller/issues/1616
<h1>Do Not Merge:</h1>
There's some git history cleanup that the author needs to perform before merging, please let the author merge this when its ready.
=> [feat] add gke release testing

internal/proxy/clientgo_cached_proxy_resolver.go, internal/proxy/clientgo_cached_proxy_resolver_test.go, internal/proxy/proxy.go, internal/proxy/suite_test.go, internal/sendconfig/common_workflows.go, internal/store/store.go
Based on the investigation and report in https://github.com/Kong/kubernetes-ingress-controller/issues/1519 this patch disables the backpressure system that was introduced during the alpha stage which intended to try and help highlight kong proxy backend issues to operators. The findings were that the tradeoffs in performance didn't justify the value added and that for the moment we are going to make this work more like v1.x did for consistency and perhaps look at improvements in this area again in a later iteration.
Supports https://github.com/Kong/kubernetes-ingress-controller/issues/1519
=> [fix] disable proxy backpressure mechanism

CHANGELOG.md, go.mod, internal/mgrutils/reports.go, internal/proxy/clientgo_cached_proxy_resolver_test.go
This use only one library as direct dependency for uuid generation as it was done on go-kong and deck before
=> use only github.com/google/uuid for uuid generation

.github/workflows/release.yaml
CI image builds again, in a post-cleanup world.
Since the old file is gone, see [build.diff.txt](https://github.com/Kong/kubernetes-ingress-controller/files/6918344/build.diff.txt) for the actual job changes.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: Part of #1596
=> Add Docker build and push workflow

.github/workflows/release.yaml, go.mod, go.sum, hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/ctrlutils/ingress-status.go, internal/ctrlutils/utils.go, internal/store/store.go, test/integration/controller_test.go, test/integration/ingress_bulk_test.go, test/integration/ingress_https_test.go, test/integration/ingress_test.go, test/integration/knative_test.go, test/integration/kongingress_test.go, test/integration/plugin_test.go, test/integration/suite_test.go
- fixes broken compatibility with legacy `Ingress` from netv1beta1 & extv1beta1
- enables release testing against v1.17 and v1.18 clusters
Supports https://github.com/Kong/kubernetes-ingress-controller/issues/1095
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1614
These changes have been tested:
=> [feat] legacy fixes & release tests for v1.17 & v1.18

test/integration/knative_test.go
This includes some fixes to our Knative integration tests so that they work properly against a GKE cluster.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1617
I have tested these changes _manually_ against a GKE cluster and they are working properly.
=> fix: knative tests on gke

.github/workflows/cleanup.yaml, .github/workflows/release.yaml, go.mod, go.sum, hack/e2e/cluster/cleanup/main.go, hack/e2e/cluster/deploy/main.go, hack/e2e/run-tests.sh
This PR adds a cleanup workflow cronjob which will regularly check for and delete orphaned CI resources.
Supports https://github.com/Kong/kubernetes-ingress-controller/issues/1095
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1627
Blocked by https://github.com/Kong/kubernetes-testing-framework/pull/73
The rules for cleanup are restricted:
1. the cluster must have been specifically created by [KTF](https://github.com/kong/kubernetes-testing-framework)
2. the cluster must be older than 30m
3. the cluster must be in the same project and location specified in the `gcloud` CI environment
4. the cluster must have been created by the same Google Cloud IAM Service …
=> feat: cleanup workflow

CHANGELOG.md, internal/manager/config.go
We removed several flags in the first alpha release
that we forgot to add to the release notes. After
doing a comparison of v1 and v2 flags this patch
checks in the remaining flags that aren't coming
forward into v2.
Additionally removed some superflous default notes
in flag descriptions (flagset will produce defaults in
the `--help` output anyway, so these are redundant).
Supports https://github.com/Kong/docs.konghq.com/issues/2904
=> docs: fix alpha changelog for flag breaks

internal/ctrlutils/ingress-status.go
- makes logging updates when objects are out of date debug instead of info
- adds missing retry logic to the `TCPIngress` status update implementation
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/1639
=> fix: tcp ingress status updates

go.mod, go.sum, test/integration/knative_test.go, test/integration/suite_test.go
When releasing `v2.0.0-alpha.3` some problems were encountered with the Knative ingress tests, which turned out to be flakes caused by timing issues with deploying Knative components. This PR removes all provisioning of Knative components in favor of leaving that up to the testing environment's Knative addon, fixes some issues, does some refactoring of the tests and ultimately re-enables the tests in release testing CI in support of upcoming `v2.x` releases.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/1637
Blocked by https://github.com/Kong/kubernetes-testing-framework/pull/77
I have tested this manually with both `v1.17` and `v1.18` GKE clusters locally to to …
=> fix: knative ingress tests

CHANGELOG.md, internal/deckgen/generate.go
Small fix to prevent a panic when an empty username is given for a `KongConsumer`.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/550
=> fix: panic in consumer sort func

.github/workflows/codeql.yaml
This removes an extra run of codeql on each PR by
only running on specific branches for "push" triggers.
Additionally this does some cleanup on the workflow
to make the namings and logging simpler to fit better
with the rest of our CI workflows.
=> fix: de-duplicate codeql runs on PRs

RELEASE.md
Updated release instructions to mention that you should bump your base manifest versions to reflect what you're releasing.
=> doc(release) note manifest version bump

Makefile, hack/e2e/run-tests.sh, test/integration/controller_test.go, test/integration/ingress_bulk_test.go, test/integration/ingress_https_test.go, test/integration/ingress_test.go, test/integration/knative_test.go, test/integration/kongingress_test.go, test/integration/plugin_test.go, test/integration/suite_test.go, test/integration/tcpingress_test.go, test/integration/udpingress_test.go, test/integration/utils_test.go, test/integration/webhook_test.go, test/performance/ingress_bulk_test.go, test/performance/suite_test.go
This PR makes several changes to our integration test suite:
- general cleanup and refactoring
- ensures all tests receive (and use) their own unique namespace (namespace `default` is no longer supported)
- ensures all tests cleanup after themselves and tear down their resources
- enables parallelization of the integration test cases
- moves the bulk ingress tests into `test/performance` as these tests are costly and noisy, and now with parallelization of tests some of their value has been replaced
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1592
**Notes**
I ran `./hack/e2e/run-tests.sh` locally to verify these changes in our release testing, and it's working properly on GKE.
=> feat: parallelize the integration test suite

CHANGELOG.md, internal/admission/server.go
This is in direct response to the gosec lint which
we disabled due to backwards compatibility issues
in the v1.3.x releases of KIC, but now with KIC v2
on the horizon it's time to pull off the band-aid.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1065
=> fix: support minimum TLS v1.2 for webhook admission server

.github/workflows/test.yaml, Makefile
Our codecov integration is noisy and gets multiple profiles at different times, causing it to drop multiple messages on PRs.
Additionally, we want to be able to capture coverage output from multiple different test types (unit, integration, e.t.c.)
This PR fixes these problems by having each test target in the `Makefile` provide it's own coverage profile, and adds a CI workflow which will wait for all tests to finish before combining them and uploading them to codecov.
Additionally this enables the use of our codecov API token instead of doing anonymous updates.
=> fix: combine coverage and CI workflow

internal/metrics/prometheus.go
fix exposing business logic metrics using controller-runtime metrics
=> only global registry publisize data through controller-runtime metrics ports

Dockerfile
This bumps up Alpine to 3.14 as alpine 3.11 EOL is 01 Nov 2021
=> Dockerfile - bumpup alpine to 3.14

CHANGELOG.md, Makefile, deploy/manifests/base/kong-ingress-dbless.yaml, deploy/manifests/enterprise-k8s/kustomization.yaml, deploy/manifests/enterprise/kustomization.yaml, deploy/manifests/postgres/kong-ingress-postgres.yaml, deploy/manifests/postgres/migration.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Releases 1.3.2. Primary motivator was #1691. We need to run through a backport (sorta--2.0.0 isn't actually out yet) release. Also bumps to Kong 2.5 because may as well.
We have not previously done any releases from version branches. This may not work. We need to confirm CI results and address any issues after pushing the tag.
We don't yet have a procedure for updating content in main when changes occur in other branches but only main matters. Here, the changelog and single manifests need to be in main. I've set up the commits so that cherry-picking should be an option after. Changes to the internals (the manifest sources and Makefile) can be left on this branch alone.
=> Release 1.3.2

.github/workflows/release.yaml
Fixes a regression introduced in 9d719cc61f670dc0035e193cfd3582f192cc71ca:
An unintended consequence of the change above is that pushes of the `main` tag to Docker Hub stopped working.
This PR:
- reenables the release job for `main`
- adds a triggering condition for gcloud tests that address the primary motivation of the referenced commit (to run the gcloud test only on tag pushes)
=> Re-add pushing to dockerhub on pushes to `main`

README.md
Related to https://github.com/Kong/docs.konghq.com/pull/3099#issuecomment-896968376
Adds a section to the top of the readme to announce that KIC 2.0 is in public beta, including a link to the interim documentation site.
**Do not merge** before https://github.com/Kong/kubernetes-ingress-controller/pull/1689 is released and the deploy manifests run the newly released version.
=> README header for KIC 2.0 public beta

CHANGELOG.md, go.mod, go.sum, internal/kongstate/types.go, internal/parser/parser.go, test/integration/tcpingress_test.go, test/integration/udpingress_test.go
- Add a test for a TCPIngress and UDPIngress that point to the same integer port (but different protocols) on the same Service.
- Add a map to de-duplicate upstreams by name. Upstreams use names of the form "<service>.<namespace>.<port>.svc". Kong upstreams _do not_ differentiate by protocol (despite, yes, the fact that including a port implies that they probably should) and thus TCP and UDP Service ports with the same port number should indeed both generate the same upstream.
fixes #1446 
The new tests also add locks to the TCP and UDP tests. This ensures that …
=> Address TCPIngress and UDPIngress collision

CHANGELOG.md, internal/adminapi/validators/consumer/credentials/constraints.go, internal/adminapi/validators/consumer/credentials/validation.go, internal/adminapi/validators/consumer/credentials/validation_test.go, internal/adminapi/validators/consumer/credentials/vars.go, internal/adminapi/validators/errors.go, internal/kongstate/kongstate.go
Up until now if violations of unique key constraints occurred while processing the credentials for `KongConsumer` objects the result would be a hard lockup of the controller as updates to the Kong Admin API would fail until the offending resources were removed or updated.
This patch references the Admin API's own constraints to enable pre-validation of consumer credentials and changes the behavior to drop the offending credentials and avoid the hard lockup and instead only log the errors continually until the offending resources are corrected.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/729
=> fix: credentials validation for constraint violations

config/prometheus/monitor.yaml
w/o enable namespace selector, PodMonitor could not locate which namespace Pods need to be monitored
=> [bug] add namespace selector into PodMonitor

.github/workflows/release.yaml
This enables the newly added `v1.22.0` [Kind Image](https://hub.docker.com/layers/kindest/node/v1.22.0) to ensure release testing is done against the new Kubernetes `1.22.x` release.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1725
**Notes**
The following issues were found when testing `v1.22` and were reported as follow-ups:
- https://github.com/Kong/kubernetes-ingress-controller/issues/1728
- https://github.com/Kong/kubernetes-ingress-controller/issues/1730
=> chore: enable k8s v1.22.0 release testing

keps/0003-kic-kubebuilder-re-architecture.md, keps/0004-kong-kubernetes-testing.md, keps/0006-officially-supported-platforms.md, keps/0007-kic-performance-test.md
This is a maintenance task to update our existing KEPs in response to what has been delivered with the KIC 2.0.0 BETA releases.
- docs: mark ktf and kubebuilder keps implemented
- docs: spacing cleanup for performance testing KEP
- docs: decline arm64 KEP
=> docs: KEP updates for KIC v2.0.0-beta release

hack/generators/controllers/networking/main.go, hack/generators/manifests/main.go, internal/adminapi/client.go, internal/admission/server.go, test/integration/knative_test.go, test/integration/suite_test.go, test/integration/utils_test.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
N/A
N/A
=> refactor: move from io/ioutil to io and os package

keps/0008-unreferenced-object-filtration.md
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1259
Keep in mind that this is a `provisional` step and is mostly in place to start gathering alignment and come to a decision.
Maintainers please feel free to make commits directly to this branch with ideas, updates, and fixes to the KEP so long as you maintain the git history.
=> docs: add unreferenced object filtration KEP

.gitignore, Makefile, config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, config/crd/bases/configuration.konghq.com_kongingresses.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, deploy/single-v2/all-in-one-dbless.yaml, deploy/single-v2/all-in-one-enterprise-dbless.yaml, deploy/single-v2/all-in-one-enterprise-postgres.yaml, deploy/single-v2/all-in-one-postgres.yaml, hack/deploy/build-single-manifests.sh, hack/generators/manifests/main.go
Filters some CRDs out of the CRD auto-generation tooling so they can be manually managed, as our tooling needs some investigation and potential fixes (that we intend to do at a later time) to ensure the auto-generation for these types is working properly.
Resolves Task 1 in https://github.com/Kong/kubernetes-ingress-controller/issues/1762
=> Manually manage Kong<TYPE> CRDs

.github/workflows/license.yaml
This reverts commit cc7098829797deaa3e1db475b5e9255804a4b281 (#1863).
Reason: `actions/github-script@v5` has a [breaking API change](https://github.com/actions/github-script#breaking-changes-in-v5) which is incompatible with our script.
=> Revert "chore(deps): bump actions/github-script from 4.1 to 5 (#1863)"

.github/workflows/test.yaml, test/e2e/istio_test.go
It was found in Github Actions when the environment is
very slow that rate-limiting by the minute could sometimes
break due to slowness of the underlying environment.
This makes the rate-limit for the Istio e2e tests longer
than the tests themselves are allowed to take to compensate
and ensure that the ratelimits work as intended.
Based on some findings of how Github Actions seems to work
when running kind clusters, this PR also bumps the
=> fix: rate limit by hour in e2e tests

CHANGELOG.md
This patch compiles the `alpha` and `beta` interim changelog for the `2.0.0` release into a single changelog entry now that the release is imminent. Several things were updated, fixed, added, or improved along the way.
Partially resolves #1881
Here's a list of some of the kinds of changes that were made in this patch:
- `alpha` and `beta` changelog entries were compiled into a single `2.0.0` entry
- added some entries to `breaking changes` which were present in other sections but missing from breaking changes
- added some helpful links to our upgrade guide and to our 
- made some entries for features and changes that were higher severity more prominent in the lists
- reworded and/or …
=> docs: CHANGELOG entry for 2.0.0

hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/ctrlutils/ingress-status.go, internal/diagnostics/server.go, internal/manager/run.go, internal/sendconfig/sendconfig.go, internal/util/logging.go, test/e2e/istio_test.go
For 2.0 we're launching with multiple logging implementations under the hood, which isn't much of any problem from the end-user perspective and is [something we'll converge in time](https://github.com/Kong/kubernetes-ingress-controller/issues/1893) but in the interim we were not properly configuring how we did log levels between the two implementations and had several places that were too noisy and repetitive and needed to be made into debug entries instead of info. This PR takes care of both problems.
Resolves #1810
- feat: add converted loglevels for go-logr vs logrus
- chore: reconfig debug logging for new converter
- chore: cleanup some startup log language
- chore: run …
=> feat: converted loglevels for logrus -> go-logr

keps/0002-kong-gateway-api.md
This is another iteration on our Gateway APIs KEP which is meant to bring us to a partially `implementable` (meaning, some work can start but the entirety of the project is not yet planned out).
Note that `implementable` in this context is _specifically meant to signal that implementation is technically ready_ it does **not signal that work can actually be started** as this will be determined by a separate grooming and planning process of the [maintainers](https://github.com/orgs/kong/teams/team-k8s).
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1543
I tried to break the PR into specific commits to help review:
- docs: update gw apis kep for in-cluster gw mode
- docs: add placeholders for …
=> [KEP] Gruduation Criteria and initial implementability for Gateway APIs

test/integration/controller_test.go, test/integration/metrics_test.go
fixes #1817
Implements an integration test that GETs KIC's Prometheus endpoint (`/metrics`) and passes only if all the required metrics are present in the returned data.
"All required metrics" is the 3 metrics currently defined by KIC and listed in the documentation.
Also moves the test into a separate file.
=> Prometheus metrics regression test

go.mod, go.sum
This updates our containerd dependency to a version that resolves https://github.com/advisories/GHSA-c2h3-6mxw-7mvq.
While we don't use containerd directly, it is just as well we upgrade our dep.
=> chore: update containerd to v1.5.7

CHANGELOG.md, CONTRIBUTING.md, FEATURE_GATES.md, README.md, go.mod, internal/manager/config.go, internal/manager/controllerdef.go, internal/manager/feature_gates.go, internal/manager/feature_gates_test.go, internal/manager/run.go, internal/mgrutils/reports.go, internal/util/reports.go
This patch documents and enables feature gates for KIC to add tooling which helps to manage the lifecycle of new and/or experimental features for the KIC.
This was meant to solve two problems:
- strongly communicate the lifecycle and trajectory of features, and give us a path to graduate as well as deprecate while significantly reducing any surprises for end-users
- provide a safe/isolated way to iteratively develop Gateway support without putting it directly in end-users hands day 1
- allow Gateway development to start quickly but without being locked in forever if the long term implementation lives partially or wholly elsewhere in time (e.g. operator code)
=> feature gates

CHANGELOG.md, internal/kongstate/kongstate.go, internal/kongstate/kongstate_test.go
Kubernetetes Secrets do not support boolean values. We store all
credentials in Secrets. OAuth2 credentials contain a boolean field,
"hash_secret".
When filling credentials, this change detects "hash_secret" fields and
converts them to boolean values if they successfully convert, or if the
value cannot convert, to the field default, false.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes internally reported issue. With a string:
```
ingress-controller time="2021-10-31T05:34:06Z" level=error msg="failed to provision credential: failed to decode oauth2 credential: failed to decode credential: 1 error(s) decoding:\n\n* 'has
h_secret' expected …
```
=> fix(creds) coerce oauth hash_secret to bool

.github/workflows/e2e.yaml, .github/workflows/test.yaml, go.mod, go.sum, test/e2e/all_in_one_test.go, test/integration/suite_test.go, test/integration/utils_test.go, test/utils/controller_manager.go
This fixes some inconsistencies with how enterprise licenses were handled across testing suites, and uses a single common implementation (and environment variable)
- I tested E2E tests locally and they succeeded with this patch
=> feat: enterprise license utilities for testing

internal/ctrlutils/ingress-status.go, test/integration/ingress_test.go
Currently, we don't update Ingresses or Ingress-likes unless their associated Kong service's protocol is tcp, udp, or http. This adds the rest of the protocols (https, grpc, grpcs) that should result in an Ingress update.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1991
The test confirms the status update now works, but not much anything else, largely owing to my lack of familiarity with gRPC. I initially tried this after the status check:
```
t.Log("waiting for routes from Ingress to be operational")
require.Eventually(t, func() bool {
conn, err := grpc.Dial(fmt.Sprintf("%s:%s", proxyURL.Hostname(), …
```
=> fix(status) update non-http upstream Ingresses

CHANGELOG.md, hack/deploy-admission-controller.sh
Add KongClusterPlugin to the rules of the template ValidatingWebhookConfiguration. We omitted this earlier when adding support for KCP to the admission server code
Also moves content out of the 2.0.5 changelog since it wasn't actually part of 2.0.5.
=> fix(admission) add KongClusterPlugin config

CHANGELOG.md, internal/ctrlutils/ingress-status.go, test/integration/ingress_test.go
This patch takes care of a problem where status updates would
never complete for more than one ingress connected to a single
service. It also fixes a problem where ingress resources with
periods in the name (e.g. "my.ingress.resource") would fail to
have their statuses updated due to a parsing error. Additionally
this adds some regression tests which will prevent us reduce the
possibility that these problems would be reintroduced.
fixes #2012
=> fix: status updates for svc with > 1 ingress

go.mod, go.sum
Bumping these to 1.5.8 and 1.0.2 per a security alert. Dependabot can't handle these for some reason. Error log for that doesn't obviously show the issue, so seeing if they'll make tests mad when done manually.
Ed: apparently no. Maybe the batch of k8s libs that updated in another Dependabot PR was the prereq?
=> chore(deps) update containerd and image-spec

Makefile
Instead of writing a static tag variable in the Makefile, automatically infer it from the Git tag. Guess which piece of the release configuration we often forget to update.
See [tags.txt](https://github.com/Kong/kubernetes-ingress-controller/files/7589988/tags.txt) for example runs.
If there is no tag, this chooses the parent tag and appends a short hash onto the end. This works for both the most recent tag and older tags. If there is a tag, this uses that tag. If there are multiple tags for the same commit, it apparently chooses whichever tag was created last.
=> feat(make) determine the tag automatically

CHANGELOG.md, internal/adminapi/validators/consumer/credentials/validation.go, test/integration/webhook_test.go
Previous validation verified that any required fields
for a credentials type were present, but did not also
validate that the contents were not empty. This patch
adds a length check which matches the data-plane API
to validate that required fields are at least len 1.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1993
=> fix: credentials validation for required data

CHANGELOG.md, hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/ctrlutils/utils.go
While working on `HTTPRoute` support I noticed a subtle bug in existing controller implementations wherein objects could theoretically be removed from the proxy cache if a controller-runtime cached client `Get()` failed to retrieve them for a reason _other_ than 404. Given the method is operating on the internal cache fed by informers the situations where that would fail for a non-404 reason are very slim, however this is still _technically wrong_ and this patch changes the behavior to always report non-404 errors and requeue the requests.
=> fix: innappropriate object cache removal

.github/workflows/e2e.yaml
This patch disallows multiple cluster deployments in the nightly E2E tests to see if this helps with Istio test flakes.
Partially Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/2071
While I was able to reproduce and start work on the non-Istio test failures from #2071, I could not reproduce the Istio test failures on my local machine. As such I would like to see if those tests start passing consistently if there's less resource contention in the environment, because it is already known that the actions of the test (to deploy all of istio then perform large numbers of network requests) are resource intensive.
=> fix: reduce gh actions job resource contention for istio e2e

CHANGELOG.md, internal/adminapi/client.go, internal/manager/config.go
Add a mutex and lock it when creating Kong admin clients. Attempting to
create multiple workspaced clients simultaneously can result in a race
condition where both clients check for the workspace before either
creates it, both clients will attempt to create the workspace, and the
second client to attempt creation will hit a unique violation.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes CI errors like:
```
panic: creating workspace: HTTP status 409 (message: "UNIQUE violation detected on '{name=\"notdefault\"}'")
```
=> fix(manager) lock client creation

test/integration/gateway_test.go
I continue to be unable to reproduce the gateway test issues of late, but I have my suspicions based on the failure output I've seen in CI that they're due to the parallelization of tests and the timing of when the `PublishService` gets updated for some of those tests. This patch turns off the parallelization for these temporarily, and if that ends up fixing the problem then I will create a follow up issue to re-parallelize them later after making adjustments to avoid collisions.
Fixes #2065
=> fix: test gateway integrations sequentially

config/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Adds `KONG_KIC=on` to the base manifest environment and rebuilds manifests.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2078
No changelog added; no user-facing effect.
=> feat(deploy) add KONG_KIC to manifests

CHANGELOG.md, internal/util/reports.go, internal/util/reports_test.go
Makes reporting connections over TLS.
=> Change reporting to TLS

test/integration/gateway_webhook_test.go
This de-parallelizes the gateway webhook tests as flakes seem to be occurring in relevant tests and I have a strong suspicion that unexpected timings are causing the flakes.
Intended to fix #2104 but we'll need to see what the results are. I wasn't able to reproduce the issue locally so there's a bit of trial and error going on here. There's a follow up item in https://github.com/Kong/kubernetes-ingress-controller/issues/1988 to get these re-parallelized, add more tests, and to ultimately ensure that these controllers are eventually consistent and harden the reconciliation logic.
=> fix: de-parallelize gw webhook test

CHANGELOG.md
Per discussion with the team, we're going to keep the 2.x behavior as-is and add a retroactive changelog entry.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2090
=> doc(changelog) add missing KCP 2.x breaking change

.github/workflows/test.yaml, Makefile, config/variants/postgres/kong-ingress-postgres.yaml, config/variants/postgres/migration.yaml, deploy/single/all-in-one-postgres.yaml, hack/verify-versions.sh
Kong version updates must be made in multiple locations within the base and variant manifests, or Kong will not start due to missing migrations. That didn't happen. Now it has happened.
Add a new hack script to ensure it doesn't happen no more: 
[demo.txt](https://github.com/Kong/kubernetes-ingress-controller/files/7821635/demo.txt)
I'd wanted to do this in Kustomize, but I don't think there's a good way to do it with `image` blocks that doesn't just then shift the problem to needing to update each kustomization.yaml's `image` section, so alert bash script instead.
=> Fix mismatched migration/deployment versions

go.mod, go.sum
While this is not direct for us, this patch updates containerd deps for https://github.com/advisories/GHSA-mvff-h3cj-wj9c
=> chore: update containerd

internal/parser/translate.go, internal/parser/translate_test.go
This patch takes an iterative step towards implementing the `HTTPRoute` spec more completely in the backend `parser/`, including adding full path matching support, header matching support, and generally cleaning up the code.
Partially resolves #2079
This iteration makes improvements and passes the existing tests, but it is not complete. Follow up items include:
- implementing query param matches
- implementing regex path matches
- implementing regex header matching
- namespace restricted backendRefs
- expanded integration tests
- webhook validation for `HTTPRoute` to block options which we don't support
- code refactoring and cleanup
These are all now covered in #2079. Some of these …
=> feat: implement matching support for HTTPRoute in parser

test/e2e/all_in_one_test.go, test/e2e/istio_test.go
This patch resolves an E2E test failure that started to occur with recent [Istio](https://github.com/istio/istio) releases. Previously the outbound network traffic from the Gateway was being collected for Kiali health metrics and so a `429` response from the Gateway (due to an enabled rate-limiter plugin) would be captured in the health metrics. In recent releases even when testing manually this no longer seems to be the case: it would appear that updates to Istio have either caused traffic outbound from pods within the mesh to route differently OR they're routing the same but not picked up for these metrics any longer. In the deluge of recent Istio updates I didn't find any one issue or PR that seemed to be definitively linked to this, but after …
=> fix: kiali no longer captures errors on outbound edge

.github/workflows/e2e.yaml, .github/workflows/nightly.yaml, test/e2e/all_in_one_test.go
Nightly builds and E2E tests using nightly builds. The nightly build is available on demand, so we can also run it during the day for release testing.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2143
This requires coordination with other teams to create the new `kong/nightly-ingress-controller` Docker repo and grant our Docker token permission to it. This must be held until that is ready.
=> Add and test nightly builds

internal/validation/gateway/httproute.go, internal/validation/gateway/httproute_test.go
Some validation was missing for unsupported `HTTPRoute` features which this PR adds.
=> chore: add extra validation for supported httproute features

Makefile, config/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Bumps versions for 2.0.7, forgot to handle the version bumps along with backports.
=> chore(*) update controller version

CHANGELOG.md, internal/admission/utils.go, internal/admission/validator.go, internal/validation/consumers/credentials/validation.go, test/integration/webhook_test.go
We had a previous oversight in our recent validation code and tests which missed the case where a credential `Secret` referenced by a managed `KongConsumer` could wrongly fail validation if it employed a unique constrained key and the value was updated. This patch fixes that issue and adds an integration test item for the missing coverage.
Resolves #2190 
I tested the new integration test for this against in `main`, where it failed (expected) prior to this branch where it now passes.
=> fix: validation for update-in-place unique constrained credentials

.github/workflows/nightly.yaml
Job worked, but forgot to rename it something different than the actual release job.
=> fix(ci) rename nightly build

.github/workflows/e2e_targeted.yaml
Add an option to run integration tests to the targeted job, disabled by default. This allows running integration tests in CI against an arbitrary Kubernetes version.
=> ci(*) add integration test to targeted job

grafana.json
I didn't export the Grafana dashboard originally, hence the issue. This enables the "Export for sharing externally" option.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2128
=> fix(grafana) use shareable dashboard

.github/workflows/e2e.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml, CHANGELOG.md, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, internal/validation/gateway/httproute.go
Releases `v2.2.0` which notably includes a technical preview level of support for [Gateway APIs](https://github.com/kubernetes-sigs/gateway-api).
Resolves #2231
=> Release 2.2.0

internal/util/reports_test.go, test/integration/ingress_https_test.go, test/integration/ingress_test.go, test/integration/knative_test.go, test/integration/tcpingress_test.go, test/integration/udpingress_test.go
Addresses two unrelated test flakes:
- We log an expected error during reporter unit tests using the test logger, but outside the test goroutine. This can run after the test completes successfully, and if so it results in a panic because the test logger is no longer available. This change disables logging if the error is the expected type.
- Standardize and lengthen the time allowed for status updates in integration tests. For whatever reason, status updates in CI appear to be particularly slow, and time out randomly after unrelated changes. I can never replicate these when running the individual test, so this appears to be a side effect of limited resources and concurrency in CI rather than any actual problem in the code.
=> Fix test flakes

CHANGELOG.md, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Update changelog and manifests for a 2.2.1 release.
Only contains the cache warm delay workaround, which I want to get out in a 2.2 release without a backport, before we start merging new 2.3 features.
=> chore(*) release 2.2.1

.github/workflows/release.yaml
Disables Kubernetes 1.19 and adds 1.22 in older version tests.
Gateway tests are failing on 1.19 consistently, though they shouldn't per https://gateway-api.sigs.k8s.io/faq/
=> chore(ci) update older Kubernetes versions

.github/workflows/license.yaml, .github/workflows/test.yaml
Only perform steps that require secrets if those secrets are available.
This lacks a means to test behavior for the negative case, since we're all org members, but it at least does not break for us. We will soon be informed if it functions as intended when Dependabot opens something.
=> ci(license) skip secret-required steps when secrets unavailable

internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_httproute_test.go, test/integration/httproute_test.go
Adds support for HTTPRoute regex path and exact matches. This basically does nothing other than add tests, as Kong determines the path type automatically and will use regex matching if you give it a path that looks like a regex.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2153 
I was unsure how to handle [the automatic selection of strip_path on our end](https://github.com/Kong/kubernetes-ingress-controller/blob/d8274a81b75a941c9eecfacca9df58063c7e3f54/internal/dataplane/parser/translate_httproute.go#L151-L152). Is there part of the Gateway specification that generally requires paths in matches never …
=> feat(gateway) support HTTPRoute regex and exact matches

.github/workflows/license.yaml
Replace the token presence check in the license checker with an API call
to determine membership. GITHUB_TOKEN is always present, but may not
have access to update issue comments.
**Notes**
The failure case is now tested and shown in the test run at https://github.com/rainest/kubernetes-ingress-controller/runs/5254856175?check_suite_focus=true
The GITHUB_TOKEN that's used for that fork doesn't have permission to check this repo, whereas the one here does.
=> fix(ci) use github api to determine membership

CHANGELOG.md, go.mod, go.sum, internal/dataplane/sendconfig/sendconfig.go
Updates deck, including some signature changes.
This incorporates https://github.com/Kong/deck/pull/573, which means that defaults are now populated by based on what Kong reports the default as if not present. This is good, because it avoids the long-standing "unrelated change updates some value that should be 'empty' according to the requested object" problem (e.g. the removal of `https_verify_certificate` in the example in https://github.com/Kong/kubernetes-ingress-controller/issues/2248#issue-1124403000).
KIC has its own set of defaults embedded in the code. Many of these were previously in place only to prevent config thrashing, but some actually differ from Kong defaults, e.g. …
=> chore(deps) update deck to v1.11.0

CHANGELOG.md, config/base/ingressclass.yaml, config/base/kustomization.yaml, config/rbac/role.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/manager/config.go, internal/manager/controllerdef.go, internal/store/fake_store.go, internal/store/fake_store_test.go, internal/store/store.go
Adds an IngressClass controller and store to ingest and cache IngressClasses. Does not actually do anything with IngressClasses after adding them; parser functionality will be added separately.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: This handles the first bullet from #2177 
IMO there are two things we should consider here:
- Do we support IngressClass on networking.k8s.io/v1beta1? As proposed this only handles networking.k8s.io/v1, though partly to get feedback on anything we need to change before writing v1beta1 if we implement it (the code will end up being essentially identical). We could reasonably …
=> feat(controllers) add IngressClass v1

test/e2e/helpers_test.go, test/e2e/utils_test.go
Adds a utility to retrieve container logs for E2E tests.
This was originally part of https://github.com/Kong/kubernetes-ingress-controller/pull/2258 but I accidentally rebased it out. Per the original comments it's not actually used because it's noisy; it's around in case you want to use it temporarily for debugging and/or for us to possibly incorporate in a less noisy fashion using https://pkg.go.dev/github.com/stretchr/testify/suite?utm_source=godoc#AfterTest or something.
Edit: now it does include usage, because we have an ongoing issue we want to use it to debug.
=> test(e2e) add log retrieval utility

hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/utils/utils.go, internal/dataplane/kong_client.go
While working on #2295 I noticed that the `EnsureProxyDeleteObject()` method was superfluous: the underlying client go cache already does the existence checks and the underlying deletion is not asynchronous.
=> chore: refactor dp obj deletion ensure

internal/manager/controllerdef.go, test/e2e/features_test.go, test/e2e/helpers_test.go
https://github.com/Kong/kubernetes-ingress-controller/pull/2292 added a new controller around the same time https://github.com/Kong/kubernetes-ingress-controller/pull/2296 changed the controller configuration. The new IngressClass controller did not include the new required DataplaneClient, which resulted in nil dereference panics when the controller attempted to use it.
This sets the IngressClass controller DataplaneClient.
Reverts the noisy E2E logging change we made to diagnose this.
Fixes E2E test failures.
Wait for success on …
=> Add dataplane client to IngressClass controller

CHANGELOG.md
A changelog entry was missing for the new Kong Admin mTLS flags, this patch adds it.
Fixes #1958 
=> chore: update CHANGELOG.md for mtls flags from #1958

CHANGELOG.md
This PR isn't actually in 2.2.1: https://github.com/Kong/kubernetes-ingress-controller/commit/39a424adf744421c19b835484c7b562e216f9931
Probably submitted around the same time as the release and not updated after to fix the section.
=> chore(docs) move changelog item

CHANGELOG.md, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go
Orders identical certs with the same creation timestamp by their uuid. This fixes an issue where the ordering of such certs can be nondeterministic and cause the sync loop to post updates on subsequent iterations.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2248
Idiomatic go recommendations are welcomed! I have zero go background.
=> Orders similar certs by uuid when their creation timestamps are identical

CHANGELOG.md, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/httproute_controller.go, test/conformance/gateway_conformance_test.go
This enables the `HTTPRouteCrossNamespace` conformance test from upstream [Gateway API](https://github.com/kubernetes-sigs/gateway-api).
This PR also fixes some issues that were relevant to adding that test:
- fix: remove duplicate addrs on unmanaged gateways (a random bug I noticed)
- fix: prepend LB addrs in unmanaged GWs (fixes #2050, I was already working in that code and it was easy)
- fix: use ConditionRouteAccepted for HTTPRoute accept (specifically for HTTPRoute conformance)
- fix: wait for dataplane before reporting httproute accepted status (specifically for HTTPRoute conformance)
Partially resolves #2210 
Fully resolves #2050
=> tests: add HTTPRouteCrossNamespace Gateway conformance test 

CHANGELOG.md, internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_httproute_test.go, test/conformance/gateway_conformance_test.go
This adds most of the rest of the L7 Gateway conformance tests, minus cross namespace ones that will be taken care of later as a part of #2080.
Resolves #2210 
=> tests: more L7 gateway API conformance tests

deploy/README.md
Removes an old no longer needed redirect page.
=> chore: delete old unneeded doc redir

examples/gateway-httproute.yaml
Some cleanup for the httproute example manifest:
- renamed to make it more clear that this file relates to gateway api support
- some language cleanup in the comments
- removed no longer required annotation
=> chore: cleanup httproute example

examples/ingress.yaml
Cleans up the old httpbin ingress example, including removing the ancient ingress resource versions.
=> chore: remove old ing types from httpbin example

internal/util/test/controller_manager.go, internal/util/test/crds.go, internal/util/test/webhooks.go, test/conformance/suite_test.go, test/e2e/istio_test.go, test/integration/suite_test.go, test/integration/webhook_test.go
`internal/test` was a confusing place for these test utils. Since they are utils for test, this patch moves them under `internal/util/test` to make that more clear.
=> chore: move test utils under internal/utils/test

examples/udpingress.yaml, test/integration/examples_test.go, test/integration/utils_test.go
Adds some tests which cover the fully testable `examples/` manifests.
Partially resolves #1096
=> tests: add tests for example manifests

.github/stale.yml
We've previously had 14 as the number of days before stalebot would mark an issue as stale, which I feel is pretty long for something to remain entirely dormant after marking it `pending-author-feedback`. Given that this doesn't do anything but notify the collaborators it seems more appropriate to shorten this to a week, meaning stale issues that _remain_ stale will be autoclosed within a 14 day period of no activity (but again, only if we mark them as `pending-author-feedback` explicitly).
=> chore: update daysUntilStale as 7

Dockerfile
A couple of extra `copy` lines were found in our `Dockerfile`, this patch resolves them.
Resolves #2377
=> fix: remove redundant copy in Dockerfile

internal/util/reports.go, internal/util/reports_test.go
Adds missing serialization for feature gates in reports.
Resolves #2376
=> fix: serialize fgs in reports

.github/workflows/e2e.yaml, .github/workflows/release.yaml, CHANGELOG.md, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Tentative 2.3.0 release, for tomorrow, 2022-04-05.
Awaiting https://github.com/Kong/kubernetes-ingress-controller/actions/runs/2091424181
=> Release 2.3.0

Dockerfile
Fix #2375 
We [moved the metadata package](https://github.com/Kong/kubernetes-ingress-controller/commit/a9682f6790a4d6b3146934b766401d79530b6e23), but didn't update the Dockerfile to reflect this, so builds would always use the default `NOT_SET` values.
=> fix(build) correct Dockerfile metadata paths

hack/deploy-admission-controller.sh
Adds SAN in the admission hack script. Originally filed to docs, but intended for this repo. The script openssl invocation now matches the docs:
```
12:52:36-0700 esenin $ . ~/src/ingress-controller/hack/deploy-admission-controller.sh 
Generating a RSA private key
............................................................................................+++++
.......+++++
writing new private key to 'tls.key'
-----
error: failed to create secret namespaces "kong" not found
Error from server (NotFound): namespaces "kong" not found
validatingwebhookconfiguration.admissionregistration.k8s.io/kong-validations created
```
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when …
=> fix(hack) add SAN to admission setup script

CHANGELOG.md, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, hack/deploy-admission-controller.sh, internal/admission/server.go, test/e2e/features_test.go
Release a 2.3.1 hotfix
Correct the admission webhook TLS configuration cases to check that all
configuration is empty for the case that handles empty configuration.
Previously it was identical to the case that handled certificate files.
This fixes a bug where admission controllers with no certificate
configuration would prevent the controller from starting.
Modified an unrelated E2E test (the tested configuration doesn't overlap, so this is to save time by not needing an additional E2E test that modifies the deployment) to enable the admission controller without any certificate configuration. Previously we only tested this after the fact in the Helm chart tests.
The E2E tests now run the admission webhook setup …
=> fix(admission) correct no-cert condition and release 2.3.1

CHANGELOG.md, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/route_utils.go, test/integration/gateway_test.go, test/integration/ingress_test.go, test/integration/suite_test.go
Implements the https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.RouteNamespaces filter. This allows a Gateway Listener to filter the routes it will accept by namespace (any namespace, same namespace as Gateway, or namespaces identified by a selector).
Merges allowedRoutes section from user Listener sections into the generated managed Gateway Listeners. An allowedRoute in a user Listener whose procotol matches a generated Listener will be copied into that generated Listener.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2080. Some tasks were moved to separate issues.
I move to separate the …
=> Implement Gateaway Listener allowedRoutes.namespaces

CHANGELOG.md, internal/dataplane/parser/translate_tcproute.go, test/integration/tcproute_test.go
Enables multi-backendRef support for `TCPRoute` to enable load-balancing.
Partially https://github.com/Kong/kubernetes-ingress-controller/issues/2405
=> feat: enable multi-backendRefs for TCPRoute

CHANGELOG.md, go.mod, go.sum, internal/manager/config.go, internal/manager/run.go, internal/manager/setup.go
This PR adds a simple retry routine for KIC to establish a connection with the Kong Admin API during startup. Currently, KIC goes on a CrashLoop until the Kong Admin API is ready. The crashes should be addressed as it is known that AdminAPI takes a while to start up and KIC should be made aware of that
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/2274
=> Retry init connections to kong admin api

CHANGELOG.md, internal/manager/setup.go
Disable deck's full diff output at log level info and above. diffs will only print at debug or trace.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2411 
deck doesn't run this output through the regular logging pipeline, so it has no log level, and is controlled independently by the `--silence-events` flag.
I opted to limit it to debug and lower since AFAIK it doesn't have any type-specific logic for anything other than Konnect Documents, so it prints changes to certificates and credentials and such, which we don't want at info.
Ideally deck would return diff text to a callers to allow them to …
=> fix(sendconfig) suppress deck diff logs at info

CHANGELOG.md, internal/dataplane/parser/translate_udproute.go, test/integration/tcproute_test.go, test/integration/udpingress_test.go, test/integration/udproute_test.go
Adds support for load-balancing `UDPRoutes` with multiple `backendRefs`.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/2405
=> feat: multi backendref load-balancing for UDPRoute

internal/adminapi/client.go
Kubernetes ingress controller does not start with mTLS when certificates are provided by files #2443
Clenup options after reding from file location.
fixes #2443
=> Kubernetes ingress controller does not start with mTLS when certificates are provided by files #2443

CHANGELOG.md, internal/dataplane/kong_client.go
This resolves race conditions that can occur when updating the status of an object in a controller shortly after caching it in the dataplane client.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/2446
=> fix: race conditions for object status updates

CHANGELOG.md, internal/dataplane/kong_client.go, internal/dataplane/sendconfig/sendconfig.go, internal/manager/config.go, internal/manager/run.go
This adds a flag to control the deck behavior added in https://github.com/Kong/deck/pull/617
- ~At present, deck doesn't provide an option to skip these in file parsing (i.e. generating the target config), so it and this draft strip the certificates out after the fact. We should add an option to the `file.RenderConfig` to handle this instead so that the controller doesn't duplicate logic.~ https://github.com/Kong/deck/pull/622 changes this and the draft has been updated to remove the duplicated logic.
- This currently uses an unreleased deck tag.
=> Add flag to skip CA certificates

internal/cmd/rootcmd/env.go, internal/cmd/rootcmd/env_test.go
**What this PR does / why we need it**: This pr introduces the environment variable name in the error message for better UX and understanding when an env fails to bind with its value.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2412
=> fix(kic): updated error message of env binding to include environment variable name

PROJECT, config/rbac/role.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, internal/controllers/gateway/referencepolicy_controller.go, internal/manager/controllerdef.go, internal/store/fake_store.go, internal/store/fake_store_test.go, internal/store/store.go
Add a controller to watch Gateway ReferencePolicies and associated store functions and RBAC permissions.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: part of #2407 
Just controller scaffolding, doesn't actually do anything with the policies we ingest yet.
This controller is simple enough (just ingest everything we can see, no cross-resource validation needed) that it probably could be handled by the generator, but none of the other Gateway resources use it, so I hand-rolled it.
This drops policies into the store for (future PR) evaluation at configuration generation time. It's probably technically possible …
=> feat(controllers) add ReferencePolicy controller

test/integration/httproute_test.go
Tests that we can bind plugins to HTTPRoutes.
Removes some test content that was just making the test take longer (see #2452) as written.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2391
=> Test HTTPRoute plugin support

.github/workflows/nightly.yaml, .github/workflows/release.yaml
We missed this in the earlier PR. Found after looking at nightly and seeing that RH was still single-arch.
=> fix(build) enable arm64 for Red Hat images

CHANGELOG.md, internal/controllers/gateway/gateway_controller.go
This PR makes it possible for `Gateway` resources to be considered usable even if they are attached to a `LoadBalancer` type `Service` which has not yet had any IP addresses (or hostnames) provisioned for it.
Resolves #2413
=> fix: enable gw apis with broken lb svc

.github/workflows/license.yaml, Dockerfile, LICENSES, RELEASE.md
This replaces the license bot (RIP, it was wrong half the time anyway) with FOSSA reporting.
**Notes and caveats**
- Accurate scanning requires running against code in CI and pushing results using an API key. The pull mode (FOSSA reads your repo from their end) generates a lot of false positives. As such, this is set to run on cron so that contributor secret access is a non-issue.
- Alerts will come in via the team alias email (we can alternately send it to Slack, but I didn't set that up). In the event of a problem, we'll need to revert code that introduces a problem dependency. IMO this is fine since we don't expect them to happen often. I can optionally set up variants that run on PRs with secret access, just means some copy pasta workflow stuff.
- LICENSES is the license report as of …
=> chore(ci) replace license bot with FOSSA

.github/workflows/test.yaml
Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>
Looking at the Github actions code I saw `# TODO: deduplicate the download-artifact steps by implementing a matrix workflow step instead`.
Instead of using the `matrix` to solve this problem of duplicating the artifact download step, it's possible to use a better approach.
1. Store coverage files to the same upload artifact folder called `coverage`.
```yaml
- name: collect test coverage
uses: actions/upload-artifact@v3
with:
name: coverage
path: coverage.postgres.out
```
2. When it comes to downloading, we can simply download all coverage reports from this artifact folder and store to a subfolder defined using the variable `path`
```yaml
- name: collect test coverage artifacts
id: …
```
=> Refactor test coverage download and upload steps

CHANGELOG.md, Makefile, PROJECT, config/rbac/role.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, examples/gateway-tlsroute.yaml, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/tlsroute_controller.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/translate_tlsroute.go, internal/manager/controllerdef.go, internal/store/fake_store.go, internal/store/fake_store_test.go, internal/store/store.go, test/integration/examples_test.go, test/integration/tlsroute_test.go
It's TLSRoute :shrug: 
Basically the same as the other non-HTTP routes, but it populates route.snis instead of route.destination.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2088 
- This does not implement loading certificates, which aren't actually loaded via TLSRoute. For now, TLSRoutes will always use the default proxy certificate. TLSRoute code is not expected to change when we add support for Gateway.CertificateRefs, as we'll still just add SNI+certificate pairs independent of route creation: https://github.com/Kong/kubernetes-ingress-controller/issues/2474
- Passthrough is not implemented per …
=> feat(*) add support for TLSRoute

CHANGELOG.md, internal/annotations/annotations.go, internal/controllers/utils/utils.go, internal/dataplane/parser/parser_test.go, internal/store/fake_store_test.go, internal/store/store.go, test/integration/knative_test.go
Use `networking.knative.dev/ingress-class` as well as `networking.knative.dev/ingress-class` annotations (with the priority on the former - added in this PR) since knative has already added support for `networking.knative.dev/ingress-class` in https://github.com/knative/networking/pull/522
**Which issue this PR fixes** :
fixes #2344
=> chore: use `networking.knative.dev/ingress-class` additionally to `networking.knative.dev/ingress.class`

internal/util/reports.go
When usage reporting calls encounter an error, the code logs an error. 
These errors are not actionable for users and cause unnecessary confusion.
Hence, this patch disables those log statements.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes none
No changelog entry required.
=> fix: skip logging errors for usage reports

CHANGELOG.md, internal/cmd/fips/main.go, internal/cmd/main.go, internal/cmd/rootcmd/rootcmd.go, internal/cmd/rootcmd/run.go, internal/cmd/rootcmd/signal.go, internal/manager/config.go, internal/util/test/controller_manager.go
This PR adds a `--term-delay` option to the CLI for the ingress-controller.
**Context:** 
There are cases where due to network load balancer (NLB) configuration that a delay needs to be introduced to the containers, this delay is configurable for the Kong Proxy container through the helm chart, however it is not possible to configure this delay for the ingress-controller. This can result in stale upstreams during NLB draining and downtime for services. Making this delay configurable seems the easiest approach to addressing this limitation.
With the ingress-controller gone, any changes to the underlying services that the proxy is routing to would be missed. Due to limitations with AWS NLB deregistration delays, we've had to configure a sleep of up to …
=> Feature: Add `--term-delay` option to CLI

.github/workflows/test.yaml, CHANGELOG.md, FEATURE_GATES.md, Makefile, examples/ingress.yaml, internal/dataplane/kong_client.go, internal/dataplane/kongstate/service.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/translate_ingress.go, internal/dataplane/parser/translators/ingress.go, internal/dataplane/parser/translators/ingress_test.go, internal/manager/feature_gates.go, internal/manager/run.go, test/integration/httproute_test.go, test/integration/suite_test.go, test/integration/tcproute_test.go, test/integration/utils_test.go
Historically a `kong.Route` was made for _every path_ that was present in an `Ingress` resource. This patch adds an option for an alternative `Ingress` object translation in the `dataplane/parser` code that will combine those paths into a single `kong.Route` if their `ingress.Namespace`, `ingress.Name`, `ingress.Host`, `service.Name`, and `service.Port` match. The result is smaller configuration sizes which is particularly helpful for end-users who configure their `Ingress` resources with incredibly large numbers of paths all pointing to the same Kubernetes `Service`.
Fixes #2490
=> feat: ingress translator w/ combined routes

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, config/crd/bases/configuration.konghq.com_kongingresses.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, config/crd/bases/configuration.konghq.com_tcpingresses.yaml, config/crd/bases/configuration.konghq.com_udpingresses.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, pkg/apis/configuration/v1/kongclusterplugin_types.go, pkg/apis/configuration/v1/kongconsumer_types.go, pkg/apis/configuration/v1/kongingress_types.go, pkg/apis/configuration/v1/kongplugin_types.go, pkg/apis/configuration/v1beta1/tcpingress_types.go, pkg/apis/configuration/v1beta1/udpingress_types.go
**What this PR does / why we need it**: To add categories to CRD and make e.g. querying for KIC related objects more convenient.
**Which issue this PR fixes** : fixes #1147 
**Special notes for your reviewer**: 
- Do we want to use the proposed `kong-ingress-controller` category or maybe something else? Or maybe we'd like to keep the proposed `kong-ingress-controller` but add an additional one?
=> feat(crd): add categories

Dockerfile, Makefile
This is needed to make sure that arm64 container image builds end up having a binary built for arm64 arch and not amd64 like e.g. in [this build](https://hub.docker.com/layers/nightly-ingress-controller/kong/nightly-ingress-controller/2022-05-27/images/sha256-df1bd43b7f150bcbcb074092f995f464975b15b44ea4a8b5e1a40f075e8a2dcc?context=explore)
The reason for this is because the `--platform` flag doesn't seem to make any effect when `TARGETARCH`/`TARGETPLATFORM`/`TARGETOS` are set. It was already mentioned by @rainest in: https://github.com/Kong/kubernetes-ingress-controller/pull/2387#issuecomment-1106695450
The effect of this PR will be that by default, when starting image build, we'll get the image for the host arch not `linux/amd64`.
**Special notes …
=> fix(build): remove default for TARGETARCH which made arm64 builds end up with amd64 binaries

.github/workflows/nightly.yaml
To be able to run nightly builds on request. Without this patch the metadata is not generated because it's only configured to do so on schedule.
Hence use [`type=raw`](https://github.com/docker/metadata-action#typeraw) instead of `type=schedule`.
Perhaps we could change the nightly tag format to include e.g. a SHA? Not sure if that can be easily done with https://github.com/docker/metadata-action
=> fix(ci): make it possible to run nightly builds on request

hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go
When controllers log that they can't move forward with an object yet because it's not yet been configured fully on the dataplane, this is a normal and transient issue so it should only be logged at debug level and it should be logged as info not an error.
=> fix: unconfigured objects in ctrls should debug log as info

README.md
This PR removes dead links from README, reorganizes sections and links definitions and it also adds some information about our container images and where can they be found.
=> docs(README): README.md cleanup

internal/util/test/crds.go, test/e2e/all_in_one_test.go
Pin the Gateway APIs CRD version, currently to 0.4.2
Addresses CI failures like
```
2022-06-07T13:56:57.0069650Z     tcproute_test.go:661: 
2022-06-07T13:56:57.0072564Z         	Error Trace:	tcproute_test.go:661
2022-06-07T13:56:57.0072985Z         	Error:      	Received unexpected error:
2022-06-07T13:56:57.0074015Z         	            	the server could not find the requested resource (post referencepolicies.gateway.networking.k8s.io)
2022-06-07T13:56:57.0074575Z         	Test:       	TestTCPRouteReferencePolicy
```
Upstream master changed this in …
=> chore(tests) pin Gateway CRD version

Makefile, internal/controllers/gateway/utils.go
Related release: https://github.com/golangci/golangci-lint/releases/tag/v1.46.2
- As of now the current implementation [`go-get-tool`](https://github.com/Kong/kubernetes-ingress-controller/blob/22e53cdcb23c3bf908b4e4ae951eedb0b4b671fd/Makefile#L48-L58) doesn't check for the version of the tool it "gets" which requires users to manually remove the binary in order to get the update. Perhaps it would be nice to add a mechanism which would replace `go-get-tool` which would account for current tool's version and the "in-tree" version and in case those differ, to download the "in-tree" version.
=> chore: bump golangci-lint to v1.46.2

internal/manager/run.go
This PR fixes an incorrect usage of logger `logr.Logger`, specifically the formatting in the `Info()`, which does not support format strings.
Before this PR the changes log looked like:
```console
INFO[0007] Retrying kong admin api client call #%d/%d after error: %w  logger=setup
```
and after:
```console
INFO[0002] Retrying kong admin api client call after error  #=2/60 error="making HTTP request: Get \"https://172.18.0.23:444/\": x509: “localhost” certificate is not standards compliant" logger=setup
```
=> chore: correctly format logger fields on admin api connection retries

hack/deploy-admission-controller.sh
Ports changes made in helms charts in [#612](https://github.com/Kong/charts/pull/612) to the `hack/deploy-admission-controller.sh` deploy script.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
Fixes #2501 
As suggested in [kubernetes-ingress-controller/issues/2501](https://github.com/Kong/kubernetes-ingress-controller/issues/2501) PR was tested manually:
1. Verified that unique constraint of secrets does trigger failure when admission failure policy is `Ignore` as described in [kubernetes-ingress-controller/issues/2431. Verified that `Fail` policy prevents config from being applied …
=> fix: change admissionWebhook.failurePolicy value to Ignore

CHANGELOG.md, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/route.go, internal/dataplane/kongstate/route_test.go, internal/dataplane/kongstate/service.go, internal/dataplane/kongstate/service_test.go, internal/dataplane/kongstate/upstream.go, internal/dataplane/kongstate/upstream_test.go, internal/dataplane/kongstate/util.go, internal/dataplane/kongstate/util_test.go, internal/dataplane/parser/ingressrules.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translate_utils.go, internal/dataplane/parser/translate_utils_test.go, internal/util/objectmeta.go, internal/util/objectmeta_test.go
In order to prevent users on relying on `KongIngress` annotation overrides this PR disables the ability to do so for:
- Gateway API *`Route` objects
- kubernetes `Service`s defined as Gateway API *`Route`'s backends
fixes #2505 
N/A
=> chore: remove KongIngress support for Gateway API Route objects and Services referenced by those Routes

test/integration/knative_test.go
Update the KNative minimum test cluster version. The current KNative version we use requires 1.22 or higher.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes broken 2.4 release jobs.
Reviewing a GKE cluster that never got past the cluster setup phase showed:
```
2022/06/15 17:55:51 Failed to get k8s version kubernetes version "1.21.12-gke.2200" is not compatible, need at least "1.22.0-0" (this can be overridden with the env var "KUBERNETES_MIN_VERSION")
```
on most of the KNative Pods.
=> chore(tests) update KNative min version

.github/workflows/release.yaml
Adds an example version format to the release workflow
This will actually accept any valid semver if I'm reading it correctly, and appropriately use the v prefix for the tag and not the image, but whatever, this makes it so you don't have to think about it.
=> chore(ci) add example to release

.github/ISSUE_TEMPLATE/release.yaml
Adds some links for finding the latest versions of other software used in release testing.
=> chore(docs) add links to release template

.github/ISSUE_TEMPLATE/release.yaml
We missed broken E2E tests because the current link points to the build job, which builds the image _before_ we test it. The new link are the tests we run after on that image.
=> chore(release) change link to E2E tests

config/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Add the Pod namespace to the manual ServiceAccount token mount. Without this mount, controller-runtime cannot automatically determine the leadership election namespace.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #251
E2E run on this branch: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/2572549219
After merge, we need to create a 2.4.x branch, cherry-pick this into it, and release 2.4.2, and finally cherry-pick the release commit into main.
Based on the filesystem from 2.3 there shouldn't be any other items we need:
```
/ $ ls /var/run/secrets/kubernetes.io/serviceaccount/
ca.crt …
```
=> fix(manifests) mount namespace from downward API

config/variants/enterprise/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
**What this PR does / why we need it**: To have consistent version of kong-gateway in manifests
Related PR that bumped it in other manifests: https://github.com/Kong/kubernetes-ingress-controller/pull/2343
=> chore: bump kong-gateway image from 2.7 to 2.8 in enterprise manifest

test/e2e/helpers_test.go
To have move verbose e2e failures (w.r.t enterprise version string) so that one does not need to rerun the tests to get the log. This effectively changes
```
helpers_test.go:351:
Error Trace:    helpers_test.go:351
all_in_one_test.go:426
Error:          Should be true
Test:           TestDeployAllInOneEnterprisePostgres
```
into
```
helpers_test.go:351:
Error Trace:    helpers_test.go:351
all_in_one_test.go:432
Error:          "2.8.1" does not contain "enterprise-edition"
Test:           TestDeployAllInOneEnterprisePostgres
```
=> tests: make verifyEnterprise helper more verbose on version string failure

config/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Further iterates on  #2620. Copies the change from https://github.com/Kong/charts/pull/623
This is not really necessary in this repo, since it only applies to Deployments with no controller container, and we don't actually offer that in the all-in-one manifests here. However, it doesn't really hurt us to add it, so I added it for consistency with the chart.
=> chore(deploy) add Kuma token annotation

.github/ISSUE_TEMPLATE/release.yaml, RELEASE.md
Remove most of RELEASE.md, since it's now handled by the form and
there's no way to easily keep both up to date. It now links to the form
and includes some troubleshooting steps that do not easily fit into the
form.
Link the troubleshooting guide from the form.
Add information on running GKE tests from a local machine.
=> doc(release) reorganize troubleshooting guide

.github/dependabot.yml
After #2600 has been merged, it seems that we need to add `third_party` directory explicitly to [dependabot's config](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/dependabot.yml) to make it update Go dependencies in that dir.
Additionally, this PR adds appropriate labels for dependabot's PRs.
=> chore(ci): add third_party dir to dependabot config

CHANGELOG.md, LICENSES, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
**What this PR does / why we need it**: cherry pick 2.4.2 onto main to e.g. fix links from [v2.4.2 release page](https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v2.4.2)
=> chore: release 2.4.2 changes

CHANGELOG.md, internal/manager/utils/reports.go, internal/util/reports.go, internal/util/reports_test.go
logs from telemetry reporter in `internal/utils.Reporter` does not appear in pod logs. 
Here I changed the logger `logr.Logger` and initialize it with `ctrl.Log.WithName()`, instead of the deprecated `logrus.Logger`.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
=> fix(log): change logger in reporter to logr.Logger to make the log appear in pod logs

test/integration/gateway_test.go, test/integration/gateway_webhook_test.go, test/integration/helpers_test.go, test/integration/httproute_test.go, test/integration/httproute_webhook_test.go, test/integration/suite_test.go, test/integration/tcpingress_test.go, test/integration/tcproute_test.go, test/integration/tlsroute_test.go, test/integration/udpingress_test.go, test/integration/udproute_test.go
This PR aims at consolidating and factorizing the `gatewayClass` and `Gateway` resources across all the integration tests, to remove duplicated code and improve code quality.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #2461 
You can find the PR's change list below:
* All the explicit instantiation of `GatewayClass` and `Gateway` objects, followed by the respective `GatewayV1alpha2().GatewayClasses().Create()` and `GatewayV1alpha2().Gateway().Create()`  function calls have been replaced by a helper call. These helpers are in the `helpers_test.go` file.
* Each function that needed a `gatewayClass`, …
=> Gateway resources consolidation

internal/adminapi/client_test.go, internal/dataplane/kongstate/route_test.go, internal/dataplane/kongstate/service_test.go, internal/dataplane/kongstate/upstream_test.go, test/e2e/utils_test.go
`ioutil` got [deprecated in go1.16](https://go.dev/doc/go1.16#ioutil) and started failing when experimenting with go1.19 (specifically running `make lint`.
Didn't dig into the subject but it seems this will necessary regardless.
Exemplar failure: (related `staticcheck` rule: https://staticcheck.io/docs/checks/#SA1019)
```
internal/adminapi/client_test.go:12:2: SA1019: package io/ioutil is deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
"io/ioutil"
```
=> chore: remove deprecated `ioutil` usage

.github/workflows/e2e.yaml, .github/workflows/e2e_targeted.yaml, .github/workflows/test.yaml
To make kong EE license management easier/more automated.
**Which issue this PR fixes**: related https://github.com/Kong/team-k8s/issues/27
In order to make this work, `PULP_PASSWORD` has been added to `Configure ci`'s environment secrets.
=> feat(ci): use github action to obtain kong license

test/e2e/all_in_one_test.go, test/e2e/kuma_test.go
Adds an E2E test with Kuma with Postgres and DB-less.
E2E run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/2666075834
=> test(e2e) add a DB-less Kuma test

test/e2e/all_in_one_test.go, test/e2e/utils_test.go
dump pod logs if the flaky e2e test case `TestDeployAllInOnePostgresWithMultipleReplicas` fails
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
related to #2670
=> test(e2e) print pod logs if the flaky test fails

test/integration/helpers_test.go
This PR removes the unnecessary log of `err` when it's `nil`.
=> tests: print error only when not nil in gateway tests

test/e2e/helpers_test.go
currently `deployIngress` creates a `LoadBalancer` type service, but we do not need to access its LoadBalancer IP, since the service is only used as an upstream in kong-proxy. However, the metallb controller may update the service when LoadBalancer IP is ready, then the `update` operations would get error if the service is updated by metallb. This caused a flaky e2e test: #2699 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: may fix #2699 
=> test(e2e) create service in ClusterIP type in deployIngress

.github/PULL_REQUEST_TEMPLATE.md
This PR addresses the unnecessary PR template boilerplate which often ends up in the final PR description. Specifically this removes:
```
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
```
from `Which issue this PR fixes` section and adds comments documenting what is expected in particular section. Thanks to the usage of comments, there should be no boilerplate being added to the final PR description and one can hope that the contributors will place their comments in designated places.
=> chore: remove boilerplate in pr template

.golangci.yaml, test/e2e/utils_test.go, test/integration/helpers_test.go, test/integration/knative_test.go
This PR adds the following builds tags to `golangci-lint` invocation so that tests code is also linted:
- `integration_tests`
- `e2e_tests`
- `conformance_tests`
It also fixes the excluded dirs in the config: `pkg/client` doesn't exist so it was replaced by `pkg/clientset` which contains generated code and `config` dir was also added as it only contains the k8s manifests.
=> ci: add tests build tags to golangci-lint

.github/PULL_REQUEST_TEMPLATE.md
There was a duplicate comment block under the fixes section after the most recent change. This removes it along with a minor grammar fix.
=> chore(repo) remove duplicate block from template

.golangci.yaml, test/e2e/kuma_test.go, test/integration/tlsroute_test.go
This PR removes an exception from `golangci-lint`'s config which allowed to not check errors in test files.
=> ci(lint): do check errors in tests

test/integration/tcpingress_test.go, test/integration/utils_test.go
~Bitnami made changes that effectively require a passphrase. They'll probably roll that back but this fixes it til then and doesn't otherwise affect the test.~ Redis rejects the passphrased key even though openssl in the container is fine using it to decrypt the key. May be something else broken in the script, don't really care to investigate, pinning it instead.
fix #2735
=> fix(tests) pin Redis version

CHANGELOG.md, internal/validation/consumers/credentials/vars.go
`mtls-auth` was omitted from the supported types list since the inception of this validator, although we added supported fields for it.
=> fix(admission) allow mtls-auth

test/e2e/kuma_test.go
https://github.com/Kong/kubernetes-ingress-controller/runs/7513607112?check_suite_focus=true 
```
kuma_test.go:89: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/e2e/kuma_test.go:89
Operation cannot be fulfilled on services "httpbin": the object has been modified; please apply your changes to the latest version and try again
Test:       	TestDeployAllInOneDBLESSKuma
```
error happens in e2e run of `TestDeployAllInOneDBLESSKuma`. added function dumping service when updating fails.
related: #2733 
=> test(e2e) dump service status if failed to update in kuma test

CHANGELOG.md, hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go
https://github.com/Kong/kubernetes-ingress-controller/pull/2577 missed some IngressClass lookups. This does more of the same.
Fix #2712 
Draft pending changelog, trying to avoid merge conflicts with creating the unreleased section.
=> fix(controllers) disable more IngressClass lookups

test/integration/helpers_test.go, test/integration/ingress_test.go
use retry on setting `ingress.spec.class` in `TestIngressClassNameSpec` because nightly build failed:
https://github.com/Kong/kubernetes-ingress-controller/runs/7596036145?check_suite_focus=true
```
ingress_test.go:352: 
Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/ingress_test.go:352
Operation cannot be fulfilled on ingresses.networking.k8s.io "httpbin": the object has been modified; please apply your changes to the latest version and try again
Test:       	TestIngressClassNameSpec
```
=> chore(tests) add retry on setting ingress class

go.mod, internal/dataplane/parser/translate_routes_helpers.go, internal/dataplane/parser/translate_routes_helpers_test.go, internal/dataplane/parser/translate_tcproute.go, internal/dataplane/parser/translate_tlsroute.go, internal/dataplane/parser/translate_udproute.go
This extracts the common bits of Gateway Routes to `kong.Route` translation into common functions (which could also be extended to other types like `HTTPRoute`).
=> refactor: add generic Gateway Routes to kong.Route translation functions

.github/workflows/check_pr_labels.yaml
In order to prevent accidentally merging PRs that shouldn't be merged - due to labels set on them - but have all the checks pass successfully which might make it tempting to merge.
For now it only blocks PRs with those labels:
- `do not merge`
- `on-hold`
=> ci: add labels checker

.github/workflows/check_pr_labels.yaml
This PR [disables reviews](https://github.com/pmalek/verify-pr-label-action#disable-reviews) from [labels checker](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/check_pr_labels.yaml) so that now whenever a "blocking label" is used, the GH action would fail instead of submitting a review requesting changes.
=> chore(ci): don't review code for labels checker

.github/workflows/test.yaml, .github/workflows/test_nightly.yaml
Remove the nightly Kong image tests from the normal test run.
Run nightly Kong image tests when the PR has a "ci/run-nightly" label or via dispatch.
As reviewers have probably observed, the nightly image tests fail rather often, because the nightly image is apparently less stable for existing functionality than we'd have hoped, and not reporting much in terms of useful failures (most of the failed nightly runs I've reviewed just exceeded the timeout for some reason, instead of indicating some particular failure).
We only _need_ these tests on PRs that introduce features to support as-yet unreleased Kong functionality, so I think this is probably the best option. I plan to discuss this in tomorrow's team meeting, …
=> chore(ci) make nightly tests conditional

.github/workflows/test.yaml, CHANGELOG.md, FEATURE_GATES.md, Makefile, internal/manager/controllerdef.go, internal/manager/feature_gates.go, internal/manager/feature_gates_test.go, test/conformance/suite_test.go, test/e2e/features_test.go, test/integration/utils_test.go
This patch promotes the "Gateway" feature gate to beta and
turns it on by default for future releases.
Due to the fact that some Gateway API resources are still
in an alpha stage, this commit also creates the new feature
gate "GatewayAlpha" to lock alpha stage APIs behind a gate
that's off by default and not mix them with the beta APIs.
Partially resolves #2779
=> feat: promote Gateway feature gate to beta

go.mod, go.sum, test/integration/gateway_webhook_test.go, test/integration/httproute_webhook_test.go, test/integration/webhook_test.go
wait for webhook service to be connective before running test cases to avoid test flakes caused by webhook service being unavailable.
would fix #2760 
=> test: wait for webhook service to be connective in integration tests

CHANGELOG.md, go.mod, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils.go, test/conformance/gateway_conformance_test.go
All the conformance tests related to the gateways are passing and enabled by default.
Fixes #2777 
=> Gateway-related conformance tests

.github/workflows/cleanup.yaml, .github/workflows/e2e.yaml, .github/workflows/e2e_targeted.yaml, .github/workflows/nightly.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml, .github/workflows/test_nightly.yaml, CHANGELOG.md, go.mod, pkg/clientset/fake/register.go, pkg/clientset/scheme/register.go, third_party/go.mod
Bump to go1.19 since the upgrade has already been started by dependabot in #2770 and it causes issues when e.g. 1.19 is being used in CI to generate and verify no diff in generated files https://github.com/Kong/kubernetes-ingress-controller/runs/7744303539?check_suite_focus=true#step:8:34 but the author of PR uses 1.18 which ( as a result of changes between 1.18 in 1.19 in comments formatting ) does not produce a diff when generating files. 
=> chore: bump to go1.19 where we're still using 1.18

internal/cmd/rootcmd/env.go
This PR turns the discussion @pmalek and I had into a code comment for posterity.
It explains the genesis of the `bindEnvVars` mechanism that makes `pflag` flags settable by associated environment variables.
=> docs: document the `bindEnvVars` design choice

.github/workflows/e2e.yaml, .github/workflows/e2e_targeted.yaml, test/e2e/all_in_one_test.go, test/e2e/utils_test.go
- dump logs of pods in KIC deployment in `TestDeployAllInOnePostgresWithMultipleReplicas` it it fails, to see the status of leader election.
- pass the test if any one of the pod became the leader to solve the flakiness
.
related:  #2670 
=> test(e2e) dump logs of KIC pods and pass the test if there is one leader

Makefile
This PR removes the version of used gateway API from `Makefile` and makes it so we store it only in go.mod.
=> ci: store gateway API version only in go.mod

.golangci.yaml
`golint` has been deprecated and having it enabled in `.golangci.yaml` causes the following warning:
```
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.
```
This PR removes it from the config. The replacement - `revive` - is already in place in the config.
=> chore: remove unsupported golint linter

.github/actions/redhat-opdev-preflight-action/action.yaml, .github/actions/redhat-opdev-preflight-action/entrypoint.sh, .github/workflows/nightly.yaml, .github/workflows/release.yaml
Nightly builds do not submit images to scan registry, not results to connect portal
Fixes #2811
=> fix: do not publish RedHat nightly images

CHANGELOG.md, examples/gateway-httproute.yaml, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translate_utils.go, internal/dataplane/parser/translate_utils_test.go, internal/util/conversions.go, internal/util/hostname.go, internal/util/hostname_test.go, internal/util/k8s.go, test/conformance/gateway_conformance_test.go, test/integration/httproute_test.go
=> HTTPRoute conformance tests

internal/controllers/gateway/gateway_controller.go
Disables a list I overlooked in https://github.com/Kong/kubernetes-ingress-controller/pull/2797
Fix #2816
=> fix: disable ReferenceGrant list when unavailable

test/integration/tcproute_test.go
Runs a check in an eventually in a defer, to try and diagnose that eventually's failure without spamming logs.
Related to https://github.com/Kong/kubernetes-ingress-controller/issues/2668#issuecomment-1211219322
=> chore(tests) add temp TestTCPRouteEssentials diag

keps/0010-dynamic-plugin-configuration.md
Small expansion on the intended behavior of literal values. Effectively
being able to use syntax similar to shell expansion `$()` to reference
previously defined configuration values. And double dollar `$$` as a
means to escape from expansion
see: #2807
=> kep: amendment to kep 10 expanding on variable references in configuration

CHANGELOG.md, internal/dataplane/parser/parser.go
Missing service endpoints were being logging at error level, but this is unnecessary noise: there are plenty of normal operational reasons why these could be missing for a time, such as waiting on pods to provision. This patch switches this from error to info level to avoid undue noise and alarm.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/2820
=> fix: info log missing service endpoints

CHANGELOG.md, internal/dataplane/parser/parser.go
This turns a previous warning log about targets not being available for an upstream into an info log, as this condition is expected any time there are pods in flight.
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/2820
=> fix: info instead of warn for no targets

internal/controllers/gateway/gateway_controller.go, test/e2e/features_test.go, test/e2e/helpers_test.go
Ensure that the controller's desired addresses for Services with no external addresses (such as NodePorts) match the Gateway representation of no addresses. This ensures that the address update check does not attempt to proceed with an unnecessary update every reconcile, which would prevent the Gateway from becoming ready.
Add an E2E test that confirms Gateways work with NodePorts.
Fix #2808 
Fix #2823
E2E run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/2871403290
=> fix(gateway) handle NodePort addresses

internal/adminapi/client.go
This PR removes a seemingly outdated docblock comment. As I was reading through the source code, I stumbled upon this comment that looks like it was resolved by #2332 and left in by mistake.
=> Remove old comment

internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/httproute_controller.go, internal/dataplane/parser/translate_utils.go, internal/manager/controllerdef.go
Disable listing `ReferenceGrant`s in `HTTPRoute` controller when `GatewayAlpha` feature is not opened. Because  `HTTPRoute` is in v1beta1 resources, it should not depend on `v1alpha2` resource `ReferenceGrant`.
fixes #2828. 
No need to update `CHANGELOG.md`
=> fix(gateway): disable referenceGrant when GatewayAlpha feature is off

Makefile
Fixes a broken link in a TODO.
=> chore: replace broken link in TODO

Makefile, test/internal/cmd/generate-gateway-api-urls/main.go
This PR addresses a nuance where `make generate` would trigger generation of Gateway API URLs twice (once incorrectly).
Due to this Makefile target definition:
```
.PHONY: generate
generate: generate.controllers generate.clientsets generate.gateway-api-urls
...
.PHONY: generate.controllers
generate.controllers: controller-gen
...
go generate ./...
```
`generate.controllers` was invocation all `go:generate`s recursively from the whole repo. This was unnecessary.
This PR makes it so that `make generate.controllers` will now only call the necessary `go:generate`s and the generate code in `test/internal/cmd/generate-gateway-api-urls/` is now behind a build tag `generate_gateway_api_urls` so in the future `go generate ./...` will not trigger it without …
=> ci: add build tag to go generate invocation for gateway API URLs

config/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Kong gateway 3.0 added a new router, and 3 router modes configured by `KONG_ROUTER_FLAVOR`:
- `traditional` to use the old router
- `traditional_compatible` (default) to use the new router, while the old router APIs are still available. But have incompatibilities.
- `expression` to use the new router, and remove the support of old router APIs.
KIC 2.6 should use `traditional` for compatibility, while the default mode is `traditional_compatible`. So we need to configure the env var `KONG_ROUTER_FLAVOR` here. 
fixes #2852 
=> chore(manifests) add KONG_ROUTER_FLAVOR env var to set kong router mode to traditional

test/integration/gateway_test.go, test/integration/httproute_test.go, test/integration/ingress_https_test.go, test/integration/ingress_test.go, test/integration/kongingress_test.go, test/integration/plugin_test.go, test/integration/utils_test.go
Stops using the same route path across different tests. I'm not sure why this hasn't caused many problems in the past (maybe they were just uncommon and ambiguous enough that we never dug into them), but it makes sense. If nothing else, it confirms what made what when reading diagnostic dumps.
Update the plugin test to use the diagnostics system. Adding this required a small helper to handle the v1/v1beta1 Ingress split.
=> Separate test request paths

Makefile, third_party/client-gen.go, third_party/controller-gen.go, third_party/golangci-lint.go, third_party/gotestfmt.go, third_party/kustomize.go, third_party/pkg.go
This retrofits https://github.com/Kong/gateway-operator/pull/90 into this repo.
The reason why I want to do this now is that after https://github.com/Kong/gateway-operator/pull/252 got merged, `make generate.apis` throws this error:
```
<PATH>/gateway-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
pkg.go:4:2: import "github.com/golangci/golangci-lint/cmd/golangci-lint" is a program, not an importable package
pkg.go:6:2: import "k8s.io/code-generator/cmd/client-gen" is a program, not an importable package
pkg.go:7:2: import "sigs.k8s.io/controller-tools/cmd/controller-gen" is a program, not an importable package
pkg.go:8:2: import "sigs.k8s.io/kustomize/kustomize/v4" is a program, not an importable package
```
=> build: use third_party build tag for dependencies

third_party/gotestfmt.go
This PR fixes `make gotestfmt` target (which installs `gotestfmt` utility).
It seems that the install path was incorrect and it didn't install the binary.
=> chore(build): fix gotestfmt install path

CHANGELOG.md, Makefile, PROJECT, internal/admission/validator.go, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gatewayclass_controller.go, internal/controllers/gateway/gatewayclass_controller_test.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/dataplane/sendconfig/sendconfig.go, internal/manager/controllerdef.go, internal/manager/run.go, pkg/apis/configuration/v1/configsource.go, pkg/apis/configuration/v1/kongingress_types.go, pkg/apis/configuration/v1/kongprotocol_types.go, pkg/apis/configuration/v1beta1/groupversion_info.go, test/conformance/gateway_conformance_test.go, test/e2e/helpers_gateway_test.go, test/integration/gateway_test.go, test/integration/helpers_test.go, test/integration/httproute_webhook_test.go
This PR updates the handled Gateway API's CRD `GatewayConfiguration` from `v1alpha2` to `v1beta1`
Partially addresses #2887
Fixes #2890 
=> chore: bump Gateway API's GatewayClass from v1alpha2 to v1beta1

.github/workflows/kong3.0_compatibility.yaml
upload diagnostics of running Kong 3.0 compatibility tests, and temporarily disable tests against Kong EE for #2891.
failures: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/2983305677
=> test: temp disable kong EE and upload diag

test/integration/suite_test.go
For some reason we've ended up using kind v0.15.0 (which by default deploys k8s v1.25)
even though that
* our CI runners use ubuntu-latest (which at the time of writing this comment was ubuntu20.04)
which uses kind v0.14 https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
* when used with ktf (which at the time of writing this comment was set to v0.19.0) we
should use kind v0.14 since that what ktf has set as dependency
With all that said, we still managed to get kind v0.15 on our CI
https://github.com/Kong/kubernetes-ingress-controller/runs/8211490522?check_suite_focus=true#step:5:6
which causes issues down the line (`metallb` manifests using PSP which is not available
in k8s v1.25+).
**Special notes for your …
=> chore: pin k8s to v1.24.4 in integration tests

test/conformance/suite_test.go
For some reason we've ended up using kind v0.15.0 (which by default deploys k8s v1.25)
even though that
* our CI runners use ubuntu-latest (which at the time of writing this comment was ubuntu20.04)
which uses kind v0.14 https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
* when used with ktf (which at the time of writing this comment was set to v0.19.0) we
should use kind v0.14 since that what ktf has set as dependency
With all that said, we still managed to get kind v0.15 on our CI
https://github.com/Kong/kubernetes-ingress-controller/runs/8211490522?check_suite_focus=true#step:5:6
which causes issues down the line (`metallb` manifests using PSP which is not available
in k8s v1.25+).
**Special notes for your …
=> chore: pin k8s to v1.24.4 in conformance tests

.golangci.yaml
This PR aims at silencing these errors in `golangci-lint`
```
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```
=> chore(ci): replace abandonded linters with unused (as suggested by golangci-lint)

.github/workflows/e2e.yaml, test/e2e/all_in_one_test.go, test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/istio_test.go, test/e2e/kuma_test.go
fix the problem that kubernetes version and istio version was not correctly set in e2e action. This causes e2e always run in latest kubernetes version of `kind`. So when k8s 1.25 released and kind bumped k8s version to 1.25, metallb stopped working and caused e2e tests fail.
fixes #2897 
=> test: fix e2e variable for k8s version

PROJECT
After merging #2900 and #2984 we forgot to update `PROJECT` file which is what this PR is doing to account for new version of `Gateway` and `HTTPRoute` CRDs that we handle.
=> chore: correct PROJECT file with `Gateway` and `HTTPRoute` `v1beta1` CRD versions

PROJECT, config/rbac/role.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, hack/generators/controllers/networking/main.go, internal/controllers/configuration/zz_generated_controllers.go
The name of resource (used in RBAC) are in ALL lower case. So `IngressClassParameterses` in clusterroles should be changed into `ingressclassparameterses`. 
fixes the recent e2e failure.
=> fix: change name of ingressclassparameterses into lower case

.github/workflows/kong3.0_compatibility.yaml
fix the problem that dbmode is not passed to `make _test.integration` correctly because env `DBMODE` is actually used in makefile. Also skipped enterprise/dbless combination because we do not have such test in makefile yet.
fixes #2891 
=> test: fix dbmode in 3.0 compat test

internal/dataplane/deckgen/generate.go, internal/dataplane/kong_client.go, test/integration/consumer_test.go
Sets format version 3.0 if the Kong version is 3.0.x or higher.
Adds a consumer and credential integration test, which surprisingly we apparently never had before.
After #2833 tested successfully, [another manual run today](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3023799669) resulted in failures on DB-less. Review of diagnostics indicates this is likely due to paths including the prefix twice:
```
routes:                 
- regex_priority: 200 
service: 3d13ec4a-1c07-52f5-a3a1-ced6cae4cfd4
protocols:             
- http                  
- https                                      
https_redirect_status_code: 426                          
paths:                
- /test_ingress_essentials/ …
```
=> fix(sendconfig) vary the format version

internal/util/test/webhooks.go, test/integration/suite_test.go
* changes binding address of the webhook server to `0.0.0.0` so that it's reachable from any address host is called 
* makes `AdmissionWebhookListenHost` depend on the host environment 
* for vanilla docker host it will use default docker bridge network gateway - `172.17.0.1` as it already did 
* for colima docker host it will use a hardcoded host IP address routable from colima VM and colima hosted containers - `192.168.5.2`. 
It allows to run admission webhook integration tests locally on a colima based docker host. 
Drawback is that we're building more hacks on top of the hack which is tracked by this issue: https://github.com/Kong/kubernetes-ingress-controller/issues/1613
Complete these before marking the PR as `ready …
=> fix: adapt admission webhook tests to run in colima host

CHANGELOG.md, examples/gateway-httproute.yaml, examples/gateway-tcproute.yaml, examples/gateway-tlsroute.yaml, examples/gateway-udproute.yaml, internal/annotations/annotations.go, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gatewayclass_controller.go, internal/manager/config.go, internal/manager/run.go, test/conformance/gateway_conformance_test.go, test/e2e/helpers_gateway_test.go, test/integration/gateway_test.go, test/integration/gateway_webhook_test.go, test/integration/helpers_test.go, test/integration/httproute_webhook_test.go, test/integration/suite_test.go, test/integration/tlsroute_test.go
=> KIC-KGO integration

Makefile, test/e2e/helpers_gateway_test.go
Fix e2e test failures after #2917 merged, which requires KIC to reconcile gateway when `gatewayClass` is annotated as unmanaged.
=> test: set gatewayclass to unmanaged in e2e tests

.github/workflows/kong3.0_compatibility.yaml, CHANGELOG.md, config/base/kong-ingress-dbless.yaml, config/variants/postgres/kong-ingress-postgres.yaml, config/variants/postgres/migration.yaml, config/variants/postgres/wait/kong-ingress-postgres.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, internal/dataplane/parser/translate_knative.go, test/e2e/all_in_one_test.go, test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/istio_test.go
Updates the 3.x compatibility test to use release images. Awaiting https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3039067881 as a test run against this branch.
Changes the the various `/bin/sh -c` invocations in container commands to `/bin/bash -c` as all images provide a bash and the default's `/bin/sh` is not compatible with our scripts.
Fixes the error type check for Knative's IngressClass scan; I forgot it earlier when I fixed the not-Knative version.
The Enterprise image pull credentials were not properly configured; this fixes those by virtue of no longer requiring them. We want to start using the release images anyway since they're now the newest versions.
However, it breaks the OSS runs …
=> chore(tests) use 3.x release images

go.mod, go.sum, internal/dataplane/kong_client.go, internal/manager/run.go, test/integration/utils_test.go
The controller expects the original version of the semver library, not the fork. To avoid a more extensive rework of the controller version code at this time, this converts the forked semver back into a standard semver.
A follow-up issue to try and disentangle this mess is forthcoming.
=> chore(*) translate semver fork to original

.github/workflows/release.yaml, CHANGELOG.md, LICENSES, config/image/enterprise/kustomization.yaml, config/image/oss/kustomization.yaml, config/variants/enterprise/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Releases 2.6.
Fix #2880 
```
15:03:41-0700 esenin $ docker run --rm kong:3.0 /bin/bash -c "echo aaa" 
Unable to find image 'kong:3.0' locally
3.0: Pulling from library/kong
docker: no matching manifest for linux/amd64 in the manifest list entries.
```
=> Release 2.6

.github/workflows/release.yaml
I forgot to look at the older versions still supported. See https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3056146579/jobs/4930247339
Does not abort release tests due to unsupported versions.
Force-merging for expediency.
=> chore(ci) remove 1.20 from previous Kubernetes

internal/dataplane/parser/translate_ingress.go
Currently the controller does not correctly add the `3.x "~" regular expression path prefix` to ingress paths  when all of the conditions are met:
- Path match the 2.x regex heuristic
- IngressClass has the EnableLegacyRegexDetection flag set.
- The `combined routes` feature is enabled. 
The `combined routes`  feature seems to disable the regexp detection.
As a result test `TestIngressClassRegexToggle` fails when run with `KONG_CONTROLLER_FEATURE_GATES="GatewayAlpha=true,CombinedRoutes=true"`.
This PR aims at fixing that by making the code for ingress rule translation on `featureEnabledCombinedServiceRoutes` path behaves the same as on `!featureEnabledCombinedServiceRoutes` path.
Fixes …
=> fix: handling lagacy regexp detection for paths when combined routes are enabled

.github/ISSUE_TEMPLATE/release.yaml
Release template describes red hat catalog process.
=> chore: release template describes red hat catalog process

internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gatewayclass_controller.go, internal/dataplane/parser/parser.go, internal/util/conditions.go, internal/util/conditions_test.go, test/e2e/features_test.go, test/e2e/helpers_gateway_test.go, test/integration/gateway_test.go, test/integration/helpers_test.go, test/integration/tlsroute_test.go
* introduces `CheckCondition` helper function to reduce code repetition across the codebase (replaces repeating for loops with nested ifs) 
* makes sure that `Condition.ObservedGeneration == Resource.Generation` while matching conditions 
Resolves #2609 
As I can see according to the [API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status) we do populate the `ObservedGeneration` property when updating conditions. That's why I have made it to be verified when matching conditions. Please correct if I'm missing something here.  
Complete these before marking the PR as `ready …
=> chore: introduce CheckCondition helper

internal/dataplane/parser/ingressclassparemeters_test.go, internal/store/store.go
fix panics when some field is `nil` in `ingressClass.spec.parameters`
fixes #2958.
=> fix: check nils in ingressClass.Parameters

CHANGELOG.md, internal/annotations/annotations.go, internal/dataplane/parser/translate_ingress.go, internal/dataplane/parser/translate_ingress_test.go, internal/dataplane/parser/translate_knative.go, internal/dataplane/parser/translate_knative_test.go, internal/dataplane/parser/translate_utils.go, internal/dataplane/parser/translators/translator_vars.go, test/integration/ingress_test.go
Translate between an Ingress-compatible regex prefix and the Kong regex prefix. Allow users to override the default regex prefix using an annotation.
Add tests for regex Ingress paths using the prefix.
By default, Ingress paths beginning with `/~` will translate to Kong route paths beginning with `~`. This functionality _is not_ version-gated, with the expectation that such paths are uncommon in the wild. For users that do need these paths translated verbatim, overriding the prefix with the `konghq.com/regex-prefix` allows you to preserve `/~`-prefixed paths as they are.
Fix #2945 
=> fix(translate) use Ingress-specific regex prefix

test/integration/ingress_test.go, test/integration/suite_test.go
- fixes the failure when creating a cluster in KIND with specified version
- skip `TestIngressClassRegexToggle` in k8s versions <= 1.21 (EOL now) which does not support namespaced ingress class parameters by default.
fixes #2957 
=> test: fix specifying kind cluster version

.github/workflows/e2e.yaml
Disables E2E job fail fast. The job iterations are independent and there's no reason one failure should abort the rest. We want all of them to run to always get coverage across all matrix versions.
=> chore(ci) disable E2E fail fast

test/e2e/helpers_test.go
This resulted in several E2E failures and just shouldn't be written this way. I don't care about the case where the output is zero bytes but still passes the string contains check.
=> fix(tests) remove require inside eventually

CHANGELOG.md
The changelog has a section at the bottom. This section is often forgotten. This PR adds a comment at the top to remind us to not forget that section.
=> chore(docs) add changelog update instructions

.github/workflows/e2e.yaml, Makefile, test/e2e/istio_test.go
Move the Istio tests into their own directory and create a separate make target and job for them.
Most E2E tests function by deploying a complete deploy manifest to the test cluster, running both Kong and the controller in a Pod. These tests only log information from the test function itself. The integration tests, by comparison, run Kong in a Pod but start the controller from the test function, and their logs include both the test and controller logs. We should maybe separate these and have the controller log to a file, but that's a different discussion.
The Istio E2E tests are not like most E2E tests, and instead operate similar to the integration tests. They spawn a controller from the test suite and display its logs intermixed with test logs. …
=> chore(tests) separate Istio tests

.github/workflows/e2e.yaml, .github/workflows/e2e_targeted.yaml
This PR bumps istio versions in e2e tests to more recent.
=> chore: bump istio version

Makefile, test/e2e/all_in_one_test.go, test/e2e/helpers_test.go, test/e2e/istio_test.go, test/e2e/utils_test.go
Refactors https://github.com/Kong/kubernetes-ingress-controller/pull/2989 to replace the hack with build tags.
Thanks @randmonkey and @pmalek for educating me on how to use the build ORs
Sample run at https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3153122011
=> chore(tests) separate Istio via build tags

internal/dataplane/parser/translators/ingress.go, internal/dataplane/parser/translators/ingress_test.go
The translator used to combine the ingress rules into services on rare occasions could combine routes that should not be combined when host and service name in the ingress overlapped.
This commit changes how the ingress translation index computes the key for the entries, preventing overlapping host,serviceName,port combinations from being combined.
Fixes #3004 
=> fix(parser): combining overlapping host and service ingress rules

test/conformance/suite_test.go, test/integration/suite_test.go
Add `--anonymous-reports=false` to controller flags when launching it in conformance and integration tests.
E2Es will require a separate kustomization to apply when running the controller as a container which can be done in a separate PR.
=> chore: don't send telemetry from integration and conformance tests

test/e2e/kustomizations.go, test/e2e/utils_test.go
Refactor E2E kustomize patching to use structs. This allows contsructing kustomizations with patches or other complex features more easily.
Add a patch to increase the controller init retries.
This was an attempt to address E2E failures where Kong fails to ever listen (it simply never makes any `bind()` call) by allowing more retries. It didn't quite work; we need at least extended liveness probes also. Extending the kustomize support and DRYing those functions is useful on its own.
Testing other things to try and reduce timeouts other ways but going ahead and submitting this on its own. https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3147412453/attempts/1 is the "didn't fall over entirely" …
=> chore(tests) refactor E2E kustomize handling

.github/workflows/e2e.yaml
Only two JUnit xmls are reported for e2e tests due to overlapping names. Let's use matrix values in order to make the names unique. 
Sample run which reported only 2 files: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3190367410/jobs/5206110000
- ~~[ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~~
=> chore(tests): make e2e junit results names unique

CHANGELOG.md, internal/dataplane/parser/ingressrules.go, internal/dataplane/parser/ingressrules_test.go, internal/dataplane/parser/parser.go, test/integration/httproute_test.go
Gateway routes with conflicting services in their backend don't break config build.
Fixes #2565 
=> fix: routes with conflicting services

.github/workflows/test.yaml
In order to get more data points let's run build pulse reporting on all branches.
Additionally this PR pins the build pulse reporting workflow to a specific commit to avoid problems with malicious code being added in the future.
=> chore(ci): run buildpulse reporting on all branches

.github/ISSUE_TEMPLATE/release.yaml
Adds an additional step in releasing KIC to notify team.
=> add additional step in release cycle

.github/workflows/e2e.yaml, Makefile
Adds a new `E2E_TEST_RUN` variable for the E2E make target. It populates the `-run` argument value. By default, it is blank and will run all tests
Dynamically generates a matrix of all tests in the E2E directory and runs with that matrix populating E2E_TEST_RUN. Each test+Kubernetes version combination runs as a separate job.
The separate jobs indicate more clearly what failed (they're only running a single test) and complete in about 25% of the original time (E2E tests were parallelizable but run in sequence, this runs them all in parallel).
General issues with E2E test stability (KIND failing to come online) appear to be resolved with this approach. E2E was apparently leaving clusters behind after completing a test …
=> chore(ci) split E2E into a job per test

.github/workflows/nightly.yaml
remove the need `test-previous-kubernetes-gke` prerequisite in `buildpulse-report` step of nightly because it was removed.
=> chore: remove invalid needs in buildpulse-report of nightly

test/e2e/helpers_test.go, test/e2e/kustomizations.go
- remove the `Base` field specification in kustomization to fix the "base.yaml not found" error in e2e tests.
- more: add build tags in `kustomization.go` to avoid "unused" notes from editor plugin/ IDEs
targeted e2e still has failures on case `TestDeployAllInOneEnterpriseDBLESS`: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3213059078/jobs/5252443520 
=> test: fix base.yaml not found in e2e tests

CHANGELOG.md, Dockerfile
Move the distroless target to the end of the Dockerfile. This makes it the default when Docker buildx builds are run without a target. Although our make targets and release workflow _do_ specify targets, custom CD may not, and this change leads them to produce a better output.
Inspired by #3036 
https://gist.github.com/rainest/ae3f00050b66429aca052eeb7057b540#file-docker-txt-L324-L347 is the example buildx build without this change.
The `docker build` invocation above just builds everything. There's nothing we can really do for vanilla Docker builds; they always build everything unless you provide a target.
This is listed as a fix since we never intended for the FIPS target to be …
=> chore(build) make distroless default Docker target

.golangci.yaml, test/e2e/istio_test.go, test/e2e/kustomizations.go
It seems that istio e2e tests were failing because the build tags were not set right and the compilation would fail with the following error:
```
Error: test/e2e/utils_test.go:141:26: undefined: patchControllerImage
Error: test/e2e/utils_test.go:163:26: undefined: patchKongImage
Error: test/e2e/utils_test.go:170:25: undefined: patchControllerStartTimeout
Error: test/e2e/utils_test.go:176:25: undefined: patchLivenessProbes
Error: test/e2e/utils_test.go:182:25: undefined: patchLivenessProbes
WARN invalid TestEvent: FAIL	github.com/kong/kubernetes-ingress-controller/v2/test/e2e [build failed]
bad output from test2json: FAIL	github.com/kong/kubernetes-ingress-controller/v2/test/e2e [build failed]
=== Errors
Error: test/e2e/utils_test.go:141:26: …
```
=> fix(tests): fix istio tests

test/e2e/kustomizations.go
fix `addControllerEnv` in kustomization of e2e tests that makes test case `TestMissingCRDsDontCrashTheController` fail in e2e run https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3247564012/jobs/5327698068.
Changes:
- replace all `\t`s in `addControllerEnvPatch` string to `  ` (2 spaces) for consistency
- remove `Bases` field in Kustomization to avoid "base.yaml not found" error  
=> test: fix kustomization patch addControllerEnvPatch in e2e

CHANGELOG.md, internal/dataplane/kong_client.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/dataplane/parser/translate_secrets.go, internal/dataplane/parser/translate_secrets_test.go
CA certificate expiration validation is introduced. Once it fails, synchronization to the data plane is skipped (analogically to the other already existing validations against CA certificate secrets). It also adds logging of affected plugins for better context. 
This is the first step to resolving https://github.com/Kong/kubernetes-ingress-controller/issues/1892. 
=> feat: Skip synchronisation of expired CA certificates 

test/conformance/suite_test.go, test/integration/suite_test.go
After [pinning k8s version to v1.24 for some tests](https://github.com/Kong/kubernetes-ingress-controller/pull/2904) it seems that the issue is now resolved and we can get rid of the hardcode.
=> chore(tests): remove hardcoded v1.24 version for tests

Makefile, internal/controllers/configuration/zz_generated_controllers.go
Currently, the indentation and imports order in the generated controllers are not following `go fmt`. Let's make `fmt` dependency of `generate` target to make the code properly formatted at all times. 
=> chore: make sure the generated code is properly formatted

Makefile
This PR adds a bit more comments to the Makefile to make it easier to run KIC locally. It also:
- adds a `_run` target which can be used to skip running all the preconditions, code generation and other logic which is used in `run`
- fixes the `KONG_ADMIN_URL` variable which can now be customized in a way so that users with custom `KONG_NAMESPACE`, `KONG_ADMIN_SERVICE` and/or `KONG_ADMIN_PORT` variables can now also run KIC locally with one command like so (here we specify only `KONG_ADMIN_SERVICE`):
```
KONG_ADMIN_SERVICE=my-own-kong-admin make _run
```
- adds `_ensure-namespace` target which ensures that `KONG_NAMESPACE` namespace exists on the cluster before proceeding to run the controller
=> chore: add more options to Makefile for running KIC locally

internal/controllers/gateway/gateway_controller.go
This PR removes an unnecessary invocations of `DeleteObject()` on gateway which has already been called a couple of lines above and since we're in the code path where the error from that operation has been set to `nil` there's no need to retry that.
Additionally there's a small tweak in logging: moves the log "marking gateway as scheduled" inside an `if` branch where the marking is actually being done. No need to log this when marking isn't happening.
=> chore: remove unneded DeleteObject() on gateway

internal/controllers/gateway/httproute_controller.go
After HTTPRoute has been bumped to v1beta1 in 2.6/2.7 it seems we forgot to update the HTTPRoute controller logger with that information.
=> chore: update HTTPRoute controller version in logs

Makefile
In order to be able to deploy objects with alpha level of support from Gateway API, install CRDs for them along the regular ones.
=> chore: install experimental Gateway API CRDs as well as standard ones

internal/controllers/gateway/gateway_controller.go
fill in gateway namespace and name when failed to find it in k8s, to print the logs and delete object in dataplane object cache correctly.
It seems that the original implementation operates different from the usual case in other controllers. In common logics of controller, we forget the object it the error is a "not found", and requeue it and report error if other errors happened. Here in the PR I changed the logic to the same as other controllers. Please let me know if there are any considerations for the implementations here.
fixes #3069
=> fix: fill in gateway namespace and name when failed to find it in k8s

.github/workflows/nightly.yaml, .github/workflows/release.yaml
- Change the redhat registry backend to quay.
- Makes the redhat certification scan on nightly runs run in parallel with test.
- Makes the redhat certification scan on nightly runs run optional, not failing the workflow.
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/2977
=> chore(ci): change the redhat registry backend to quay

internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_tcproute.go, internal/dataplane/parser/translate_tlsroute.go, internal/dataplane/parser/translate_udproute.go, internal/dataplane/parser/translate_utils.go, internal/dataplane/parser/translate_utils_test.go
This PR refactors the functions used for route translation, so the PR https://github.com/Kong/kubernetes-ingress-controller/pull/3060/ has less noise.
Changes to kong route generation:
- Added  `generateKongRouteFromHTTPRouteMatches` function, that generates the `kong.Route` from a list of backends. It's being invoked in `generateKongRoutesFromHTTPRouteRule` function on two codepaths, thus reducing amount of copied code. It will be used in one more place when #3060 is merged. 
- `generateKongRoutesFromHTTPRouteRule` was made smaller by extracting code blocks into a descriptive functions.
- The new `kong.Rote` generation logic from #3060 is not able to reuse `generateKongRoutesFromHTTPRouteRule`, but `generateKongRouteFromHTTPRouteMatches` will be …
=> refactor(parser): extract functions to be used in HTTPRouteMatch consolidation

.gitattributes
Excludes generated files from [pull-request-size](https://github.com/noqcks/pull-request-size) calculation. 
As it was discovered, the tool does not use `.gitattributes` globbing the way we would expect it to do (the same way as git does). Instead, it uses its own library for that purpose ([`minimatch`](https://github.com/noqcks/pull-request-size/blob/f839be1b2b91687584602f24e753325eeb0166c3/index.js#L99)). This change uses this intel to match all generated files in the repository using patterns that `minimatch` library will accept fine. 
It was tested against all generated files in the repository: https://codesandbox.io/s/js-playground-forked-fvx49r?file=/src/index.js
As I understand the tool code it uses [`.gitattributes` from …
=> chore(ci): exclude generated files from pr size calculations using globbing

internal/dataplane/parser/translate_httproute_test.go
This PR adds a k8s obj info  utility function to reduce parser tests lengths.
=> chore(tests): add k8s obj info  utility to reduce parser tests lengths

go.mod, internal/dataplane/kong_client.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translate_ingress_test.go, internal/dataplane/parser/translate_knative_test.go, internal/dataplane/parser/translate_kong_l4_test.go, internal/dataplane/parser/translate_utils_test.go, internal/metrics/prometheus.go
It adds `TranslationFailureCollector` to the `Parser`. `Build` method is modified so that translation failures are returned from it. `KongClient` inspects the failures and in case any occurred, reports `TranslationCount` metric with `SuccessKey=SuccessFalse`. 
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3097.
Number of the line changes in this PR is mostly affected by the alignments after making `Build` method propagate `[]TranslationFailure` and `Parser` constructors returning an error. 
- ~[ ] the `CHANGELOG.md` release notes have been updated to reflect any significant …
=> feat(#3097): use TranslationFailureCollector in Parser

CHANGELOG.md, internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translators/httproute.go, internal/util/builder/httproutematch.go
This PR consolidates `HTTPRouteMatch` objects into paths in `kong.Route` if they share the route, filters and matching data.
The behaviour depending on `CombinedRoutes` being enabled or not:
- When the `CombinedRoutes` feature is disabled, the parser generates one `kong.Service` per `HTTPRouteRule` and one `kong.Route` per `HTTPRouteMatch` pointing to that service. 
- When the`CombinedRoutes` feature is enabled, prior to this PR, multiple `HTTPRouteRule` objects can be consolidated into a single `kong.Service` if they share the backend refs. However, single `HTTPRouteMatch` generates a single rule pointing to the generated service.
- With this PR and the `CombinedRoutes` enabled, the multiple `HTTPRouteMatch` objects are further consolidated into a …
=> feature(parser): consolidation of multiple `HTTPRouteMatch` objects into single `kong.Route`

internal/cmd/rootcmd/run.go, internal/manager/run.go, internal/manager/setup.go, internal/util/test/controller_manager.go, test/conformance/gateway_conformance_test.go, test/conformance/suite_test.go, test/e2e/istio_test.go, test/integration/suite_test.go, test/integration/utils_test.go
This PR fixes missing controller logs in integrations tests.
Logger needs to be configured before anything else happens.This is because the controller manager has a timeout for logger initialization, and if the logger isn't configured after 30s from the start of controller manager package init function, the controller manager will set up a no op logger and continue. The logger cannot be configured after that point.
Fixes #2882
=> tests: fix the missing controller logs

internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/dataplane/parser/translate_secrets.go, internal/dataplane/parser/translate_secrets_test.go, internal/store/store.go
It adds helper methods to the Parser that allow reporting translation failures and uses them to propagate CA certificate secrets' issues. 
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3097.
=> feat(#3097): propagate translation failures of CA certificate secrets

CHANGELOG.md, internal/annotations/annotations.go, internal/annotations/annotations_test.go, internal/dataplane/kongstate/route.go, internal/dataplane/kongstate/route_test.go, internal/dataplane/kongstate/service.go, internal/dataplane/kongstate/service_test.go
Adds annotations for connect/write/read timeouts and retries to Services. These were available in KongIngress but not via annotations.
Adds annotations for headers and path handling to Routes. Ditto KongIngress/annotation split.
Fix #3017 
**Special notes**
`headers` is more complicated than most fields. It is a string->string array map and cannot really be handled by a single key/value pair without compromises.
The design presented here, where part of the value we give to Kong is embedded in the annotation name, seems reasonable to me, but it is novel, so I'm calling it out. It's also handled a bit differently in the code. The annotations package functions usually return the value with minimal parsing, if any, and the …
=> Add missing Service/Route annotations

CHANGELOG.md, internal/dataplane/kong_client.go, internal/manager/consts.go, internal/manager/run.go, test/integration/translation_failures_test.go
It starts creating Kubernetes Events for all TranslationFailures detected during the translation phase. It will create one event per causing object. An integration test suite is also added in order to track all translation failure cases - that should make eventual future refactors safer (e.g. moving validation rules from the parser to the controllers). 
Part of #3097. 
=> feat(#3097): create warning translation failure events for CA secrets

internal/dataplane/synchronizer_test.go
Skip `TestSynchronizer` when `-short` is specified.
This makes it so that when e.g. `GOTESTFLAGS=-short make test.unit.pretty` is run, this test is skipped to shorten the runtime of tests.
=> chore(tests): mark dataplane synchronizer unit test as long

internal/adminapi/client_test.go
In order to shorten the duration of `./internal/adminapi` TLS unit tests, use smaller RSA keys (`4096` -> `2048`) to decrease the runtime of tests.
Before:
```
go test -count 1 -v ./internal/adminapi/...
=== RUN   TestMakeHTTPClientWithTLSOpts
--- PASS: TestMakeHTTPClientWithTLSOpts (2.15s)
=== RUN   TestMakeHTTPClientWithTLSOptsAndFilePaths
--- PASS: TestMakeHTTPClientWithTLSOptsAndFilePaths (4.30s)
PASS
ok      github.com/kong/kubernetes-ingress-controller/v2/internal/adminapi      6.456s
```
After:
```
go test -count 1 -v ./internal/adminapi/...
=== RUN   TestMakeHTTPClientWithTLSOpts
--- PASS: TestMakeHTTPClientWithTLSOpts (0.12s)
=== RUN   TestMakeHTTPClientWithTLSOptsAndFilePaths
--- PASS: TestMakeHTTPClientWithTLSOptsAndFilePaths (0.35s)
PASS …
```
=> chore(tests): use shorter rsa keys for adminapi unit tests

.github/workflows/test.yaml, CHANGELOG.md, FEATURE_GATES.md, internal/manager/feature_gates.go
Flips the CombinedRoutes feature gate default to `true`.
Sets `CombinedRoute=false` in the feature gates integration test. We now have this in place for any tests of the old system so long as it's deprecated.
Adds documentation to FEATURE_GATES.md (do we instead want this somewhere else) to help users understand the change impact.
Fix #2881 
https://github.com/Kong/kubernetes-ingress-controller/issues/3131 is the follow-up issue to collect community comments and eventually remove traditional in 3.0 barring and showstopper issues.
=> chore(config) enable combined routes by default

CHANGELOG.md, internal/dataplane/parser/failures.go, internal/dataplane/parser/failures_test.go, internal/dataplane/parser/ingressrules.go, internal/dataplane/parser/ingressrules_test.go, internal/dataplane/parser/parser.go, internal/util/test/name.go, test/consts.go, test/integration/translation_failures_test.go
Adds propagation of translation failure: annotations not matching in services backing a single route.
Part of #3097.
=> feat(#3097): propagate translation failures for annotations not matching in grouped services

CHANGELOG.md, internal/dataplane/parser/ingressrules.go, internal/dataplane/parser/parser_test.go, test/integration/translation_failures_test.go
It will propagate translation failures for services for which the referred client-cert cannot be fetched.
Part of #3097.
=> feat(#3097): propagate translation failures for missing service's referred client-cert

CHANGELOG.md, go.mod, go.sum, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go, internal/controllers/gateway/types.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/translate_errors.go, internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translate_routes_helpers.go, internal/dataplane/parser/translate_tcproute.go, internal/dataplane/parser/translate_tlsroute.go, internal/dataplane/parser/translate_udproute.go, test/integration/helpers_test.go, test/integration/httproute_test.go, test/integration/utils_test.go
This PR aims to implement [GEP-957: Destination Port Matching](https://gateway-api.sigs.k8s.io/geps/gep-957/)
Fixes #2709 
- Which `Accepted` reason to use:
~For now, the routes that will end up not being attached to a Gateway because of unmet port criteria (missing listener in the Gateway with the specified `Port`) will get an `Accepted` condition with `NoMatchingListenerHostname` reason.~
~This should be addressed also in this PR IMHO and the proposed course of action is:~
~- use a `const` defined in our codebase~
~- submit an issue with the above described proposal to https://github.com/kubernetes-sigs/gateway-api/~
~- swap the self defined `const` with the one defined in …
=> feat(gateway-api): add destination port matching GEP-957

.github/workflows/e2e.yaml, .github/workflows/release.yaml, Makefile, hack/e2e/cluster/deploy/main.go, test/e2e/all_in_one_test.go, test/e2e/environment.go, test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/kuma_test.go, test/e2e/utils_test.go
- Adds GKE and existing cluster support to E2E tests.
- ~Uses the E2E tests as the release job condition for creating the release tag~ not yet, currently just a test variant because I can't easily test with the release workflow.
We need this because we aren't currently running the test suite we want to during releases. It also requires some refactoring of the E2E tests themselves, which is a good opportunity to refactor them and KTF to address some ease of use issues. Tests cannot easily load cluster-specific functionality (loading images, adding a KIND configuration, etc.) without abusing the environment addon functionality (we have addons that fail if loaded on an unsupported cluster, which we don't want). …
=> Support GKE E2E tests and use (actual) E2E tests to gate releases

internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, test/integration/crd_validations_test.go
Removes validation of `targetPort` being `>= 0` for `corev1.Service` of `ExternalName` type. It's not needed as the validation is handled on Kubernetes API level (proved in the added testcase). 
Part of #3097. 
=> chore(validations): remove unnecessary targetPort validation for ExternalName services

go.mod, go.sum, hack/e2e/cluster/cleanup/main.go
#3140 updated `cloud.google.com/go/container` to `1.7.0`, which marked `container/v1` as deprecated. Code importing the package need to be updated to import `containerpb` instead.
~[ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~
=> chore(deps): update gcloud package containerpb

internal/cmd/rootcmd/run.go, internal/cmd/rootcmd/servers.go, internal/cmd/rootcmd/signal.go, internal/manager/run.go, internal/manager/setup.go, internal/util/logging.go, internal/util/test/controller_manager.go, internal/util/test/crds.go, test/conformance/gateway_conformance_test.go, test/conformance/suite_test.go, test/e2e/istio_test.go, test/integration/suite_test.go
Refactor logger setup. Create only a single instance each of the modern and deprecated logger, and share it across each of the manager, diagnostics server, signal handler, and admission server.
Add a new `TEST_KONG_KIC_MANAGER_LOG_OUTPUT` integration test envvar. When set, manager logs output to this file instead of stderr along with test logs.
Fix a race condition in test setup where Gateway API CRDs were deployed successfully but not immmediately available, disabling related controllers at startup.
Inspired by discussion on some PR. Because a lot of the controller logs are just the same task, with unchanging results, in an infinite loop, they're often just noise. This lets you shunt the noise elsewhere.
The CRD …
=> feat(tests) support manager logs to file

CHANGELOG.md, config/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Update the listen configurations in the deploy manifests to use the same parameters as the upstream default kong.conf listens.
Removes discrepancies between configuration here and kong.conf defaults (https://github.com/Kong/kong/blob/ea485a8467259c2f7fee5959d757fee6a7318c99/kong.conf.default#L527 and https://github.com/Kong/kong/blob/ea485a8467259c2f7fee5959d757fee6a7318c99/kong.conf.default#L397).
With https://github.com/Kong/kubernetes-ingress-controller/issues/2435 resolved by 3.0 (as far as we know--there's one report that it's still happening but not one that I can replicate) there's no reason to not use the same config as upstream anymore.
E2E test for the modified manifests: …
=> chore(deploy) align listens with upstream

internal/dataplane/parser/ingressrules.go, internal/dataplane/parser/ingressrules_test.go, internal/dataplane/parser/parser.go, internal/dataplane/parser/parser_test.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translate_ingress_test.go, internal/dataplane/parser/translate_knative_test.go, internal/dataplane/parser/translate_kong_l4_test.go
It makes the `SecretNameToSNIs` use maps internally to store hosts and parents in order to avoid expensive maps building while adding a host/parent.
Global (meaning - in the scope of all secrets stored under a single `SecretNameToSNIs` instance) `seenHosts` map is kept in order to make sure only one secret is assigned to a host. `parents` map is stored on a single `SNIs` entry level to make sure we have no duplicates there as well.
Fixes #3166.
=> perf: use maps in SecretNameToSNIs

CHANGELOG.md, internal/dataplane/parser/translate_httproute.go, test/integration/translation_failures_test.go
Adds propagation of translation failures for HTTPRoute not having any backendRef specified. 
Part of #3097. 
=> feat(#3097): propagate translation failures for http routes not having backend refs

CHANGELOG.md, go.mod, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go, internal/controllers/gateway/types.go, test/integration/httproute_test.go
This PR implements matching listeners by [Listener.AllowedRoutes](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1beta1.AllowedRoutes) as well as some refactor in `getSupportedGatewayForRoute`
Should fix #2408
This PR also adds matching routes against listener's status and most specifically `.SupportedKinds`. I'm not sure if that's the right thing to do given the [comment in the spec](https://github.com/kubernetes-sigs/gateway-api/blob/a8f72f5778d9d769dfda5d4332d23529aeb7f2e1/apis/v1beta1/gateway_types.go#L656-L666) but it surely feels right. For now in such cases we'd add a `gatewayv1beta1.RouteReasonNotAllowedByListeners`.
**PR Readiness …
=> feat(gateway-api): matching routes by `Listener.AllowedRoutes`

internal/controllers/gateway/route_utils_test.go, internal/util/builder/allowedroutes.go, internal/util/builder/routegroupkind.go, internal/util/builder/routenamespaces.go
This PR adds builders for `AllowedRoutes`, `RouteNamespaces` and `RouteGroupKind`
=> Add builders for `AllowedRoutes`, `RouteNamespaces` and `RouteGroupKind`

Dockerfile
When Redhat connect detect a vulnerability it blocks publishing of an image version with the following prompt 
```
Health index must be A to publish
```
In order to prevent that, run `yum update -y` on release builds.
=> chore: add yum update in redhat's image

CHANGELOG.md, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go, test/integration/httproute_test.go
- Does not filter hostnames when `HTTPRoute` contains empty `spec.hostnames`, and any of compatible listeners does not specify `hostname`
- When no hostnames in `HTTPRoute` could match hostnames in listners, do not accept this `HTTPRoute`: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRoute
fixes #3175 
According to API specification of gateway APIs, what should do when `HTTPRoute` does not contain `hostnames`
but listeners contains `hostname` is not defined. I think the most reasonable behavior is to match the hostname specified by the listener which the `HTTPRoute` attached to. When an `HTTPRoute` is not attached to a listener (has empty …
=> fix: filter hostnames in HTTPRoute

.github/workflows/nightly.yaml
It seems that we didn't use the proper output name in nightly CI's `redhat-certification-test` workflow.
This PR fixes it and uses `TAGS_REDHAT_STANDARD` which is the actual name of `build-push-images` output.
Fixes #3202
=> fix(ci): use correct redhat standard tags in nightly CI

.github/workflows/nightly.yaml
#3127 changed junit file names ever so slightly thus making the artifact download job not being able to find them.
This PR fixes it by using the same file names in integration tests make target and in artifact upload step.
Exemplar failure: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3593876328/jobs/6052288394
=> fix(ci): use correct junit file name in nightly CI

config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, docs/api-reference.md, pkg/apis/configuration/v1/configsource.go, scripts/apidocs-gen/template/gv_details.tpl
It changes the order of types in the generated API reference. The package's exported top-level kinds are displayed first, and the rest of the types after them.
It also adds descriptions for secretValue fields to not leave the comment empty. 
Part of #3019.
**Notes for reviewers**:
Unfortunately, the tool we use to generate docs doesn't expose template functions or a config that would allow ordering the types in a different way, thus the additional template logic had to be introduced.
=> chore(docs): display exported kinds first in the API reference

config/crd/bases/configuration.konghq.com_ingressclassparameterses.yaml, config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongconsumers.yaml, config/crd/bases/configuration.konghq.com_kongingresses.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, config/crd/bases/configuration.konghq.com_tcpingresses.yaml, config/crd/bases/configuration.konghq.com_udpingresses.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, docs/api-reference.md, pkg/apis/configuration/v1/kongclusterplugin_types.go, pkg/apis/configuration/v1/kongconsumer_types.go, pkg/apis/configuration/v1/kongingress_types.go, pkg/apis/configuration/v1/kongplugin_types.go, pkg/apis/configuration/v1alpha1/ingress_class_param_types.go, pkg/apis/configuration/v1beta1/tcpingress_types.go, pkg/apis/configuration/v1beta1/udpingress_types.go, scripts/apidocs-gen/post-process-for-konghq.sh
Removes top-level CRD godocs. They will be included in hand-written markdown files in the docs repository to give wider possibilities of formatting (`{:.warning}` directives etc.). 
Part of #3019 
**Notes for the reviewers**:
removed godocs are going to be moved to docs.konghq.com in [this PR](https://github.com/Kong/docs.konghq.com/pull/4813).
=> chore(docs): remove top-level CRD extensive godocs

internal/controllers/gateway/route_utils_test.go, internal/controllers/gateway/types.go, internal/util/builder/backendref.go, internal/util/builder/listener.go, internal/util/builder/routegroupkind.go, internal/util/conversions.go
- Adds `getSupportedGatewayForRoute` unit tests for TCP/UDP/TLSRoute 
- Reduces tests volume by extracting common parts and reusing them
Part of #2709.
=> test(gateway-api): cover L4 routes in getSupportedGatewayForRoute tests

internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils_test.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_utils_test.go, internal/dataplane/parser/ingressrules_test.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translate_routes_helpers_test.go, internal/util/address/of.go, internal/util/builder/address.go, internal/util/builder/httpbackendref.go, internal/util/builder/kongstateservicebackend.go, internal/util/builder/listener.go, internal/util/builder/routegroupkind.go, internal/util/builder/routenamespaces.go, internal/util/conversions.go
To minimize the spread of `addressOf` implementations across the codebase let's introduce one that's exported (nested under `internal/` directory tree) and use that throughout the codebase.
=> refactor: use one version of getting address to a variable

.github/workflows/test.yaml
Since we can't reliably and securely give outside contributors access to our secrets we can't run the EE tests for those PRs.
This PR will allow us to accept patches contributed from outside of our org without enterprise tests failing.
=> ci: don't run tests when license unavailable

CHANGELOG.md, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go
Match listener names if routes specified `sectionName` in their parentRefs. If a route specifies `sectionName` in its parentRef, and no listeners can match the name, the route is not accepted.
fixes #3221
=> fix: match listener names for routes

CHANGELOG.md, config/crd/bases/configuration.konghq.com_kongingresses.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, docs/api-reference.md, pkg/apis/configuration/v1/kongingress_types.go
Adds deprecation comments to all KongIngress fields that have their replacement in form of an annotation.
Part of #2941. 
=> chore(docs): deprecate KongIngress' proxy and route in favor of annotations

.github/workflows/e2e.yaml, .github/workflows/e2e_targeted.yaml, .github/workflows/nightly.yaml, .github/workflows/test.yaml, .github/workflows/test_nightly.yaml
k8s v1.26 is released, include the latest version in nightly(integration) tests and e2e tests. 
Also bump other k8s versions to the latest patch release of its minor release.
fixes #3240 
=> chore(tests): add v1.26 to k8s versions of nightly and e2e tests

CHANGELOG.md, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gateway_utils_test.go
This prevents creating two Detached conditions for Listener that has no matching protocol in `kongProtocolsToPort`. 
Fixes #3256. 
Proven in the following tests run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3685516223/jobs/6237448308
=> fix: do not create two Detached conditions when no port for the protocol available

go.mod, go.sum
Bump controller-runtime to [v0.14.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.14.0)
Fixes #3253
=> chore(deps): bump controller-runtime to v0.14.0

.golangci.yaml, go.mod, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils_test.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_utils_test.go, internal/dataplane/parser/ingressrules_test.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translate_routes_helpers_test.go, internal/util/address/of.go, internal/util/builder/backendref.go, internal/util/builder/httpbackendref.go, internal/util/builder/kongstateservicebackend.go, internal/util/builder/listener.go, internal/util/builder/routegroupkind.go, internal/util/builder/routenamespaces.go, internal/util/conversions.go, test/integration/kongingress_webhook_test.go
Removes the local implementation of `address.Of`, replaces it with `lo.ToPtr`, and disallows usage of `k8s.io/utils/pointer`. 
Follow up of #3261.
=> chore(deps): use lo.ToPtr for pointer casting

internal/dataplane/synchronizer.go, internal/dataplane/synchronizer_test.go, internal/manager/setup.go
This PR makes the dataplane synchronizer accept options as parameter and refactors its tests so that instead of running for 17s they complete in 0.16s.
=> refactor: make synchronizer accept option parameters

grafana.json
Improves Grafana dashboard:
* display metrics taking into account only the values from the dashboard time range 
* removes legend for the config push time histogram as it was just adding noise to it 
Before:
After:
Follow up after doing a demo of translation failures visibility improvements.
=> chore(metrics): display metrics over dashboard time

test/integration/ingress_regex_match_test.go, test/integration/suite_test.go, test/integration/utils_test.go
When ingress class for tests is already present in the cluster don't fail outright but try to recreate it ( so that it's in the state that we want it to be ) and continue on.
=> fix: don't fail integration tests when ingres class is already present in the cluster

.github/workflows/test.yaml, .github/workflows/test_nightly.yaml
In order to improve tests reliability and resilience to github API rate limiting we need to pass the `GITHUB_TOKEN` env into CI steps that run the tests so that they can use it for authentication.
Exemplar CI failure caused by the above: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3714943949/jobs/6299504976#step:6:356
```
Error: tests failed: couldn't fetch latest knative/serving release: GET https://api.github.com/repos/knative/serving/releases/latest: 403 API rate limit exceeded for 172.177.73.1. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 10m00s]
```
=> fix(tests): add GITHUB_TOKEN to tests so that they can authenticate against Github API

.github/workflows/nightly.yaml
In the same spirit as #3272, this adds `GITHUB_TOKEN` to integration test runs to prevent Github API rate limiting but in nightly test runs.
Exemplar failed CI pipeline: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3718281847/jobs/6306456862#step:5:378
```
Error: tests failed: couldn't fetch latest knative/serving release: GET https://api.github.com/repos/knative/serving/releases/latest: 403 API rate limit exceeded for 65.52.35.16. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 25m45s]
```
=> chore(tests): add GITHUB_TOKEN to nightly test runs

.github/workflows/e2e.yaml
- Bump all Istio versions to the latest patch
- Add Istio `v1.16.1` 
- Bump GKE Kubernetes version to `v1.24.7`
Part of #3199
=> chore(deps): bump e2e matrix dependencies

CHANGELOG.md, internal/manager/config.go
This PR marks the `--kong-custom-entities-secret` flag as deprecated and adds a "known issue" note in v2.8 changelog stating that this does not work currently.
**Related issue(s)**
https://github.com/Kong/kubernetes-ingress-controller/issues/3278
=> chore: custom entites known issue note

.github/workflows/e2e.yaml
According to [Istio's support status](https://istio.io/latest/docs/releases/supported-releases/), Kubernetes v1.26 isn't supported by any Istio version.
Part of #3199
=> chore(ci): don't test istio against k8s v1.26

.github/workflows/e2e.yaml
- Do not test against Istio < v1.14. v1.13 had its EOL on Oct 12, 2022
- Test against two versions of Kubernetes as Kubernetes v1.25 is not supported by Istio v1.14.6 (exclude this one case)
Istio support: https://istio.io/latest/docs/releases/supported-releases/
Part of #3199
=> chore(e2e): test istio according to its support matrix

test/integration/gateway_webhook_test.go, test/integration/ingress_test.go, test/integration/knative_test.go, test/integration/kongingress_test.go, test/integration/suite_test.go, test/integration/udpingress_test.go, test/integration/utils_test.go, test/integration/webhook_test.go
Generate test namespaces in tests so that when tests are run separately only necessary namespaces are created in the cluster.
Additionally this makes it so that each test is responsible for each own namespace that it needs.
=> fix(tests): generate test namespaces in tests

.github/workflows/release.yaml
When switching to running E2E tests instead of integration tests as the release gate, we missed adjusting commands properly: https://github.com/Kong/kubernetes-ingress-controller/commit/c6344be0ccf080010c9b422a53f0cf463dd52603
Failing job: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3732606321/jobs/6333473197
Part of #3199
=> chore(ci): fix release tests command

.github/workflows/release.yaml
Use full versions for E2E release check. Basically copies what's in https://github.com/Kong/kubernetes-ingress-controller/blob/2da95cf0036e7fbe82fe2095e74f5cd1231ff4fb/.github/workflows/e2e.yaml#L28-L36
Move 1.25 to previous Kubernetes.
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3733633765/jobs/6335083552
=> fix(release) align test inputs with regular E2E

config/image/enterprise/kustomization.yaml, config/image/oss/kustomization.yaml, config/variants/enterprise/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
It's [out](https://hub.docker.com/layers/kong/kong-gateway/3.1.0.0-debian/images/sha256-ad345462fe02a5acec549ad0e6d6f56d1e479ca41f5fcdb5366f971bb8bdfa9f?context=explore). Part of  #3220
=> chore(deploy) bump Kong to 3.1

.github/ISSUE_TEMPLATE/release.yaml
As a follow-up to #3199:
- merge docs steps into one
- add details for FOSSA report generate
- add a step for ensuring the latest Gateway image is used in manifests
Part of https://github.com/Kong/team-k8s/issues/267.
=> chore: update release issue template

.github/ISSUE_TEMPLATE/release.yaml
Adds a step requiring cleaning up all the existing issues in FOSSA before making a release.
Part of https://github.com/Kong/team-k8s/issues/267.
=> chore: extend fossa instructions in release template

.github/ISSUE_TEMPLATE/release.yaml, .github/workflows/release_docs.yaml, scripts/apidocs-gen/post-process-for-konghq.sh
As a follow-up to #3199:
- make the job an initial step of creating a PR for the release
- add a version as an input and use it to name the generated reference accordingly
Related to: https://github.com/Kong/kubernetes-ingress-controller/pull/3294
Part of https://github.com/Kong/team-k8s/issues/267.
=> chore(ci): align docs workflow

.github/workflows/release.yaml
Enables tagging RedHat images with the `latest` when the workflow's `latest` input is set to `true`.
Part of https://github.com/Kong/team-k8s/issues/267.
=> chore: tag RH images with latest tag in release

CHANGELOG.md, internal/dataplane/parser/translators/ingress.go, internal/dataplane/parser/translators/ingress_test.go, test/integration/ingress_test.go
replace `*` in hostname to `_` in kong route names, because `_` could not appear in hostnames, and `*` is not allowed in kong route names. `*` in hostnames will cause application of kong configuration fail if `CombinedRoutes` is turned on if not replaced.
fixes #3311 
=> fix: replace * in name of kong routes

.github/workflows/release.yaml
Modifies the release pipeline so it's now possible to pass a prerelease tag (e.g. `v2.9.0-alpha.1`) to create a non-production ready pre-release. It will only push images with the full version (e.g. `v2.9.0-alpha.1` tag only) and publish a pre-release to GitHub (which will be marked as non-production ready). 
It also modifies the testing jobs to run E2E tests in parallel, similarly to what we've got in `e2e.yaml`.  They also will be run against the images built in the workflow (thanks to `TEST_KONG_CONTROLLER_IMAGE_OVERRIDE: "kong/kubernetes-ingress-controller:${{ steps.semver_parser.outputs.fullversion }}"`).
It should allow us to run the prerelease workflow in order to verify it works as expected before running a production release. Should be also …
=> chore(ci): allow running pre-release pipeline

CHANGELOG.md, internal/dataplane/parser/translate_ingress.go, internal/dataplane/parser/translate_knative.go, internal/dataplane/parser/translators/ingress.go, internal/dataplane/parser/translators/ingress_test.go, internal/dataplane/parser/translators/portdef.go, test/integration/ingress_test.go
Part of #3296 
When user provides only service port name and not the number e.g.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
annotations:
konghq.com/strip-path: "true"
kubernetes.io/ingress.class: kong
name: nginx-ingress
spec:
rules:
- http:
paths:
- path: /
pathType: Prefix
backend:
service:
name: nginx
port:
name: http
```
and [`CombinedRoutes`](https://github.com/Kong/kubernetes-ingress-controller/blob/255296c9d71f84400cc33e6c9f556127edd35bab/internal/manager/feature_gates.go#L24-L27) feature flag is used the translation logic incorrectly used port number which wasn't specified. This PR fixes it.
Complete these before marking the PR …
=> fix: use port name when port number is not provided in combined routes

CHANGELOG.md, internal/dataplane/kongstate/kongstate.go, internal/dataplane/kongstate/kongstate_test.go
parse `ttl` field of kong key-auth credentials to `int` type to fix error of invalid type when filling the `ttl` in secret to Kong credential.
fixes #2734 
=> fix: parse ttl to int in key auth credentials

.github/workflows/release.yaml, .github/workflows/release_docs.yaml
Update the parse-semver action to 1.4.6 now that it's on Marketplace. Set the other workflow that uses it to use the same released version instead of a SHA.
Exclude CI-only changes from code tests because why not, they should never perturb code. Doesn't seem to be taking effect though, does that check against the target? https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths and https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore seems like it should work for that :thinking: 
Should clear Github deprecation warnings for the release jobs.
=> chore(ci) update and sync action version

.github/ISSUE_TEMPLATE/release.yaml, CHANGELOG.md, LICENSES, config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Milestone [is done](https://github.com/Kong/kubernetes-ingress-controller/milestone/37?closed=1), so going ahead and shipping the fix.
Fix #3322
Wasn't sure if we wanted to wait for the revised release process, but assuming that will take a while to write and test, figured no. We wanted to get these fixes out quickly and 2.9 will be coming sooner rather than later as the next opportunity to try it.
Instructions indicated that manifest version bumps were only for major/minor, but this looks wrong since we _don't_ use the minor-only tags for the controller image. Since those correspond directly to the tag, we do actually use the complete version.
Complete …
=> Add 2.8.1 release changes

.github/workflows/e2e.yaml, .github/workflows/release.yaml
As per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ replace `set-output` with `GITHUB_OUTPUT`
=> chore(ci): replace set-output with GITHUB_OUTPUT

.github/workflows/release.yaml
Running every e2e test case in a separate worker turned out to cause more trouble than expected. It's not feasible as we had to limit concurrency anyway + there's an issue with GKE subnets cleanup: https://github.com/Kong/kubernetes-ingress-controller/issues/3331 
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3322.
=> chore(ci): don't run each e2e case in separate worker

CHANGELOG.md, internal/manager/run.go, internal/manager/utils/reports.go
Disable mesh detection if the configuration uses --watch-namespaces. The mesh detector attempts to scan all namespaces and cannot be configured to use the multi-namespace cache used by the manager. Since it will fail when --watch-namespaces is set, disable it altogether.
Fix #3158 
Disabling altogether since the report data isn't critical. Alternatives are:
- Find some way to use the manager client for mesh detection. I don't think this is easily doable without taking it out of the reports system and instead building it into the Service controller. controller-runtime does not expose the manager client and I don't particularly want to roll my own …
=> fix(reports) skip mesh when namespace-limited

CHANGELOG.md, internal/dataplane/deckgen/deckgen.go, internal/dataplane/kong_client.go, internal/dataplane/sendconfig/sendconfig.go, internal/dataplane/sendconfig/sendconfig_test.go, internal/manager/config.go
It seems that custom entities where never used (at least in a handful of recent versions).
The notion of them was "somehow" introduced in #1339 and #2296 made `sendconfig.PerformUpdate()` always pass `nil` in place for "custom entities".
Since it's always `nil` we may as well just delete it altogether.
There is still the [CLI flag](https://github.com/Kong/kubernetes-ingress-controller/blob/eb47a6906e583a5b39cbb15038671d7fef472062/internal/manager/config.go#L155)
```
flagSet.StringVar(&c.KongCustomEntitiesSecret, "kong-custom-entities-secret", "", `A Secret containing custom entities for DB-less mode, in "namespace/name" format`)
```
~I'd argue that we can add a deprecation notice and state that it doesn't do …
=> refactor: delete custom entities

internal/cmd/rootcmd/rootcmd.go, internal/cmd/rootcmd/run.go, internal/cmd/rootcmd/signal.go, internal/manager/config.go, internal/util/test/controller_manager.go
This PR
- performs a minor cleanup around rootcmd
- adds passing context through `cobra.Command`'s `.Context()`
- marks via `flagSet.MarkDeprecated()` flags that have already been deprecated: this has an effect that those flags are now hidden when showing the usage and an explicit log message is being logged when they are used, e.g.:
```
Flag --sync-rate-limit has been deprecated, Use --proxy-sync-seconds instead
```
=> refactor: refactor rootcmd, add command context, mark deprecated flags with `flagSet.MarkDeprecated`

CHANGELOG.md, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_utils.go
Now more than one conditions are added to HTTPRoute.status.parentStatus[*], so we need to change the method to check if parent status for gateways changed. Instead of making a full comparison of conditions, we check if the existing parentStatus contains the expected condtion.
fixes #3345
=> fix: only check if condition contained in ensuring gateway associated of httproute

Makefile, config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongingresses.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, docs/api-reference.md, internal/dataplane/parser/translators/httproute.go, internal/dataplane/parser/wrappers_backendref.go, internal/manager/conditions.go, internal/store/store.go, internal/util/test/webhooks.go, pkg/apis/configuration/v1/kongprotocol_types.go, staticcheck.conf, third_party/go.mod, third_party/staticcheck.go
Add https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck to the set of linters we run.
We add this separately from golangci-lint because:
> The author of staticcheck doesn't support or approve the use of staticcheck as a library inside golangci-lint.
=> build: add staticcheck

.github/workflows/e2e.yaml, .github/workflows/release.yaml
Due to the issues with running E2E tests on GKE we have (https://github.com/Kong/kubernetes-ingress-controller/issues/3331), we decided to switch all the tests to Kind for now, until we find a working solution for the problems described in the mentioned issue.
Issue for tracking the enablement of GKE E2E tests back once the problems are figured out: https://github.com/Kong/kubernetes-ingress-controller/issues/3348
Workaround for https://github.com/Kong/kubernetes-ingress-controller/issues/3331.
=> chore(ci): don't run e2e in GKE clusters

docs/api-reference.md, pkg/apis/configuration/v1/kongingress_types.go
It seems that an unwanted `+` sneaked into `KongIngressService` godoc comment.
This PR removes it and regenerates the docs.
=> docs: fix `KongIngressService` docs

internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gatewayclass_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/referencegrant_controller.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go
Update the key for objects in logger of gateway API controllers to `Gateway<Version><Kind>` to prevent from confusing with objects in `networking.k8s.io`(e.g: `Ingress`).
--
=> chores: use Gateway<Version><Kind> for object key in loggers inside gateway API controllers 

internal/dataplane/parser/translators/ingress.go, internal/dataplane/parser/translators/ingress_test.go
Make the translator pass a parent Ingress object instead of its name/namespace/annotations in order to rebuild it later into Ingress object again.
Noticed the possibility to refactor this while reviewing #3359.
=> refactor: pass parent ingress object

config/crd/bases/configuration.konghq.com_kongclusterplugins.yaml, config/crd/bases/configuration.konghq.com_kongingresses.yaml, config/crd/bases/configuration.konghq.com_kongplugins.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, docs/api-reference.md, pkg/apis/configuration/v1/kongprotocol_types.go
This PR fixes KongProtocol doc by adding a missing dot at the end.
=> docs: fix KongProtocol doc

test/e2e/environment.go, test/e2e/helpers_test.go
Adds `KONG_TEST_CLUSTER_PROVIDER` env variable to unblock creating GKE clusters from code instead of using setup scripts. Uses the new features of KTF cluster provider (`WithWaitForTeardown`, `WithCreateSubnet`).
Part of https://github.com/Kong/kubernetes-ingress-controller/issues/3331.
=> chore(tests): allow creating gke clusters using getEnvironmentBuilder

.github/workflows/test.yaml
Upload diagnostics when enterprise tests fail
=> tests: upload diagnostics when enterprise tests fail

Makefile
Remove manifests.single from verify.manifest as it's already part of manifests target
=> build: remove manifests.single from verify.manifest as it's already part of manifests target

CHANGELOG.md, Dockerfile, Makefile, internal/cmd/rootcmd/rootcmd.go, internal/manager/config.go
This is a bit more than the commit message would say it is but when I was going through the `Makefile` I discovered that the `build` target uses incorrect paths to set the `ldflags`, i.e. 
$(REPO_URL)/v2/internal/metadata.Release=$(TAG)
should be 
$(REPO_URL)/v2/internal/manager/metadata.Release=$(TAG)
Hence this PR also contains that change and propagates usage of unified `Makefile` targets for building in `Dockerfile`.
Additionally in order to actually test that the binary contains the desired version information that we'd like it to I added `version` command so that the binary can be run for the sole reason to check the version information and get it in the following form:
{"release":"v2.8.1-23-gde3af6e2","repo":"git@github.com:Kong/kubernetes-ing …
=> feat: add version command

internal/cmd/rootcmd/rootcmd.go
When errors are not silenced in `cobra` then `cobra.CheckErr()` is used then we get 2 times the same error message when an error occurs. For example:
```
go run ./internal/cmd/main.go --asd
Error: unknown flag: --asd
Error: unknown flag: --asd
exit status 1
```
Or interrupted launch:
```
go run ./internal/cmd/main.go ... <flags> ...
...
INFO[0000] getting enabled options and features          logger=setup
INFO[0000] found configuration option for gated feature  enabled=true feature=GatewayAlpha logger=setup
INFO[0000] getting the kubernetes client configuration   logger=setup
INFO[0000] getting the kong admin api client configuration  logger=setup
...
^CINFO[0001] Signal received, shutting down                graceful_period=0s signal=interrupt …
```
=> chore: silence cobra errors to prevent double message about exit error

CHANGELOG.md, internal/controllers/gateway/httproute_controller.go
change exsiting `resolvedRefs` condition in `HTTPRoute` when there is already one in status to avoid multiple appearances of conditions with same type.
=> fix: change existing resolvedRef condition to avoid duplicates

internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_parent_status.go, internal/controllers/gateway/route_parent_status_test.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go
This PR adds a generic version of getting route's parent ref map.
With this PR you can learn how to write 289 lines of code to replace 44 lines just to make it reusable 😄
=> refactor: add a generic version of getting route parent refs map

internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_parent_status.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/types/types.go, test/integration/helpers_test.go, test/integration/httproute_test.go, test/integration/tcproute_test.go, test/integration/tlsroute_test.go, test/integration/udproute_test.go
As described in [GEP-1364](https://gateway-api.sigs.k8s.io/geps/gep-1364/#programmed), gateway API has published "Programmed" condition in release 0.6.0. We will add the condition to the following managed objects:
- `HTTPRoute`
- `TCPRoute`
- `TLSRoute`
- `UDPRoute`
Also, setting "Programmed" condition properly is a prerequisite for bumping gateway API to 0.6.0 because conformance tests includes tests for setting the "Programmed" condition.
expected to fix #3343
=> feat: set "Programmed" condition for *Route in gateway APIs

Dockerfile, Dockerfile.debug, Makefile, config/debug/manager_debug.yaml, skaffold.yaml
This PR extracts debug related image build instructions from `Dockerfile` to `Dockerfile.debug` and fixes skaffold config so that version information is injected during build process (instead of relying on running git commands in the image itself, to prevent copying `.git`)
=> build: extract debug related targets from Dockerfile to separate one

internal/dataplane/parser/ingressclassparemeters_test.go, internal/dataplane/parser/parser.go, internal/store/store.go
With #3385 merged, there's still one more thing to cover, which is to avoid errors when an IngressClass does not reference any IngressClassParameters. It's perfectly normal to do so. In that case we fall back to using [defaults](https://github.com/Kong/kubernetes-ingress-controller/blob/51185a91f2c6aa86a8acafa6eee4f73dc51acfc0/pkg/apis/configuration/v1alpha1/ingress_class_param_types.go#L54-L64).
=> fix: do not return an error when IngressClass does not reference IngressClassParameters

.github/workflows/cleanup.yaml, .github/workflows/e2e.yaml, go.mod, go.sum, hack/deploy-admission-controller.sh, test/e2e/all_in_one_test.go, test/e2e/compatibilities_test.go, test/e2e/features_test.go, test/e2e/helpers_gateway_test.go, test/e2e/helpers_test.go, test/e2e/istio_test.go, test/e2e/kuma_test.go, test/e2e/utils_test.go
- Brings GKE tests back to `e2e.yaml` workflow
- Adapts `hack/deploy-admission-controller.sh` to accept kubeconfig as an argument to make it possible to run against GKE cluster
- Cleans up test cleanup code into `finalizeTest` helper
- Extracts `runOnlyOnKindClusters` helper and handles new `KONG_TEST_CLUSTER_PROVIDER` env var in it
- Refactors `getKongProxyIP` to work with GKE clusters properly
- Deduplicates temporary kubeconfig dumping by extracting `getTemporaryKubeconfig`
Fixes https://github.com/Kong/kubernetes-ingress-controller/issues/3348 and https://github.com/Kong/kubernetes-ingress-controller/issues/3331
**Note to reviewers**: 
Successful run of the e2e workflow with GKE tests actually running: …
=> tests: fix e2e tests for gke

.github/workflows/e2e.yaml
As we run every GKE E2E test as a separate job, leaving the property on the job level would make all the GKE E2E jobs block each other.
Part of #3348.
=> chore(ci): move 'concurrency' property from job to workflow level

test/integration/gateway_test.go
This PR has 2 goals ( in 2 separate commits ):
- to refactor `TestGatewayFilters` and use builders and cleaner 
- to fix test calling `.Update()` on possibly stale route causing
```
Operation cannot be fulfilled on httproutes.gateway.networking.k8s.io "6ae778b1-c824-4dbf-9b8f-da41142bc950": the object has been modified; please apply your changes to the latest version and try again
```
As in https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3949604605/jobs/6761031742#step:5:2418
Occurred in #3396
=> tests: fix TestGatewayFilters

.github/workflows/cleanup.yaml, .github/workflows/e2e.yaml, Makefile, hack/cleanup_gke_clusters.go, test/e2e/clusters.go, test/e2e/helpers_test.go
- Removes unused `deploy.go` script and Makefile targets
- Turns `cleanup.go` into `cleanup_gke_clusters.go` with a single purpose of being used in the `cleanup.yml` workflow 
- Removes the `concurrency` property from workflows as it's proven to not work well in our case (it doesn't allow queueing more than 1 job, more on that [in the discussion](https://github.com/community/community/discussions/5435)). In order to mitigate the possible issue with clusters being deleted by the cleanup job before E2E tests are finished, clusters are considered orphaned after 1h from their creation (instead of 30min).
Part of #3378.
=> chore(ci): cleanup gke related scripts

test/e2e/features_test.go
As the admission webhook itself is already tested in many aspects in integration tests, we prefer to remove this check completely from the E2Es.
Closes https://github.com/Kong/kubernetes-ingress-controller/issues/3393.
=> chore: remove #3393 todo

internal/cmd/rootcmd/rootcmd.go, internal/cmd/rootcmd/rootcmd_test.go, internal/cmd/rootcmd/run.go, internal/manager/config.go, internal/manager/config_test.go, internal/manager/controllerdef.go, internal/manager/feature_gates.go, internal/manager/feature_gates_test.go, internal/manager/flagnamespacedname.go, internal/manager/run.go, internal/manager/setup.go
This PR adds `Config.Validate()` to allow validation of configuration options before starting the manager.
This will also set the stage to allow stopping the manager boot up process when mutually exclusive options are being provided (e.g. as in single controller deployments `kong-admin-url` and potential future Admin API service name specified for service discovery).
Additionally this performs some minor refactor around config and passing down the configuration options to downstream consumers of said options. It also stores the flagset in the `Config` so that we can use `c.flagSet.Changed()` to verify if the flag has been provided by the user ( in case the default flag value is a non empty/default value).
=> feat: add Config.Validate() to allow validation of configuration options before starting the manager

Makefile
Prevent sending anonymous reports when running locally.
=> chore: don't send anonymous reports when running locally

CHANGELOG.md, internal/dataplane/parser/ingressrules.go, internal/dataplane/parser/ingressrules_test.go, test/integration/translation_failures_test.go
Adds Kong Service name to invalid multi-Service backend Events. This name indicates the route resource that requires the Service, and will in turn indicate the other Services that need matching annotations:
```
11:32:06-0800 esenin $ kubectl -n 71dba048-df32-448b-bfb4-d6df2913e4f7 get events | grep multi                                         
74s         Warning   KongConfigurationTranslationFailed   service/httpbin                                  Service has inconsistent konghq.com/host-header annotation and is used in multi-Service backend httproute.71dba048-df32-448b-bfb4-d6df2913e4f7.2ab68c8f-e26c-4a32-86d1-96208bb7c6ef.1.All Services in a multi-Service backend must have matching Kong annotations. Review the associated route resource and …
```
=> Include Kong service name in multi-Service Events

go.mod, go.sum
Bump `github.com/emicklei/go-restful` to v3.10.1
Fixes #3414
=> chore(deps): bump github.com/emicklei/go-restful to v3.10.1

Makefile
Adds `-trimpath` flag to the command building a debug binary. It solves the problem of not being able to set breakpoints when attaching to a remote process (local paths do not match the ones embedded in the binary that is being built in the Dockerfile).
```
go help build
-trimpath
remove all file system paths from the resulting executable.
Instead of absolute file system paths, the recorded file names
will begin either a module path@version (when using modules),
or a plain import path (when using the standard library, or GOPATH).
```
=> chore: add -trimpath when building debug binary

test/e2e/utils_test.go
This PR fixes a data race where a port forwarding function would access the buffer provided to the `cmd.Start()` at the same time the command is writing to it.
Fixes #3424
=> fix(tests): fix e2e data race when starting port forwarding

.github/workflows/codeql.yaml, .github/workflows/test.yaml
This PR aims to use Github Actions' [`concurrency`](https://docs.github.com/en/actions/using-jobs/using-concurrency) to run tests and code scanning only on most recent PR commits and cancel anything prior to that.
This seems to work but unfortunately it notifies you whenever a job gets cancelled and it's impossible to suppress this notification
It's supposedly on Github's roadmap to address this: https://github.com/community/community/discussions/13015
=> ci: add concurrency to run tests only on most recent PR commit

test/internal/helpers/teardown.go
To prevent test failures like : https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4012330723/jobs/6890689291#step:6:37 don't constrain test helpers with build tags.
Just let anyone use them from wherever.
=> fix: don't constrain test helpers with build tags

test/integration/consumer_test.go, test/integration/crd_validations_test.go, test/integration/examples_test.go, test/integration/gateway_test.go, test/integration/gateway_webhook_test.go, test/integration/helpers_test.go, test/integration/httproute_test.go, test/integration/httproute_webhook_test.go, test/integration/ingress_https_test.go, test/integration/ingress_regex_match_test.go, test/integration/ingress_test.go, test/integration/knative_test.go, test/integration/kongingress_test.go, test/integration/kongingress_webhook_test.go, test/integration/plugin_test.go, test/integration/suite_test.go, test/integration/tcpingress_test.go, test/integration/tcproute_test.go, test/integration/tlsroute_test.go, test/integration/translation_failures_test.go, test/integration/udpingress_test.go, test/integration/udproute_test.go, test/integration/utils_test.go, test/integration/webhook_test.go
This PR removes the shared `context.Context` and `context.CancelFunc` from integration tests.
This makes us one step closer to more isolated tests.
=> tests: don't share context in integration tests

.golangci.yaml, hack/generators/controllers/networking/main.go, internal/admission/utils.go, internal/admission/validator.go, internal/controllers/configuration/secret_controller.go, internal/controllers/configuration/zz_generated_controllers.go, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gatewayclass_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/referencegrant_controller.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/controllers/knative/knative.go, internal/controllers/reference/reference.go, internal/util/test/crds.go, test/e2e/helpers_gateway_test.go, test/e2e/helpers_test.go, test/integration/gateway_webhook_test.go, test/integration/ingress_test.go, test/integration/kongingress_test.go, test/integration/suite_test.go, test/integration/udproute_test.go, test/integration/webhook_test.go
In order to be consistent let's use just 1 alias for `k8s.io/apimachinery/pkg/api/errors` package. The proposal in this PR is to use `apierrors` but that can be discussed.
What's important is to use just 1 alias and enforce it in the linter.
=> refactor: use 1 alias for k8s api errors package

test/integration/examples_test.go, test/integration/tcpingress_test.go, test/integration/tcproute_test.go, test/integration/tlsroute_test.go, test/integration/udpingress_test.go
After running
```go
package main
import "testing"
func TestX(t *testing.T) {
t.Cleanup(func() {
t.Log("cleanup 1")
})
defer func() {
t.Log("defer 1")
}()
t.Cleanup(func() {
t.Log("cleanup 2")
})
defer func() {
t.Log("defer 2")
}()
}
```
and getting the following output:
```
=== RUN   TestX
main_test.go:16: defer 2
main_test.go:10: defer 1
main_test.go:13: cleanup 2
main_test.go:7: cleanup 1
--- PASS: TestX (0.00s)
PASS
ok      defercleanup    0.004s
```
I realized that our approach in tests where we do:
```go
func TestUDPRouteExample(t *testing.T) {
_, cleaner := setup(ctx, t)
t.Log("locking Gateway UDP ports")
udpMutex.Lock()
defer udpMutex.Unlock()
...
```
Might cause issues because:
- `setup()` registers `cleaner.Cleanup()` via `t.Cleanup()`
- …
=> tests: use cleanup for locking gateway ports to prevent `defer` and `t.Cleanup` ordering issues

.github/workflows/test.yaml, Makefile, test/integration/addons_knative_test.go, test/integration/addons_test.go, test/integration/knative_test.go, test/integration/suite_test.go
This PR adds matrix for integration tests and extracts knative tests into a separate build tag: `knative`.
By doing this:
- we avoid the need for deploying knative addon where it's not needed (nowhere besides the knative test)
- we extract knative test into a separate Github job (via `matrix`) so we isolate the workflows even further
---
Adding new matrix entries (hence separate, parallel workflow runs for integration tests) is as easy as adding a new intro into:
```yaml
integration-tests:
name: integration-tests-${{ matrix.name }}
runs-on: ubuntu-latest
...
strategy:
fail-fast: false
matrix:
include:
- name: dbless
test: dbless
- name: postgres
test: postgres
- name: feature-gates
test: dbless
feature_gates: "GatewayAlpha=true,CombinedRoutes=false" …
```
=> tests: add matrix for integration tests

.github/workflows/codeql.yaml
In order to make codeql happy and prevent the following warning:
> 1 issue was detected with this workflow: Please make sure that every branch in on.pull_request is also in on.push so that Code Scanning can compare pull requests against the state of the base branch.
Let's just run codeql on branches that are in PRs that target `main`.
Codeql run from this branch seems indeed happy: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4025032677
=> ci: make codeql workflow happy by targeting only main

.github/workflows/test.yaml, test/integration/ingress_test.go
This does the similar thing that #3441 did but for ingressclass related tests.
It also fixes the aggregated step in CI checking that all tests passed.
=> tests: use t.Cleanup() for locks on IngressClass in integration tests

Makefile
Bumps skaffold to the latest version. Unfortunately, it's still not possible to install it the same way we do with other tools.
=> chore(deps): bump skaffold to v2.1.0

test/e2e/features_test.go, test/e2e/helpers_gateway_test.go, test/e2e/helpers_test.go, test/e2e/istio_test.go, test/e2e/utils_test.go, test/integration/consumer_test.go, test/integration/controller_test.go, test/integration/examples_test.go, test/integration/httproute_test.go, test/integration/ingress_regex_match_test.go, test/integration/ingress_test.go, test/integration/kongingress_test.go, test/integration/metrics_test.go, test/integration/plugin_test.go, test/integration/tcpingress_test.go, test/integration/utils_test.go, test/internal/helpers/http.go
This PR removes the shared `http.Client` instance and changes all references to it to call introduced in this PR `helpers.DefaultHTTPClient()` function.
This is part of an effort to extract everything from `utils_test.go` and `suite_test.go` so that we're able to initiate tests from different directories and not share variables.
=> tests: don't share http.Client in tests

internal/admission/validator.go, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/gatewayclass_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/udproute_controller.go, internal/manager/config.go, internal/manager/config_validation_test.go, internal/manager/run.go, test/conformance/gateway_conformance_test.go, test/e2e/helpers_gateway_test.go, test/integration/helpers_test.go
This PR extracts gateway controller name utilities from #3421 which will be useful when getting or setting controller name from different goroutines (e.g. in tests).
=> refactor: extract gateway controller name utils

internal/controllers/gateway/httproute_controller.go
Fixes #2939 
How the lack of flakiness has been proven:
- enabling up to initially 20, then 100, and finally  500 subsequent runs of conformance tests (109ac08b06df6b49d2e09bc10a07fd11b96132da)
- three different runs with these numbers:
- 20 runs completed successfully: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4052876746/jobs/6972833107
- 100 runs completed successfully: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4053635300/jobs/6974483236
- 136 runs completed successfully: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4056394996/jobs/6980848816. The 500-runs setup did not complete, as GH stopped the job after 6 …
=> test: Conformance tests flakiness fix

internal/metrics/prometheus.go, internal/metrics/prometheus_test.go
It seems that we never tested calling `dataplane.NewKongClient()`, specifically more than once.
This PR fixes a panic which occurs when calling `NewKongClient()` twice. This is due to the fact that we call `.MustRegister()` on https://github.com/Kong/kubernetes-ingress-controller/blob/0f55f293fca8ae71af6de780f7b7d1d05d2b0abb/internal/metrics/prometheus.go#L111 on prometheus `RegistererGatherer`.
Found when adding tests for #3421
=> fix: don't panic when calling NewCtrlFuncMetrics() more than once

test/integration/httproute_test.go
Don't set the plugin annotation in test where it's not needed and additionally add the plugin (created in another test) to `cleaner`.
=> tests: don't set plugin annotation when not needed

internal/manager/config.go
Fix flags descriptions to prevent incorrect indentaion.
=> chore: fix udp related flags descriptions

test/integration/ingress_test.go, test/integration/suite_test.go
Fix recent ingress class `const` refactor.
=> chore: fix ingress class const refactor

test/integration/suite_test.go
This fixes a problem where we skip tests that we wouldn't like to skip, e.g. https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4086412787/jobs/7045676471#step:7:15296 
```
=== Skipped
=== SKIP: test/integration TestIngressRegexMatchPath (0.00s)
ingress_regex_match_test.go:32: regex prefixes are only relevant for Kong 3.0+
=== SKIP: test/integration TestIngressRegexMatchHeader (0.00s)
ingress_regex_match_test.go:186: regex prefixes are only relevant for Kong 3.0+
=== SKIP: test/integration TestIngressClassRegexToggle (1.00s)
ingress_test.go:565: legacy regex detection is only relevant for Kong 3.0+
=== SKIP: test/integration TestIngressRegexPrefix (0.00s)
ingress_test.go:698: regex prefixes are only relevant for Kong 3.0+
=== SKIP: …
```
=> fix(tests): overwrite an old enterprise image in ktf

internal/dataplane/parser/translate_utils.go, test/integration/ingress_regex_match_test.go, test/integration/ingress_test.go, test/integration/plugin_test.go
As a follow up to #3486, let's print kong version when we decide to skip a test.
This way we'll actually know what version we were running against and it'll be easier to debug what that was the case (if it wasn't supposed to be).
=> feat: print kong version when skipping tests

test/integration/ingress_test.go
This fixes the following deck warning:
```
time="2023-02-03T13:45:21+01:00" level=debug msg="converting configuration to deck config" kong_url="http://172.18.1.1:8001/"
1 unsupported routes' paths format with Kong version 3.0
or above were detected. Some of these routes are (not an exhaustive list):
18a19edb-0b01-4d9a-988b-146c3c086e04
Please upgrade your configuration to account for 3.0
breaking changes using the following command:
deck convert --from kong-gateway-2.x --to kong-gateway-3.x
This command performs the following changes:
- upgrade the `_format_version` value to `3.0`
- add the `~` prefix to all routes' paths containing a regex-pattern
These changes may not be correct or exhaustive enough.
It is strongly recommended to perform a manual …
```
=> fix(tests): don't use 2.x style path regex where requiring 3.x one

internal/dataplane/sendconfig/sendconfig.go, internal/dataplane/sendconfig/sendconfig_test.go
Extracts `hasConfigurationChanged` helper function and covers it with tests to make this code easier to reason about.
Part of #3437.
=> refactor: extract hasConfigurationChanged

CHANGELOG.md, internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_controller_test.go, internal/controllers/gateway/gateway_utils.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/referencegrant_controller.go, internal/controllers/gateway/route_utils.go, internal/dataplane/parser/backendref.go, internal/dataplane/parser/translate_utils.go, internal/dataplane/parser/translate_utils_test.go, internal/dataplane/parser/wrappers_refchecker.go, internal/store/fake_store.go, internal/store/fake_store_test.go, internal/store/store.go, test/integration/tcproute_test.go, test/integration/tlsroute_test.go
Now that the Gateway API has been bumped to `0.6.0`, we can use the beta version of `ReferenceGrants`
Fixes #2954 
=> chore: referenceGrant promoted to beta

internal/adminapi/endpoints.go, internal/adminapi/endpoints_test.go
This PR adds 2 helpers for handling Admin API EndpointsSlices together with tests. These are not used currently but in order to minimize the size of #3421 they were extracted here.
=> feat: add adminapi endpoints helpers

.github/workflows/test.yaml, test/integration/suite_test.go
This PR unpins the enterprise tag that we set in integration tests. This way the nightly tests and locally run tests will respect `TEST_KONG_IMAGE` and `TEST_KONG_TAG` through https://github.com/Kong/kubernetes-ingress-controller/blob/3ce7c14afd2099e991c4dcd3370f23ef8c742a5e/test/internal/testenv/testenv.go#L24-L32 and https://github.com/Kong/kubernetes-ingress-controller/blob/3ce7c14afd2099e991c4dcd3370f23ef8c742a5e/test/internal/helpers/ktf.go#L32-L37
This is just unblocking and kicking the can down the road. We need to figure out an approach for this.
Related: https://github.com/Kong/kubernetes-testing-framework/issues/542
- If we set a default in ktf then we'd need to bump that every GW release, release ktf …
=> fix(ci): fix pinned enterprise tag

CHANGELOG.md, internal/manager/controllerdef.go
Since `ReferenceGrant` has been promoted to beta, we should enable it by default if `gateway` turned on.
=> feat: enable ReferenceGrant controller if Gateway feature gate turned on

.github/workflows/test.yaml
There's no point in sending buildpulse report when the pipeline got cancelled so let's not do it. The same condition was set previously on the step inside buildpulse job but there's not point in run that job at all when we're cancelled.
=> chore(ci): don't run buildpulse if workflow has been cancelled

CHANGELOG.md, config/rbac/role.yaml, config/variants/multi-gw/base/manager_multi_gateway_patch.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-multi-gw.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml, internal/adminapi/client.go, internal/adminapi/kong.go, internal/adminapi/kong_test.go, internal/controllers/configuration/kongadminapi_controller.go, internal/dataplane/client.go, internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/synchronizer.go, internal/dataplane/synchronizer_test.go, internal/manager/config.go, internal/manager/config_validation.go, internal/manager/controllerdef.go, internal/manager/run.go, internal/manager/setup.go, internal/manager/utils/kongconfig/root.go, test/e2e/all_in_one_test.go, test/e2e/helpers_test.go, test/e2e/utils_test.go, test/internal/helpers/teardown.go
This PR introduces kong Admin API service discovery via the `--kong-admin-svc` flag (to be discussed).
When that flag is specified (as `namespace/service_name`) KIC will watch `EndpointSlice`s for that `Service` and add (and remove when the endpoint gets removed) a kong client for each endpoint for that `Service`.
This in its current form does not take into account the fact that gateway should be made ready only when its config is applied and ready (Admin API readines != Gateway Proxy readiness). We don't yet have a mechanism to be sure that a config has been applied (it can come in one of the upcoming Gateway releases) but we could implement a mechanism to make Gateway Proxy service marked as ready after the config has been sent.
#3499 covers …
=> feat: add service discovery for kong admin service

CHANGELOG.md, internal/dataplane/deckerrors/conflict.go, internal/dataplane/kong_client.go, internal/dataplane/sendconfig/sendconfig.go, internal/dataplane/sendconfig/sendconfig_test.go, internal/metrics/prometheus.go, internal/metrics/prometheus_test.go
This PR adds `dataplane` metrics label to account for KIC sending configuration to more than 1 gateway.
The outcome of this PR will be that users will see separate time series for each dataplane for the following metrics:
- `ingress_controller_configuration_push_count`
- `ingress_controller_configuration_push_duration_milliseconds`
Fixes #3417
Blocked by #3421
This will make it so all `ingress_controller_configuration_push_count` and `ingress_controller_configuration_push_duration_milliseconds` time series will change. Regardless of running SCD or not. If we'd like to retain the current behaviour (not include the label) then we'd need to tweak this PR to account for this, i.e.:
- …
=> feat: add dataplane metrics label

CHANGELOG.md, internal/manager/run.go, internal/manager/setup.go
This PR ensures we enable leader election when Admin API service discovery is enabled.
Fixes #3528
~When implemented this way (the same we used to do it for other configurations, dbless or not) KIC's deployment has only 1 ready Pod - the leader - and all the other ones are not ready, because the readiness probe set to~
https://github.com/Kong/kubernetes-ingress-controller/blob/22f6bad0f1c25e973aa6def5db79fab7fcf058bb/internal/manager/run.go#L171-L178
~is not responding since the dataplane synchronizer is not ready yet.~
~Is that desired? Or do we want non-leader pods to be ready as well?~
The readyz handler was changed to allow all Pods from KIC's Deployment to be marked as ready. …
=> feat: set leader election when single controller deployments are configured

test/e2e/all_in_one_test.go, test/e2e/clusters.go
move function `logClusterInfo` to `clusters.go` which does not contain build tags, to fix `logClusterInfo` not found in istio tests.
=> tests: fix logClusterInfo not defined in istio tests

go.mod, go.sum, test/e2e/all_in_one_test.go, test/e2e/compatibilities_test.go, test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/istio_test.go, test/e2e/kuma_test.go
Extracts a helper function that sets up a cluster, returns a test context, and prepares cleanup calls.
Successful targeted E2E run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4173464849
=> tests(e2e): extract setup function

examples/gateway-udproute.yaml, examples/udpingress.yaml, test/integration/udpingress_test.go
Kubernetes is [replacing the k8s.gcr.io registry](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/). Besides it just becoming frozen soon the new registry.k8s.io registry is also less costly to use so the sooner we can stop using the old one the better to help out upstream.
=> chore: replace k8s.gcr.io registry usage

test/internal/helpers/teardown.go
For some reason, e2e tests on GKE v1.25 take longer to clean up the environment, so to unblock extend the timeout.
There's an issue in ktf https://github.com/Kong/kubernetes-testing-framework/issues/565 to track an effort to extend cleaner's API to allow e.g. configuration whether to wait for namespaces to be deleted.
=> chore(ci): extend test environment cleanup timeout to unblock e2e tests

CHANGELOG.md, internal/adminapi/endpoints.go, internal/adminapi/endpoints_test.go, internal/controllers/configuration/kongadminapi_controller.go, internal/manager/config.go, internal/manager/controllerdef.go, internal/manager/setup.go
In order to allow more flexible usage of Admin API service discovery this PR introduces configurable port names that will be used for matching against port from Admin API Service during service discovery.
=> feat: add configurable Admin API service port names to be used for service discovery

test/e2e/clusters.go, test/e2e/helpers_test.go, test/e2e/kuma_test.go, test/e2e/utils_test.go, test/internal/testenv/testenv.go
This PR adds `testenv.WaitForClusterDelete()` which looks at the value of `KONG_TEST_CLUSTER_WAIT_FOR_DELETE` environment variable and if it's set to `true` then it wait for the cluster deletion to complete.
This should help in our recent problems with e2e tests timing out.
=> tests: introduce `testenv.WaitForClusterDelete()` to make wait for cluster deletion configurable

CHANGELOG.md, config/base/kong-ingress-dbless.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-multi-gw.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Ports the changes from helm chart: https://github.com/Kong/charts/pull/722. A projected volume is used instead of a static secret.
That effectively makes our manifests not compatible with Kubernetes < 1.21 versions. According to our [support matrix](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/version-compatibility/), we already do not support such. 
E2E tests run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4187269214
Closes #3475.
=> feat(config): use projected volume for SA token

.github/workflows/e2e.yaml, .github/workflows/e2e_targeted.yaml
Istio tests are [run separately](https://github.com/Kong/kubernetes-ingress-controller/blob/4c92de5567678f8f6ac2741a994a18141b5abc07/.github/workflows/e2e.yaml#L157-L222) in e2e (and not run in e2e targeted: works as designed?)
Since we use `grep` and `sed` magic to get test names in github actions yaml and we don't use builds tags there we also include istio tests names in the matrix which causes CI to run a workflow for each but not run it because the tags do not match.
Example: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4182210606/jobs/7245050991
```
(cd third_party && go mod tidy && \
GOBIN=/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/bin go generate -tags=third_party ./gotestsum.go ) …
```
=> chore(ci): filter out istio tests from general e2e pipeline

internal/konnect/node_agent.go, internal/manager/run.go
Ensures that the NodeAgent goroutines are run only when the KIC instance has been elected a leader.
Part of #3438.
=> fix(konnect): make NodeAgent manager.Runnable

test/e2e/all_in_one_test.go
Wait until all pods are ready to be sure we can safely port-forward to them. Also pass build args when building ci docker image in targeted e2e workflow so that `metadata.Release` (aka version) is properly populated in the binary (which when missing made [KonnectConfigPush test to fail](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4194316203/jobs/7272381057))
E2Es run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4197202223
=> tests: wait for all pods ready in multi-gw e2e

internal/manager/setup.go, internal/manager/utils/kongconfig/root.go
This PR adds context to `getKongClients()` so that cancellation e.g. coming from os signals can get through.
It also adds it to `kongconfig.GetRoots()`.
=> fix: add context to retry in `getKongClients()` and `kongconfig.GetRoots()` to allow proper cancellation

internal/dataplane/parser/ingressrules.go
Properly copies the parent info from different sources when consolidating ingress rules.
Fix #3570
=> fix(parser) copy parent info when consolidating

internal/versions/versions.go
To prevent data races like [this one](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4204271323/jobs/7294710834#step:8:13738):
```
==================
WARNING: DATA RACE
Read at 0x0000061fd9e0 by goroutine 211:
github.com/kong/kubernetes-ingress-controller/v2/internal/versions.(*KongVersion).MajorMinorOnly()
/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/internal/versions/versions.go:65 +0x184
github.com/kong/kubernetes-ingress-controller/v2/test/integration.TestConfigErrorEventGeneration()
/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/config_error_event_test.go:31 +0x147
testing.tRunner()
/opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:1576 …
```
=> fix: don't return address to package variable

internal/manager/run.go, internal/manager/telemetry/manager.go, internal/manager/telemetry/manager_test.go, internal/manager/telemetry/reports.go, internal/manager/utils/reports.go, internal/util/k8s.go
No need to query the pod info if the only thing that we need is pod's name and namespace.
Add `util.GetPodNN()` solely for that purpose.
=> chore: don't get pod info when not necessary

internal/controllers/gateway/gateway_utils.go
The *Route Accepted condition is set to false when the reason is UnsupportedProtocol.
=> fix: not accepted when unsupportedProtocol

internal/controllers/gateway/gateway_controller.go, internal/controllers/gateway/gateway_utils.go, test/conformance/gateway_conformance_test.go
The `GatewayProgrammedCondition` and `ListenerProgrammedCondition` conditions are set on the Gateway. Furthermore, the tests `GatewaySecretReferenceGrantAllInNamespace` and `GatewaySecretReferenceGrantSpecific` are fixed. Only `GatewaySecretReferenceGrantAllInNamespace` has been re-enabled because of an upstream issue that makes the tests fail: https://github.com/kubernetes-sigs/gateway-api/pull/1745.
Part of #3305
=> chore: programmed condition and conformance

internal/controllers/gateway/gateway_utils.go, test/conformance/gateway_conformance_test.go, test/integration/translation_failures_test.go
The conformance test `GatewayInvalidTLSConfiguration` has been fixed by checking the `tls` certificate content.
Part of #3305 
=> chore: gateway certificates checked

config/base/kustomization.yaml, config/base/secret-sa-token.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-multi-gw.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
In https://github.com/Kong/kubernetes-ingress-controller/pull/3563 we overlooked removing the secret. It's not needed anymore since we're using a projected volume.
Follow up of https://github.com/Kong/kubernetes-ingress-controller/pull/3563.
=> chore(config): remove not needed secret

CHANGELOG.md, internal/admission/adminapi_provider.go, internal/admission/adminapi_provider_test.go, internal/admission/validator.go, internal/admission/validator_test.go, internal/konnect/client.go, internal/manager/run.go, internal/manager/setup.go
Use the `AdminAPIClientsManager` to always get the latest list of clients in the admission webhook
to avoid calling outdated services that were set statically during the setup.
Also includes a quick-fix for nil dereference in `konnect.NodeAPIClient`.
E2E run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4264473116/jobs/7422655686
Fixes #3600.
=> fix: get Admin API services dynamically in admission webhook

internal/dataplane/parser/translate_grpcroute.go
Corrects some copy-pasta incorrect names and comments for the GRPCRoute translator.
=> fix(parser) use proper name for GRPCRoute routes

CHANGELOG.md, internal/adminapi/konnect.go, internal/adminapi/konnect_test.go, internal/dataplane/config_status.go, internal/dataplane/config_status_test.go, internal/dataplane/kong_client.go, internal/konnect/client.go, internal/konnect/node_agent.go, internal/konnect/node_agent_test.go, internal/manager/run.go, test/e2e/konnect_test.go
Ensures that even if the user misconfigures Konnect, the basic ingress controller functionality is not affected. It includes:
- propagate context in `NodeAPIClient` methods to ensure they properly close when the context gets canceled
- never return an error from `NodeAgent.Start` to not interrupt the `controller-runtime.Manager` (and unit-test it)
- propagate context in `NodeAgent` methods to ensure it can be aborted properly
- setup Konnect Admin API client in a goroutine to not block the main setup flow
- ensure that config status notifications are not blocking (and unit-test it)
- cleanup logging
- cover the case with misconfigured Konnect integration in an E2E test to ensure the basic ingress functionality doesn't get broken
E2E tests run: …
=> feat(konnect): make sure Konnect misconfiguration doesn't affect ingress

internal/dataplane/config_status.go
`time.After` spawns a goroutine that could be stopped sooner than the timeout itself.
Addresses https://github.com/Kong/kubernetes-ingress-controller/pull/3617#discussion_r1119756192 comment.
=> fix: don't leak timer

.github/workflows/test.yaml
It seems that #3508 missed the fact that a condition can end up being a string. Use `toJSON()` as suggested in https://github.com/actions/runner/issues/1483 to "cast" to boolean".
Exemplar CI that failed to check this condition as expected: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4287103315/jobs/7476535337
=> chore(ci): don't run enterprise tests for PRs from forks

CHANGELOG.md, pkg/apis/configuration/v1/doc.go, pkg/apis/configuration/v1/groupversion_info.go, pkg/apis/configuration/v1alpha1/doc.go, pkg/apis/configuration/v1alpha1/groupversion_info.go, pkg/apis/configuration/v1beta1/doc.go, pkg/apis/configuration/v1beta1/groupversion_info.go, pkg/clientset/typed/configuration/v1/configuration_client.go, pkg/clientset/typed/configuration/v1/fake/fake_kongclusterplugin.go, pkg/clientset/typed/configuration/v1/fake/fake_kongconsumer.go, pkg/clientset/typed/configuration/v1/fake/fake_kongingress.go, pkg/clientset/typed/configuration/v1/fake/fake_kongplugin.go, pkg/clientset/typed/configuration/v1alpha1/configuration_client.go, pkg/clientset/typed/configuration/v1alpha1/fake/fake_ingressclassparameters.go, pkg/clientset/typed/configuration/v1beta1/configuration_client.go, pkg/clientset/typed/configuration/v1beta1/fake/fake_tcpingress.go, pkg/clientset/typed/configuration/v1beta1/fake/fake_udpingress.go, pkg/clientset_test/clientset_test.go
This PR fixes the group mismatch reported in https://github.com/Kong/kubernetes-ingress-controller/issues/3517
fixes #3517 
=> fix: fake clientset not using the correct group name

CHANGELOG.md, config/variants/enterprise/kong-enterprise.yaml, config/variants/enterprise/kustomization.yaml, config/variants/multi-gw/base/gateway_deployment.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless-konnect.yaml, deploy/single/all-in-one-dbless-legacy.yaml, deploy/single/all-in-one-dbless.yaml, scripts/build-single-manifests.sh, test/e2e/all_in_one_test.go, test/e2e/compatibilities_test.go, test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/konnect_test.go, test/e2e/kuma_test.go, test/e2e/kustomizations.go, test/e2e/utils_test.go
- Makes all all-in-one DB-less manifests use multi-gw config.
- Renames old single-Deployment `all-in-one-dbless.yaml` to `all-in-one-dbless-legacy.yaml`.
- Uses a projected volume instead of a static SA secret in the multi-gw proxy deployment.
- Aligns all the affected E2E tests to work with multi-gw config as expected.
E2E tests run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4308118461
Closes #3423.
=> feat(config): make all all-in-one dbless manifests use multi-gw

test/e2e/kuma_test.go
k8s <= 1.23 does not support absence of namespace in `autoscalingv1/scale`, so e2e tests for kuma would fail because namespace was not specified.
failing e2e run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4310619858/jobs/7519243677 
passing e2e run with k8s 1.21: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4311227099/jobs/7520460878
=> fix: add namespace for scale request in e2e tests

test/e2e/all_in_one_test.go, test/e2e/compatibilities_test.go, test/e2e/features_test.go, test/e2e/konnect_test.go, test/e2e/kuma_test.go, test/e2e/utils_test.go
We can `require.NoError` in the helper itself.
=> chore(tests): do not return error from getTestManifest

test/e2e/all_in_one_test.go, test/e2e/compatibilities_test.go, test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/konnect_test.go, test/e2e/kuma_test.go, test/e2e/kustomizations_test.go, test/e2e/utils_test.go
Adds `getManifestDeployments` to programmatically dispatch expected names of the deployments. Also provides helpers to get the deployments from the cluster. Adds consts for deployments and containers names.
E2E tests run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4314114019
Inspired by the https://github.com/Kong/kubernetes-ingress-controller/pull/3643#pullrequestreview-1321248515 comment.
=> chore(tests): do not hardcode deployments' names in e2e

CHANGELOG.md, internal/manager/config_validation.go, internal/manager/config_validation_test.go, internal/manager/run.go
Allow gateway discovery only in db-less mode
fixes #3401 
=> feat(gateway_discovery): allow gateway discovery only in dbless mode

CHANGELOG.md
update CHANGELOG for limiting gateway discovery to be used with dbless gateways: https://github.com/Kong/kubernetes-ingress-controller/pull/3642#discussion_r1124157248
#3401 
=> docs: wording ON CHANGELOG for limiting gateway discovery to be used with dbless gateways

test/e2e/all_in_one_test.go, test/e2e/helpers_test.go, test/e2e/konnect_test.go, test/e2e/utils_test.go
Improves E2E coverage by verifying that when multi-gateway configuration is used, scaling proxy deployment to 0 replicas doesn't break anything and the controller pods remain ready as expected.
Effectively turns the test scenario from "2 replicas, scale to 3 replicas and ensure all configured" into "2 replicas, ensure all configured, scale down to 0, ensure controller pods didn't crash, scale up to 3, ensure all configured".
E2E tests run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4317334266
Part of #3429.
=> tests(e2e): extend multi-gw test with scaling to 0

internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/config_change_detector.go, internal/dataplane/sendconfig/config_change_detector_test.go, internal/dataplane/sendconfig/sendconfig.go, internal/dataplane/sendconfig/strategy.go, internal/dataplane/sendconfig/strategy_test.go, internal/manager/run.go
Refactors `dataplane.KongClient` to accept `UpdateStrategyResolver` and `ConfigurationChangeDetector` interfaces and covers the `Update` method with unit tests.
E2E tests run just in case: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4325511573
Closes #3634.
=> tests(dataplane): cover `KongClient.Update` with unit tests

Makefile, test/integration/grpcroute_test.go
Fixes an issue that was missed when #3661 got merged (with come commits already in `main` that #3661 didn't check).
Additionally this also adds `envtest` build tag for `staticcheck` that #3661 forgot.
=> chore: fix linter

.github/workflows/test.yaml, test/integration/utils_test.go
set kong image to 3.2.x in per-PR integration tests:
`kong/kong:3.2.1` for open source version
`kong/kong-gateway:3.2.1.0` for enterprise edition
part of #3220
=> set kong image to 3.2 in per-PR integration tests

.github/workflows/e2e.yaml
Konnect E2E tests should be run in the E2E job and lack of the secret prevented it.
=> fix: pass Konnect PAT to E2E tests

.github/workflows/e2e.yaml, .github/workflows/e2e_targeted.yaml, .github/workflows/release.yaml
This PR bumps k8s versions for 2.9 release.
Most notably this makes the complete list of k8s versions that we test to be:
- 'v1.22.15'
- 'v1.23.13'
- 'v1.24.7'
- 'v1.25.3'
- 'v1.26.0'
It also:
- drops istio v1.14 (which has reached End of Life as in https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases)
- adds v1.17.
Version | Currently Supported | Release Date | End of Life | Supported Kubernetes Versions | Tested, but not supported
-- | -- | -- | -- | -- | --
1.17 | Yes | February 14, 2023 | ~Sept 2023 (Expected) | 1.23, 1.24, 1.25, 1.26 | 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22
1.16 | Yes | November 15, 2022 | ~June 2023 (Expected) | 1.22, 1.23, 1.24, 1.25 | 1.16, 1.17, 1.18, 1.19, 1.20, 1.21
1.15 | Yes | …
=> chore: bump k8s versions for 2.9 release

test/conformance/gateway_conformance_test.go
The old way of running conformance tests has been replaced by `csuite.Run`. Somehow, with the old method we did not run all the tests, hence we couldn't see the eventual failures. By using the new method, it popped up that we need to fix 
- `HTTPRouteMatching`,
- `HTTPRouteRedirectHostAndStatus`,
in addition to the already known 
- `HTTPRouteHeaderMatching`,
Additionally, all the optional features have been enabled and the additional failing tests have been disabled to clearly state that we need to fix them sooner or later.
=> test(conformance): all tests enabled

test/e2e/helpers_test.go
Current logic in `runOnlyOnKindClusters()` skipped tests running against kind clusters when `strings.Split(existingCluster, ":")[0] == string(kind.KindClusterType)` was equal to `false` which is the case for our e2e tests when we run "by default" against kind, relying on test code to create the cluster.
```
existingClusterIsKind := strings.Split(existingCluster, ":")[0] == string(kind.KindClusterType)
clusterProviderIsKind := clusterProvider == "" || clusterProvider == string(kind.KindClusterType)
if !existingClusterIsKind || !clusterProviderIsKind {
t.Skip("test is supported only on Kind clusters")
}
```
This PR changes the logic to fix that particular case and to make the conditions a bit more verbose.
Working e2e webhook test on kind: …
=> fix(tests): fix e2e webhook test condition

.github/ISSUE_TEMPLATE/release.yaml, .github/workflows/nightly.yaml, .github/workflows/release.yaml
Removes steps in the release and nightly workflows related to the Red Hat certification process (similar to https://github.com/Kong/gateway-operator/pull/642). I had an action item for this to happen but forgot to do that in KIC.
I created an issue to track the effort to bring this process back once we decide to do so: https://github.com/Kong/kubernetes-ingress-controller/issues/3689
=> chore: remove redhat certification steps from workflows

.golangci.yaml, go.mod, internal/dataplane/synchronizer_test.go, internal/manager/health_check_test.go
For some reason we ended up using https://pkg.go.dev/golang.org/x/net@v0.8.0/context which was AFAIK the original context package when context was introduced.
Instead of that we should use the regular `context` package from std library.
This PR enforces that through linter config.
=> chore(ci): disallow golang.org/x/net/context

Dockerfile
As @pmalek [noticed](https://github.com/Kong/kubernetes-ingress-controller/issues/3689#issuecomment-1460059605), we can also remove RedHat dockerfile targets as they're not in use right now.
=> chore: remove unused rhel dockerfile targets

README.md
This adds a mention about Gateway Discovery to README.md.
Related: #3604
Unfortunately, for some reason when specifying a link with an anchor e.g.  https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/deployment/#kong-gateway-oss the browser would not scroll down and since the newly added chapter about Gateway Discovery is under an anchor adding it would direct the user to a screen where he'd need to scroll down manually.
Would we want to include that link anyway?
=> docs: add Gateway Discovery to README.md

.github/workflows/release.yaml
This PR has two fixes that are necessary for the 2.9.0-rc.1 pre-release:
- the `release` workflow mentions `test-current-kubernetes` and `test-previous-kubernetes` that got replaced by a single `test-e2e` step in #3347.
- the current `release` workflow fails if the update mainfests are not updated to the version being released. This requirement does not make sense for pre-releases. This PR lifts that requirement if the semver parses into a pre-release (that is, has a `-...` suffix).
=> fix(release): fix workflow dependencies & allow pre-releases to not update kustomize

internal/manager/conditions.go
Current log entry describing a disabled controller due to missing CRD is vague at best:
```
level=info msg="disabling the 'ingresses' controller due to missing CRD installation" logger=controllers.crdCondition
```
This PR aims at making it a bit more descriptive by including the Group and Version, so that the above becomes:
```
level=info msg="Disabling controller for Group=networking.internal.knative.dev/v1alpha1, Resource=ingresses due to missing CRD" logger=controllers.crdCondition
```
Would you have guessed it that it was knative ingress from the first log entry 🙃 ?
As for capitalizing `Disabling`, I created #3708 to track the effort of making logs consistent w.r.t. capitalization.
=> chore: make CRD detection log entry more descriptive

internal/controllers/gateway/grpcroute_controller.go, internal/controllers/gateway/httproute_controller.go, internal/controllers/gateway/route_parent_status.go, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go, internal/controllers/gateway/tcproute_controller.go, internal/controllers/gateway/tlsroute_controller.go, internal/controllers/gateway/types.go, internal/controllers/gateway/udproute_controller.go
Extracts `ensureParentsProgrammedCondition` from all `*RouteController`s to share 1 implementation.
Closes: #3390
=> chore(gateway-api): extract common programmed condition helper

internal/dataplane/kong_client.go
In order to disambiguate the log entry about the skipped object status update, let's change the debug log entry that notifies about this.
=> chore: reword log entry for skipping object status update

CHANGELOG.md, internal/dataplane/parser/translate_errors.go, internal/dataplane/parser/translate_httproute.go, internal/dataplane/parser/translate_httproute_test.go, internal/dataplane/parser/translate_utils.go, internal/dataplane/parser/translate_utils_test.go, test/conformance/gateway_conformance_test.go, test/integration/translation_failures_test.go
=> feat: Gateway API `RequestRedirect` filter translated to combination of kong plugins

CHANGELOG.md, internal/controllers/configuration/object_references.go, internal/controllers/configuration/object_references_test.go
When `ingress.Spec.TLS` does not contain a secret, skip the updating of referred secrets because they are "Optional".
fixes #3711 
=> fix: do not update secret when tls.secretName is empty

internal/manager/health_check_test.go
It seems that recently added `TestHealthCheckServer_Start` has a tendency to sporadically fail.
This PR should fix that by allowing some failures when issuing requests towards at just after start and using a discard logger which prevents:
```
panic: Log in goroutine after TestHealthCheckServer_Start has completed: "level"=0 "msg"="healthz server closed"
```
It also checks if the `err` is not `nil` at line:
```
if err != nil && !strings.Contains(err.Error(), "connection refused")
```
to prevent accessing `.Error()` for `nil` errors.
---
Exemplar CI failure: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4414460387/jobs/7736204246#step:5:2831
```
=== FAIL: internal/manager TestHealthCheckServer_Start (0.00s) …
```
=> tests: fix TestHealthCheckServer_Start flaky test

.github/workflows/e2e.yaml, .github/workflows/e2e_targeted.yaml, .github/workflows/e2e_trigger_via_label.yaml
(After recent @czeslavo's [comment](https://github.com/Kong/kubernetes-ingress-controller/pull/3715#discussion_r1135429071) all e2e references here, refer to e2e targeted)
This PR bring the ability to run e2e tests via PR labels.
The flow is as follows:
- user adds a label to a PR: either `ci/run-e2e`
- [`trigger e2e on label` workflow](https://github.com/Kong/kubernetes-ingress-controller/blob/f78a20686e828f8b3cbb45315b7cb44ff2aa71fd/.github/workflows/e2e_trigger_via_label.yaml) picks it up and if those labels are detected then it starts appropriate workflow (either e2e).
- a conditional job has been added in e2e workflows, to check if `pr-number` input has been provided. If that's the case then it uses that number to
- add a comment with e2e …
=> feat(ci): allow triggering e2e tests via Github labels

CHANGELOG.md, internal/konnect/node_agent.go, internal/konnect/node_agent_test.go, internal/manager/run.go
Currently `konnect.NodeAgent` runs a loop with a fixed nodes updates period. It makes propagating the changes in Gateways configuration take longer than it could. In this PR, we subscribe to the Gateway clients' changes to reactively update nodes in the Konnect when a change in discovered Gateways is detected.
Additionally, it moves the `NodeAgent`'s tests into a separate test package to make them black-box.
Part of #3501.
=> feat(konnect): react to gateway clients updates in NodeAgent

go.mod
After deck has [already bumped](https://github.com/Kong/deck/blob/f6e8ee2fcf1eaab991c18c6fa8f2b87f83635848/go.mod#L19) `imdario/mergo` to `v0.3.13` and `v0.3.13` does include the one patch https://github.com/imdario/mergo/blob/v0.3.13/merge.go#L82 that we needed (diff between kong's fork and upstream: https://github.com/imdario/mergo/compare/master...Kong:mergo:v0.3.13 we can do away with the replace in our `go.mod`.
=> chore(deps): remove unneeded mergo replace

.github/workflows/cleanup.yaml, .github/workflows/e2e.yaml, .github/workflows/e2e_targeted.yaml, .github/workflows/release.yaml, .github/workflows/test.yaml, .github/workflows/test_nightly.yaml
After bumping to https://github.com/actions/setup-go/releases/tag/v4.0.0 we can remove all the explicit steps for go cache as from this version it's enabled by default.
I noticed it's a thing to do after getting warnings in my workflows (example run that was affected by the cache errors: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4428778621/jobs/7768401060). That's expected according to the `setup-go` release notes:
>  The action won’t throw an error if the cache can’t be restored or saved. The action will throw a warning message but it won’t stop a build process.
=> chore(ci): remove explicit go cache

CHANGELOG.md, Makefile, internal/controllers/gateway/route_utils.go, internal/controllers/gateway/route_utils_test.go
This fixes setting the incorrect status for Gateway API routes.
- It sets the section name in `ParentReference` when it was specified
- It adds unit tests for cases where section names are specified and where more than 1 gateway is matching the route's `ParentRefs`
- It prevents adding multiple parentRefs status for the same parent which was found in local debugging
The relevant conformance test was run multiple times in a loop locally to ensure the fix is in place.
Fixes: #3721
=> tests: fix flaky gateway conformance `HTTPRouteListenerHostnameMatching` test

.github/workflows/e2e_targeted.yaml, test/e2e/environment.go, test/e2e/features_test.go, test/e2e/helpers_test.go, test/e2e/utils_test.go
Instead of depending on both `TEST_KONG_CONTROLLER_IMAGE_OVERRIDE` and `TEST_KONG_CONTROLLER_IMAGE_LOAD` when patching the controller image, let's just always use `TEST_KONG_CONTROLLER_IMAGE_OVERRIDE`. 
Instead of using `TEST_KONG_CONTROLLER_IMAGE_LOAD`, let's have a boolean `TEST_KONG_LOAD_IMAGES` that will tell whether to load overridden images to the cluster or not.
E2E tests run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4437636384
=> chore(e2e): simplify loading images

Makefile
After #3660 got merged we don't seem to need to set the PATH in integration tests anymore.
=> chore(ci): don't set PATH for integration tests

.github/workflows/_conformance_tests.yaml, .github/workflows/_integration_tests.yaml, .github/workflows/_unit_tests.yaml, Makefile, third_party/go-junit-report.go, third_party/go.mod, third_party/go.sum
This PR aims to solve a rather convoluted issue with using `-json` when used in `go test`.
https://github.com/golang/go/commit/295516813efb84589a2417178741f31cbb050298#diff-b3e6126779b5ec9d3d6cea7cc54054ba78f4d7a0a6248d9e458bbd9b3d72fce3R1828 (from this CR: https://go-review.googlesource.com/c/go/+/443596) introduced a write to `os.Stderr` when using `-json` with `go test` (which is what `gotestsum` uses).
That creates a (rather rare) data race with https://github.com/Kong/go-kong/blob/c71247b5c8aae2a0afe76da4dcfaf48a17f10bd5/kong/client.go#L182.
This PR aims to fix that by not using `gotestsum` in integration tests (which used `standard-verbose` format by default anyway).
Examplar CI run that contains this data race: …
=> fix(ci): don't use gotestsum in integration tests

examples/gateway-referencegrant-httproute.yaml
Adds Gateway API [ReferenceGrant](https://gateway-api.sigs.k8s.io/api-types/referencegrant/) example manifest.
=> feat(examples): add Gateway API ReferenceGrant example

examples/gateway-grpcroute.yaml, examples/gateway-httproute.yaml, examples/gateway-referencegrant-httproute.yaml, examples/gateway-tcproute.yaml, examples/gateway-tlsroute.yaml, examples/gateway-udproute.yaml
As noted by @gAmUssA, the command we put in the examples no longer works. Since the GWAPI team may change the install path again in the future, this changes the comment to link to their install page, rather than copying the current commands.
=> fix(examples) link to updated GWAPI install guide

.github/workflows/pr_checks.yaml
It turned out they take too much resources and contribute to job queueing.
Closes #3725.
=> chore: don't run e2es in pr workflow

CHANGELOG.md, internal/dataplane/clients_manager.go, internal/dataplane/clients_manager_test.go, internal/manager/telemetry/manager.go, internal/manager/telemetry/manager_test.go, internal/manager/telemetry/reports.go, internal/manager/telemetry/workflows/gateway_discovery.go
Adds a `discovered_gateways_count` to a telemetry signal when the Gateway Discovery feature is turned on.
Solves #3779.
=> feat(telemetry): add `discovered_gateways_count`

CHANGELOG.md, internal/annotations/annotations.go, internal/util/k8s.go, internal/util/k8s_test.go
Adds a `konghq.com/tags` annotation. Given a CSV of tags, Kong resources generated from the Kubernetes resource with this annotation will have the tags from the CSV. This allows users to set additional tags on generated Kong resources.
Fix #3198
=> feat(annotations) support user-supplied tags

.github/workflows/backport.yaml
This adds a `backport.yaml` workflow that will automatically create backporting PRs if a label in the format `backport {branchName}` is assigned to a PR. It will be triggered once the original PR gets merged.
As we've introduced long-living feature branches, it can become useful for automatic backporting. 
Test run on my fork:
- Created a `release/2.9.x` release branch.
- Added a PR with main as a base: https://github.com/czeslavo/kubernetes-ingress-controller/pull/2.
- Labeled the PR with `backport release/2.9.x`.
- Merged the PR.
- The workflow created a backporting PR with `release/2.9.x` as a base: https://github.com/czeslavo/kubernetes-ingress-controller/pull/3
- Squash&merge of the backporting PR resulted in the following commit on …
=> ci: add backport workflow

test/integration/consumer_test.go, test/integration/ingress_regex_match_test.go, test/integration/ingress_test.go, test/integration/plugin_test.go, test/internal/helpers/http.go
Makes the test code wait until the expected `404` code is returned from the Gateway. There was a case in our CI where Gateway returned `503` and it caused the test to fail (reported in #3786).
Bonus: following Patryk's comment I also sneaked in some replacements of redundant code checking HTTP status codes and responses' bodies with already existing helpers.
Solves #3786.
=> fix(tests): wait for expected status in TestIngressRegexMatchPath

CHANGELOG.md, LICENSES
Final date and license updates for the 2.9 release.
Steps up until _For all releases Create a Release Pull Request_ for #3672 
Calling this the 27th. Barring issues this will probably be merged, and the release job initiated by @randmonkey during the 28th China time, but whatever, timezones :shrug: 
This has a minor deviation from the checklist due to the newer parts of the release process. I am opening this to main with a backport to the 2.9 branch since that's how we've handled the other changes since we made that branch, and we have an action for backports only, not forward ports. A local test cherry-pick indicates no issue stemming from the additional unreleased changes in …
=> Final 2.9 release chores

internal/dataplane/parser/atc/expression_test.go, internal/dataplane/parser/atc/field.go, internal/dataplane/parser/atc/matcher.go, internal/dataplane/parser/atc/predicate.go
Fixes a 
Additional issues found while getting https://github.com/Kong/kubernetes-ingress-controller/tree/feat/httproute-expression to work:
- The headers predicate string is plural.
- To allow translators to add matchers without checking the number of match criteria in the source resource up front, the matcher adders need to handle both literally `nil` values (though we probably shouldn't get these in practice) and matchers that are _empty_. This occurs if you `And` or `Or` a predicate with no value, or if you combine an empty slice of predicates.
Local integration test against the above branch successfully tests an expression with multiple criteria (a path and a header from a …
=> Handle empty matchers in ATC generator

.github/ISSUE_TEMPLATE/release.yaml, CHANGELOG.md
We should actually fold RC changelog entries into the final release like Kong/kong does, but I didn't think to do this originally.
Fold the old 2.9.0-rc1 entries into 2.9.0.
Replace the 2.9.0-rc1 diff link with a 2.9.0 link.
Update the release guide to reflect these steps. The additional "merge to main and backport to the release branch always" did work for 2.9.0, so formalizing it.
See above.
=> chore(doc) collapse 2.9 changelog and update release guide

CHANGELOG.md
2.8.2 changelog to main. 
Dunno if this will backport properly. Quite possibly not.
If it breaks copy-paste changes into a separate commit in https://github.com/Kong/kubernetes-ingress-controller/pull/3827
=> chore(docs) add 2.8.2 changelog

config/image/oss/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml, deploy/single/all-in-one-dbless.yaml, deploy/single/all-in-one-postgres-enterprise.yaml, deploy/single/all-in-one-postgres.yaml
Bumps image versions for 2.8.2
E2E targeted run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4558178393
=> chore(config) bump KIC image version for 2.8.x

internal/dataplane/clients_manager_test.go
Calling `.Load()` two times can end up with two different results, giving a user incorrect information in the log.
=> chore(tests): fix receivedNotificationsCount log

internal/util/k8s.go, internal/util/k8s_test.go
This PR:
- makes `TestGenerateTagsForObject` use `cmp.diff`
- makes `TestGenerateTagsForObject` test the order of returned tags since `GenerateTagsForObject` returns a slice of pointers to strings not a set or a map. This is to catch any changes in the order of returned values. In the end it shouldn't matter but better be explicit about it while we're at it.
- make `GenerateTagsForObject` use `lo.Uniq` only on the user provided tags. No need to call it on the tags that we set.
=> tests: refactor GenerateTagsForObject and its UT

go.mod, internal/manager/utils/kongconfig/root.go
Go 1.20 added [`errors.Join()`](https://pkg.go.dev/errors#Join) which provides the same functionality as `go.uber.org/multierr`'s `Combine()` so let's remove it from our direct dependencies.
=> chore: remove `go.uber.org/multierr` direct dependency

internal/dataplane/kong_client.go, internal/dataplane/kong_client_test.go, internal/dataplane/sendconfig/config_change_detector.go, internal/dataplane/sendconfig/config_change_detector_test.go, internal/dataplane/sendconfig/sendconfig.go
This PR
- prevents KIC continuously sending empty configs when Gateway already has an empty config
- refactors logging around sending the configuration
- additionally this adds a distinction in the logs between clients sending config to Konnect and to Gateway in `internal/dataplane/sendconfig/sendconfig.go`
As an effect of this PR, when debug logging is enabled we're going from:
```
time="2023-04-05T12:51:53Z" level=debug msg="parsing kubernetes objects into data-plane configuration"
time="2023-04-05T12:51:53Z" level=debug msg="successfully built data-plane configuration"
time="2023-04-05T12:51:53Z" level=debug msg="sending configuration to 2 clients"
time="2023-04-05T12:51:53Z" level=debug msg="converting configuration to deck config" …
```
=> refactor: don't send empty configs when no config detected in dataplace

CHANGELOG.md, internal/versions/versions.go
Lock the Kong version singleton with an RWMutex in its getter/setter functions.
Fixes a data race detected in an unrelated test run:
[race.txt](https://github.com/Kong/kubernetes-ingress-controller/files/11153415/race.txt)
=> fix(versions) add mutex to version functions

config/variants/enterprise/kustomization.yaml, deploy/single/all-in-one-dbless-k4k8s-enterprise.yaml
We should use a single Kong image source to bump all versions at once. At some point we added a separate image override to the Enterprise DB-less kustomization, causing it to get stuck at 3.1.
This uses the standard override component, which keeps it in line with the current value, 3.2.
- ~[ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~ I think we do want a release for this, since some 2.9 features rely on 3.2, but I also think making the changelog update here will break the backport.
=> Fix the Enterprise DB-less manifest overlay

.github/workflows/_integration_tests.yaml
Use the Kong floating minor tags for testing instead of specific patch versions.
I don't think there was a reason for us to use exact patch versions, and we hit a bug in an older version. Using the minor tags should avoid this (and a bunch of routine maintenance) in the future.
https://github.com/Kong/kubernetes-ingress-controller/pull/3886 hacked startup diagnostics into suite_test.go. https://github.com/Kong/kubernetes-ingress-controller/actions/runs/4694072692?pr=3886 found failures like:
```
./saml/utils/xmlcatalog.lua:21: file 'xml/xsd/saml-metadata.xml' not found
```
This is the read-only root issue described in FTI-4873.
Testing demonstrated some issues getting consistent …
=> chore(tests) use Kong minor tags for testing

CHANGELOG.md, internal/controllers/configuration/kongadminapi_controller.go, internal/controllers/configuration/kongadminapi_controller_envtest_test.go, internal/dataplane/clients_manager.go, internal/dataplane/clients_manager_test.go
This PR aims to fix a situation where `KongAdminAPIServiceReconciler` would not update the stored Admin API endpoints because it didn't react to the EndpointSlice not being found properly.
It also adds several tests for this scenario which fail without this patch.
=> fix: fix reconciliation for Admin API EndpointSlice deletion

config/components/konnect/kustomization.yaml, config/components/konnect/manager.yaml, config/variants/konnect/base/kustomization.yaml, config/variants/konnect/enterprise/kustomization.yaml, config/variants/konnect/oss/kustomization.yaml, config/variants/multi-gw/enterprise/kustomization.yaml, config/variants/multi-gw/oss/kustomization.yaml, deploy/single/all-in-one-dbless-enterprise.yaml, deploy/single/all-in-one-dbless-konnect-enterprise.yaml, scripts/build-single-manifests.sh
Adds a kong-gateway/Enterprise variant for multi-gateway and Konnect deploy manifests.
Needed for doing Enterprise stuff with Konnect-connected instances.
Our current Kustomize building blocks use [multiple bases](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/multibases/README.md), but this breaks as we start introducing more variants. The [component](https://kubectl.docs.kubernetes.io/guides/config_management/components/) system (the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/1802-kustomize-components/README.md) is also useful reading) lets us use more modular blocks.
This PR only uses them for the Konnect patches, but we can probably reorganize other things …
=> Add kong-gateway variants for multi-gateway and Konnect deploy manifests

test/conformance/suite_test.go, test/e2e/helpers_test.go, test/e2e/istio_test.go, test/expressionrouter/suite_test.go, test/integration/consts_test.go, test/integration/suite_test.go, test/internal/testenv/testenv.go
Add a `timeout` to context passed into `env.WaitForReady` to trigger returning errors and cleanup, to avoid the timeout of test command that will not call the env cleanup, thus no diagnostics are outputted.  
- ~~[ ] the `CHANGELOG.md` release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR~~  Just affect integration tests
=> test: add timeout to context to trigger cleanup on wait for env ready

internal/dataplane/clients_manager_test.go
This aims to prevent a data race described in #3893.
Fixes #3893.
=> chore(tests): fix data race in `TestAdminAPIClientsManager_ConcurrentNotify`

CHANGELOG.md, internal/controllers/configuration/kongadminapi_controller.go, internal/controllers/configuration/kongadminapi_controller_envtest_test.go, internal/dataplane/clients_manager.go, internal/dataplane/clients_manager_test.go
=> [Backport release/2.9.x] fix: fix reconciliation for Admin API EndpointSlice deletion

CHANGELOG.md
As we decided to collapse release candidates' changelogs into the proper releases, let's do that for 2.9.0 and 2.9.0-rc.1.
=> chore(docs): collapse 2.9.0 changelog

internal/adminapi/client.go, internal/konnect/client.go, internal/konnect/node_agent.go, internal/konnect/node_agent_test.go, internal/manager/id.go, internal/manager/run.go, internal/manager/telemetry/reports.go, test/e2e/konnect_test.go
Uses NodeIDs of discovered Gateways to register them in Konnect's Node API.
Closes #3907.
=> feat(konnect): assign gateway nodes their respective ids
